### ISSUE TITLE
On Android 8 can't connect and make call

### ISSUE THREAD

**Issue by goderfly** [juha-h/baresip-studio#1]
[
![photo_2018-07-09_21-06-44 2](https://user-images.githubusercontent.com/5620293/42494717-bfe13e60-8429-11e8-9db0-e23707c846b1.jpg)
](url)

**Comment by juha-h** [comment]
Log shows that DNS lookup failed.  Check domain name in your sip uri
hostpart or your DNS configuration.

**Comment by goderfly** [comment]
But why other device < 8.0 works fine with that domain name and network conf?

**Comment by juha-h** [comment]
goderfly writes:

> But why other device < 8.0 works fine with that domain name and
> network conf?

I don't have a 8.x device to test.  Try if commenting these out in the
config makes any difference:

# Media NAT modules
module                  stun.so
module                  turn.so
module                  ice.so

**Comment by juha-h** [comment]
Have you made some changes to the github code, for example, turned on
medianat?

**Comment by goderfly** [comment]
i change domen name with ip adress and it works

**Comment by juha-h** [comment]
goderfly writes:

> i change domen name with ip adress and it works

I don't know why dns lookup does not work for you 8.x. There is nothing
I can do about it in Baresip Android code.  Did you comment out these
lines in config?

module			stun.so
module			turn.so
module			ice.so

**Comment by goderfly** [comment]
libre.a outdated Access denied finding property "net.dns1"

**Comment by juha-h** [comment]
goderfly writes:

> libre.a outdated Access denied finding property "net.dns1"

I don't understand what your point is in above.

**Comment by juha-h** [comment]
I'll close this for now  due to lack of more specific information.

**Comment by juha-h** [comment]
Is the problem solved if you in config set:

dns_server 8.8.8.8:53

**Comment by goderfly** [comment]
it is solved my problem

**Comment by juha-h** [comment]
Good.  8.8.8.8:53 is now default in config and I'll add a note about it to About.
