### ISSUE TITLE
Build command failed.

### ISSUE THREAD

**Issue by ahmedneffati** [juha-h/baresip-studio#107]
Build command failed.
Error while executing process /Users/morsi/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/morsi/Downloads/baresip-studio-master/app/.cxx/cmake/debug/arm64-v8a baresip}
ninja: Entering directory `/Users/morsi/Downloads/baresip-studio-master/app/.cxx/cmake/debug/arm64-v8a'

ninja: error: '/Users/morsi/Downloads/baresip-studio-master/distribution/baresip/lib/arm64-v8a/libbaresip.a', needed by '/Users/morsi/Downloads/baresip-studio-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so', missing and no known rule to make it

**Comment by juha-h** [comment]
As the error tells, you have not built/installed the libs.
