### ISSUE TITLE
TURN username limitation

### ISSUE THREAD

**Issue by alexis-loumeau** [juha-h/baresip-studio#109]
Hi, 

I' tried to use this app, with twilio turn relay and the app told me that i have an invalid username for turn.

i've seen in the code and the code seem limiting to 63 char but username account of twilio is 64

**Comment by juha-h** [comment]
I just pushed commit 1aa9abd77d59b11c21de585387fbeaae21b6a76a  that increased the size to 64 chars.  Did you install the app from some repo or rolled your own?

**Comment by alexis-loumeau** [comment]
i tried it from f-droid then compile it ( some days ago) from the code changing the size and it was ok. i just opened this issue to improve this
