### ISSUE TITLE
Turn issue

### ISSUE THREAD

**Issue by alexis-loumeau** [juha-h/baresip-studio#110]
I can't make the app work with TURN but i can see the following message 

2020-11-12 17:58:54.966 18159-18199/com.tutpro.baresip D/Baresip Lib: loc with params laddr=192.168.0.22, af=AF_INET, use_rtp=0
    [31mcall: medianat session: Operation not supported on transport end
2020-11-12 17:58:54.966 18159-18199/com.tutpro.baresip D/Baresip Lib: point
2020-11-12 17:58:56.930 18159-18199/com.tutpro.baresip D/Baresip Lib: [;mua: incoming OPTIONS message from sip:428@192.168.178.58 (3.127.138.57:11152)
    ua: using best effort AF: af=AF_INET
    call: al

can you help me to understand "medianat session: Operation not supported on transport endpoint"?

**Comment by juha-h** [comment]
"Operation not supported on transport endpoint" is Linux kernel error message (EOPNOTSUPP).  It comes from some system call, not directly from baresip.  It could come from webrtc_aec.  Try if you get if when you uncheck Acoustic Echo Cancellation in Settings.

Have you tried the same with baresip cli app?

**Comment by juha-h** [comment]
The error message comes from piece of code in src/call/call.c call_alloc() function:
```
/* Initialise media NAT handling */
	if (acc->mnat) {
		err = acc->mnat->sessh(&call->mnats, acc->mnat,
				       dnsc, call->af,
				       acc->stun_host,
				       acc->stun_user, acc->stun_pass,
				       call->sdp, !got_offer,
				       mnat_handler, call);
		if (err) {
			warning("call: medianat session: %m\n", err);
			goto out;
		}
	}
```

**Comment by alexis-loumeau** [comment]
i didn't try baresip cli and i did the test of uncheck Acoustic Echo Cancellation  and the same happened. Did you experiment turn with this app? or is it just bind to baresip code?

Sorry for annoying you, it's a important for me to make it work.

**Comment by juha-h** [comment]
I have never tried to use TURN with baresip, since I don't need TURN.
I'm using rtpengine instead.  I'll setup a TURN server during the next
few days and give it a try.

**Comment by alexis-loumeau** [comment]
thanks you a lot for your help!

**Comment by juha-h** [comment]
Have you configured Media NAT Traversal to value "TURN" or "ICE"?  If I remember correctly, ICE is using TURN too.

**Comment by alexis-loumeau** [comment]
I only used turn

**Comment by juha-h** [comment]
I installed coturn on my Debian host, created an account in it and gave it a try.  Looks like everything worked. I was able to make a call without any errors:
```
11-12 21:05:18.735 20981 21014 D Baresip Lib: call connecting to 'sip:test@<my domain>.com'..
11-12 21:05:18.854 20981 21014 D Baresip Lib: call: media-nat 'turn' established/gathered
11-12 21:05:18.854 20981 21013 D Baresip Lib: ua event (CALL_LOCAL_SDP) offer
11-12 21:05:18.855 20981 21013 D Baresip Lib: sending ua/call 490907752080/491127698448 event call answered
```
Baresip debug showed that media flow went through my turn server:
```
11-12 21:05:26.204 20981 21014 D Baresip Lib: stream: audio: starting RTCP with remote <ip addr of my turn server>:60119
```
Also turn server debug showed that everything went OK.

So hard to tell why your call failed.  Could it be a firewall or authentication issue?

**Comment by juha-h** [comment]
Test with web browser (e.g. at https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) on the same device you have installed baresip that the turn server uri/username/password you have configured in baresip works.

**Comment by alexis-loumeau** [comment]
I'm not sure of what it means but there is a screenshot
![Uploading Screenshot_20201113-111023__01.jpg…]()

**Comment by juha-h** [comment]
You don't have working turn server.  Text on the page tells:

> If you test a TURN server, it works if you can gather a candidate with type "relay".

There is no 'relay' lines in the output.  When I tested my turn server, there was two relay lines.

**Comment by alexis-loumeau** [comment]
must be better like this . isn't it ?

![image](https://user-images.githubusercontent.com/5849697/99079818-bc6ada80-25c0-11eb-9f82-e391c01e4248.png)

**Comment by juha-h** [comment]
Yes, that looks good.  If you use the same turn uri/username/password in baresip, is call still failing?

**Comment by alexis-loumeau** [comment]
On my phone it still not working. So i ask to a colleage to try it and it seems working on his phone, so we will try to work with it for moment.

**Comment by juha-h** [comment]
I'll close this now.  Reopen if you find that something is wrong with baresip's turn implementation.

**Comment by alexis-loumeau** [comment]
Thanks for your help.

**Comment by juha-h** [comment]
I may have found the reason for your issue.  Looks like baresip lib does not currently support `turns`  scheme, i.e., turn request over TLS.  Did you try with `turn:` or `turns:`?  Also the port needs to match the protocol at the server.

**Comment by alexis-loumeau** [comment]
we only use turn: scheme.

**Comment by juha-h** [comment]
LOUMEAU Alexis writes:

> we only use turn: scheme.

OK, that one works in my tests as long as the port is the one at which my
turn server listens at UDP/TCP on that port.
