### ISSUE TITLE
Audio stops after 2 seconds when calling via VPN

### ISSUE THREAD

**Issue by attley86** [juha-h/baresip-studio#118]
Tested with latest baresip and did register & calling towards Asterisk PBX with one announcement number. Without VPN I can register and hear the continuous RTP stream from the PBX nicely, but when I turn on VPN (WireGuard) and restart baresip, I can register but after 200OK message I only hear about 2 seconds of the announcement and after that no audio can be heard via the Baresip client. Audio cuts off for some reason. Same goes with baresip+ when I tested the same scenario. Traced the RTP stream from the UAS machine and verified that Asterisk is pushing RTP packets to the VPN assigned IP which is owned by the phone that is running Baresip. Using Oneplus 8 Android phone with Baresip 23.0.0

**Comment by juha-h** [comment]
On console run 'adb logcat | grep Baresip', then start baresip and make
the call.  Also, tap the Info button on baresip screen during the call
and check if audio flows both ways.

**Comment by attley86** [comment]
Info button during call shows:  PCMA ch1 / PCMA ch1 with 0/0 bit/s speed.

The adb log is quite messy, I will attach it as a file to this post.

[baresip_adb_log_2sec_music.txt](https://github.com/juha-h/baresip-studio/files/5599174/baresip_adb_log_2sec_music.txt)

**Comment by juha-h** [comment]
attley86 writes:

> Info button during call shows:  PCMA ch1 / PCMA ch1 with 0/0 bit/s
> speed.

It shows 0/0 in the beginning of the call.  Try again 5-10 sec later and
then again.

**Comment by attley86** [comment]
Ok, now tried after 10sec from beginning of the call and it shows the same codecs but speed is 63957/0 (bit/s). I cannot hear the announcement besides the 2sec short audible period right after answer. I guess the voice is only active on one direction (UAC->UAS).

**Comment by juha-h** [comment]
attley86 writes:

> Ok, now tried after 10sec from beginning of the call and it shows the
> same codecs but speed is 63957/0 (bit/s). I cannot hear the
> announcement besides the 2sec short audible period right after
> answer. I guess the voice is only active on one direction (UAC->UAS).

Yes, 63957/0 tells that baresip transmits audio, but there is nothing
coming in.

I haven't looked at your adb log yet, but I suspect that the VPN or
network starts to block incoming audio.

**Comment by attley86** [comment]
After some searching it seems that my router was to blame.  

There were other peope too suffering from this kind of issue with this same Router model and with WireGuard VPN:
https://community.ui.com/questions/Paket-loss-with-hwnat-enabled-to-Wireguard-device/e0112b17-ff0b-4348-893c-73b413873209

So after disabling this hardware offloading on the router the RTP is now succesfull in both ways.

Details about this router hw offloading if interested:
https://help.ui.com/hc/en-us/articles/115006567467-EdgeRouter-Hardware-Offloading

So no issue on the Baresip after all. Thanks anyway. I will close this issue.

**Comment by attley86** [comment]
Router related problem (hardware offloading messing up RTP stream). Closing issue.

**Comment by juha-h** [comment]
attley86 writes:

> After some searching it seems that my router was to blame.

Good that the issue got solved.
