### ISSUE TITLE
not successfully answer the call after "answer button" is clicked.

### ISSUE THREAD

**Issue by eric-jswang** [juha-h/baresip-studio#12]
Hi Juha, I tried baresip-studio 5.3.0 (also 5.1.0) many times, and found that it did not pick-up the phone after I clicked "answer button", where the call comes from x86_64/Linux/baresip. 

The logcat shows that baresip-studio was internally answering the call, but the ring tone did not stop until timeout. The log file is attached for your reference.
[baresip_log.txt](https://github.com/juha-h/baresip-studio/files/2720975/baresip_log.txt)

**Comment by eric-jswang** [comment]
In that log file, the Baresip tag is not expanded (printed as I/%s). Attached is a new full logcat file with Baresip tag. Yes, I checked the code again, it's 5.3.0.
[logcat.txt](https://github.com/juha-h/baresip-studio/files/2722455/logcat.txt)

**Comment by juha-h** [comment]
The call was never established.  Perhaps baresip did not receive a proper or any ACK after answering the call?

**Comment by eric-jswang** [comment]
I just have done 2 more testings,

(1) use Antisip app to be the callee, caller is still at baresip/linux side.
     result = Antisip app succeeds to answer the phone and live audio/video are there in either direction.

(2) use Baresip-studio to be the callee, but disable the video capability of the caller.
     result = Baresip-studio succeeds to answer the phone (by click the 'answer button'),
                  and the live audio are there in either direction.

It looks this issue appears in answering video+audio incoming calls, not audio-only one's.

**Comment by eric-jswang** [comment]
Third testing is done,

(3) use 2 Baresip/linux instances as caller and callee. The video capability of callee is set to be disabled, and the video capability of caller is set to be enabled.
result = callee succeeds to answer the phone (by pressing 'a'), and a audio-only call is established.

The "/sysinfo" of the baresip/linux used is,
--- System info: ---
 Machine:  x86_64/linux
 Version:  0.6.0 (libre v0.6.0)
 Build:    64-bit little endian
 Kernel:   Linux eric-ubuntu-16 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64
 Uptime:   8 secs
 Started:  Thu Jan  3 11:11:27 2019
 Compiler: 5.4.0 20160609
 OpenSSL:  OpenSSL 1.0.2g  1 Mar 2016

**Comment by eric-jswang** [comment]
Got it, Thank you very much !
