### ISSUE TITLE
Question on Icon [not a bug]

### ISSUE THREAD

**Issue by gnimor** [juha-h/baresip-studio#121]
I am wondering what is the purpose of the icon in the upper right corner. I didn't find a description/documentation

![image](https://user-images.githubusercontent.com/14901306/101651690-a1637d00-3a3d-11eb-9301-06e82f5dfeea.png)

**Comment by juha-h** [comment]
That is speakerphone toggle.

**Comment by gnimor** [comment]
Thanks for your update.

**Comment by sjlongland** [comment]
Maybe a bullet point explaining those icons in the "Usage hints" section of the "About" page could be good?  The icon didn't mean much to me either.

**Comment by juha-h** [comment]
Stuart Longland writes:

> Maybe a bullet point explaining those icons in the "Usage hints"
> section of the "About" page could be good?  The icon didn't mean much
> to me either.

The icons are standard material design icons, but not all users may be
familiar with them.  I'll add a new bullet point:

  Icons at the bottom of the main screen lead to voicemail (if Voicemail
  URI has been configured for the account), contacts, messages, and call
  history, and allow toggling between numeric and alphanumeric keyboard.

Feel free to suggest improvements.

**Comment by sjlongland** [comment]
Yep, I'd agree with that… but don't forget the _other_ icons up the other end of the screen, like the one that prompted this bug.

You'd be right that I don't memorise the name of each Material Design icon. :-)

**Comment by juha-h** [comment]
I now have these new bullet points:

-  Swipe left/right gesture toggles between the accounts.
-  Icon at the top of the main screen toggles speakerphone.
-  Icons at the bottom of the main screen lead to voicemail (if Voicemail URI has been configured for the account), contacts, messages, and call history, and allow toggling between numeric and alphanumeric keyboard.
