### ISSUE TITLE
Automatic call recording

### ISSUE THREAD

**Issue by adatum** [juha-h/baresip-studio#123]
Thanks for this solid SIP client. 

Is there an option to automatically record calls? If not, would it be possible to implement this feature?

**Comment by gdt** [comment]
In many jurisdictions, you have to provide notice and an opportunity for the other party to disconnect before recording.  Even if this isnt' the law, it's common decency.   A feature to record before the human concludes that process is complete seems like a recipe for trouble, so I'm basically opposed.

**Comment by adatum** [comment]
Several other SIP clients have this optional feature, eg. CSipSimple. 

As for jurisdiction and courtesy, many areas have single-party consent laws, such as where I live. Plus, many organizations automatically records calls and (some?) have the "courtesy" of informing the caller, without giving a choice in the matter other than to hang up. IMO giving the user this same option is just leveling the playing field, and potentially helpful in avoiding trouble (eg. being able to prove details in contract negotiations), not causing it.

**Comment by juha-h** [comment]
I personally don't like the idea that someone is recording my calls without telling me about it.  In my country also law requires a pre-call announcement if the call is recorded.

Currently baresip cli client does not have recording capability and it may not exist in the lib either.

For these reasons, I not going to add this feature to my TODO list.

Last time I checked, CSipSimple was not supported anymore.  Perhaps some supported SIP client, e.g. Linphone, has this feature.

**Comment by adatum** [comment]
> Currently baresip cli client does not have recording capability and it may not exist in the lib either.

It is listed as a featue of baresip. I'm not sure but it may be via the sndfile module. 
https://github.com/baresip/baresip
>     Call features:
>         [...]
>         Call recording
>         [...]

I can understand if you do not want to implement a functionality to which you object. Such is the beauty of open source.

Correct, CSipSimple is no longer maintained, but it still works. Linphone has a button to record calls. Zoiper has automatic call recording in paid versions. My voip provider has the option to automatically record calls and store them on their servers and even transcribe them. etc.

Personally, I don't like it either, (I don't even keep chat logs) but personal preference does not prevent others from doing it. So, I think it's just a matter of time before someone implements it because anyone who does not have this feature is just disadvantaging themselves in favor of those who do, and it is already widespread.

**Comment by adatum** [comment]
Now that the baresip-studio app has implemented a call recording feature for the next (outgoing?) call, would you consider adding automatic call recording as an option? Calls that would need to be recorded are often incoming calls.

**Comment by juha-h** [comment]
adatum writes:

> Now that the baresip-studio app has implemented a call recording
> feature for the next (outgoing?) call, would you consider adding
> automatic call recording as an option? Calls that would need to be
> recorded are often incoming calls.

If recording icon is ON, then also next incoming call will be recorded.
So you would like to have an account option that turns recording icon
ON automatically?

**Comment by adatum** [comment]
Good to know that the next incoming call as well as outgoing call is recorded when the recording icon is selected.

Either of these would be suitable: 
1) an account option that turns the recording option ON and keeps it ON
2) simply keep the call recording icon ON when the user turns it ON until the user manually toggles it OFF, instead of automatically turning it OFF after a call

**Comment by juha-h** [comment]
adatum writes:
> 
> Either of these would be suitable: 
> 1) an account option that turns the recording option ON and keeps it ON
> 2) simply keep the call recording icon ON when the user turns it ON
> until the user manually toggles it OFF, instead of automatically
> turning it OFF after a call

PR https://github.com/juha-h/baresip-studio/commit/704b97aa10e6ad1f095a6b8bdcd20055d9b5ffd7
implemented the latter.

**Comment by adatum** [comment]
> PR [704b97a](https://github.com/juha-h/baresip-studio/commit/704b97aa10e6ad1f095a6b8bdcd20055d9b5ffd7) implemented the latter.

That's wonderful!

Where are the recording files stored? It's useful, even necessary, to be able to sort recordings by date or file size for cleanup occasionally. You could implement more detailed ways of handling this in the app, or just let the user do it with a file manager.

Couple of optional suggestions: 
1) The `radio_button_checked` icon might be more recognizable as a record button than the current `record_voice_over` icon
2) Showing a button's enabled or disabled state might be more intuitive if the disabled color is a faded color like a gray or an icon with a slash. The current implementation of white (disabled) and red (enabled) colors it isn't particularly intuitive, at least to me.

**Comment by juha-h** [comment]
adatum writes:

> Where are the recording files stored? It's useful, even necessary, to
> be able to sort recordings by date or file size for cleanup
> occasionally. You could implement more detailed ways of handling this
> in the app, or just let the user do it with a file manager.

There are two files for each call: encoder and decoder file. baresip
plays them simultaneously when recording is played in the app.  I have not
found any Android API calls what would allow merging the two files into
one.

I'm thinking to add possibility to delete a single call including its
recording from history, but don't want to spend much more time with
recordings.  baresip app is not meant for a call center.

> Couple of optional suggestions: 
> 1) The `radio_button_checked` icon might be more recognizable as a
> record button than the current `record_voice_over` icon

baresip is using google material design icons listed on wiki page.

> 2) Showing a button's enabled or disabled state might be more
> intuitive if the disabled color is a faded color like a gray or an
> icon with a slash. The current implementation of white (disabled) and
> red (enabled) colors it isn't particularly intuitive, at least to me.

I have no plans to start redoing the icons.

**Comment by adatum** [comment]
> There are two files for each call: encoder and decoder file. baresip plays them simultaneously when recording is played in the app. I have not found any Android API calls what would allow merging the two files into one. I'm thinking to add possibility to delete a single call including its recording from history, but don't want to spend much more time with recordings. baresip app is not meant for a call center.

I imagine `baresip`'s audio modules probably provide the required capabilities. 

"you can use the `sndfile` module to write WAV files":  https://github.com/baresip/baresip/issues/333#issuecomment-350542837

For example, CSipSimple stores its recordings as WAV files in `/storage/emulated/0/CSipSimple/records/`. If you do something similar, it will be simple for a user to manage recordings with a file manager without requiring you to develop recording deletion capabilities in the app.

> Couple of optional suggestions: 1) The `radio_button_checked` icon might be more recognizable as a record button than the current `record_voice_over` icon
> baresip is using google material design icons listed on wiki page.

I gave you the icon names from google material design.

> I have no plans to start redoing the icons.

That's fine with me, though keep in mind the UI/UX is a major factor in attracting or repulsing a user base.
