### ISSUE TITLE
UI improvement suggestions

### ISSUE THREAD

**Issue by adatum** [juha-h/baresip-studio#124]
A few thoughts/requests about the UI:

- option to keep the dial pad displayed on the main screen instead of having to tap the input field, which brings up an alphabetic keyboard before being able to switch to a numpad
- have `*` and `#` on the main screen of the numpad with the numbers, instead of on a second screen with other special characters, since these keys are sometimes needed on calls
- option to prevent automatic screen rotation on baresip
- button to easily disable/de-register an account without deleting it or going deep inside the account settings (btw, love the ability to easily switch between accounts before making calls) 
- dark mode... not a priority, but it would be nice to be easier on the eyes

**Comment by juha-h** [comment]
Thanks for the suggestions.  When time permits, I'll take a closer look.

Disabling an account is pretty easy:  just touch the account's dot on the main page, un-check Register, and save.

**Comment by juha-h** [comment]
I created Feature Request wiki page and put these there with the exception of disabling/enabling an account, since can be already done with three touches.

**Comment by juha-h** [comment]
I added some comments to the feature requests in the wiki after I had taken a look at the requests.

**Comment by juha-h** [comment]
Remove rotation feature request, since it is better to use an app, such as Auto Auto-Rotate, to control rotation of all apps.

**Comment by juha-h** [comment]
There is now preliminary dark theme support in latest version.
