### ISSUE TITLE
Audio stream used by baresip

### ISSUE THREAD

**Issue by adatum** [juha-h/baresip-studio#125]
baresip is not using the phone audio stream (phone icon) and thus I cannot adjust the volume with the volume buttons. It is using another stream with a music note icon (music or media stream?) so it takes extra steps to change the volume.

On another note, I had some significant echo which I resolved by reducing the volume, but the echo cancellation option in the Audio settings didn't seem to make much difference. It probably unrelated to the audio stream, but thought I'd just mention it anyway.

**Comment by juha-h** [comment]
I have not been able to figure out, why baresip volume is controlled by media volume, not by call volume.  When call starts, I set AudioManager mode
```
am.mode = AudioManager.MODE_IN_COMMUNICATION
```
and
```
am.requestAudioFocus(AudioAttributes.USAGE_VOICE_COMMUNICATION)
```
Still volume is controlled by media.

I'll keep investigating.

What comes to echo cancellation, baresip is using WebRTC AEC for that.  Looks like it works better on some devices/Android versions than others.  In case of problems, the "solution" is (as you tell) to reduce media volume.

**Comment by adatum** [comment]
Ok, at least I know it's a known issue and not a configuration problem on my part.

**Comment by juha-h** [comment]
I just made a commit that in the Android 9 and 10 devices that I have access to, makes the volume keys by default control ring volume when call is coming in and media volume when call is connected.   This may not work in all devices, since according to Android developer documentation:

> It is not guaranteed that the hardware volume controls will always change this stream's volume (for example, if a call is in progress, its stream's volume may be changed instead). 

I would appreciate if you could let me know if it works for you.  If you don't roll your own baresip, I'll make a new release in a day or two.

**Comment by adatum** [comment]
Sure, I'll let you know when the update arrives through F-Droid.

**Comment by juha-h** [comment]
Tested this today with friend's Motorola Android 8.1.0 device and volume keys worked by default OK both during ringing and connected call.

**Comment by adatum** [comment]
I can confirm that with baresip v24.1.0 from F-Droid, the volume buttons now adjust the ringing volume during ringing and the call audio volume during a call. Thanks for the quick fix!
