### ISSUE TITLE
Voicemail URI?

### ISSUE THREAD

**Issue by adatum** [juha-h/baresip-studio#127]
Sorry for what might be a silly question, but what is a voicemail SIP URI? I asked my voip provider and they didn't know what I was talking about, and said the client software should just have a checkbox to subscribe to MWI. 

I tried `mynumber@sip.provider.com` which did not work for voicemail or MWI. 

I also tried `*98@voipserver.com` which works for retrieving voicemails if in baresip I tap the voicemail icon and select "Listen" on the popup. However, the popup claims there are no messages when in fact there are. There is also no notification, but I suppose that is to be expected if the app is not aware of the messages.

**Comment by juha-h** [comment]
There is no standard for voicemail URI. it depends on your SIP provider.  Call to voicemail is a regular SIP call.  If you call and there is no messages, baresip cannot do anything about it.

What comes to voicemail notifications, baresip sends SIP SUBSCRIBE message to the given  voicemail URI and then, if the provider supports voicemail subscriptions, starts to send back NOTIFY messages for each new voicemail.

You can trace the messages with` logcat | grep Baresip` if you check `SIP Trace` setting.

**Comment by adatum** [comment]
I'm not familiar with voicemail URI, but apparently neither is my voip provider. Every other app I've used just has a checkbox to enable/disable MWI and maybe specify the star code to enter the mailbox. 

As mentioned, if using something like `*98@voipserver.com `, I still don't get voicemail notifications, but the voicemail icon does succeed in accessing the mailbox.

It would be good to know if others face the same situation I described or if it's just my device and/or configuration.

**Comment by juha-h** [comment]
Did you try trace what happens when baresip at start sends MWI SUBSCRIBE message?  It should get back 200 OK followed by NOTIFY message.  Perhaps you are getting back some error response.

**Comment by adatum** [comment]
```
mwi: subscribing to messages for sip:[account]@[voipserver]:5061
mwi: subscription for sip:[account]@[sip_provider]:5061 closed: Connection timed out (0 )
```

The voicemail URI I entered is `*97@[voipserver]`.

I am using TLS/SRTP which requires use of port 5061 for my provider. I wonder if that could be a complication. 

Btw, MWI with other apps works fine. I have an unopened test voicemail for which CSipSimple shows a notification, but not Baresip.

**Comment by juha-h** [comment]
It can be TLS related.  Have you specified Outbound Proxy for the account?  If yes, SUBSCRIBE should be sent there and TLS would be used if Outbound URI has form sip:[voipserver]:5061;transport=tls or if DNS NAPTR/SRV records point to that URI.

**Comment by adatum** [comment]
> Have you specified Outbound Proxy for the account?

No I have not. I am not familiar with proxy settings nor have I needed to use them with other clients.

**Comment by juha-h** [comment]
adatum writes:

> > Have you specified Outbound Proxy for the account?
> 
> No I have not. I am not familiar with proxy settings nor have I needed to use them with other clients.

In that case, baresip sends the request according to NATPR/SRV records.
It is hard for me to figure out what is happening unless I see them.

You could try to with Outbound Proxy setting of the form what I
suggested just to check if that works.

**Comment by adatum** [comment]
I entered Outbound Proxy in the form of `sip:[voipserver]:5061;transport=tls` and it worked! Now the voicemail icon is red and tapping on it shows a popup informing of a new message. Is that the only indication expected? Any notification LED, or status bar icon, or lock screen notification?

Here is part of the logcat:

```
Baresip : Handling service event 'mwi notify' for [number]
Baresip Lib: ua event (MWI_NOTIFY) Messages-Waiting: yes
Baresip Lib: Message-Account: sip:asterisk@[voipserverIP];transport=TLS
Baresip Lib: Voice-Message: 1/0 (0/0)
Baresip Lib: 
Baresip Lib: sending ua/call [number]/0 event mwi notify,Messages-Waiting: yes
Baresip Lib: Message-Account: sip:asterisk@[voipserverIP];transport=TLS
Baresip Lib: Voice-Message: 1/0 (0/0)
Baresip Lib: 
Baresip Service: got uaEvent mwi notify,Messages-Waiting: yes
Baresip Service: Message-Account: sip:asterisk@[voipserverIP];transport=TLS
Baresip Service: Voice-Message: 1/0 (0/0)
Baresip Service: /sip:[account]@[voipserver]:5061/0
Baresip : Handling service event 'mwi notify' for [number]
Baresip Lib: ua event (REGISTER_OK) 200 OK
Baresip Lib: sending ua/call [number]/0 event registered
Baresip Service: got uaEvent registered/sip:[account]@[voipserver]:5061/0
```

I have no idea what was necessary or why. It would be good to make this process more straightforward or user friendly. 
At least we know the MWI function is working.

**Comment by juha-h** [comment]
adatum writes:

> I entered Outbound Proxy in the form of
> `sip:[voipserver]:5061;transport=tls` and it worked! Now the voicemail
> icon is red and tapping on it shows a popup informing of a new
> message. Is that the only indication expected? Any notification LED,
> or status bar icon, or lock screen notification?

Red voicemail icon is the only notification.  I could at some point try
to add missed call status notification.

> I have no idea what was necessary or why. It would be good to make
> this process more straightforward or user friendly.  
> At least we know the MWI function is working.

My baresip is able to send SUBSCRIBE over TLS without Outbound Proxy
being set.

Are you using TLS also with the other SIP UAs that work without outbound
proxy being set?

I'm suspecting that something is wrong with NAPTR/SRV records of your
SIP UA domain.

**Comment by juha-h** [comment]
Here is how NAPTR records and SRV record for TLS are configured for my domain:
```
$ host -t naptr tutpro.com
tutpro.com has NAPTR record 100 10 "s" "SIPS+D2T" "" _sips._tcp.tutpro.com.
tutpro.com has NAPTR record 102 10 "s" "SIP+D2U" "" _sip._udp.tutpro.com.
tutpro.com has NAPTR record 101 10 "s" "SIP+D2T" "" _sip._tcp.tutpro.com.
$ host -t srv _sips._tcp.tutpro.com.
_sips._tcp.tutpro.com has SRV record 0 0 8003 box.tutpro.com.
```
NAPTR records tell the desired priority order for transport protocols and SRV record(s) of a transport protocol tell the servers and their priority.

Compare to yours.

**Comment by juha-h** [comment]
Just to add to the above, if there is no SIP NAPTR records for the domain, this will happen (RFC 3263):

`If no NAPTR records are found, the client constructs SRV queries for
   those transport protocols it supports, and does a query for each.
   Queries are done using the service identifier "_sip" for SIP URIs and
   "_sips" for SIPS URIs.  A particular transport is supported if the
   query is successful.  The client MAY use any transport protocol it
   desires which is supported by the server.`

So if your domain does not have SIP NAPTR records, there is no guarantee that TLS will be used.

**Comment by adatum** [comment]
> Are you using TLS also with the other SIP UAs that work without outbound
proxy being set?

By SIP UAs do you mean other SIP clients/apps? 
I am using TLS with multiple accounts with CSipSimple and it works without configuring proxies.

> Compare to yours.

Both a computer running linux and the android phone using termux got the same result:
```
$ host -t naptr tutpro.com
tutpro.com has NAPTR record 102 10 "s" "SIP+D2U" "" _sip._udp.tutpro.com.
tutpro.com has NAPTR record 101 10 "s" "SIP+D2T" "" _sip._tcp.tutpro.com.
tutpro.com has NAPTR record 100 10 "s" "SIPS+D2T" "" _sips._tcp.tutpro.com.
```
For `$ host -t srv _sips._tcp.tutpro.com.` the computer got:
`_sips._tcp.tutpro.com has no SRV record` but the phone shows: `_sips._tcp.tutpro.com has SRV record 0 0 8003 box.tutpro.com.`


I have no idea what any of this means..

**Comment by juha-h** [comment]
I meant, try what you get when you use your domain:
```
$ host -t naptr <domain of your sip uri>
$ host -t  <uri from "SIPS+D2T" naptr result>
```

**Comment by adatum** [comment]
I'm not sure what the domain of the SIP URI is, but I tried:

```
$ host -t naptr voip.ms
voip.ms has no NAPTR record
```
and also `[POP].voip.ms`, with the same result. 

This has something to do with the provider's configuration? 

The account portal when logged in on the voip.ms website has an indicator when TLS is being used. TLS is indicated with baresip and the proxy configured, as well as with CSipSimple without the proxy.

**Comment by juha-h** [comment]
It your domain does not have NAPTR records, baresip looks for SRV records, but as the RFC specifies, it can choose any of them, i.e., it does not need to choose the TLS one.

Just for curiosity, check if your domain has SIP SRV records:
```
$ host -t srv _sips._tcp.<domain of your SIP URI>
$ host -t srv _sip._tcp.<domain of your SIP URI>
$ host -t srv _sip._udp.<domain of your SIP URI>
```

**Comment by adatum** [comment]
> Just for curiosity, check if your domain has SIP SRV records:

I don't know if the SIP URI is correct, but here's what I get:

```
$ host -t srv _sips._tcp.voip.ms
_sips._tcp.voip.ms has no SRV record

$ host -t srv _sip._tcp.voip.ms
_sip._tcp.voip.ms has no SRV record

$ host -t srv _sip._udp.voip.ms
_sip._udp.voip.ms has no SRV record

```

and again the same result with `<domain of your SIP URI>` = `[POP].voip.ms`

**Comment by juha-h** [comment]
So voip.ms does not provide NAPTR or SRV records.  In this kind of situation, there is no guarantee, which transport protocol a SIP User Agent (client) will use.  If you want to force TLS, configure outbound proxy(s).

I'll close this now, since baresip s working according to standards.
