### ISSUE TITLE
Connection alive issue

### ISSUE THREAD

**Issue by kairavi-magnates** [juha-h/baresip-studio#128]
Hello,

I need help with an issue of connection alive.

I am able to register the app with SIP server. And quickly after registration I can make/receive call. But after some time although registration indication stays green but I can not make/receive any call. I think connection is getting lost with SIP server instead of staying alive. Any idea?

**Comment by juha-h** [comment]
If you are behind NAT and using UDP transport, your SIP proxy/registrar should keep the NAT binding alive by sending, e.g., OPTIONS requests frequently enough.  If you are using TCP or TLS (like you should), TCP keepalive messages are sent automatically and the connection should stay open.

**Comment by kairavi-magnates** [comment]
We are using UDP transport. So just wanted to know that is there any configuration provided in baresip application to enable/set time to keep alive NAT binding?

**Comment by juha-h** [comment]
No, there isn't.  In theory it could be possible to create a thread that would send OPTIONS requests at a given interval, but normally that is the task of the SIP Proxy/Registrar.  That would increase power consumption of the app. Also, UDP is not a recommended transport.  Ask your provide to support TCP/TLS.

**Comment by kairavi-magnates** [comment]
Thanks for the explanation. I will check with SIP Proxy/Registrar.
