### ISSUE TITLE
Feature Request: Video resolution and codec

### ISSUE THREAD

**Issue by cananda** [juha-h/baresip-studio#133]
Hello,

I see baresip+ supporting 1280x720 and was wondering if it could also add 1920x1080 resolution.

Also, add h265 codec support?

Thanks!

**Comment by juha-h** [comment]
cananda writes:

> I see baresip+ supporting 1280x720 and was wondering if it could also
> add 1920x1080 resolution.

It would just be a matter of adding "1920x1080" to the list ConfigActivity.kt:

  val sizes = arrayListOf("640x360", "640x480", "800x600", "960x720", "1024x768", "1280x720")

I haven't tested that on my devices, but will give it a try.

> Also, add h265 codec support?

Most likely that could also be done.

I'll add both of these to the the Wiki Feature Requests page.

**Comment by juha-h** [comment]
Added these two to Wiki/Feature Requests page.

**Comment by juha-h** [comment]
H.265 codec (as well as AV1) and resolution "1920x1080" are now supported.
