### ISSUE TITLE
No DTMF tones

### ISSUE THREAD

**Issue by MisterY** [juha-h/baresip-studio#134]
DTMF doesn't work for me. The keypad shows up but never send any tones, no matter what I type. 
I can't find any instructions on how to use it, either. Works in many other VoIP clients.

Makes it impossible to listen to voicemail and navigate the automated phone systems.

**Comment by juha-h** [comment]
I cannot reproduce this. Just tested with version 26.0.0 and sending DTMF worked fine.  This is what Linux baresip app received when I sent DTMF digits from Android app:
```
received event: '2' (end=0)/0 (bit/s) efps=0.0/0.0    
received event: '2' (end=1)/0 (bit/s) efps=0.0/0.0    
received event: '1' (end=0) video=0/0 (bit/s) efps=0.0/0.0    
received event: '1' (end=1)
received event: '3' (end=0) video=0/0 (bit/s) efps=0.0/0.0    
received event: '3' (end=1)
```

**Comment by MisterY** [comment]
The version number prompted some comparison on my side. I had the F-Droid version of baresip+ (not sure if that should be in a separate repository), 9.0.0. Then I managed to upgrade to Play Store version, 10.0.0, by backing up the settings.
However, that did not change anything in relation to DTMF sending. Tried to check the voicemailbox and it did not react to any number commands, just like before.
Could you tell me how I'm supposed to send the tones and whether this issue should be recorded in a different repo (I got to this one through a search engine but now I see there are others, including the one for the app)? Thanks

**Comment by juha-h** [comment]
I just tested with baresip+ version 10.0.0 from Play store.  I called The Test Call that is in the factory default Contact.  There is DTMF test and it worked fine.

**Comment by MisterY** [comment]
I get "503, the call failed" when trying to make the test call.

**Comment by juha-h** [comment]
Alen Siljak writes:

> I get "503, the call failed" when trying to make the test call.

503 means "Service Unavailable".  Either your device or your outbound
SIP proxy (if you have configured one) does not have access to the URI
of the contact (sip:thetestcall@opensips.org).  This is not an issue
with baresip app.

**Comment by MisterY** [comment]
Great, thanks. Uninstall.
