### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by zolfone** [juha-h/baresip-studio#139]
Hi @juha-h,
I've compiled the app in android studio from source without any modifications (first I copied the compiled libbaresip to distribution), but when I run it through run->run app it crashes with these errors ([here is the full log](https://pastebin.com/1ASH7XiZ)):

```
E/libc: Access denied finding property "net.dns1"

Access denied finding property "net.dns2"

Access denied finding property "net.dns3"

Access denied finding property "net.dns4"
```

I tried with two different devices with two different android versions (8 and 9) but the error is the same.
I thought it was a mismatching NDK version for android 8 so I switched from 28 to NDK 27 but the compilation fails:

```
/home/user/.gradle/caches/transforms-2/files-2.1/4629cac30e493d029221c9668d14f8d5/material-1.2.1/res/values/values.xml:1071:5-1082:11: AAPT: error: style attribute 'android:attr/dialogCornerRadius' not found.
    
/home/user/.gradle/caches/transforms-2/files-2.1/4629cac30e493d029221c9668d14f8d5/material-1.2.1/res/values/values.xml:3235:5-3242:23: AAPT: error: resource android:attr/lineHeight not found.
    
/home/user/.gradle/caches/transforms-2/files-2.1/4629cac30e493d029221c9668d14f8d5/material-1.2.1/res/values/values.xml:3243:5-3247:23: AAPT: error: resource android:attr/lineHeight not found.
```

I'm really new to android-studio so maybe I'm missing something basic here, please advice.
EDIT: installing baresip from the Play Store runs fine.

Thanks

**Comment by juha-h** [comment]
Check that the source you are using includes this fix: [https://github.com/juha-h/baresip-studio/commit/8c4a5321f6a1caf52346cef3bba75c2c444e0e18](url)

**Comment by juha-h** [comment]
"net.dnsX" errors can be ignored.  Newer Android version don't allow access to system dns servers.

**Comment by zolfone** [comment]
with that fix now it works, I didn't have it because I got the source code with git clone more than a week ago.

Thanks
