### ISSUE TITLE
For metadata usage

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#14]
...please rename folder from: `fdroid/repo/com.tutpro.baresip` to `fastlane/metadata/android`

Ref: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#changelogs-whats-new

**Comment by juha-h** [comment]
Licaon_Kter writes:

> ...please rename folder from: `fdroid/repo/com.tutpro.baresip` to
> `fastlane/metadata/

Done.
