### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by jspricke** [juha-h/baresip-studio#149]
Hi, your last release fails to build on F-Droid, can you have a look?
```
/home/vagrant/build/com.tutpro.baresip/app/src/main/res/values-el/strings.xml:4: Error: "baresip_link" is translated here but not found in default locale [ExtraTranslation]
    <string name="baresip_link">
            ~~~~~~~~~~~~~~~~~~~
/home/vagrant/build/com.tutpro.baresip/app/src/main/res/values-nb-rNO/strings.xml:4: Error: "baresip_link" is translated here but not found in default locale [ExtraTranslation]
    <string name="baresip_link">
            ~~~~~~~~~~~~~~~~~~~
```
https://monitor.f-droid.org/builds/log/com.tutpro.baresip/161

**Comment by juha-h** [comment]
Jochen Sprickerhof writes:

> Hi, your last release fails to build on F-Droid, can you have a look?
> ```
> /home/vagrant/build/com.tutpro.baresip/app/src/main/res/values-el/strings.xml:4: Error: "baresip_link" is translated here but not found in default locale [ExtraTranslation]
>     <string name="baresip_link">
>             ~~~~~~~~~~~~~~~~~~~
> /home/vagrant/build/com.tutpro.baresip/app/src/main/res/values-nb-rNO/strings.xml:4: Error: "baresip_link" is translated here but not found in default locale [ExtraTranslation]
>     <string name="baresip_link">
>             ~~~~~~~~~~~~~~~~~~~
> ```

OK, I'll try to use Weblate to remove the unused strings.  If I do it
directly in the repo it usually means trouble.  Weblate somehow goes out
of sync and I don't know how to fix it.

**Comment by juha-h** [comment]
I did not know how to remove the strings in weblate to I removed them in
the repo and then did pull in weblate.

I'm working on a new version, which is about ready to go.  Just waiting
a user to do final testing.

F-Droid build of that should then work.

**Comment by juha-h** [comment]
New versions 15.2.0 and 29.2.0 now exists.
