### ISSUE TITLE
baresip+ refusing incoming calls

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#150]
baresip+ 16.0.0 on calyxOS (AOSP 11)

I'm able to make outgoing calls.  However, people calling me don't get through.  What they hear varies.  My voip provider says they see the calls come through but that baresip+ is refusing them.  They say the reason the callers hear different things is because their providers all handle refused calls differently.

I'm not sure I understand what refusing a call means or why an app would do that.  My look at general settings and at the settings for the  voip account in question didn't show anything obvious to me.  Can you help me figure this out?

Thank you

**Comment by juha-h** [comment]
You can try to find out why incoming calls are refused by turning on
debug in setting and then check what logcat gives.  See Wiki/Debug.

**Comment by znoteer** [comment]
Hi,

On Sun, Apr 11, 2021 at 10:33:33PM -0700, juha-h wrote:
> You can try to find out why incoming calls are refused by turning on
> debug in setting and then check what logcat gives.  See Wiki/Debug.

Didn't do anything -> Tried making a call:  Call refused.
Turn on USB debugging -> try call: call refused.

I'm confused by all the IPs in the logcat output, so...

On baresip+ phone, open browser to whatsmyip.com to help figure out where
baresip is in logcat output -> try calling: call ACCEPTED, with good sound
on both ends!

Turn off USB debugging and dev mode -> try calling : call refused
Turn USB debugging back on -> try calling: call accepted
Turn off USB debugging -> try calling: call accepted

Logcat output doesn't seem to survive shutting down USB debug mode, so I
don't have any output of the call that was refused when USB debug output was
available.  All other times I've had debug mode turned on, the calls have
gone through (well rang at least, I only answered and sound-checked one
call).

Is this caused by impossible-to-track-down gremlins, or is there something
else I can do to try to help debug this?

-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
If device is connected to USB port of Linux device and Android device
has USB debugging enabled, terminal command

$ adb logcat | grep Baresip

shows baresip related debug messages when a call is made or answered.

I don't know (and don't want to know) anything about adb debugging on
any proprietary operating system.

**Comment by znoteer** [comment]
On Mon, Apr 12, 2021 at 07:17:12AM -0700, juha-h wrote:
> If device is connected to USB port of Linux device and Android device
> has USB debugging enabled, terminal command
> 
> $ adb logcat | grep Baresip
> 
> shows baresip related debug messages when a call is made or answered.

Yes, that is what I tried, only it all of a sudden baresip started accepting
calls while I was playing in debug mode and I didn't understany why.  For
days it wasn't accepting calls.  It is very curious to me.  I thought you
might have some idea why debug mode made it work, that's all.

> I don't know (and don't want to know) anything about adb debugging on
> any proprietary operating system.

No proprietary OSes involved.  I'm not sure where that idea comes from. 
Debian Stable on the adb terminal end, and CalyxOS a deg00gled fork of AOSP
11 on the phone running baresip+.

Thank you,

-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
znoteer writes:

> Yes, that is what I tried, only it all of a sudden baresip started accepting
> calls while I was playing in debug mode and I didn't understany why.  For
> days it wasn't accepting calls.  It is very curious to me.  I thought you
> might have some idea why debug mode made it work, that's all.

Sorry, don't know.  Turning on debug only activates log messages and
does not change any other behavior.

> > I don't know (and don't want to know) anything about adb debugging on
> > any proprietary operating system.
> 
> No proprietary OSes involved.  I'm not sure where that idea comes
> from.

Good, I didn't know which OS you used in your computer.

**Comment by znoteer** [comment]
On Mon, Apr 12, 2021 at 10:33:11AM -0400, Znoteer wrote:
> On Mon, Apr 12, 2021 at 07:17:12AM -0700, juha-h wrote:
> > If device is connected to USB port of Linux device and Android device
> > has USB debugging enabled, terminal command
> > 
> > $ adb logcat | grep Baresip
> > 
> > shows baresip related debug messages when a call is made or answered.
> 
> Yes, that is what I tried, only it all of a sudden baresip started accepting
> calls while I was playing in debug mode and I didn't understany why.  For

Calls are being refused again.

I've activated debugging, but the output is quite overwhelming.  There seems
to be stuff every few seconds, especially keepalive activity.  Also, there
are lots of bits of personal information that I will want to santize before
posting the output.

I was wondering if you could help me identify what I'm looking for so I
don't send a bunch of useless output, and spend time santizing useless
output.  What does the beginning of incoming call look like?  For example,
the keepalive stuff all seems to begin with:

---- begin snippet -----
04-14 16:27:29.562  4260  4730 D Baresip Lib: UDP someIP:port -> anotherIP:someotherport
---- end snippet -----

Is there some similar way to detect the beginning of a call attempt?

Thanks,

-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
Output should not be overwhelming if you filter output:
```
$ adb logcat | grep Baresip
```
that is, filter out everything else except Baresip messages.

**Comment by juha-h** [comment]
Closing this due to lack of further info.
