### ISSUE TITLE
baresip+ not reacting to proximity sensors, screen stays on

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#151]
baresip+ 16.0.0 on CalyxOS (AOSP 11)

When I bring the phone close to my face after pressing the dial icon to initiate a call, the screen stays lit up and  reacts to contact with my cheek.  This frequently leads me to unwanted things.

I don't see anything in Settings that seems related to this.  Is there something that can be done to deactivate the screen when it is near my head?

Thanks,

**Comment by juha-h** [comment]
Thanks for reporting.  This is now fixed in master and the fix will be
included in the next release.

**Comment by juha-h** [comment]
Fixed.

**Comment by znoteer** [comment]
Hello,

On Mon, Apr 12, 2021 at 12:28:39AM -0700, juha-h wrote:
> Thanks for reporting.  This is now fixed in master and the fix will be
> included in the next release.

Thank you for the rapid fix!  How often do you release?

-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
znoteer writes:

> Thank you for the rapid fix!  How often do you release?

I just created a new release (16.1.1).  It will take one-two days to
show up in Google Play.

**Comment by znoteer** [comment]
On Mon, Apr 12, 2021 at 07:18:04AM -0700, juha-h wrote:
> znoteer writes:
> 
> > Thank you for the rapid fix!  How often do you release?
> 
> I just created a new release (16.1.1).  It will take one-two days to
> show up in Google Play.

Nice! I hope F-Droid is updated as quickly since that's where I got baresip+

Thanks for you help

-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
znoteer writes:

> Nice! I hope F-Droid is updated as quickly since that's where I got baresip+

I also activated F-Droid build, but it usually takes longer than one-two
days before the build takes place.
