### ISSUE TITLE
baresip+ appears not to use TLS

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#153]
I've selected SRTP-MAND on my phone and selected encrypted SiP traffic on my portal at my provider.  However, if I look at my connection on the portal it tells me that the transport is UDP rather than TLS.  If I turn on debug and sip trace and look at the output I see entries such as "UDP <ip address> -> <some other ip address>"  I don't see anything about encryption in the output, though I admit not knowing exactly what to look for.  Am I doing something wrong, or is this normal?

If this is normal, how can I know if baresip is connecting via encryption, or in the clear?

**Comment by juha-h** [comment]
SRTP-MAND is media encryption protocol.  If you want to force TLS for SIP traffic, define an outbound proxy with ;transport=tls parameter or use ;transport=tls in SIP URI of the callee.

**Comment by juha-h** [comment]
Please close when issue has been dealt with.

**Comment by znoteer** [comment]
Sorry, I thought srtp-mand was mandatory srtp.

So, it's not at the account level but at a proxy level that one enforces TLS
for sip traffic?  

It's not just outbound I'm after.  If someone calls my sip number, I want
anything between my provider's server and baresip+ to be encrypted.  Will a
proxy handle incoming as well?


On Tue, Apr 27, 2021 at 07:58:02AM -0700, juha-h wrote:
> SRTP-MAND is media encryption protocol.  If you want to force TLS for SIP traffic, define an outbound proxy with ;transport=tls parameter or use ;transport=tls in SIP URI of the callee.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/juha-h/baresip-studio/issues/153#issuecomment-827672979

-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
If you define outbound proxy with tls transport and register with your sip proxy, then your sip proxy will send requests to baresip over tls.  You can check this by turning on sip trace in settings.

**Comment by znoteer** [comment]
On Wed, Apr 28, 2021 at 07:43:45AM -0700, juha-h wrote:
> If you define outbound proxy with tls transport and register with your sip
> proxy, then your sip proxy will send requests to baresip over tls.  You
> can check this by turning on sip trace in settings.


I'm not sure I understand entirely this proxy.  I see in the account
settings a place to enter a url for a proxy server.  Do I need to set up a
box with some kind of proxy server software on it?  If not, to what server
to I point that proxy url in the account settings?


-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
I don't know in what kind of  SIP environment you are.  Outbound proxy has been defined in RFC 5626.  Usually you set Outbound proxy to point to your registrar that also acts as your SIP Proxy.  Please ask general SIP related questions on some SIP related mailing list.
