### ISSUE TITLE
No audio in DND mode

### ISSUE THREAD

**Issue by golserma** [juha-h/baresip-studio#162]
If I set my android phone to DND mode I can't hear anything if I start a call.
I think there is a workaround for this since other phone applications don't do this.
Would be great if you could fix this :) Great app BTW

**Comment by juha-h** [comment]
I tested incoming call with Linphone and it was ringing even when device was in "Do not disturb mode", which it should not do. baresip didn't ring, but as you noticed, I was not able to hear the other party after answering.  I'll investigate.

**Comment by juha-h** [comment]
In my Android 9 device I went to Settings -> Sound -> Do Not Disturb -> Sound & Vibration and turned on Media.  And in Settings -> Sound -> Do Not Disturb -> Notifications I choose No sound from notifications.  After that I got visual notification when call was coming in and was able to hear the other party.

**Comment by golserma** [comment]
I can confirm this.
If I allow media in DND mode I can hear the other party.
If media is not allowed it does not work using baresip it works for common phone calls.

**Comment by juha-h** [comment]
golserma writes:

> I can confirm this.
> If I allow media in DND mode I can hear the other party.
> If media is not allowed it does not work using baresip it works for
> common phone calls.

My understanding is that pstn call do not use media.  In my Sound
settings, there is Media volume, Call volume, Ring volume and Alarm
volume.  Perhaps call volume is by default excluded from DnD.

Anyway, I'm not planning to do anything about this, since it can handled
with DnD settings.
