### ISSUE TITLE
video disable and rotate

### ISSUE THREAD

**Issue by thomazsh** [juha-h/baresip-studio#164]
1.In video call camera rotation is not working.

2.Disable only send camera button is not  working properly or is not meant that way? It disconnect complete video call.

3.For video call options it would be great if send video is disabled completly (for doorphones).

4. Option for Self video preview window that can be disabled.

br,thomas

**Comment by juha-h** [comment]
Answers:

1  Camera rotation is not supported (see About text).
2 & 3  There is currently no possibility to disable/enable a video direction.  Suggestions on how to conveniently express it in the UI when call is initiated/answered and during call are welcome.
4 Currently self view is always shown if video is bi-directional.

I'll add 2, 3 and 4 to feature requests in the wiki.

**Comment by PavloIv** [comment]
In order to return the image for your use in your application, you need to change the parameters in the file vidisp.c static const GLfloat coords[4 * 2] to such static const GLfloat coords[4 * 2] = {0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0}; // Changed coordinates  
This is the best solution I found for myself. since you are creating an application for internal communication, this will work for you too

**Comment by juha-h** [comment]
@PavloIv Thanks for the comment. What do you mean by "return the image for your use in your application"?  Which of the issues 1-4 does the suggested change solve?

**Comment by PavloIv** [comment]
The video will be sent and received in its original orientation, but you will view it correctly on your smartphone. This way, you adjust the video display for yourself. In other words, you will be able to conduct high-quality video calls between subscribers of your SIP client. When making calls to other clients, you will remain in the same orientation.

**Comment by PavloIv** [comment]
That about first question, About rotation camera view

**Comment by juha-h** [comment]
I tried with
```
 GLfloat coords[4 * 2] = {0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0};
```
by making call from baresip+ on Android to baresip on Linux and video on Android was not OK in any rotation.

**Comment by PavloIv** [comment]
video  rotation  for  you  program,not  for  other. That method  working, only if you call  from phone with your program, to  other  phone with your program.

**Comment by juha-h** [comment]
PavloIv writes:

> video  rotation  for  you  program,not  for  other. That method
> working, only if you call  from phone with your program, to  other
> phone with your program.


OK, got it.  I only have one Android device with camera support and
cannot test between two baresip+ apps.
