### ISSUE TITLE
Hearing sound with delay

### ISSUE THREAD

**Issue by mactka** [juha-h/baresip-studio#168]
Hi
I have istalled two baresip-studio aplications at two phones with Android system. I am calling from one to second. After answering connection I hear sound with 2 or 3 seconds delay. I dumped tcpdump from my router, and stream rtp appeared immediately after answering connection. What can a problem source be?  I would like to implement baresip at my Android aplication so that why I am asking. 

Kind regards
Maciej

**Comment by juha-h** [comment]
mactka writes:

> I have istalled two baresip-studio aplications at two phones with
> Android system. I am calling from one to second. After answering
> connection I hear sound with 2 or 3 seconds delay. I dumped tcpdump
> from my router, and stream rtp appeared immediately after answering
> connection. What can a problem source be?  I would like to implement
> baresip at my Android aplication so that why I am asking.

It is device dependent issue.  See this:

https://stackoverflow.com/questions/35239422/some-seconds-delay-on-starting-sending-voip-with-android-net-rtp

Either set AudioManager.MODE_IN_COMMUNICATION permanently in constructor
or delay calling after you have set the mode:
```
    am.mode = AudioManager.MODE_IN_COMMUNICATION
    Handler().postDelayed({
      if (!call(ua, uri, "outgoing")) {
              am.mode = AudioManager.MODE_NORMAL
              callButton.visibility = View.VISIBLE
              hangupButton.visibility = View.INVISIBLE
      }
    }, 2500)
```

**Comment by mactka** [comment]
Thank you very much for your fast anwer. My application inits `am.mode = AudioManager.MODE_IN_COMMUNICATION` at the start of baresip service. It works correctly, I have not delay.

**Comment by juha-h** [comment]
mactka writes:

> Thank you very much for your fast anwer. My application inits `am.mode
> = AudioManager.MODE_IN_COMMUNICATION` at the start of baresip
> service. It works correctly, I have not delay.

I'll make the same change in baresip app.
