### ISSUE TITLE
SRTP and SRTP-MAND are never secure

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#18]
..not sure if I misunderstood what they do or my setup is broken.

Note that the info dialogue says `Rate: 0/0 (bit/s)` whereas ZRTP and DTLS-SRTPF have non zero values, and are secure.

Android 6 & 9

5.3.1 F-Droid

**Comment by juha-h** [comment]
It takes a few seconds after call is started before the rate gets updated.  Does it stay 0/0 for you during the whole call?

**Comment by juha-h** [comment]
SRTP and SRTP-MAND security button now changes to yellow is call is secure.  Closing also rate issue due to lack of response.

**Comment by licaon-kter** [comment]
Now none of the methods are ever secure, not sure why, will retest on next release.
