### ISSUE TITLE
960x720 Video display crash

### ISSUE THREAD

**Issue by amneiht** [juha-h/baresip-studio#181]
Hi . I am newbie about baresip and android
When I start video call with 970x720 with baresip+ , the application will be crash when callee acept the call . But with other resolution, it working well . What problem on this case . Please help me

**Comment by juha-h** [comment]
amneiht_ltu writes:

> When I start video call with 970x720 with baresip+ , the application
> will be crash when callee acept the call . But with other resolution,
> it working well . What problem on this case . Please help me

baresip+ settings do not include 970x720 resolution.

**Comment by amneiht** [comment]
> amneiht_ltu writes:
> When I start video call with 970x720 with baresip+ , the application will be crash when callee acept the call . But with other resolution, it working well . What problem on this case . Please help me
> baresip+ settings do not include 970x720 resolution.

Sory about my english , i will setting "Video Frame Size" : 960x720 for my call , and it will crash immediately

**Comment by juha-h** [comment]
amneiht_ltu writes:

> Sory about my english , i will setting "Video Frame Size" : 960x720 for my call , and it will crash immediately

I tried that frame size on my Android device and didn't get the crash.
It may be device dependent issue.

You could run `adb logcat | grep Baresip` to get more information about
the crash.
