### ISSUE TITLE
Account with IP Address requires a / at the end

### ISSUE THREAD

**Issue by trampster** [juha-h/baresip-studio#2]
If you try and enter an account with an IP Address for the domain part for example:

1011@172.16.164.82

Then you get the Notice:
Invalid SIP URI: sip:1011@172.16.164.82

Looking at the code the Regex expects the IP Address to end with a slash '/'

^(([0-1]?[0-9]{1,2}\\.)|(2[0-4][0-9]\\.)|(25[0-5]\\.)){3}(([0-1]?[0-9]{1,2})|(2[0-4][0-9])|(25[0-5]))/$

This seems like a mistake. Including a '/' at the end makes it accept the Account. But it shows with an orange dot beside it.

If I try and call 1012 then it auto adds the domain with the lash 1011@172.16.164.82/, and the call doesn't work, if I edit to remove the / then the call goes through.

I am also unable to receive calls

**Comment by juha-h** [comment]
trampster writes:

> If you try and enter an account with a IP Address for the domain part
> for example: 
> 
> 1011@172.16.164.82
> 
> Then you get the Notice:
> Invalid SIP URI: sip:1011@172.16.164.82
> 
> Looking at the code the Regex expects the IP Address to end with a slash '/'
> 
> ^(([0-1]?[0-9]{1,2}\\.)|(2[0-4][0-9]\\.)|(25[0-5]\\.)){3}(([0-1]?[0-9]{1,2})|(2[0-4][0-9])|(25[0-5]))/$
> 
> This seems like a mistake. Including a '/' at the end makes it accept
> the Account. But it shows with an orange dot beside it.

Thanks for reporting.  Should be fixed now.

**Comment by trampster** [comment]
I can confirm that this is fixed and can be closed
