### ISSUE TITLE
Chat ideas

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#20]
Right now it's a wall of text, those arrows don't really help.

Some thoughts:
* left indent "my" text
* add avatars of some sort

**Comment by juha-h** [comment]
Based on your comments, I made some chat related (and other) UI improvements in version 6.0.0.  See if those help. I'm not going to implement avatars, since I don't use them myself.

**Comment by licaon-kter** [comment]
Well, avatars...just an icon of sorts, default Android contact one or, if simple enough, [identicons]().

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Well, avatars...just an icon of sorts, default Android contact one or,
> if simple enough, [identicons]().

For security reasons I don't want baresip to have anything to with
Android contacts.

**Comment by licaon-kter** [comment]
@juha-h that's not what I've said

Android has a default icon, siluette of a human head of sorts, that you can use.

**Comment by juha-h** [comment]
Added reference to https://github.com/juha-h/baresip-studio/issues/26.

**Comment by p5panam** [comment]
It will be great to add file transfer of any file format. So apart from sending chat sms plain text, we could share files. Also adding secure zrtp to chats will be great for security.

**Comment by juha-h** [comment]
William Anderson writes:

> It will be great to add file transfer of any file format. So apart
> from sending chat sms plain text, we could share files. Also adding
> secure zrtp to chats will be great for security.

The app is based on re and baresip libs, which do not currently support
MSRP for file transfer.  I think Blink SIP client supports it, but is
not available for mobile OSes.

What comes to ZRTP, it is for securing real time media steams and my
understanding is that it not suitable for chat.  Sending SIP MESSAGE
messages over TLS via a trusted server is the best what I think is
currently possible.

**Comment by juha-h** [comment]
@licaon-kter Version 15.0.0 now includes Contact avatars that show in contact, call, and chat lists.  Give it a try and close this issue if OK.

**Comment by juha-h** [comment]
Contact avatars are now supported.
