### ISSUE TITLE
Number Pad does not open on Locked Screen

### ISSUE THREAD

**Issue by paskalito** [juha-h/baresip-studio#200]
Thanks a tousand times for this app!

Version 35.0.0
Android 9, Lineage OS

I just figured, that when i accept a call from the Locked phone, i am not able to open the Keybord neccecarry to give an input into a Phone/Asterix System. > So i can not interact with it.

I don´t know if that is a restriction of Androids "show things over the lock screen" ability tough.

**Comment by juha-h** [comment]
I may not understand correctly your case.  I tried as follows:

- baresip is running but not currently visible (instead Android main screen with app buttons is shown)
- I lock the device by pressing power button (screen goes black)
- I call an account of baresip app
- baresip main page becomes visible
- I press green button and answer the call
- keyboard becomes visible at the bottom of the screen
- I'm able to send DTMF digits to caller

**Comment by juha-h** [comment]
Also, when reporting issues, please use the latest version of baresip app that currently is 36.2.0 (both in F-Droid and Play Store).

**Comment by paskalito** [comment]
I think you understad the case correctly. The only thing i would add is to define that the lockscreen must indeed be locked by some pattern or phrase. (as you can have a lock screen that you can just swipe away)

I updated the app and now i have a diffrent behaviour all togheter.

1. phone is in locked and display off state.
2.  i call
3. phone vibrates one time and display is going on (no specific message is shown)
4. at that point i would probably just miss the call but
5. i unlock my screen and can see the baresip interface. i can accept it i get the DTMF Input field no problem (as it is unlocked)

**Comment by juha-h** [comment]
In step 3, I see baresip main window and I'm able to either answer or reject the call without need to unlock my screen with a pin code.

**Comment by juha-h** [comment]
I was not able to reproduce this.
