### ISSUE TITLE
Audio is always routed to loud (bottom) speaker

### ISSUE THREAD

**Issue by arkanoid87** [juha-h/baresip-studio#201]
I've been testing baresip android and it's working nicely on the SIP side (been waiting for a foss sip client like this for a while, thanks!) but the audio output is always routed to the loud (bottom) speaker no matter if the speaker icon on top is enabled or not.
I've tested this on different Samsung smartphones.

~~More precisely, it seems that audio comes out *at the same time* from both speakers, but enabling the icon makes the bottom one somewhat louder (I should explore more time on this)~~
EDIT: was just apparent, not really changing using the button

**Comment by arkanoid87** [comment]
I've also tested if proximity sensor would change something but no, no matter how I use the phone, the sound won't stop being delivered from the bottom speaker

**Comment by juha-h** [comment]
When you touch speaker icon, it sets speaker phone on or off depending it it was off or on:
```
R.id.speakerIcon -> {
                am.isSpeakerphoneOn = !am.isSpeakerphoneOn
                if (am.isSpeakerphoneOn)
                    item.setIcon(R.drawable.speaker_on)
                else
                    item.setIcon(R.drawable.speaker_off)
```
In Android there is no other function to control speaker phone.

Perhaps your Samsung devices do not allow turning speaker phone off.  The control work on all four devices that I myself have and I have not learn about this issue from other users.

**Comment by juha-h** [comment]
I'll investigate.  Which version of baresip and Android you have?

**Comment by arkanoid87** [comment]
37.0.0 from fdroid

**Comment by juha-h** [comment]
arkanoid87 writes:

> 37.0.0 from fdroid

Android version?

**Comment by arkanoid87** [comment]
Android 11

**Comment by juha-h** [comment]
The issue may be related to incorrect handling of Default Call Volume setting.  I'm on the road and will take two days before I can check further.  If you set it to None, then your Media Volume setting should stay at your desired volume level.

**Comment by arkanoid87** [comment]
"Default Call Volume" setting seems not doing anything on my devices.
Tried 1/10/None options with a restart in between and calling a Playback(music) extension on my asterisk server, I always hear music from both ear speaker and bottom speaker and the speaker toggle seems not doing anything.

As before, other sip app (Zoiper) does the right thing.

I can help doing more tests or providing logs, if you guide me doing so, in the meanwhile I'm trying to reduce the scope of the problem.

**Comment by arkanoid87** [comment]
Not sure if it helps, but on same devices Sipdroid https://github.com/i-p-tel/sipdroid handles top/bottom speakers correctly, and also the speaker toggle works as expected, so their code may say something.

**Comment by arkanoid87** [comment]
I've managed to find a dirty fix

BaresipService.kt
```kotlin
...
"call outgoing" -> {
    am.mode = AudioManager.MODE_IN_COMMUNICATION // <- this line fixes ear speaker and also the speaker toggle
    val call = Call.ofCallp(callp) ?: return
    android.util.Log.wtf(TAG,"Never reached ?") // This line is not reached in my context
    if (call.status == "transferring")
        break
    stopMediaPlayer()
    if (am.mode != AudioManager.MODE_IN_COMMUNICATION)
        am.mode = AudioManager.MODE_IN_COMMUNICATION
    requestAudioFocus(AudioManager.STREAM_VOICE_CALL,
        AudioAttributes.CONTENT_TYPE_SPEECH)
    setCallVolume()
    proximitySensing(true)
    return
}
...
```

Here the extensions I'm using for testing, just in case
```asterisk
exten => echo,1,Answer()
same => n,Echo()

exten => music,1,Progress()
same => n,Wait(1)
same => n,Playback(/home/pbx/music,noanswer)
same => n,Hangup()
```

**Comment by juha-h** [comment]
arkanoid87 writes:

> I've managed to find a dirty fix

Thanks for spotting the problem.  The issue was introduced by recent
call transfer related commit:

https://github.com/juha-h/baresip-studio/commit/e5797a7caab28d61859ed454c669bb6b77b96b15

I need to create a proper fix.

**Comment by arkanoid87** [comment]
I can confirm that Version 36.2.0 behaves correctly

**Comment by juha-h** [comment]
arkanoid87 writes:

> I can confirm that Version 36.2.0 behaves correctly

Yes. that was the version before the bug. I just created 37.0.1 that
should include the fix.
