### ISSUE TITLE
[Feature request] Packet loss ratio in Call Info and other network stats

### ISSUE THREAD

**Issue by arkanoid87** [juha-h/baresip-studio#202]
One nice feature of other sip apps is the possibility to track down a problem using the provided stats.
The most important to me is the packet loss and jitter monitor, but I've listed here also other possibilities:
- incoming packet loss
- incoming jitter
- total I/O packets
- total I/O bytes
- current I/O bitrate
- average I/O bitrate
- 
are these stats already tracked by bearsip lib?

**Comment by juha-h** [comment]
These kind of stats would be available at the end of call:
```
audio           Transmit:     Receive:
packets:           1128         1128
avg. bitrate:       3.2         19.3  (kbit/s)
errors:               0            0
pkt.report:         986          986
lost:                 0            0
jitter:             4.2          5.6  (ms)
```
I'll add a setting to turn them on.  Initially they will be available in adb log, but could later add some means to see them on the screen too.

**Comment by juha-h** [comment]
Commit https://github.com/juha-h/baresip-studio/commit/8b8a34ee8816dadc124aa6c47e7fd3281c1ff637 adds RTP Statistics setting.  If checked RTP stats are written to Logcat when call is closed.  Currently baresip lib does not allow other way to access the stats.

**Comment by arkanoid87** [comment]
while it is useful on the dev side, it is more useful if the stats are available inside the gui, as most of the time the problem has to be tracked down remotely and it's quite unfeasible to ask enabling adb logcat to voip users

**Comment by juha-h** [comment]
I agree, but currently baresip lib produces the stats only to log.  I asked about the feature on baresip list:

https://groups.google.com/g/baresip/c/_ABtWKOGt3I

**Comment by arkanoid87** [comment]
Actually the stats should be somewhere realtime, not static at the end of the call, but it's better than not having them

**Comment by juha-h** [comment]
Currently, baresip lib generates RTP stats when the audio or video stream is closed.  I created new feature request in Wiki about showing the stats in the app.

**Comment by juha-h** [comment]
It may be possible to dynamically get lost and jitter stats on the fly.  I'll take a look and if so, I'll add them under Info button.

**Comment by juha-h** [comment]
Latest master has added Current Rate, Average Rate, Jitter, Packets, and Lost statistics into Call Info.
