### ISSUE TITLE
baresip+ won't register over data, only over wifi

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#204]
baresip+ 24.0.0 from F-droid
calyxOS 2.11.0 (aosp 11)

To reproduce:
1) quit baresip+
2) deactivate Wifi on the phone
3) make sure mobile data is turned on
4) restart baresip+ and wait and wait and wait until the dot turns red.

To validate:
1) quit baresip+
2) activate Wifi
3) deactivate mobile data
4) restart baresip+ and watch it rapidly register and turn the dot green, nearly instantaneous.

I noticed this recently, but I couldn't say for sure whether is was the latest update or one before it.

This means no sip calls unless I'm near open Wifi, not when I'm on mobile data.

Thanks,

**Comment by juha-h** [comment]
znoteer writes:

> baresip+ 24.0.0 from F-droid
> calyxOS 2.11.0 (aosp 11)
> 
> To reproduce:
> 1) quit baresip+
> 2) deactivate Wifi on the phone
> 3) make sure mobile data is turned on
> 4) restart baresip+ and wait and wait and wait until the dot turns
> red.

I can't reproduce this using 24.0.1 from Play store (Nokia 6.2, Android
11).  When I start baresip+ with only mobile data turn on, baresip+
registers immediately after start.  There has been no network related
changes from 24.0.0 to 24.0.1.

Baresip+ also re-registers fine over mobile data when it has registered
over WiFi and I turn WiFi off (if mobile data is also available).

**Comment by znoteer** [comment]
On Tue, Dec 21, 2021 at 09:34:13AM -0800, juha-h wrote:
> znoteer writes:
> 
> > baresip+ 24.0.0 from F-droid
> > calyxOS 2.11.0 (aosp 11)
> > 
> > To reproduce:
> > 1) quit baresip+
> > 2) deactivate Wifi on the phone
> > 3) make sure mobile data is turned on
> > 4) restart baresip+ and wait and wait and wait until the dot turns
> > red.
> 
> I can't reproduce this using 24.0.1 from Play store (Nokia 6.2, Android
> 11).  When I start baresip+ with only mobile data turn on, baresip+
> registers immediately after start.  There has been no network related
> changes from 24.0.0 to 24.0.1.

Do you have any idea how long it will take for 24.0.1 to appear in F-droid?

> 
> Baresip+ also re-registers fine over mobile data when it has registered
> over WiFi and I turn WiFi off (if mobile data is also available).

Yes, it used to for me, too.

Thanks,

-- 
Znoteer
***@***.***

**Comment by juha-h** [comment]
znoteer writes:

> Do you have any idea how long it will take for 24.0.1 to appear in
> F-droid?

F-Droid build of 24.0.1 succeeded on Dec 20 7am.  I don't know how long it
takes before 24.0.1 gets published.

**Comment by znoteer** [comment]
Inexplicably, this has stopped being a problem.  I checked, and am still on 24.0.0.  For a few days baresip+ had failed to connect when out of range of wifi, even when data was on.  Stopping and restarting the app never helped to get a connection over mobile data.

But, today baresip+ is switching effortlessly between wifi and mobile data.  I may have rebooted the phone, but I can't remember for sure.

Please close this ticket.  Sorry for the disturbance.
