### ISSUE TITLE
baresip+ overrides lock screen

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#205]
If baresip was the last application on screen before inactivity locks the screen, when one taps to relight the screen, rather than being presented with the lock screen, one sees baresip+.  The screen can't be unlocked until baresip+ is moved out of the way either by pressing the < icon to go back, or by trying to use baresip.

I would expect the lock screen to appear right away upon reactivating the screen, not an app.

Thanks,

**Comment by juha-h** [comment]
znoteer writes:

> If baresip was the last application on screen before inactivity locks
> the screen, when one taps to relight the screen, rather than being
> presented with the lock screen, one sees baresip+.  The screen can't
> be unlocked until baresip+ is moved out of the way either by pressing
> the < icon to go back, or by trying to use baresip.

This I can reproduce.

> I would expect the lock screen to appear right away upon reactivating
> the screen, not an app.

I'll investigate.

**Comment by juha-h** [comment]
Commit https://github.com/juha-h/baresip-studio/commit/42f69977995fe558cc70f69dce445e03dd9caa24 that is included in baresip+ version 24.2.0 should fix. Reopen if the issue persists.

**Comment by znoteer** [comment]
baresip+ 24.4.0 I don't think I ever had 24.2.0, the one you mentioned, on my phone.

Things are different now, but I wouldn't say fixed.

I use the term lock screen the same way my phone does, which is more a notification screen, because one option to unlock, in addition to a pattern, pin or password, is simply to swipe up.  But, another option is no lock (notification) screen at all. In this case, when you wake up the black screen you see whatever was there before the screen went black.

So, the lock screen is where one sees a clock and the date, and things like missed calls or unseen incoming SMS.  baresip+ is still getting in front of the lockscreen when the screen wakes up if baresip was the last thing open when the screen went black and locked.  baresip+ is the only application I've used that does this.

If I have the lockscreen configured so that I need only swipe up, and baresip is the application visible when the phone locks, when I reactivate the screen I see baresip and I can use it to make calls.  I don't see the lockscreen with time and date and missed calls and texts, which is frequently what I'm after.   I am expecting to see the lock/notification screen.

If I have the lockscreen set to that I need a pin or a pattern to unlock it (I haven't tried a password), if baresip was the last application visible, when I activate the screen I am prompted immediately for the pin or pattern.  Again I expect to see the lockscreen first.  The lock/notification screen is what I see when I wake up the screen if any other application than baresip was the last one open when the screen locked.

**Comment by juha-h** [comment]
I think I got the above issues solved.  If you want to try, I placed test version of baresip (not baresip+) apk available here https://tutpro.com/tmp/baresip.apk

One thing that I noticed with this version is that if call comes in and the device is locked with a pin, then pin must be given before the call can be answered.

**Comment by znoteer** [comment]
Thanks for looking at this again.

1. I've never installed an app other than through g00gl's or f-droid's repos. I'll see what I can do.
2. Do you have a checksum for the package?
3. I use baresip+. Will the correction I'm testing be directly transferable to the + version?
4. Having to enter a pin to answer is suboptimal. Do you have plans to make this unnecessary, soon?

**Comment by juha-h** [comment]
You can download the apk and then the device will ask what to do with it. I usually develop new features in baresip and then backport them to baresip+.

I have not been able to figure out, how to avoid asking of the pin when device is locked.  If it would be somehow possible, then I would also need to be able to figure out, how to prevent the user from making new calls while the device is still locked.

**Comment by znoteer** [comment]
That's fixed the problem with taking over the lock screen.  Thank you.

Unfortunately, not being able to answer a call without a pin makes it unusable for important calls.  I am not a programmer, so I can't help you with that, nor can I say how difficult it might be.  But, I can say it's possible. The regular phone app, the one that handles the calls to my SIM's number, can't be used to make calls without a pin, but is available to answer incoming calls without a pin.  When such an incoming call ends, the phone is effectively locked again.

It would be great if you were able to figure how to pull this off.  But either way, thanks for what you accomplished so far.

**Comment by juha-h** [comment]
znoteer writes:

> Unfortunately, not being able to answer a call without a pin makes it
> unusable for important calls.  I am not a programmer, so I can't help
> you with that, nor can I say how difficult it might be.  But, I can
> say it's possible. The regular phone app, the one that handles the
> calls to my SIM's number, can't be used to make calls without a pin,
> but is available to answer incoming calls without a pin.  When such an
> incoming call ends, the phone is effectively locked again. 

I created a new test version:

http://tutpro.com/tmp/baresip.apk

If you have time, try if it solves the above problem.

**Comment by znoteer** [comment]
Dude, if you have time to try and fix this, of course I'll find time to test!!!

Did 3 calls.  The first one was weird because their was a brief call, only long enough to ring a bit, and to light up the screen, not long enough to react to. A few seconds after the phone settled down after that the call I was expecting came, and I needed to enter my pin to answer.

But today, I had someone call two more times after setting up the phone, and I was able to answer both times without the pin.  So 2 out of 3, I say it's fixed and the first call was just a fluke of some kind.

Thank you.

**Comment by juha-h** [comment]
Thanks for testing.  In my tests, sometimes the lock screen appeared
when the call came in, but it went away w/o pin after a few seconds.

I'll try to find a better solution.

**Comment by juha-h** [comment]
znoteer writes:

> Please disregard my previous comment.  I'm not sure, but I may have
> tested baresip+ in the last two tests rather than the baresip you had
> me download.  I'm going to try again making sure I have the right app
> open.

No problems,  Wait an hour and I'll give you better version to test.

**Comment by juha-h** [comment]
Try with the new version:

9144 -rw-r--r-- 1 jh jh 9356642 Jan 10 15:49 baresip.apk

It works fine in my tests except in the case where baresip app is
cleared by swipe and screen is locked.  In that it takes a few seconds,
before the key request disappears.

I'll later today also baresip+ version available for testing.  With it
the above mentioned delay is much smaller.

**Comment by znoteer** [comment]
I just tried to use the url you gave me the last times, but it just downloaded 37.4 again.  How can I get the lastest baresip.apk?

thanks

**Comment by juha-h** [comment]
znoteer writes:

> I just tried to use the url you gave me the last times, but it just
> downloaded 37.4 again.  How can I get the lastest baresip.apk?

I have not updated the version yet.  The one you downloaded is the
latest test version.

**Comment by juha-h** [comment]
Here is test version of baresip+:

http://tutpro.com/tmp/baresip+.apk

In my tests with it incoming call showed up OK in all situations:

- app is visible
- app is not visible, but has not been cleared
- app is not visible and has been cleared
- app was visible when I locked the device
- app was not visible, but had not been cleared when I locked the device
- app was not visible and had been cleared when I locked the device

**Comment by juha-h** [comment]
znoteer writes:

> I downloaded baresip+, chose install when asked, then got a message
> saying it was not installed. I tried a couple of times.  I don't know
> why.  Sorry, couldn't test it.

Perhaps due to version mismatch.  Maybe you would need to (1) backup
your config from main menu, (2) uninstall baresip+ app, (3) install the
downloaded baresip+.apk and (4) restore your config.  I just tried that
and it worked.

By the way, there could be differences in screen/locking behavior
depending on Android version.  I did my successful baresip+ tests with
Android 11 device.

**Comment by znoteer** [comment]
Sorry it took so long to test.  I was going to report that it was fixed, but
on rereading your message, I realize I tested the lastest fdroid baresip+
(25.0.0) and not baresip 38.

Oh well, baresip+ is the one I use, so I'm happy that it has been resolved
for that at least.

Thank you for all your testing and working.  I promise, when I can wrangle
another friend to make some calls, I'll test baresip 38 to properly confirm
for you.

Z

**Comment by juha-h** [comment]
znoteer writes:

> Sorry it took so long to test.  I was going to report that it was fixed, but
> on rereading your message, I realize I tested the lastest fdroid baresip+
> (25.0.0) and not baresip 38.

No problems.  Latest F-Droid versions of baresip and baresip+ now are 39.0.0
and 26.0.0.
