### ISSUE TITLE
Add mechanism to tell baresip+ that a SIP account can be used to dial PSTN numbers

### ISSUE THREAD

**Issue by gdt** [juha-h/baresip-studio#218]
Some SIP accounts are for what I'd call "normal sip" and some are connected to a provider that will complete calls to E.164 numbers.  If the user is able to say "this account can call phone numbers, by calling [+ E.164]@provider-gateway.foo" or some such, then baresip+ could offer to make such calls from contacts, and also look up incoming calls matching that by number for name display.

I realize this is a completely different use case than SIP where both parties are via Internet.

**Comment by juha-h** [comment]
Would it be OK if account had  `PSTN Provider` configuration item, whose value would be `host[:port][;transport=udp|tcp|tls]`?  Then if user of that account calls an E.164 number, Request-URI would be `sip:<E.164 number>@<PSTN Provider value>`.

**Comment by gdt** [comment]
I think so.  It might even be enough to have a toggle that turns it on and calls that URI with the same outbound proxy as the entire account.     But it being configurable and defaulting to match when first enabled would be great, and really anything that can be made to work would be a very nice improvement.

**Comment by juha-h** [comment]
I started to work on calling telephone numbers and got into trouble.

If user calls a telephone number, how can the app figure out, if the resulting SIP URI should have hostpart of user's account or hostpart of telephony service provider?

My conclusion is that it is the job of the SIP proxy serving user's account would figure out, where to route such a call.  So like today, the app completes the number with account's domain unless the called number is found in contacts and then, of course, the URI found there would be used.

**Comment by gdt** [comment]
I guess the real question is how actual PSTN gateways are configured and what they expect.   I am familiar with one, where you get a URI that is NNNNNNN@example.com   where that is a number local to the provider, not a PSTN number.   In addition to calling URIs like that you can also make calls to <countrycode><number>@example.com, e.g 12125551212@example.com for the usual example in NYC.   So in that case, hostpart of user's account and hostpart of ITSP are the same.

**Comment by gdt** [comment]
Thanks, I will try to test.

I don't understand "What if there is more that one account with telephony provider configured and the first one is not the desired one? I'm thus likely to remove this feature. It is unsafe and can easily be unnoticed." at all.    If you configure an account as being a telephony provider, you are telling baresip that the account is the (a) proper way to handle outgoing PSTN calls.  If you have two, either is a perfectly ok choice in line with the user's config and I don't see anything dangerous about that.    It might be that you should enable only one to be configured as a telephony provider at any given time, and then a lot of ways the user could confuse themselves are taken off the table.

**Comment by juha-h** [comment]
@gdt I just uploaded new test version with fixes and improvements.

**Comment by juha-h** [comment]
Just to clarify my earlier comment regarding more than one PSTN accounts. They could serve different purposes, for example, one for national and another for international calls.  In such situation, automatic selection of first account that has Telephony Provider configured, can lead to making of the call using wrong account. 

It is really too much trouble to first select the account to use and when go to contacts?

**Comment by juha-h** [comment]
@gdt Versions 40.0.0 and 27.0.0 that were just created prompt the user to select another account if callee is telephone number and the current account does not have Telephony Provider defined.

**Comment by juha-h** [comment]
@gdt Version 27.0.1 is  now available on F-Droid so you should be able test with that.

**Comment by gdt** [comment]
I managed a brief test, more later.  I added an account which will gateway to PSTN.  That provider wants "CC" "area" "number", e.g. for US "1 212 555 1212".  Note that the 1 is not the US long distance code, but the NANP country code.  For UK, one dials "44 ...".     This is odd, compared to local actual POTS lines, as there is no international dialing prefix.  I have no idea if this is or is not normal with PSTN gateway services.

I added a (US) phone number to  a baresip contact, as "1AAAEEENNNN", and when I touched the contact it offered message/call and I clicked call and the phone at the called number rang.

I guess next step is to reset the phone app and see if my regular phone contacts will offer to use baresip and if it will work.  I have a mix of "+1 AAA EEE NNN" for US, a few international numbers all in "+CC [country format]" format, and some "1 AAA EEE NNNN" US numbers from before I got compulsive about +, and might have some "AAA EEE NNNN".  (On a US cellphone you can dial 1 and 10 digits, or just the 10 digits, or at least Android copes and translates.)    I'm really not sure where the various magic happens and yes I know I should use adb to learn more :-)

**Comment by juha-h** [comment]
Thanks for testing.  Telephone number in baresip contact needs to be in the format that is acceptable to your PSTN gateway. provider.  baresip does not understand local dialing plans and requirements of various providers and thus does not do any rewriting of the number.  Usually it is best to enter contact numbers in E.164 format starting with + that _should_ be acceptable to any PSTN gateway provider. Not all numbers (e.g. emergency numbers) are E.164 numbers and must be written withoout +.

**Comment by juha-h** [comment]
Will close this now.  Reopen if something still needs to be done.
