### ISSUE TITLE
Emoticons missing when typing text messages

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#219]
baresip+ 26.0.0
Android AOSP 12 (CalyxOS 3.1.0)

To my delight I've noticed that baresip+ does texting, but I can't find a way to insert emoticons into the text.

On the keyboard, where there is usually the emoticon selector button, baresip+ puts a carriage return key.  Signal messenger also does this, but then provides a button in the text entry box that allows one access to a list of emoticons to choose from. 

Is there some way to provide access to an emoticon selector when texting in baresip+?

Regular texting app with emoticon selector next to space bar (lower right):

![Screenshot_20220127-160400](https://user-images.githubusercontent.com/10201567/151447902-58488226-cbc3-48f7-b31f-9797529acd09.png)

Texting within baresip+ where the emoticon selector has been replaced with a return key:

![Screenshot_20220127-160256](https://user-images.githubusercontent.com/10201567/151448111-e83557fa-e864-4884-8bf2-e221c1530c6d.png)

Signal Messenger where there is a return key next to the space bar, but where an emoticon selector is offered in the text entry field at the left end (just above the keyboard):

![Screenshot_20220127-160548](https://user-images.githubusercontent.com/10201567/151448460-33f4edd8-6972-4873-8989-d5cde416e3b8.png)

**Comment by juha-h** [comment]
Thanks for your comment.  Currently baresip lib only supports content type `text/plain` in MESSAGE request body.

I don't know anything about emoticon.  Can they be represented as `text/plain` or do they require some other content type?

**Comment by znoteer** [comment]
First, doing a little research has made me realise that I misused the term "emoticon". Emoticon refers to the textual representation of something like a smiling face with text characters like this `   ` `:)` 

What I was actually referring are apparently properly called emoji and are a colourful pictorial representation of something like a thumps up :+1:  or that same smiling face 🙂

To answer your question, I would say "I think so".  I don't know much about emoji either, but I created this issue so I figured it was in my best interest to try and learn a bit. 

Emoji are part of the Unicode standard. According to the first FAQ [here](https://home.unicode.org/basic-info/faq/) Unicode is for "processing, storage and interchange of text data in any language".

I also had a look at the different [text content types](https://www.iana.org/assignments/media-types/media-types.xhtml#text), and `text/plain` seems to be the only thing that would fit the bill.

Lastly, I went into a programme on my phone where I could type an emoji, typed and copied one, then pasted it successfully into the message entry field in baresip+. I was able to send the message to a cell phone number.  The cell phone received the emoji properly.

So, it looks like al that is needed is a mechanism less cumbersome than opening another app and copying characters to paste into baresip+.  

I hope this can give you a starting point. If it raises other questions, I'd be happy to help with research.  Also, I know your time is limited, and I've created other issues (and will likely create more :) ).  The [contacts issue](https://github.com/juha-h/baresip-studio/issues/217) is more pressing for me than emoji are, if you're wondering how you might prioritise.  Thanks.

**Comment by juha-h** [comment]
When soft keyboard was visible, I touched the settings icon at the top row of soft keyboard, and then in Preferences turned on "Show emoji switch key".  That changed the world icon shown in your image above to emoji icon.  Now if I during typing of a message touch the emoji icon it shown me lots of smileys and emotions to choose from.  I tested and the peer received the emojis included in the message.

**Comment by znoteer** [comment]
which softkeyboard are you using? My AOSP keyboard does not seem to have a setting icon at the top row.  See the screen shots in the OP and the following landscape mode screenshot.  I just have the mic and suggested words in the top row and letters in the second.  I'm guessing your using your vendors version of the keyboard rather than AOSP.

![Screenshot_pixel3-AOSP-keyboard_really-small](https://user-images.githubusercontent.com/10201567/151632133-3d4c9edb-6140-49cc-8d25-ccdb8da73fe7.png)

**Comment by juha-h** [comment]
znoteer writes:

> which softkeyboard are you using? My AOSP keyboard does not seem to
> have a setting icon at the top row.  See the screen shots in the OP
> and the following landscape mode screenshot.  I just have the mic and
> suggested words in the top row and letters in the second.  I'm
> guessing your using your vendors version of the keyboard rather than
> AOSP.

No, my device is Nokia 3.1, which is Android One device, i.e., has pure
Android.  Its current keyboard app is Gboard, i.e., Google's keyboard
app.

Please install Gboard from Google Play

https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

and try with that or with any other keyboard app that supports emoji.
Also F-Droid has keyboard apps, which may support emoji.

So I suspect that this issue is not baresip. but keyboard app, related.

**Comment by znoteer** [comment]
I wondered myself if this was a baresip or keyboard issue. I think it's actually between the two, in that is has something to do with how they interact.

I will point out that the keyboard I was using (AOSP) *does* support emoji as I use they in other app no problem with this keyboard. I won't install gboard because I don't want g0*gle watching me.  But I did find another keyboard (AnySoftKeyboard) on which the emoji selector button doesn't disappear.  

So, I have found a way around the issue by changing keyboards.

Thanks.

**Comment by juha-h** [comment]
znoteer writes:

> I will point out that the keyboard I was using (AOSP) *does* support
> emoji as I use they in other app no problem with this keyboard. I
> won't install gboard because I don't want g0*gle watching me.  But I
> did find another keyboard (AnySoftKeyboard) on which the emoji
> selector button doesn't disappear. 
> 
> So, I have found a way around the issue by changing keyboards.

Good that another keyboard worked. I added textShortMessage input type
to the chat text:

android:inputType="textMultiLine|textShortMessage"

Perhaps it helps with your original keyboard.

**Comment by znoteer** [comment]
Ah, I wonder if this will also fix the [issue](https://github.com/juha-h/baresip-studio/issues/220) I just opened...
