### ISSUE TITLE
No automatic capitalisation in text message entry field

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#220]
baresip+ 26.0.0
Android 12 (CalyxOS 3.1.0)
Google Pixel 3

Whenever I type in other apps, I get automatic capitalisation of letters.  That is to say, when you activate a text field that is empty to enter text, the keyboard automatically switches to capital letter mode.  After the first letter is typed as a capital letter the keyboard automatically switches back to small letter mode. The same thing happens after a period `(.)`, the capital letters get switched on automatically to begin the next sentence and then switch off automatically after the first letter is typed.

I've tried this in several apps with 4 different keyboards (AnySoftKeyboard, AOSP, Unexpected Keyboard and OpenBoard). The only exception I've seen is if the text entry field is expecting a URI.  In that case, the capital letter key stays off all the time to avoid typing `Https://www.Example.Com/index.Html` instead of `https://www.example.com/index.html`.

When I want to send a text message with baresip+ the capitalisation stays off with all the keyboards I've tried.  This is at the very beginning of a message when the field is empty and at the beginning of new sentences.  

Can this behaviour be changed? I don't programme, but I wonder if the text enter field is declared as some type that expects a URI rather than regular text.  Any way, thanks for any input you may be able to offer.

**Comment by juha-h** [comment]
Thanks for reporting, Should now be fixed by https://github.com/juha-h/baresip-studio/commit/15ccf029f7a77e30c4da2a37d1714510fc66e3ab.

**Comment by znoteer** [comment]
Wonderful! I can't wait for it to show up in F-Droid. Thank you.

**Comment by juha-h** [comment]
znoteer writes:

> Wonderful! I can't wait for it to show up in F-Droid. Thank you.

I already created new version 26.1.0:

- Improved and fixed handling of message and call transfer events
- Toast registration failure it to any current activity
- Automatically capitalize message sentences
- Made AV1 video codec available again, but beware of bad performance
- Replaced deprecated local broadcasts with LiveData events
- Fixed some bugs related to handling of external call actions
- New Portuguese (Brazil) translations

Usually it takes two/three days before showing up in F-Droid.

**Comment by juha-h** [comment]
@znoteer Did you try with version 26.1.0 that is now available in F-Droid?

**Comment by znoteer** [comment]
Had to wait for it to show up in my updates before I could try :)

Automatic capitalisation is now working as expected.

Thank you for your time and effort

**Comment by juha-h** [comment]
znoteer writes:

> Automatic capitalisation is now working as expected.

Good, for the next version I added two more attributes to the field:

android:inputType="textMultiLine|textShortMessage|textCapSentences|textAutoComplete|textAutoCorrect"

**Comment by znoteer** [comment]
Excellent.  I was wondering whether or not to bring up autocorrect now or wait a bit :)
