### ISSUE TITLE
Feature: Loud speaker option

### ISSUE THREAD

**Issue by twisteros** [juha-h/baresip-studio#223]
It would be nice to have a toggle to enable loud speaker while on a call

**Comment by juha-h** [comment]
twisteros writes:

> It would be nice to have a toggle to enable loud speaker while on a
> call

If by "load speaker" you mean "speakerphone", there already exists
toggle icon for it between mic mute and menu icons.

**Comment by twisteros** [comment]
There is an icon indeed.
I didn't notice it.
