### ISSUE TITLE
No bluetooth in Android 11

### ISSUE THREAD

**Issue by myfirstnameispaul** [juha-h/baresip-studio#225]
I did see #55 mentions a commit that added bluetooth support, but in Android 11 I cannot discover a way to use baresip with bluetooth.

**Comment by juha-h** [comment]
I just tested with my Android 11 device and baresip used bluetooth at least when bluetooth device was connected when the call was established.  Bluetooth device needs to have both speaker and microphone.

Did you have same or some other setup?

**Comment by juha-h** [comment]
I made another test and baresip+ 4.0.1 switched to to use bluetooth device also during call.

**Comment by myfirstnameispaul** [comment]
The bluetooth device is a Plantronics Legend earpiece with microphone.

When I make a phone call, baresip does not switch to bluetooth. When I call a number that fails, the failed call attempt sounds off in the bluetooth earpiece.

I will test later today on whether incoming calls are picked up with bluetooth.

**Comment by myfirstnameispaul** [comment]
It isn't working on inbound calls.

I did figure out that Linphone version in F-Droid is working as expected with bluetooth.

**Comment by juha-h** [comment]
I'll do more testing:  Start baresip when bluetooth is already connected, connect bluetooth after start, connect bluetooth during call, etc.  I recently had to make this change, because Google started again demanding more permissions, but it should not affect Android 11 (API level 30) devices:
```
@SuppressLint("MissingPermission")
    private fun isBluetoothHeadsetConnected(): Boolean {
        return if (VERSION.SDK_INT < 31)
            btAdapter != null && btAdapter!!.isEnabled &&
                btAdapter!!.getProfileConnectionState(BluetoothHeadset.HEADSET) == BluetoothHeadset.STATE_CONNECTED
        else
            // getProfileConnectionState requires asking fot BLUETOOTH_CONNECT permission
            true
    }
```

**Comment by juha-h** [comment]
I may have found the cause of the issue.  Looks like for Bluetooth stream type must always be STREAM_VOICE_CALL.  It used STREAM_RING when call came in and ring started. 

If you want to test, I can create baresip or baresip+ apk for you.  Otherwise I'll include the change in the next release.

**Comment by myfirstnameispaul** [comment]
Well, assuming the next release isn't month away or something, I can live with answering through Linphone. So far, it doesn't interfere with SMS (Linphone SMS on F-droid has really weird issues, while baresip functions normally).

**Comment by juha-h** [comment]
Paul writes:

> Well, assuming the next release isn't month away or something, I can
> live with answering through Linphone. So far, it doesn't interfere
> with SMS (Linphone SMS on F-droid has really weird issues, while
> baresip functions normally).

I anyway made baresip.apk available here:

https://box.tutpro.com/tmp/baresip.apk

if you have time to test.  With that I have not noticed any bt issues
(Android 10 or 11).

**Comment by myfirstnameispaul** [comment]
Fixed! With last update posted to F-droid.

**Comment by juha-h** [comment]
Paul writes:

> Fixed! With last update posted to F-droid.

Good, thanks for testing.
