### ISSUE TITLE
Feature request: connection duration on the main screen

### ISSUE THREAD

**Issue by twisteros** [juha-h/baresip-studio#228]
I know a user can display connection time by tapping the info icon.
However it would be handy to have it on the main screen and counting rather than static and in a separate window.

**Comment by juha-h** [comment]
twisteros writes:

> I know a user can display connection time by tapping the info icon.
> However it would be handy to have it on the main screen and counting
> rather than static and in a separate window.

There is not much real estate left on the screen in small devices.
Would it be OK if the mm:ss counter would by running at the end of the
"Call from|to ..." line?

**Comment by twisteros** [comment]
> Would it be OK if the mm:ss counter would by running at the end of the "Call from|to ..." line?

Yes, that would be great

**Comment by juha-h** [comment]
Has been provided by https://github.com/juha-h/baresip-studio/commit/7faf64558e2ae8d4fdfaf266b4319040a63e5899.
