### ISSUE TITLE
Chat listings show contact's number rather than their name

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#230]
When in the Chat History screen, one sees a list of the chats one currently has ongoing.  If one has created a contact for a given number, one sees the name of the contact and (part of) the last message sent in the chat.  If there is no contact for the number, one sees the number instead of a name.

If one opens an existing conversation for which there is a contact, when the conversation opens, one is nevertheless greeted with a screen that has as title "Chat with <telephone number>" rather than with "Chat with <contact name>".

I would personally find it more useful to have the person name in that screen.  Is this possible?

Thanks

**Comment by znoteer** [comment]
Thank you.

**Comment by juha-h** [comment]
Try with version 42.2.0 or 29.2.0 (+) that are now available in Google Play and should show up in F-Droid after a couple of days.  Reopen if still an issue.
