### ISSUE TITLE
plans to provide apk releases here on github?

### ISSUE THREAD

**Issue by beaglesnuf** [juha-h/baresip-studio#236]
f-droid has a history of providing days to weeks late builds. any plans to provide apk builds here on github instead?

**Comment by juha-h** [comment]
I too have noticed that it takes long time before new version of baresip gets published on F-Droid.  But it is already a big job to create new release of two apps (baresip and baresip+) in two repositories (Google Play and F-Droid).  A third repo would be too much.  New release usually shows up in Google Play in about 24 hours at least during week days, so you get get it from there.

**Comment by beaglesnuf** [comment]
will do. though the izzyondroid repo can pull from github and provide to f-droid users, thereby keeping your workload confined to two total repos: google play and github.

**Comment by gdt** [comment]
@beaglesnuf Note that izzy's repo is not "f-droid", it is "izzy's repo accessible by f-droid client".   The point is that the f-droid official repo is special in that it guarantees open source and built by f-droid.org.   And, f-droid main builds automatically from tags.   So asking for baresip to be moved from f-droid main to izzy's repo makes no sense.

Also, f-droid main repo has been doing better at reasonable build latency lately, usually only a few days.

What would be useful is to use github CI to build apks, but I'm not sure that's wise and it's a lot of work to set up.

**Comment by juha-h** [comment]
I created latest baresip version 42.3.0 four days ago.  F-Droid build has succeeded, but according to F-Droid build status app, it has not been published yet.  Perhaps tomorrow :-)
