### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by kidcohen** [juha-h/baresip-studio#237]
I am getting the issue Device support x86, but APK only supports armeabi-v7a, arm64-v8a on device. I tried adjusting to API 24 as a lower API than with the newest phones and it's still having issues. I tried to make a few adjustments to get it to work, but I am not sure what could get it to work.

**Comment by juha-h** [comment]
First you need to build the libs also for x86 architecture, add x86 architecture to app/build.gradle, and perhaps something else.  At this point, I have no plans to do that.
