### ISSUE TITLE
Handle multiple phone numbers from android contacts

### ISSUE THREAD

**Issue by varac** [juha-h/baresip-studio#238]
Hi, first of all thanks for this great app !
I saw that support for internal android contacts was recently added. I noticed that you can choose with phone number to call if a contact has multiple phone numbers. It would be nice if this could be implemented.

**Comment by juha-h** [comment]
I don't quite understand this issue.  If Android contact has multiple phone numbers, it is possible to choose which one to call.

**Comment by juha-h** [comment]
If you mean matching contact name suggestions that are shown when you start typing contact name in Callee URI then only those Android contact names are shown that have only one URI.  Otherwise, the URI to call would not be unique.

**Comment by juha-h** [comment]
Closed due to lack of further communication.

**Comment by muellert** [comment]
> I don't quite understand this issue. If Android contact has multiple phone numbers, it is possible to choose which one to call.

I'm sorry, but I can't seem to do that. If I select a name from the contact app, then select baresip to call the contact (I can't do this from within baresip), I can choose the number, but when I want to quickly re-dial the number using the last call, baresip selects *some* number (it doesn't show which one), which might be the wrong number, to make the call. In my case, baresip insists on calling the mobile number of the user, which costs a lot of money, and the user has a habit of turning off their mobile, too. This is baresip 47.2.0.

**Comment by juha-h** [comment]
If you want to use Android contacts then give each such contact only one number or SIP URI.  Merging baresip contacts with Android contacts is a big hassle.

**Comment by muellert** [comment]
I have a few hundred Android contacts, many of whom have more than one phone number, and none of them has an explicit SIP URI. If baresip could just pop up some dialogue asking me for which number I want to dial, that would be great. Or if it could remember the number along with the name in the call history, and reuse that.

**Comment by juha-h** [comment]
muellert writes:

> I have a few hundred Android contacts, many of whom have more than one
> phone number, and none of them has an explicit SIP URI. If baresip
> could just pop up some dialogue asking me for which number I want to
> dial, that would be great. Or if it could remember the number along
> with the name in the call history, and reuse that.

The latter option might be possible.  I'll investigate.

Regarding several numbers per contact, it would make contact selection
multidimensional. Now when user starts typing contact name to Callee
field, several matching contact names are shown.  If there would be
several numbers/uris per contact, then all of them should be shown in
addition to contact name and that would be too complicated.  Also
contact labels (mobile, work, etc.) can be contact app specific and it
would not be possible to show them baresip.  So user would need to
remember which number is which.

Regarding use of Android contacts in baresip app, it has caused big
mess.  Every time I add new version to Google Play store, Google rejects
the app claiming that it contains malware that uploads user's contact
information somewhere.  I must then object the claim and tell Google
that their malware detection sucks.

**Comment by juha-h** [comment]
It was possible to implement the latter option.  Should be available in the next release.

**Comment by juha-h** [comment]
Implemented by https://github.com/juha-h/baresip-studio/commit/589bd3079cbd95ab0bc1f818ccf61ef398a083ab.
