### ISSUE TITLE
No support for IPv6?

### ISSUE THREAD

**Issue by brianjmurrell** [juha-h/baresip-studio#24]
Looking at the DNS queries being made, I'm only seeing a query for an `A` record, no `AAAA` lookup appears to be happening at all.

Is there really no support for IPv6 at all?

**Comment by juha-h** [comment]
Brian J. Murrell writes:

> Looking at the DNS queries being made, I'm only seeing a query for an
> `A` record, no `AAAA` lookup appears to be happening at all.
> 
> Is there really no support for IPv6 at all?

There is no IPv6 support at this time.

**Comment by brianjmurrell** [comment]
Ahhh.  This is a pity given the considerable headaches that NAT causes SIP.

Hopefully it shows up at some point.

**Comment by juha-h** [comment]
Brian J. Murrell writes:

> Ahhh.  This is a pity given the considerable headaches that NAT causes SIP.
> 
> Hopefully it shows up at some point.

It can show up when I have got the time.  I'm using Kamailio SIP proxy
with rtpengine and haven't had any problems with NAT.  IPv6, on the
other hand, has given me lots of problems.  For example, name servers of
my domain are not reachable from some parts of the world over IPv6.

**Comment by juha-h** [comment]
Added reference to issue https://github.com/juha-h/baresip-studio/issues/26.

**Comment by juha-h** [comment]
@brianjmurrell Version 7.0.0 should now have support for IPv6, but I don't have IPv6 access available and cannot test it.  If you have time, give it a try.
