### ISSUE TITLE
Numberpad button only works when Callee field got focus

### ISSUE THREAD

**Issue by yennor** [juha-h/baresip-studio#246]
The app shows on the lower right corner the Symbol/Button for the number pad.
I needed a while do figure out, that it only works, if you first click on callee field.
Would be cool if it just sets focus on itself to the callee field if necessary.
The way it is now, it's a bit confusing.

**Comment by juha-h** [comment]
Number pad icon just tells if numeric or alpha numeric keyboard is shown when keyboard is visible.  It works independently of focus.  Sorry, but at least now I leave it as is.
