### ISSUE TITLE
Baresip doesn't recognize numbers from phonebook with international prefix

### ISSUE THREAD

**Issue by yennor** [juha-h/baresip-studio#247]
I've got all my numbers stored with international prefix, so like +41 31 000 00 00.
Unfortunately when I get a national call, the phone number is announed as 031 000 00 00.
Like that baresip doesn't recognize the phone book entry, and doesn't show me the caller name.

In Linphone you can enter a international prefix for each account, like that it is able to recognize the phone book entries. Maybe something like that would be possible in baresip? (btw. I've just switched from linphone to baresip. And it's definitely working a lot more stable. Thanks for the software :-) )

**Comment by juha-h** [comment]
So a Country Code, for example +41, could be specified for an account and if in incoming call userpart of From URI is a telephone number that starts with a single zero, for example 0312345678, then that 0 would be replaced by the Country Code of the account before contact lookup.  If matching contact is found that contact is shown as caller.  If matching contact is not found, +41312345678 is shown as caller.  And if userpart of From URI is a telephone number that starts with double zero, then that 00 would be replaced with +.

Would this be OK to you?

**Comment by yennor** [comment]
sounds good to me :-) just one thing, a number does not necesarily need to have a 0 at the beginning, if it is without country code (eg. in Colombia phone numbers don't start with 0).

**Comment by gdt** [comment]
This sounds like progress, but It seems to me like the world is pretty messy.  It's all about how various providers deliver numbers.  I know of one that acts as if all the world is + CC NUMBER, always, outbound and I think inbound.  That's odd, as most have a "home country" notion.   So perhaps @yennor should document in the wiki how their provider behaves for in-country and out-of-country (country-code, really, as I know NANP != US, but I think Colombia is a country=countrycode place) calls on a wiki page, and as example accumulate the exact behavior will probably crystallize out.  ( I am not set up to get incoming calls from this carrier I mention; someone else used to use it.)

**Comment by juha-h** [comment]
I added `Country Code` account configuration option with this kind of description:

`Country code of this account.  If From URI userpart of
        incoming call contains a telephone number that does not start with '+' sign followed by
        a country code, the number is prefixed with this country code before the number is looked up
        in contacts. If the telephone number starts with a single digit '0', it is replaced by
        this country code.`

Unfortunately do to libbaresip build problems, I have no idea when (if ever) baresip that includes this feature will be available in F-Droid.

**Comment by yennor** [comment]
thanks a lot. for me it will work like that ;-).
Maybe one could try first a lookup, exactly how the number arrives, and if that doesn't yield a result, with the country code.
I'm hoping for the best for the f-droid build :-)

@gdt instead of collecting all that, it probably would be easier to see how linphone solved it, and copy that. hoping in the years the software was around, they-ve already solved the problem. ;-)

**Comment by juha-h** [comment]
I could first try find the contact w/o adding the country code.  The only thing I'm worried is that the lookups get too heavy if there is lots of contacts, especially in the calls activity.

I don't know want to start reading Linphone source code in order to find out, what problem it is solving nor start copying features from it.  If someone likes baresip and something is missing, I'm open to proposals.

**Comment by juha-h** [comment]
Here is modified description of Country Code account configuration option:

`E.164 country code of this account.  If From URI userpart of
        incoming call contains a telephone number that does not start with \'+\' sign and if contact
        lookup fails, the number is prefixed with this country code and contact lookup is
        tried again. If the telephone number starts with a single digit \'0\',
        digit \'0\' is replaced by this country code.`

**Comment by juha-h** [comment]
The above is now included in published versions of baresip and baresip+.  Re-open if still an issue.

**Comment by juha-h** [comment]
Sorry, my mistake, this will be in the next published version.

**Comment by juha-h** [comment]
The above is now included in published versions of baresip (45.0.0) and baresip+ (32.0.0). Re-open if still an issue.
