### ISSUE TITLE
webrtc support and interop with asterisk

### ISSUE THREAD

**Issue by xuoguoto** [juha-h/baresip-studio#249]
Hello,

First of all thanks for this project and all the hard work you are putting into maintaining this project.

I have started using baresip recently to connect to our asterisk server. We are now using it over TLS protocol, but would like to connect over webrtc. With TLS or SIP I need to allow port 5060 or 5061 in firewall, which gets scanned and attacked quite quickly. I can use a higher port, but its just a matter of time before it is found out. 

I can avoid this with Webrtc/Websocket connection of asterisk with an nginx in front.

I have configured baresip with proxy as `sip:myserver.io:443;transport=wss`, and in nginx logs I am seeing: `"GET / HTTP/1.1" 404 240 "-" "-"` and baresip throws `Protocol Error`

What does baresip expect when it sends the HTTP request? Any one with a successful connection between asterik and baresip using WSS or webrtc?

Thanks!

**Comment by juha-h** [comment]
I don't know how you have configured your nginx as Websocket proxy, but if you use a path, such as /wss to match it, then unfortunately baresip lib does not currently support outbound URIs that include a path, such as 

 wss://asterisk.example.com:443/wss

This is listed in baresip roadmap https://github.com/baresip/baresip/wiki/Roadmap#signaling.

It should work if you can configure your web server to act as Websocket proxy w/o the path.

I have solved this by making my SIP server to listen at port 443 for SIP over Websocket transport.  Perhaps you can do the same with your asterisk and then you could skip nginx as Websocket proxy.

I started to write this before your second post.  So currently outbound URIs with /path are not supported by baresip lib.

**Comment by xuoguoto** [comment]
Thanks for the explanation, I will configure as advised and get back.

**Comment by juha-h** [comment]
I configured my Apache web server to act as Websocket proxy like this:
```
<VirtualHost _default_:443>
...
         SSLProxyEngine on
	<LocationMatch />
		ProxyPass ws://192.168.206.95:5063/
	</LocationMatch>	
        SSLEngine on
...
</VirtualHost>
```

My SIP server is configure to listen for SIP requests over WS at  at 192.168.206.95:5063.

Then I configured baresip's outbound proxy like this:
```
sip:<web server address>:443;transport=wss
```
after which baresip was able to register with my SIP server via the Apache Websocket proxy.

**Comment by xuoguoto** [comment]
Thanks, I am now able to register with Asterisk. I am using nginx and fillowing is the cofig I used:

```
        location / {
                 proxy_pass                          http://127.0.0.1:8088/ws;
                 proxy_set_header Host               $host;
                 proxy_set_header X-Real-IP          $remote_addr;
                 proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
                 proxy_set_header X-Forwarded-Proto  http;
                 proxy_set_header X-VerifiedViaNginx yes;
                 proxy_read_timeout                  300;
                 proxy_connect_timeout               75;
                 proxy_redirect                      off;

    # Specific for websockets: force the use of HTTP/1.1 and set the Upgrade header
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;

        }
```

One more issue I am facing is calls getting disconnected in 30 sec. Looks like ACK of INVITE is not reaching asterisk. I will check and post the update in this thread.

**Comment by xuoguoto** [comment]
In the baresip logcat, after the `SIP/2.0 200 OK` is received from Asterisk, following logs are seen:
```
04-13 12:04:06.487 18613 18640 D Baresip Lib: websock: connecting to 'wss://127.0.0.1:8088/'
04-13 12:04:06.490 18613 18640 D Baresip Lib: sip: websock connection closed (Connection refused)
```
In BareSIP configuration I have enabled `DTLS-STRPF` and `ICE` with `stun:stun.l.google.com:19302` as the server.

**Comment by xuoguoto** [comment]
In the `SIP/2.0 200 OK` packet:
```
SIP/2.0 200 OK
Via: SIP/2.0/WSS 192.168.1.221:9;rport=38142;received=127.0.0.1;branch=z9hG4bK9cb79a64baf40a65
Call-ID: c45c5fb14557ee72
From: <sip:webrtc_client@host-01.mydomain.io>;tag=4318f3ddf61f56f4
To: <sip:1992@host-01.mydomain.io;user=phone>;tag=8ef643d2-58a5-44a9-8fbb-b3c2ab3ddfe2
CSeq: 58169 INVITE
Server: Asterisk PBX 16.2.1~dfsg-2ubuntu1
Contact: <sip:127.0.0.1:8088;transport=ws>
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Content-Type: application/sdp
Content-Length:  1550
```

I can see that its sending `Contact: <sip:127.0.0.1:8088;transport=ws>` which is what Asterisk sees, but is obviously wrong.

**Comment by xuoguoto** [comment]
Took a clue from [this comment](https://github.com/baresip/baresip/issues/859#issuecomment-570026077) and applied the following patch:

```patch
diff --git a/src/sip/transp.c b/src/sip/transp.c
index e400f7f..e435370 100644
--- a/src/sip/transp.c
+++ b/src/sip/transp.c
@@ -1035,14 +1035,14 @@ static int ws_conn_send(struct sip_connqent **qentp, struct sip *sip,
        /* Use port if specified, otherwise use default HTTP/HTTPS ports */
        if (sa_port(dst)) {
                if (re_snprintf(ws_uri, sizeof(ws_uri),
-                               "%s://%J/", prefix, dst) < 0) {
+                               "%s://%J/ws/", prefix, dst) < 0) {
                        err = ENOMEM;
                        goto out;
                }
        }
        else {
                if (re_snprintf(ws_uri, sizeof(ws_uri),
-                               "%s://%j/", prefix, dst) < 0) {
+                               "%s://%j//ws/", prefix, dst) < 0) {
                        err = ENOMEM;
                        goto out;
                }
```
With this I am able to directly connect to asterisk bypassing nginx. So calls are lasting longer than 32 seconds.

Noticed two more issues:

1. Call quality is not that great. I am hearing some crackling sounds in between. I am now testing with debug build 
2. It takes around 9.5 seconds for callers sound to be heard by calee. During that time the encryption marker (a red icon to the right of phone number search box) is red. After 9.5 sec it turns yellow and both sides are able to hear each other.

**Comment by xuoguoto** [comment]
In the second point above, both sides are able to hear each other once re-INVITE is sent by baresip.

**Comment by xuoguoto** [comment]
One more issue: There is no audio for inbound calls:

```
INVITE sip:webrtc_client-0x7343ba9ec0@45.xx5.x1.163:10220;transport=ws SIP/2.0
Via: SIP/2.0/WSS 59.xx2.xx0.154:8089;rport;branch=z9hG4bKPj2cc14c93-08d0-44f1-8997-7749b48ee651;alias
From: <sip:97xxx15xx5@mydomain-er-01>;tag=63366ac5-6fbd-49d9-9fed-f03a2527b1d3
To: <sip:webrtc_client-0x7343ba9ec0@45.xx5.x1.163>
Contact: <sip:asterisk@mydomain-er-01:5060;transport=ws>
Call-ID: 1e6db350-1184-48c5-b465-4264884436fc
CSeq: 23257 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Session-Expires: 1800
Min-SE: 90
Max-Forwards: 70
User-Agent: Asterisk PBX 16.2.1~dfsg-2ubuntu1
Content-Type: application/sdp
Content-Length:  1260

v=0
o=- 1628464547 1628464547 IN IP4 59.xx2.xx0.154
s=Asterisk
c=IN IP4 59.xx2.xx0.154
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE audio-0
m=audio 19588 UDP/TLS/RTP/SAVPF 107 0 8 101
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 39:E4:8D:B7:0D:41:41:0A:EA:D6:49:2C:56:55:70:5F:97:E2:BF:4C:DD:E5:9F:A1:D7:08:7D:77:B0:11:13:FC
a=ice-ufrag:0d3249396e1d31b404661e9d303d053c
a=ice-pwd:6876154e6ba395905d9e9eab2a81a101
a=candidate:Hb1424ccd 1 UDP 2130706431 fe80::523e:aaff:fe10:404 19588 typ host
a=candidate:H53593ffb 1 UDP 2130706431 fe80::e269:95ff:fed8:1573 19588 typ host
a=candidate:Hffbef913 1 UDP 2130706431 fe80::a86c:48ff:fe7a:463c 19588 typ host
a=candidate:Hc0a80374 1 UDP 2130706431 192.168.3.116 19588 typ host
a=candidate:Hac170110 1 UDP 2130706431 172.23.1.16 19588 typ host
a=candidate:H3b5c469a 1 UDP 2130706431 59.xx2.xx0.154 19588 typ host
a=rtpmap:107 opus/48000/2
a=fmtp:107 maxaveragebitrate=28000;useinbandfec=1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:20
a=sendrecv
a=rtcp-mux
a=ssrc:1126562092 cname:00366cfe-5016-48c2-9ab5-8e771fb8cacf
a=msid:1ef7f500-8d22-4da0-82d8-4aa3fc0406b2 c4802524-f7b8-4f47-9f23-93f95fa5ce03
a=mid:audio-0

ua: sipsess connect via WSS 59.xx2.xx0.154:8089 --> 192.168.1.221:46592
webrtc_client@mydomain-er-01.mydomain.io: selected for webrtc_client-0x7343ba9ec0
ua: using origin address 59.xx2.xx0.154 of SDP offer
call: alloc with params laddr=192.168.1.221, af=AF_INET, use_rtp=1
ice: new session with STUN-server at stun.l.google.com (username=)
call: use_video=0
stream: audio: starting mediaenc 'dtls_srtp' (wait_secure=1)


WSS 192.168.1.221:46592 -> 59.xx2.xx0.154:8089SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 59.xx2.xx0.154:8089;branch=z9hG4bKPj2cc14c93-08d0-44f1-8997-7749b48ee651;alias;rport=8089;received=59.xx2.xx0.154
From: <sip:97xxx15xx5@mydomain-er-01>;tag=63366ac5-6fbd-49d9-9fed-f03a2527b1d3
To: <sip:webrtc_client-0x7343ba9ec0@45.xx5.x1.163>;tag=b729885a0deb127e
Call-ID: 1e6db350-1184-48c5-b465-4264884436fc
CSeq: 23257 INVITE
Server: baresip v2.0.1 (?/?)
Contact: <sip:webrtc_client-0x7343ba9ec0@192.168.1.221:46592;transport=wss>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Length: 0


ice: resolved STUN-server to address 142.250.112.127:19302
audio: added interface: rmnet_data0:25.63.178.41 (local prio 0)
audio: added interface: wlan0:192.168.1.221 (local prio 0)
audio: added interface: rndis0:192.168.172.189 (local prio 0)
ice: gathering srflx for comp 1 ..
ice: gathering srflx for comp 2 ..
ice: srflx gathering for comp 2 complete.
ice: srflx gathering for comp 1 complete.
ice: all components gathered.
audio: comp1 setting local: 45.xx5.x1.163:3314
audio: comp2 setting local: 45.xx5.x1.163:59004
ice: audio: Default local candidates: 45.xx5.x1.163:3314 / 45.xx5.x1.163:59004
call: media-nat 'ice' established/gathered
ua event (CALL_INCOMING) sip:97xxx15xx5@mydomain-er-01
sending ua/call 495057542848/495862719776 event call incoming,sip:97xxx15xx5@mydomain-er-01
--- Network debug ---
enabled interfaces:
 rmnet_data0:  25.63.178.41
 rmnet_data0:  2409:4073:38e:4254:4002:bd98:bd1d:ffe8
 rmnet_data2:  2409:4033:38a:e458:211f:186b:6e7:2c7
      wlan0:  192.168.1.221
      wlan0:  fdf9:32a9:1aff:0:a71b:a5c6:58d2:52d2
      wlan0:  fdf9:32a9:1aff:0:df5:90d1:73e0:41f
 DNS Servers from Config: (4)
   0: [fdf9:32a9:1aff::1]:53
   1: 192.168.1.1:53
   2: 49.45.0.1:53
   3: [2405:200:800::1]:53

--- Network debug ---
enabled interfaces:
 rmnet_data0:  25.63.178.41
 rmnet_data0:  2409:4073:38e:4254:4002:bd98:bd1d:ffe8
 rmnet_data2:  2409:4033:38a:e458:211f:186b:6e7:2c7
      wlan0:  192.168.1.221
      wlan0:  fdf9:32a9:1aff:0:a71b:a5c6:58d2:52d2
      wlan0:  fdf9:32a9:1aff:0:df5:90d1:73e0:41f
 DNS Servers from Config: (4)
   0: [fdf9:32a9:1aff::1]:53
   1: 192.168.1.1:53
   2: 49.45.0.1:53
   3: [2405:200:800::1]:53

answering call 495057542848/495862719776
call: answering call on line 1 from sip:97xxx15xx5@mydomain-er-01 with 200
ua event (CALL_REMOTE_SDP) offer
sending ua/call 495057542848/495862719776 event call update,3
call: update media
stream: update 'audio'
stream: receive: setting SSRC: 4325f92c
ua event (CALL_LOCAL_SDP) answer
sending ua/call 495057542848/495862719776 event call answered
{      audio.1} Set default remote candidate: host:59.xx2.xx0.154:19588
ice: audio.2: no remote candidates found (address = 59.xx2.xx0.154:19589)
ice: ICE not supported by peer


WSS 192.168.1.221:46592 -> 59.xx2.xx0.154:8089
SIP/2.0 200 Answering
Via: SIP/2.0/WSS 59.xx2.xx0.154:8089;branch=z9hG4bKPj2cc14c93-08d0-44f1-8997-7749b48ee651;alias;rport=8089;received=59.xx2.xx0.154
From: <sip:97xxx15xx5@mydomain-er-01>;tag=63366ac5-6fbd-49d9-9fed-f03a2527b1d3
To: <sip:webrtc_client-0x7343ba9ec0@45.xx5.x1.163>;tag=b729885a0deb127e
Call-ID: 1e6db350-1184-48c5-b465-4264884436fc
CSeq: 23257 INVITE
Server: baresip v2.0.1 (?/?)
Contact: <sip:webrtc_client-0x7343ba9ec0@192.168.1.221:46592;transport=wss>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Supported: ice,gruu,path,outbound,replaces
Content-Type: application/sdp
Content-Length: 1306

v=0
o=- 1111419856 164525476 IN IP4 192.168.1.221
s=-
c=IN IP4 192.168.1.221
t=0 0
a=ice-ufrag:84z8KZo
a=ice-pwd:j6sx2dQSGcneAYrCoG53A2xUjz7Nqnj
a=setup:active
a=fingerprint:SHA-256 41:14:26:73:24:6C:4C:3E:5C:C7:60:86:47:31:5B:5D:45:B0:62:17:A1:26:D1:D0:50:82:F0:8C:6D:60:0F:89
m=audio 3314 UDP/TLS/RTP/SAVPF 107 101
c=IN IP4 45.xx5.x1.163
a=rtpmap:107 opus/48000/2
a=fmtp:107 stereo=0;sprop-stereo=0;maxaveragebitrate=48000;cbr=0;useinbandfec=1
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=rtcp:59004 IN IP4 45.xx5.x1.163
a=sendrecv
a=ssrc:3874127620 cname:sip:webrtc_client-0x7343ba9ec0@45.xx5.x1.163
a=minptime:20
a=ptime:20
a=label:1
a=candidate:193fb229 1 UDP 2113929471 25.63.178.41 40184 typ host
a=candidate:193fb229 2 UDP 2113929470 25.63.178.41 40185 typ host
a=candidate:c0a801dd 1 UDP 2113929471 192.168.1.221 40184 typ host
a=candidate:c0a801dd 2 UDP 2113929470 192.168.1.221 40185 typ host
a=candidate:c0a8acbd 1 UDP 2113929471 192.168.172.189 40184 typ host
a=candidate:c0a8acbd 2 UDP 2113929470 192.168.172.189 40185 typ host
a=candidate:2d735ba2 2 UDP 1677721854 45.xx5.x1.163 59004 typ srflx raddr 25.63.178.41 rport 40185
a=candidate:2d735ba2 1 UDP 1677721855 45.xx5.x1.163 3314 typ srflx raddr 25.63.178.41 rport 40184
a=mid:audio-0
a=ice-mismatch

WSS 59.xx2.xx0.154:8089 -> 192.168.1.221:46592
ACK sip:webrtc_client-0x7343ba9ec0@45.xx5.x1.163:10220;transport=ws SIP/2.0
```

It seems ICE negotiation is failing:
```
ice: audio.2: no remote candidates found (address = 59.xx2.xx0.154:19589)
ice: ICE not supported by peer
```

**Comment by juha-h** [comment]
As I mentioned, baresip lib does not currently support path in outbound proxy URI and there is feature request note about it.  In my opinion, it should be possible to configure Asterisk to accept Websocket connection setup without path.  Port and Sec-WebSocket-Protocol=sip should suffice, like it does with my SIP server.

As you wrote, the delay before you callee hears sound from caller may be due to ICE not supported by the peer.  Or does the delay go away if you do not use Websocket transport?

**Comment by xuoguoto** [comment]
For the websocket path issue, I hard coded it , with the patch listed above. The delay is not happening in another server I tested, so it may be an ICE negotiation delay in one server. 

Now the only remaining issue is the crackling sound that happens during call. Not sure how to address it.

**Comment by juha-h** [comment]
It audio cracking both when you make a call and answer a call?  I just tested several calls between JsSIP Webrtc client on my Firefox browser and baresip.  All calls worked fine except one where I heard cracking sound.  Then baresip wrote to adb debug log these kind of errors:
```
04-17 09:03:56.618  9807  9841 D Baresip+ Lib: opus: decode error: corrupted stream
04-17 09:03:56.619  9807  9841 D Baresip+ Lib: audio: opus codec decode 70 bytes: Protocol error
04-17 09:03:56.619  9807  9841 D Baresip+ Lib: opus: decode error: corrupted stream
04-17 09:03:56.619  9807  9841 D Baresip+ Lib: audio: opus codec decode 74 bytes: Protocol error
...
```
In the failing call this was missing in the adb deog:
```
04-17 09:06:21.336  9807  9841 D Baresip+ Lib: dtls_srtp: ---> DTLS-SRTP complete (audio/RTP) Profile=AEAD_AES_256_GCM
04-17 09:06:21.336  9807  9841 D Baresip+ Lib: call: mediaenc event 'Secure' (audio,RTP)
```
So looks like  DTLS-SRTP setup for audio stream was for some reason not completed.

Delay in call setup is common when ICE is used.  If you don't really need ICE, configure both baresip and Asterisk not to use any media NAT protocol.  Webrtc transport for SIP is not dependent on ICE (nor DTLS-SRTPF).

**Comment by juha-h** [comment]
I added feature request about WebSocket outbound URI.  If you still have DTLS/ICE related issues, try with Linux baresip to make sure that they are not baresip Android app related.

**Comment by xuoguoto** [comment]
There is an update:

When I originally compiled `libbaresip-android` package `pkg-config` was missing. After installing `pkg-config` and recompiling, the crackling noise has disappeared. Now everything is working fine.

**Comment by moradi-morteza** [comment]
hi, is there any about about sip over websocket in baresip?
i want to connect to my asterisk server websocket port (8089) from baresip android and do signaling.

**Comment by moradi-morteza** [comment]
hi, Sir, has this feature been added in the new version to add the websocket domain?

**Comment by juha-h** [comment]
See Account/Outbound Proxies Help text on how use websocket transport to your SIP Proxy.

**Comment by moradi-morteza** [comment]
> See Account/Outbound Proxies Help text on how use websocket transport to your SIP Proxy.

thanks, in android app i used [wss://example.com:8089/ws] its not acceptable

**Comment by moradi-morteza** [comment]
> See Account/Outbound Proxies Help text on how use websocket transport to your SIP Proxy.

The text of the guide mentions that : **sip:IP:PORT;transport=wss**
but i need : **sip:IP:PORT/ws;transport=wss**
because asterisk websocket path has **/ws** at end of url

**Comment by juha-h** [comment]
baresip lib does not currently support path in WebSocket outbound URI.  The feature is listed in roadmap https://github.com/baresip/baresip/wiki/Roadmap#signaling.  I suggest you configure your Asterisk to accept websocket connection without path or frontend your asterisk with web server proxy.
