### ISSUE TITLE
Doesn't use local DNS

### ISSUE THREAD

**Issue by brianjmurrell** [juha-h/baresip-studio#25]
Why is baresip not using the network provided DNS by default?

Overriding DNS to use a non-network-provided DNS should be an option a user chooses.

Imagine the scenario where a phone roams in and out of a network where a SIP server is located and as such that server has a different "presence" based on whether the client is connecting to it on the local network or over the Internet.

This wouldn't be as much of an issue except #24 means that in an IPv4-only world, addresses of things inside of local networks are typically different than they are from outside and DNS servers in a LAN often produce different addresses than DNS servers outside of the LAN.  Only for IPv4 though.  IPv6 results are, (I suspect, at least) much more consistent inside and outside of the LAN due to the lack of need for NAT due to address depletion.

**Comment by juha-h** [comment]
Brian J. Murrell writes:

> Why is baresip not using the network provided DNS by default?

The reason is that libre that makes the DNS queries does not have
access to those servers:

   The following changes affect privacy in Android 8.0 (API level 26).

   The system properties net.dns1, net.dns2, net.dns3, and net.dns4 are
   no longer available, a change that improves privacy on the platform.

This is discussed in issue https://github.com/creytiv/re/issues/137.

**Comment by brianjmurrell** [comment]
While I'm fairly knowledgeable and recent in the Android ecosystem and O/S in general, I'm not an Android developer so I'm afraid none of that is making clear sense to me.

I am a software (systems, networking and more) engineer on other platforms such as Linux, so I understand the general concept that an O/S is supposed to provide name resolution services to applications and generally speaking the O/S should default to using the nameservers provided by the network configuration services (DHCP, SLAAC, etc.).

So I'm still at a loss to understand why baresip doesn't just ask Android to perform name resolutions for it, which would utilise the local nameservers.

**Comment by juha-h** [comment]
Brian J. Murrell writes:

> So I'm still at a loss to understand why baresip doesn't just ask
> Android to perform name resolutions for it, which would utilise the
> local nameservers.

As I mentioned, libbaresip is not making the DNS queries.  It is done
by libre which is used by baresip.  libre is written in C and does not
have any means to ask anything from Android.

I personally consider network provided DNS servers a big security risk.

**Comment by brianjmurrell** [comment]
> I personally consider network provided DNS servers a big security risk.

I guess you don't work in any private networks then.  Not everyone in the world only ever operates on the open Internet all of the time.

I would actually trust my own private DNS server for privacy more than I would trust "public" DNS servers.

You have previously talked about your concerns with privacy and tracking yet baresip defaults to using the Google public DNS servers.  Surely you must believe that those servers/services are tracking you, yes?

**Comment by licaon-kter** [comment]
@brianjmurrell  Though...is baresip choosing them or Android?

**Comment by juha-h** [comment]
Brian J. Murrell writes:

> > I personally consider network provided DNS servers a big security risk.
> 
> I guess you don't work in any private networks then.  Not everyone in
> the world only ever operates on the open Internet all of the time.

You can add two DNS Servers, one for the Internet and one for your
private network.

> I would actually trust my own private DNS server for privacy more than
> I would trust "public" DNS servers.

Yes, and you can point baresip to use it.

> You have previously talked about your concerns with privacy and
> tracking yet baresip defaults to using the Google public DNS servers.
> Surely you must believe that those servers/services are tracking you,
> yes?

Google DNS server is just the default, which the user can override.

**Comment by juha-h** [comment]
Licaon_Kter writes:

> @brianjmurrell  Though...is baresip choosing them or Android?

Currently libre used by libbaresip cannot access Android DNS servers and
it is thus up to the user to choose, which DNS servers baresip is using.

**Comment by brianjmurrell** [comment]
> You can add two DNS Servers, one for the Internet and one for your
private network.

Are they used failover or round-robin?  Round-robin for example does not try the other if a lookup fails.  With round-robin (the default for glibc for example, and most resolvers I suspect) it is assumed that all listed servers have the same content and they are just used for redundancy.

In any case, that still doesn't work.  If I am on my LAN where my PBX is 192.168.1.1 but the PBX has an Internet address of 10.1.1.1, if baresip uses Internet DNS server when I am on my LAN, I will get the wrong address for the PBX because I would get the Internet-facing address when I am on the same LAN as the PBX.

It also means I have to keep manually reconfiguring DNS servers as I move from LAN to LAN.  Not scalable.

> Yes, and you can point baresip to use it.

But it has different addresses on the LAN and the Internet, thanks to [IPv4 NAT](https://github.com/juha-h/baresip-studio/issues/24).

Anyway, this is getting off into the weeds.  Ultimately baresip is not really usable in environments outside of "everything and everyone is on the Internet".  And that's fair enough if that's the desired mission of baresip.

**Comment by juha-h** [comment]
Brian J. Murrell writes:

> In any case, that still doesn't work.  If I am on my LAN where my PBX
> is 192.168.1.1 but the PBX has an Internet address of 10.1.1.1, if
> baresip uses Internet DNS server when I am on my LAN, I will get the
> wrong address for the PBX because I would get the Internet-facing
> address when I am on the same LAN as the PBX.

It might work if you have your private one as the first DNS server and
the Internet one as the second.  The first one would not respond, if you
are on the Internet.

> It also means I have to keep manually reconfiguring DNS servers as I
> move from LAN to LAN.  Not scalable.

Yes, hopping between private networks could cause problems, but may that
use case is not very common.

> Anyway, this is getting off into the weeds.  Ultimately baresip is not
> really usable in environments outside of "everything and everyone is
> on the Internet".  And that's fair enough if that's the desired
> mission of baresip.

There is no such mission.  It is Android's decision.

**Comment by juha-h** [comment]
Now referenced in issue https://github.com/juha-h/baresip-studio/issues/26.

**Comment by juha-h** [comment]
I'll close this, since Google does not anymore allow access to DNS server information needed by libre.

**Comment by juha-h** [comment]
Version 8.1.0 now allows dynamic DNS server configuration based on system provided DNS information.
