### ISSUE TITLE
45.0.0 makes VoIP garbled and unintelligible

### ISSUE THREAD

**Issue by myfirstnameispaul** [juha-h/baresip-studio#253]
45.0.0 installed through update from F-Droid on Android 11 and VoIP is now garbled and unintelligible, with audio not in the correct order.

**Comment by myfirstnameispaul** [comment]
This was somehow related to logging into my provider, and has since cleared by making an outbound call using an account I normally do not make outbound calls with.

My provider lists the registration status for each account, and one was showing not registered, while the other was showing registered. After making an outbound call with the unregistered account, I made an outbound call with the registered account and the voice worked and the other account showed as registered.

**Comment by juha-h** [comment]
If baresip audio now works for you, please close this issue.
