### ISSUE TITLE
Have a Re-dial Option

### ISSUE THREAD

**Issue by muellert** [juha-h/baresip-studio#256]
I have baresip+ 32.0.0, and when I look at the call list, I can not directly just redial an entry, and (obviously) also not call back an incoming call.

**Comment by juha-h** [comment]
I'm not sure if I understand what you mean. In Call History, if you touch an entry, you got a popup where you can choose to call or send message to the caller/callee.  And on the main window, if you touch the Call to ... line, the previous caller or callee shows up.
