### ISSUE TITLE
Support for intents to control account register

### ISSUE THREAD

**Issue by jvandenbroek** [juha-h/baresip-studio#257]
It would be nice if there was a way to toggle the account register with an intent, so it can be controlled programmatically (eg. with Tasker). Maybe for other functionality as well, but I was looking for this in particular.

**Comment by juha-h** [comment]
Joost van den Broek writes:

> It would be nice if there was a way to toggle the account register
> with an intent, so it can be controlled programmatically (eg. with
> Tasker). Maybe for other functionality as well, but I was looking for
> this in particular.

Can you provide pull request?

**Comment by juha-h** [comment]
Joost van den Broek writes:

> It would be nice if there was a way to toggle the account register
> with an intent, so it can be controlled programmatically (eg. with
> Tasker). Maybe for other functionality as well, but I was looking for
> this in particular.

So something like adding to BaresipService

  <intent-filter>
    <action android:name="com.tutpro.baresip.REGISTER" />
  </intent-filter>

and then in data tell which account?

**Comment by jvandenbroek** [comment]
> So something like adding to BaresipService <intent-filter> <action android:name="com.tutpro.baresip.REGISTER" /> </intent-filter> and then in data tell which account?

Yes exactly. Unfortunately I have no experience with Android programming, so can't provide a PR for this. But hopefully you can find some time to implement it :-) Thanks.

**Comment by juha-h** [comment]
I, on the other hand, don't have any experience with Tasker.  Which Tasker app are you using and how would you configure it to send the intents?

**Comment by juha-h** [comment]
Tasker seems to be closed source paid app.  Unless there is open source variant, it is not possible for me to add and test this feature.

**Comment by gdt** [comment]
I don't know anything about Tasker, but there is a Free Software app "Easer":  https://f-droid.org/en/packages/ryey.easer/  that is useful to automate behavior.  Basically, it can trigger based on lots of things, time, wifi/cell/bluetooth connections, probably location, and then control various things.   I tried it but stopped because it solved problems I don't really have, but consider wanting a SIP account to be registered when not home and not driving, or something.    So the idea would be to have intents to register/deregister.

**Comment by juha-h** [comment]
I tried Easer, but was not able to create a profile that would send broadcast.  Even when I select "Send Broadcast" operation, it still results in "Start Activity" operation.  Register/unregister has nothing to do with an activity and there may be no baresip activity active.  I don't know why is always creates "Start Activity" operation.

**Comment by juha-h** [comment]
Turned out there is open issue on this bug: https://github.com/renyuneyun/Easer/issues/409 and it is not fixed in the version available in F-Droid.  So no luck.  I cannot implement something that I cannot test.

**Comment by juha-h** [comment]
Turned out that `adb shell` has command to send broadcast.  I have now added receiver for these two intents:
```
<intent-filter>
                <action android:name="com.tutpro.baresip.REGISTER" />
                <action android:name="com.tutpro.baresip.UNREGISTER" />
            </intent-filter>
```
and tested them like this:
```
adb shell am broadcast -a com.tutpro.baresip.REGISTER -p com.tutpro.baresip --es aor foo@test.tutpro.com
adb shell am broadcast -a com.tutpro.baresip.UNREGISTER -p com.tutpro.baresip --es aor foo@test.tutpro.com
```
Is that OK or something still missing or needs to be changed?

**Comment by jvandenbroek** [comment]
Thank you @juha-h, this works great!

To get this working in Tasker, add a Send Intent with the following values:
```
Action: com.tutpro.baresip.REGISTER (/ UNREGISTER)
Extra: aor:foo@test.tutpro.com
Package: com.tutpro.baresip
```

**Comment by juha-h** [comment]
Thanks, I added the above Tasker example to the Wiki page.
