### ISSUE TITLE
Windows Android Studio guide

### ISSUE THREAD

**Issue by arvindjkhr** [juha-h/baresip-studio#258]
Hi @juha-h ,

I really liked the App features. I would like to introduce some more feature in this as my requirement.
Can you please write some quick guide to set it up  in Windows Android studio?

Thanks
Arvind

**Comment by juha-h** [comment]
arvindjkhr writes:

> I really liked the App features. I would like to introduce some more
> feature in this as my requirement.

> Can you please write some quick guide to set it up  in Windows Android
> studio?

Sorry, I have been Unix/Linux user from the late 80s and don't know
anything about Windows.

-- Juha
