### ISSUE TITLE
proposed enhancements

### ISSUE THREAD

**Issue by juha-h** [juha-h/baresip-studio#26]

**Comment by juha-h** [comment]
- Use network provided DNS servers by default (https://github.com/juha-h/baresip-studio/issues/25)

**Comment by packetup** [comment]
- Add support for alternative ports

**Comment by juha-h** [comment]
What do you mean by "alternative ports"?

**Comment by packetup** [comment]
user@domain:port is currently an "Invalid SIP Address of Record" and no method to set a different port number.

**Comment by juha-h** [comment]
packetup writes:

> user@domain:port is currently an "Invalid SIP Address of Record" and
> no method to set a different port number.

What do you want to achieve by adding port number to AoR?  Is it so that
you don't want to register an account, but want baresip to listed at that
port?

**Comment by gdt** [comment]
SIP primarily is about looking up SRV records for a domain to connect to the proxy.  But it can also be local and/or peer-to-peer without configured domains.  There, one might connect to user@[ip-addr] and want to specify a port, rather than defaulting to 5060/5061.

**Comment by juha-h** [comment]
Baresip currently accepts ip address, port and transport in callee URI.  I think @packetup means something else (perhaps port number in account's AoR).

I'm currently in the process of adding listen ip:port in config that might help.

**Comment by packetup** [comment]
@gdt is correct. I'm looking to specify a port instead of the default 5060/5061. Sorry if I was unclear.

**Comment by juha-h** [comment]
Version 7.2.0 now has Listen Address config variable that may help with the issue that @packetup is facing.  It make take some time before 7.2.0 shows up in Play Store or F-Droid if you don't build baresip youself.

**Comment by packetup** [comment]
@juha-h that is great. Sorry, I was unaware of the addition.

**Comment by packetup** [comment]
@juha-h Unfortunately I'm still unable to connect after specifying the port in the listening address. I'm able to connect using other SIP clients.

**Comment by juha-h** [comment]
packetup writes:

> @juha-h Unfortunately I'm still unable to connect after specifying the
> port in the listening address. I'm able to connect using other SIP
> clients.

What do you mean by "connect"? Register or make a call?  Can you take
packet trace (pcap) from the attempt?  Also

adb logcat | grep Baresip

would be useful.

**Comment by juha-h** [comment]
In outgoing requests Listen Address port determines source address port only when UDP is used.  If TCP or TLS is used, source address port is any free port.

**Comment by packetup** [comment]
@juha-h The server uses the TLS transport. That explains why I was unsuccessful.

**Comment by juha-h** [comment]
packetup writes:

> @juha-h The server uses the TLS transport. That explains why I was
> unsuccessful.

If it the server where you register, then it should work when you define
an Outbound Proxy like this:

sip:<server>:5061;transport=tls

or if the server has SRV DNS records, you don't need to define
anything.

**Comment by packetup** [comment]
@juha-h Thank you for the advice. I am now able to connect and register but run into a new problem. All calls are blank. I'm able to fix this issue in other clients by enabling "Allow IP Rewrite." Perhaps you could implement this feature into baresip.

**Comment by juha-h** [comment]
packetup writes:

> @juha-h Thank you for the advice. I am now able to connect and
> register but run into a new problem. All calls are blank. I'm able to
> fix this issue in other clients by enabling "Allow IP Rewrite."
> Perhaps you could implement this feature into baresip.

What do you mean by calls being blank?  Don't you hear anything?  Can
you call The Test Call?

What does "Allow IP Rewrite" do?

**Comment by packetup** [comment]
@juha-h https://www.microsip.org/help#allowRewrite

**Comment by juha-h** [comment]
packetup writes:

> @juha-h https://www.microsip.org/help#allowRewrite

Usually NAT traversal is supported by SIP Proxy/Media Proxy. baresip
supports ICE and STUN for NAT traversal.  Currently ICE is available in
account configuration.  Have you checked Use ICE?

**Comment by packetup** [comment]
@juha-h Yes, I have tried but it does not help. The same thing occurs in MicroSIP but the "Allow IP Rewrite" makes calls work.

**Comment by juha-h** [comment]
packetup writes:

> @juha-h Yes, I have tried but it does not help. The same thing occurs
> in MicroSIP but the "Allow IP Rewrite" makes calls work.

I can add choice of media NAT traversal between ICE and STUN.  If STUN
does not help, then there is nothing I can do.  baresip library only
supports established standards.

I strongly suggest that you use a SIP Proxy/Media Proxy combination
(such as based on Kamailio/RTP Engine) that handles NAT traversal
without a need for any tricks in SIP client.

**Comment by juha-h** [comment]
juha-h writes:

> I can add choice of media NAT traversal between ICE and STUN.  If STUN
> does not help, then there is nothing I can do.  baresip library only
> supports established standards.
> 
> I strongly suggest that you use a SIP Proxy/Media Proxy combination
> (such as based on Kamailio/RTP Engine) that handles NAT traversal
> without a need for any tricks in SIP client.

I just created new release 7.3.0 that supports STUN media NAT protocol
in addition to ICE.  When STUN is selected, baresip finds out its global
IP address from STUN server and then uses that in outgoing SDP.

Note that STUN does not work if baresip is behind symmetric NAT.  In
that case there is no other choice than use SIP Proxy/Media Proxy that
supports UAs behind NATs.

**Comment by packetup** [comment]
@juha-h The only difference I've observed related to my issue is the absence of the ob parameter. For example, when registering with MicroSIP my contact is added as "sip:username@ip:port;transport=TLS;ob" but not with this app. According to RFC 5626, in this context the ob parameter "indicates that the UA would like other requests in the same dialog to be routed over the same flow."

**Comment by juha-h** [comment]
packetup writes:

> @juha-h The only difference I've observed related to my issue is the
> absence of the ob parameter. For example, when registering with
> MicroSIP my contact is added as
> "sip:username@ip:port;transport=TLS;ob" but not with this
> app. According to RFC 5626, in this context the ob parameter
> "indicates that the UA would like other requests in the same dialog to
> be routed over the same flow."

According to RFC 5626, "ob" parameter only applies to requests that
establish dialogs (such as INVITE).  It is not used in REGISTER
requests.

Previously you mentioned that you had no audio in a call and I
understood that audio was sent to private address.  STUN support added
in 7.3.0 might help there.

So I'm confused regarding what your issue actually is.  Perhaps you
could get pcap of a register request/response and then of a call
attempt.

**Comment by juha-h** [comment]
It was bad idea to try to collect all enhancement requests to a single issue.
