### ISSUE TITLE
[Question] Does baresip on Android support multiple ongoing calls ?

### ISSUE THREAD

**Issue by oliexe** [juha-h/baresip-studio#260]
Hello,

Do baresip-android and baresip-studio support multiple incoming calls ? 

Use Case: One call is already connected, another call is currently ringing and the user wants to switch between these two calls.

**Comment by juha-h** [comment]
oliexe writes:

> Do baresip-android and baresip-studio support multiple incoming calls
> ?

No, it doesn't.  Only in case of attended transfer there can
be two calls active at the same time.

There is no plans to add such feature, since it creates non-trivial user
interface challenges.
