### ISSUE TITLE
Handsfree speaking 

### ISSUE THREAD

**Issue by starbrights** [juha-h/baresip-studio#262]
I assume the icon on top (rectangle with outgoing waves) does switch between speaker or earpiece? If so that doesn't seems to work for me.
I am using latest version (46) from FDroid on Android 12 / LOS19 for microG. 
Let me say thanks for offering this app and maintanance! This is very welcome.

**Comment by juha-h** [comment]
That icon turns speakerphone on/off.  It has nothing to do with handsfree.  For that you need to use bluetooth audio.

**Comment by starbrights** [comment]
That's bit strange. Never ever I had the need to turn off speaker. I mean for what reason should this be good?
Or is it for the ring tone? Sorry I couldn't test this well with a single phone ;)

There was a bugfix released yesterday that changes the reaction of this speaker button.

I notices that this can't be changed while I am in a call, that increases my suspect it is for the ringtone. But - wether the icon is red or green: In Android status (pull down from top), bar is notices as "muted". !?!
 
What is really needed is to switch between earpiece and speaker. You will need the speaker if you want to give some dialtones (DTMF). You need to hold your phone away from ear to touch the screen but you will not listen anything than. It is not good that a BT headset is required for that, as you just often don't have it.

BTW:
I can't proof what and why this is happened. I yesterday wants to listen music via BT. I didn't get any sound out of it, only via speaker. It was connected, slider was on full volume, no sound. I  need to reboot my phone. That can have any reason but in case you operate with system wide settings - please don't do that.

**Comment by juha-h** [comment]
I think I misunderstood what you was after. The icon does this:
```
am.isSpeakerphoneOn = !am.isSpeakerphoneOn
```
See https://developer.android.com/reference/android/media/AudioManager what speakerphone is.

I just tested and during call volume was increased  when I turned it on and thus I was able to hear the other party when my device was not near my ear.

**Comment by starbrights** [comment]
OK, than this icon is for what I need. But it seems not possible to change that during a call, which sometimes is needed.

**Comment by juha-h** [comment]
starbrights writes:

> OK, than this icon is for what I need. But it seems not possible to
> change that during a call, which sometimes is needed.

On my Android 10 and 11 devices, speakerphone on/off works also during
call.  Try with another device.

-- Juha

**Comment by starbrights** [comment]
I checked in debug mode and with MatLog and filtered for "audiodevice". 
It seems the commands to AudioDeviceBroker will be send (setSpeakerphoneOn(true/false).
But the icon color doesn't change and also it will go on via earpiece.
in one test I get warning: 
setCommunicationRouteforClient: failure to start BT SCO
but in a 2nd test not. !?!

**Comment by juha-h** [comment]
Icon color does not change if there was no change:
```
R.id.speakerIcon -> {
                am.isSpeakerphoneOn = !am.isSpeakerphoneOn
                if (am.isSpeakerphoneOn)
                    item.setIcon(R.drawable.speaker_on)
                else
                    item.setIcon(R.drawable.speaker_off)
            }
```
So for some reason, change does not work on your device.  It works on my devices.

`failure to start BT SCO` means that bluetooth start has failed.  Don't know why, but I doubt that it is baresip's fault.
