### ISSUE TITLE
[Feature request] Showing all acounts in main window and let them register from there / select the one to use while dialing or per preference

### ISSUE THREAD

**Issue by starbrights** [juha-h/baresip-studio#263]
I use it with different accounts. Not always it make sense to activate all. 
At the moment for register/unregister I have to dive into the accoun menu, uncheck the box, confirm and go back.
A check/uncheck in main window would be more comfortable.

If more than one would be active it has to be decides which account to use. It could be either done by preference or by manually selection while init of call.

I am not aware how complicated that is - and this is in no way a complain. Just an idea to make barsip more comfortable.

**Comment by juha-h** [comment]
Instead via menu, you can get to account's Account activity by touching the colored dot on the left hand side of the account's address of record. You then need to check/uncheck Register there as you have described. I don't want to complicate the main screen with yet another button.  The app needs to be usable also on devices with small screens.

**Comment by starbrights** [comment]
My first expectation by pressing the colored dot was in fact to register/unregister it with a single touch. Once all is set up, this is probably the only action left. 
What I need to get used to is to confirm a change with upright button. It may protect from unwanted changes but extra 
confirmation is often not needed nowadays. But that's fine, I think.

Finally is it a question of different uses cases - so there is no right or wrong. I just want to share my ideas.

**Comment by juha-h** [comment]
Perhaps it would be possible to register/un-register by long touch of the registration status dot.  I'll check.

**Comment by juha-h** [comment]
It was possible.  Next version will have long click listener on AoR spinner that can be used to register/un-register selected account.
