### ISSUE TITLE
Listed accounts are named after username@domain, not  with user defined name

### ISSUE THREAD

**Issue by starbrights** [juha-h/baresip-studio#265]
For me this username is a crypttic number that doesn't give me an indication which account (which dial number) I actually use. 
As this is for list only - wouldn't it be much better to show the user defined name (as for me I use my dial number).

**Comment by juha-h** [comment]
A setting would need to be added to tell if user wants to see account's username@domain or Display Name in AoR spinner and elsewhere. I added a Feature Request about it to the Wiki.

**Comment by juha-h** [comment]
starbrights writes:

> For me this username is a crypttic number that doesn't give me an
> indication which account (which dial number) I actually use.  
> As this is for list only - wouldn't it be much better to show the user
> defined name (as for me I use my dial number).

It was not good idea to use account's Display Name as the name.  So a
new item should be be added to account's configuration.  Feature request
now reads:

  Add possibility to give each account a name that is shown in account
  spinner and elsewhere instead of account's address of record.

**Comment by starbrights** [comment]
Ok, thank you! 
Don't know how other sip providers handle that, but my ones username is just an number - so not helpful to identify accounts. 

Maybe I ask: the field (German: Anzeige name) English maybe: name to display - where / for what this it used?

**Comment by juha-h** [comment]
starbrights writes:

> Maybe I ask: the field (German: Anzeige name) English maybe: name to
> display - where / for what this it used?

Display Name is included in SIP request From URI, for example,

From: "John Deer" ***@***.***>;tag=35371~9f103432

It is not good idea to use it as name of an account, because several
accounts may have the same Display Name.

**Comment by gdt** [comment]
FWIW, the "Display Name" confused me too.    I might suggest "Local Nickname" as a blend of short and giving the right idea.

**Comment by juha-h** [comment]
Commit https://github.com/juha-h/baresip-studio/commit/76b66b0f936c7f74537816f08a73d6945978e226 added possibility to nickname accounts.

**Comment by juha-h** [comment]
Greg Troxel writes:

> FWIW, the "Display Name" confused me too.    I might suggest "Local
> Nickname" as a blend of short and giving the right idea.

So you suggest "Local Nickname" to name an account in baresip app?
