### ISSUE TITLE
project not importing successfully

### ISSUE THREAD

**Issue by Miteshmakwana73** [juha-h/baresip-studio#27]
I am getting this error after importing project

```
12:50 PM	Gradle sync failed: org.jetbrains.kotlin.kapt.idea.KaptGradleModel PluginClassLoader[org.jetbrains.android, 10.3.3.2] com.intellij.ide.plugins.cl.PluginClassLoader@31d6e677org/jetbrains/kotlin/kapt/idea/KaptGradleModel
						org.jetbrains.kotlin.kapt.idea.KaptGradleModel PluginClassLoader[org.jetbrains.android, 10.3.3.2] com.intellij.ide.plugins.cl.PluginClassLoader@31d6e677
						Consult IDE log for more details (Help | Show Log) (10 s 536 ms)
```

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> I am getting this error after importing project
> 
> ```
> 12:50 PM	Gradle sync failed: org.jetbrains.kotlin.kapt.idea.KaptGradleModel PluginClassLoader[org.jetbrains.android, 10.3.3.2] com.intellij.ide.plugins.cl.PluginClassLoader@31d6e677org/jetbrains/kotlin/kapt/idea/KaptGradleModel
> 						org.jetbrains.kotlin.kapt.idea.KaptGradleModel PluginClassLoader[org.jetbrains.android, 10.3.3.2] com.intellij.ide.plugins.cl.PluginClassLoader@31d6e677
> 						Consult IDE log for more details (Help | Show Log) (10 s 536 ms)
> ```

Beats me.  I just tried with Android Studio 3.3.2 and import from github
worked fine.  Perhaps IDE log tells something:

Consult IDE log for more details (Help | Show Log)

**Comment by Miteshmakwana73** [comment]
I am also using android studio 3.3.2 
this is log file I am getting
[idea.log](https://github.com/juha-h/baresip-studio/files/3120512/idea.log)

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> I am also using android studio 3.3.2 
> this is log file I am getting
> [idea.log](https://github.com/juha-h/baresip-studio/files/3120512/idea.log)

I don't see anything related to baresip in the log.  There was

2019-04-24 13:32:10,459 [thread 290]   INFO - e.project.sync.GradleSyncState - Started setup of project 'linphone_android_feature_release_4.1'

**Comment by Miteshmakwana73** [comment]
at the bottom of log file error showing,
I solve this issue by updating kotlin version  1.3.30 to  1.3.31

**Comment by Miteshmakwana73** [comment]
now I am getting a new error

```
Build command failed.
Error while executing process /home/jenya1/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/jenya1/Downloads/baresip-studio-master/app/.externalNativeBuild/cmake/debug/arm64-v8a --target baresip}

ninja: error: '/home/jenya1/Downloads/baresip-studio-master/distribution/baresip/lib/arm64-v8a/libbaresip.a', needed by '/home/jenya1/Downloads/baresip-studio-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so', missing and no known rule to make it
```

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> ```
> Build command failed.
> Error while executing process /home/jenya1/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/jenya1/Downloads/baresip-studio-master/app/.externalNativeBuild/cmake/debug/arm64-v8a --target baresip}
> 
> ninja: error: '/home/jenya1/Downloads/baresip-studio-master/distribution/baresip/lib/arm64-v8a/libbaresip.a', needed by '/home/jenya1/Downloads/baresip-studio-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so', missing and no known rule to make it
> ```

Check that you have generated the libs as mentioned in README.md.

**Comment by Miteshmakwana73** [comment]
now I have to work according to [this](https://github.com/juha-h/libbaresip-android) instruction?

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> now I have to work according to
> [this](https://github.com/juha-h/libbaresip-android) instruction?

Yes, that is what README.md clearly states.

**Comment by Miteshmakwana73** [comment]
after implementing [this](https://github.com/juha-h/libbaresip-android) successfully I get all the necessary 
folder in distribution but I am getting one error and one warning
![result](https://user-images.githubusercontent.com/38969602/56880759-a39ce180-6a7b-11e9-8dd6-bb37cb508044.png)

**Error**
[error.txt](https://github.com/juha-h/baresip-studio/files/3126255/error.txt)

**Warning**
`ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.`

**Comment by juha-h** [comment]
I don't why in your environment stdin and stdout functions are not
available, which is the reason for the errors.

f-droid is able to automatically build baresip apk including all libs
so I don't think there are any issues related to the build.

> **Warning**
> `ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.`

This is caused by a bug in android studio and can be ignored.

**Comment by Miteshmakwana73** [comment]
what should i do now?

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> what should i do now?

Check that your have not made any changes to libbaresip or
baresip-studio code and that you are using Sdk from Android Studio
3.3.2.

I you want to build your own app and encounter problems, you need to
start digging into the reasons by reading the code, searching the web,
etc.  It may require lot of work, since everything nowadays is a
rapidly moving target.

**Comment by Miteshmakwana73** [comment]
I just change in libbaresip-android-master makefile

```
# -------------------- VALUES TO CONFIGURE --------------------
# Path to your Android NDK (must be r19 or higher)
NDK_PATH  :=  /home/jenya1/Android/Sdk/ndk-bundle
#NDK_PATH  :=  /home/jenya1/android-ndk-r19c

# Android API level
API_LEVEL := 28

# Set default from following values: [armeabi-v7a, arm64-v8a]
ANDROID_TARGET_ARCH := armeabi-v7a

# Directory where libraries and include files are instelled
OUTPUT_DIR := /home/jenya1/Downloads/baresip-studio-master/distribution
#OUTPUT_DIR := /usr/src/baresip-studio/distribution
```

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> I just change in libbaresip-android-master makefile

OK, I'll remove the r19c line, since I'm not using it myself.

**Comment by Miteshmakwana73** [comment]
@juha-h I found the solution 

https://github.com/android-ndk/ndk/issues/973#issuecomment-487986928

**Comment by Miteshmakwana73** [comment]
now, what should I change in the project?

**Comment by Miteshmakwana73** [comment]
after updating minsdk 23 it worked

but getting a new error

[new error.txt](https://github.com/android-ndk/ndk/files/3133802/new.error.txt)

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> after updating minsdk 23 it worked

It works for me and F-Droid build system using baresip

minSdkVersion 21

and libbaresip

API_LEVEL := 21

> but getting a new error
> 
> [new error.txt](https://github.com/android-ndk/ndk/files/3133802/new.error.txt)

I have not tested with any other API level and have no plans to increase
the API level in near future.

In order to make sure that you have not mixed API levels, start from
scratch by cloning both projects.  Then generate libs and after that
build baresip in Android Studio.

**Comment by Miteshmakwana73** [comment]
`make download-sources` is not working now

```
Cloning into 'openssl'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 332109 (delta 1), reused 3 (delta 1), pack-reused 332102
Receiving objects: 100% (332109/332109), 164.67 MiB | 904.00 KiB/s, done.
Resolving deltas: 100% (226914/226914), done.
wget http://downloads.xiph.org/releases/opus/opus-1.1.3.tar.gz
--2019-05-01 11:51:59--  http://downloads.xiph.org/releases/opus/opus-1.1.3.tar.gz
Resolving downloads.xiph.org (downloads.xiph.org)... 140.211.15.28, 2001:470:eb26:54::1
Connecting to downloads.xiph.org (downloads.xiph.org)|140.211.15.28|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.xiph.org/releases/opus/opus-1.1.3.tar.gz [following]
--2019-05-01 11:51:59--  https://downloads.xiph.org/releases/opus/opus-1.1.3.tar.gz
Connecting to downloads.xiph.org (downloads.xiph.org)|140.211.15.28|:443... connected.
ERROR: cannot verify downloads.xiph.org's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to downloads.xiph.org insecurely, use `--no-check-certificate'.
Makefile:205: recipe for target 'download-sources' failed
make: *** [download-sources] Error 5
```

**Comment by juha-h** [comment]
Miteshmakwana73 writes:

> `make download-sources` is not working now

You must first try to solve your problems yourself rather than
immediately posting an issue without even looking first what might cause
it.

You have serious problem in your environment if it cannot verify
certificate issued by Let's Encrypt.

I'm closing this issue now.

**Comment by Miteshmakwana73** [comment]
I am already trying for 3 hours then after I posted this
