### ISSUE TITLE
Feature Request "speakerphone"

### ISSUE THREAD

**Issue by helpdeskdan** [juha-h/baresip-studio#270]
Unless I am missing something, baresip could use a speakerphone button.  Other than that, 34.1.0 seems to be working fine for me.

**Comment by juha-h** [comment]
There is official speaker phone icon https://fonts.google.com/icons?selected=Material+Icons:speaker_phone&icon.query=speaker+phone on top of the screen between menu button and mic on/off button.

**Comment by helpdeskdan** [comment]
I was wondering what that icon was!  Thanks.  I actually do have an issue to mention.  When I login to my voicemail on asterisk, I get prompted for "Password" immediately.  It's very quick, the slightest blip and you would miss it.  I hear it in Linphone.  In Baresip, I hear nothing till several second later saying "Login Incorrect."

**Comment by juha-h** [comment]
You need to blame Google for that:

> Juha Heinanen<juha.heinanen@gmail.com> #6Dec 28, 2021 01:19PM

> I noticed the problem in my baresip VoIP app (available in Play Store
and GitHub).  When the app is idle, audio mode is MODE_NORMAL, When user
makes a call, the app changes the mode to MODE_IN_COMMUNICATION.  If the
call is answered immediately, the user looses a few seconds of audio
from the called party and, for example, the first sentence starts from
the middle.

> am...@google.com<am...@google.com> #7Jan 5, 2022 07:08AM

> This is a known issue due to the need to conceal the audio glitches that
can happen when the active audio device changes when the audio mode is
modified but that we do not plan to reduce the duration of the mute
period for now. 
The app has to anticipate this delay and set the audio mode early enough
before the call is actually connected.

There is no way I could anticipate when user is going to press call button.  I could wait 3 sec after call button is pressed before actually making the call, but that would not be good either.

**Comment by helpdeskdan** [comment]
Thank you for your explanation!  For what it's worth (which is not much), I think most people expect a couple seconds for call setup as this is how pots operate.  With speakerphone on, I think I can hear the "d" of password.  Either way, it's great to see a completely open source soft phone for android, keep up the good work.

**Comment by juha-h** [comment]
helpdeskdan writes:

> Thank you for your explanation!  For what it's worth (which is not
> much), I think most people expect a couple seconds for call setup as
> this is how pots operate.  With speakerphone on, I think I can hear
> the "d" of password.  Either way, it's great to see a completely open
> source soft phone for android, keep up the good work.

Thanks for your comments.  In some earlier versions, mode was changed to
communication when user presses call button and then there was a wait
for 3 seconds before the call was actually placed, but some people
didn't like that either.

This problem only affects calls that are automatically answered
immediately.

**Comment by helpdeskdan** [comment]
My two cents:  Was 3 seconds before & people hated it?  Maybe try 1 second?  Nobody would complain because it takes that long to get the phone to your ear.   And, people who are expecting to hear "Password" would hear "word" and just think it was because they did not get the phone to their ear quick enough.

**Comment by juha-h** [comment]
helpdeskdan writes:

> My two cents:  Was 3 seconds before & people hated it?  Maybe try 1
> second?  Nobody would complain because it takes that long to get the
> phone to your ear.

Well, people didn't hate it, but some didn't like it.  1 sec would not
be enough.

**Comment by helpdeskdan** [comment]
1 second more than what it is now would likely be enough to solve most people's complaints

**Comment by juha-h** [comment]
OK, can you try with this: https://box.tutpro.com/tmp/baresip.apk.  When call button is touched, audio mode is set to MODE_IN_COMMUNICATION and call is initiated after 1 second delay if hangup button is not touched before that.

**Comment by helpdeskdan** [comment]
Even on speakerphone, version 34.1.0 cuts off "Password."  The version you asked me to try above, however, works perfectly!  It does, strangely enough, crash after adding my sip account.  (34.1.0 seemed to do this too)  But, if I relaunch it, it seems fine.

**Comment by juha-h** [comment]
I have not succeeded to produce the adding of account crash. Could you give some details:
- Does the crash happen only when you add the first account or also when you add other accounts?  
- What account fields did you fill when the crash happened?
-  Did the crash happen when you touched the check (v) button after filling the fields or when?

`$ adb logcat | grep -i baresip` or something similar would give some info.

**Comment by helpdeskdan** [comment]
I'm sorry, I've been really busy - I will try to delete my settings and recreate the crash when I have a bit, thanks.  Thanks again for the baresip version with 1 second, it works great.
