### ISSUE TITLE
Callers report my voice is very scratchy.

### ISSUE THREAD

**Issue by myfirstnameispaul** [juha-h/baresip-studio#272]
Since updating to 47.1.0 from 46.2.2, callers report my voice is very scratchy, but I can hear them fine.

I tried downgrading to 46.2.0, but it wouldn't install.

I made a backup with encrypted password.

I uninstalled 47.1.0.

I installed 46.2.0.

I cannot restore from the restore file. It just says the password was wrong or there was some error.

**Comment by myfirstnameispaul** [comment]
I reinstalled 47.1.0, and cannot restore the backup file.

In 46.2.0, I am not longer able to log into my provider using SRTP. The provider, voip.ms, reports that I am logged in using UDP, but the account is configured for SRTP-MAND in baresip.

**Comment by mwreimer** [comment]
Same issue on a Samsung S9 (stock firmware), that began after upgrade to baresip 47.1.0.

Same issue in F-Droid with failed downgrade. 

An uninstall of 47.1.0 and install of 47.0.0 worked, as did loading the backup file. Scratchy voice issue solved. In the F-Droid app, I have selected "Ignore All Updates" from the three dot menu at the top right of the screen, until this is resolved. Thanks for an excellent phone app!!

**Comment by juha-h** [comment]
There might have been a PRACK/early media related bug in baresip lib, when F-Droid built 47.1.0.

Is there early media in the calls where voice was scratchy? You can check by turning on Debug and SIP Trace and checking if there is 183 Session Progress reply before call is answered with 200 OK reply.

Can you try with https://box.tutpro.com/tmp/baresip.apk if the problems still persist?  Backup before install and restore after.
I just tested with it  SRTP worked OK against Linux baresip and also audio was OK too.

**Comment by mwreimer** [comment]
Hello, 
    
    Many thanks. The issue seems solved in 47.2.0 as tested on my
    Samsung S5 (LineageOS 16). 
    
    It worked in 47.0.0. Scratchy voice in 47.1.0, and now good again
    with 47.2.0. I could not see the 183 Session Progress reply in the
    log file of 47.1.0. That is attached.
    
    All my best,
    Mark
    
    On 2022-07-30 4:19 a.m., juha-h wrote:
    
    There might have been a PRACK/early media related bug
      in baresip lib, when F-Droid built 47.1.0.
    Is there early media in the calls where voice was
      scratchy? You can check by turning on Debug and SIP Trace and
      checking if there is 183 Session Progress reply before call is
      answered with 200 OK reply.
    Can you try with https://box.tutpro.com/tmp/baresip.apk
      if the problems still persist? Backup before install and restore
      after.
      I just tested with it SRTP worked OK against Linux baresip and
      also audio was OK too.
    —
    Reply to this email directly, view
      it on GitHub, or unsubscribe.

**Comment by juha-h** [comment]
mwreimer writes:

>     Many thanks. The issue seems solved in 47.2.0 as tested on my
>     Samsung S5 (LineageOS 16).

Good to know.  I'll create new versions of baresip and baresip+ apps.

**Comment by myfirstnameispaul** [comment]
Just wondering if this update was added to F-Droid?

**Comment by juha-h** [comment]
F-Droid has build baresip 47.2.0 today, but it has not been published yet.  Usually publish happens a few days after build.  baresip+ will take longer, because I fixed some video calling related bugs and created new version 34.2.0 today.

**Comment by dle-baresip** [comment]
I don't know how much value this will add, but I've chased this problem for a couple of days until downgrading to 46.2.0.  As alluded, it was probably an upstream problem. 

Anyway, my Wireshark traces show a mismatch between the samples and the timestamp, resulting in an ever-increasing negative skew.  This was true for all codecs and all endpoints.  The long-term average skew was always about -33%.  

SSRC | 0xd101417d
-- | --
Max Delta | 42.85 ms @ 416
Max Jitter | 11.02 ms
Mean Jitter | 10.26 ms
Max Skew | -2480.48 ms
RTP Packets | 249
Expected | 249
Lost | 0 (0.00 %)
Seq Errs | 0
Duration | 7.44 s
Clock Drift | -2480 ms
Freq Drift | 5333 Hz (-33.34 %)

The audio I captured actually sounded OK when Wireshark played it back according to the RTP timestamps.  Possibly shifted higher in pitch, but relatively clear.  My interpretation is that baresip was condensing the effective audio buffer and forcing the receiver to fill in for the missing samples.

**Comment by juha-h** [comment]
dle-baresip writes:

> I don't know how much value this will add, but I've chased this
> problem for a couple of days until downgrading to 46.2.0.  As alluded,
> it was probably an upstream problem. 
> 
...
> 
> The audio I captured actually sounded OK when Wireshark played it back according to the RTP timestamps.  Possibly shifted higher in pitch, but relatively clear.  My interpretation is that baresip was condensing the effective audio buffer and forcing the receiver to fill in for the missing samples.  

Thanks for the analysis. F-Droid built baresip 46.2.0 on July 7.  After
that and before 47.2.0, there has been a timestamp related fix in rem
lib:

https://github.com/baresip/rem/commit/7eb6d165ca2d8d2f63ef0b0c7e1245708608b27f

and also some other audio related fixes.  If 47.2.0 works for you, then
this could be the explanation.

Unfortunately F-Droid publishing process is slow and 47.2.0 has not
appeared there yet, but I made it available here:
http://box.tutpro.com/tmp/baresip.apk.

**Comment by juha-h** [comment]
47.2.0 is now available in F-Droid.  Is the issue still persisting?

**Comment by myfirstnameispaul** [comment]
Yes, this is fixed with 47.2.0.

**Comment by dle-baresip** [comment]
Also working for me.  Thanks!
