### ISSUE TITLE
ringtone loop

### ISSUE THREAD

**Issue by parse-flower** [juha-h/baresip-studio#273]
Hello

I'm sorry there is no discussion forum for this, only opening issues.

In Android baresip+, why is there this ringtone loop? How can I find out? Should it be considered a bug, or what am I doing wrong?

Whenever there is an incoming call, usually there is no way to accept it, but there is this ringtone loop that also can not be stopped in any way. Even when I occasionally manage to "accept" the call, the ringtone loop blares on so that no phone communication is possible.

The loop is running for a fixed time, probably 2 or 3 minutes, then stops by itself. It seems to run not as a ringtone, not as a media, but in a unique mode that shouldn't exist at all.

And why does nobody else report this?

thanks

**Comment by juha-h** [comment]
You should be able to answer the call by touching one the green phone handle buttons after which ringing should stop.  This works for me and most likely also for many other users.  Try with some other device.

**Comment by juha-h** [comment]
Closed due to inactivity.
