### ISSUE TITLE
VoIP.ms no longer reports connection as secure.

### ISSUE THREAD

**Issue by myfirstnameispaul** [juha-h/baresip-studio#275]
Previously we worked out configuration settings on an earlier version of baresip that resulted in VoIP.ms reporting a secure connection to their service.

This how I have configured baresip for supporting their service:

Media Encryption: `SRTP-MAND`
DTMF Mode:  `In-band RTP Events`
Telephony provider: `citylocation.voip.ms:5061;transport=tls`

Similar equivalent settings on other apps, including Jami on Android and desktop applications such as MIcroSIP, VoIP.ms reports as being connected securely. (Note that Jami has an outstanding and unrelated to this issue of their app not receiving TLS connected calls.)

This is using 47.2.0. in LineagOS 18.1 / Android 11.

**Comment by juha-h** [comment]
I just tested in baresip 47.2.0 SRTP-MAND against Linphone and Linphone reported the connection as secure.  What crypto algorithms voip.ms supports?  Do you have pcap of the invite and 200 ok?  Was the connection secure with some earlier version of baresip?

**Comment by myfirstnameispaul** [comment]
It last worked around version 39 or 40, when I worked out the settings in #222.

I hadn't looked at the VoIP.ms interface again until recently.

I only found [one page](https://wiki.voip.ms/article/Understanding_VoIP_Encryption_%E2%80%93_SIP-TLS_%26_SRTP) discussing encryption and they state SIP-TLS and SRTP.

I don't know how to "pcap of the invite and 200 ok".

**Comment by juha-h** [comment]
Instead of obtaining pcap, turn on Debug and SIP Trace and then check how message bodies of INVITE request and 200 OK response look like.

When media encryption is SRTP-MAND, you should see in the bodies media line such as
```
m=audio 20972 RTP/SAVP 96 97 98 9 18 0 8 101
```
i.e., protocol is RTP/SAVP, not RTP/AVP.

**Comment by myfirstnameispaul** [comment]
Where do those output to?

**Comment by myfirstnameispaul** [comment]
VoIP.ms customer support replied that they support but do not enforce TLS v1.1 or higher with SRTP and they support cipher suites AES_CM_128_HMAC_SHA1_80 and AES_CM_128_HMAC_SHA1_32.

**Comment by juha-h** [comment]
Paul writes:

> VoIP.ms customer support replied that they support but do not enforce
> TLS v1.1 or higher with SRTP and they support cipher suites
> AES_CM_128_HMAC_SHA1_80 and AES_CM_128_HMAC_SHA1_32.

That should be OK.  Below is an example of INVITE's SDP from baresip:
```
v=0
o=- 1747686248 1565595354 IN IP4 192.168.69.225
s=-
c=IN IP4 192.168.69.225
t=0 0
m=audio 7676 RTP/SAVP 96 97 98 99 9 18 0 8 101
a=rtpmap:96 AMR-WB/16000
a=rtpmap:97 AMR/8000
a=rtpmap:98 opus/48000/2
a=fmtp:98 stereo=0;sprop-stereo=0;maxaveragebitrate=28000;cbr=0;useinbandfec=1
a=rtpmap:99 G7221/16000
a=fmtp:99 bitrate=32000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp-rsize
a=ssrc:3618420529 ***@***.***
a=mid:0
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:WNXBpPbKl9h6sb0TW+bR3aSVk4Bx9e7+uVbexYtR
a=minptime:20
a=ptime:20
a=label:1
```
If possible, try to get SIP Trace from your INVITE and ask voip.ms what
is wrong with it if they reject the INVITE.

**Comment by juha-h** [comment]
See [here](https://github.com/juha-h/baresip-studio/wiki/Debugging) on how to see the INVITE request your device is sending.

**Comment by myfirstnameispaul** [comment]
I don't see anything like `v=0 ...` even through I have both debug and SIP trace enabled, and what I do see appears to have a lot of either hashed or encoded information.

Is it possible to email or somehow provide you with the full output other than this public forum?

I don't know how things are supposed to look but some things look strange to me:

```text
08-11 05:49:54.134 18941 18973 D Baresip : Acquiring WiFi Lock
08-11 05:50:00.917 18941 18941 D Baresip : New regint is 900
08-11 05:50:00.919 18941 18941 D Baresip Lib: registering UA '0'
08-11 05:50:00.919 18941 18976 D Baresip Lib: ua: ua_register sip:useraccount@correctsubdomain.voip.ms
08-11 05:50:00.919 18941 18941 D Baresip Lib: ua event (REGISTERING) 
08-11 05:50:00.919 18941 18941 D Baresip Lib: sending ua/call 1/-1756123120 event (null)
08-11 05:50:00.920 18941 18941 D Baresip : got uaEvent registering/sip:useraccount@correctsubdomain.voip.ms/0
08-11 05:50:01.382 18941 18976 D Baresip Lib: 05:50:01.007#
08-11 05:50:01.382 18941 18976 D Baresip Lib: UDP 192.168.1.37:45092 -> [correct.subdomain.IP.address]:5060
08-11 05:50:01.382 18941 18976 D Baresip Lib: REGISTER sip:correctsubdomain.voip.ms SIP/2.0
08-11 05:50:01.382 18941 18976 D Baresip Lib: Via: SIP/2.0/UDP 192.1
08-11 05:50:01.382 18941 18976 D Baresip Lib: 68.1.37:45092;branch=redactedcharacterstring;rport
08-11 05:50:01.382 18941 18976 D Baresip Lib: Contact: <sip:useraccount-recactedcharacterstring@192.168.1.37:45092>;expires=900;+sip.instan
08-11 05:50:01.382 18941 18976 D Baresip Lib: ce="<urn:uuid:redactedcharacterstring>";q=0.5
08-11 05:50:01.382 18941 18976 D Baresip Lib: Max-Forwards: 70
08-11 05:50:01.382 18941 18976 D Baresip Lib: To: <sip:useraccount@correctsubdomain.voip.ms>
08-11 05:50:01.382 18941 18976 D Baresip Lib: From: "USER AC
08-11 05:50:01.382 18941 18976 D Baresip Lib: COUNT" <sip:useraccount@correctsubdomain.voip.ms>;tag=redactedcharacterstring
08-11 05:50:01.382 18941 18976 D Baresip Lib: Call-ID: redactedcharacterstring
08-11 05:50:01.382 18941 18976 D Baresip Lib: CSeq: 2617 REGISTER
08-11 05:50:01.382 18941 18976 D Baresip Lib: User-Agent: baresip v2.
08-11 05:50:01.382 18941 18976 D Baresip Lib: 6.0 (?/?)
08-11 05:50:01.382 18941 18976 D Baresip Lib: Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,UPDATE,PRACK,REFER
08-11 05:50:01.382 18941 18976 D Baresip Lib: Content-Length: 0
08-11 05:50:01.382 18941 18976 D Baresip Lib: 
08-11 05:50:01.382 18941 18976 D Baresip Lib: 
08-11 05:50:01.462 18941 18976 D Baresip Lib: 05:50:01.007#
08-11 05:50:01.462 18941 18976 D Baresip Lib: UDP [correct.subdomain.IP.address]:5060 -> 192.168.1.37:45092
```
It seems odd that right away it is using port 5060? Is there some other configuration setting I have missed?

```text
08-11 05:22:22.970 14252 14303 D Baresip Lib: 
08-11 05:22:22.970 14252 14303 D Baresip Lib: user
08-11 05:22:22.970 14252 14303 D Baresip Lib: name@correctsubdomain.voip.ms: (prio 0) {0/UDP/v4} 200 OK (voip.ms) [1 binding]
```
This occurs regularly with the `username` broken up into two lines, but I am not really familiar with this output.

**Comment by juha-h** [comment]
In the log, lines may be split into multiple lines.  That is OK.  In the above registration has succeeded.   You got 200 OK with 1 binding.

I suggest that you use TCP or better yet TLS transport or if not supported by voip.ms. change provider.  UDP is pretty much history nowadays.

You can email me to jh@tutpro.com.

**Comment by myfirstnameispaul** [comment]
In baresip Settings I have:

Listen Address
0.0.0.0:5060
(The default)

DNS Servers
(blank)

TLS Ceritificate File is unchecked
Verify Server Certificates is unchecked
TLS CA File is unchecked

I think those are the ones that could possibly matter.

**Comment by juha-h** [comment]
Check from voip.ms docs if they tell what is the address or domain name of their SIP proxy in your area.  Then you can use it to assign your account's outbound proxy or proxies and include there ;transport param.  See Outbound Proxies help text.

**Comment by myfirstnameispaul** [comment]
This problem was resolved by setting the following in the account Outbound Proxies:

    sip:locationdomain.voip.ms:5061;transport=tls

**Comment by juha-h** [comment]
Paul writes:

> Where do those output to?

See https://github.com/juha-h/baresip-studio/wiki/Debugging.
