### ISSUE TITLE
Messed up codecs settings

### ISSUE THREAD

**Issue by maximko** [juha-h/baresip-studio#276]
I have baresip v47.2.0 from f-droid. Codec settings for account getting messed up after opening "Audio codecs" activity so it's impossible to receive or place calls because of failing codec negoitation. Not necessary to actually change any codec, just opening that activity is enough. Note that codecs are gone after app restart. I also have all the codecs enabled in "Audio Settings" activity. Please see attached screenshot:
![Screenshot_20220808-155038](https://user-images.githubusercontent.com/633363/183453447-fa61ff1d-f4de-461c-bfd8-2ff9eec4e0aa.png)
.

**Comment by juha-h** [comment]
I have not experienced that myself.  Check if you get any audio module/codec related error messages to the log when you start baresip. (see https://github.com/juha-h/baresip-studio/wiki/Debugging).

You could also try if re-installing baresip would help (Backup/Uninstall/Install/Restore).

**Comment by juha-h** [comment]
You screenshot shows only two lines, which means that baresip only has one audio module (amr) loaded.  If you have checked all modules in Audio Settings, then it most likely there has been some problem in loading them and that should show in the log when baresip starts.

**Comment by juha-h** [comment]
Closed since I have not been able to reproduce this.  Re-open if you have more information.
