### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#28]
..via crowdin.com or transifex.com or hosted.weblate.org

**Comment by juha-h** [comment]
Licaon_Kter writes:

> ..via crowdin.com or transifex.com or hosted.weblate.org

All used strings are now in res/values/strings.xml.

I checked hosted.weblate.org, but was not able to figure out, how to
generate res/values-b+<language code>/strings.xml files for different
languages.  I don't have resources for manual translation work.

**Comment by licaon-kter** [comment]
You don't generate them afaik, they'll get generated as users translate them.

I guess this might help: https://docs.weblate.org/en/latest/admin/projects.html

**Comment by juha-h** [comment]
Licaon_Kter writes:

> You don't generate them afaik, they'll get generated as users translate them.
> 
> I guess this might help: https://docs.weblate.org/en/latest/admin/projects.html

It looks like some kind of commercial service with billing plans. I'll
create strings-fi.xml as a test and then (if anyone is interested)
they can submit strings-<language code>,xml files for other languages.

**Comment by licaon-kter** [comment]
Weblate can be hosted that's something else, maybe my link wasn't on point.

> (if anyone is interested) they can submit strings-<language code>,xml files for other languages.

Here on Gihub? This is not that nice, translations sites make the translation a less painful process since they have a bunch of tools to help, eg. autotranslation (so the user just clicks if it's good), other languages (to see how others did it), comments (to communicate with you or others translating), other apps (if it's the same string or close enough to another project), suggestions etc. 

I for one, won't bother translating here any more if it's more than a dozen strings, while your .XML has >200 :(

Please reconsider...

Did you drop looking at Crowdin and Transifex?

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Please reconsider...

I could if there is a free translation service available somewhere.

> Did you drop looking at Crowdin and Transifex?

Yes, both of them asked for money.

**Comment by licaon-kter** [comment]
I don't understand, I've listed you 3 sites that, for FOSS projects, are free.

Many other Android apps like F-Droid, KISS, Conversations, Netguard, Dino, Syncthing-Android, WaveUp, FairEmail (just to name a few that I keep up to date for my locale) and more are using these services...for free.

Or maybe I've misunderstood? Baresip is not FLOSS?

**Comment by juha-h** [comment]
Licaon_Kter writes:

> I don't understand, I've listed you 3 sites that, for FOSS projects,
> are free.

I don't understand either. Page

https://crowdin.com/pricing#annual

tells that only a trial is free.

Same here

https://www.transifex.com/

there is "Try for free".

And from hosted.weblate.org pages I understood that there is somekind of
billing system.

> Or maybe I've misunderstood? Baresip is not FLOSS?

For sure it is and I don't have any organization to pay for the
translation.

**Comment by licaon-kter** [comment]
You setup "your fictitious organisation" and go on, please read the links. :)

Do I need to setup it myself? The thing is that you can link their repo with yours and you can just pull the latest translations before doing a release, so I'd rather leave you setup the organisation/account and have control, as expected.

**Comment by licaon-kter** [comment]
You respond by email hence you never see my edited posts...

**Comment by juha-h** [comment]
OK, I filled the form on page https://hosted.weblate.org/hosting.  In Filemask I entered
`app/src/main/res/values*/strings.xml`
Hope that was correct.

**Comment by licaon-kter** [comment]
We wait for your link, once it's done: https://hosted.weblate.org/projects/

**Comment by juha-h** [comment]
All strings for translations should now be in place and I added Finnish language strings as a test.
It was quite a big project, since there is currently 169 strings.

I'll close this now.  Let's wait what happens with weblate.

**Comment by licaon-kter** [comment]
No news?

**Comment by juha-h** [comment]
Licaon_Kter writes:

> No news?

I haven't got any email from weblate.

**Comment by licaon-kter** [comment]
Can you retry please? Thanks

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Can you retry please? Thanks

I filled the form again and got back automatic reply telling the request
was received.

**Comment by juha-h** [comment]
Baresip is now in weblate:
```
https://hosted.weblate.org/projects/baresip/baresip-app/
```
but I have not done anything about it yet.

Perhaps I'll try to add Weblate Service to the project to notify weblate about changes.

**Comment by licaon-kter** [comment]
Updated a locale, maybe you can test the Weblate workflow ;)

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Updated a locale, maybe you can test the Weblate workflow ;)

I did this:

To notify Weblate about changes in your repository please add Weblate Service
to your project:

https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

I didn't activate Weblate to push changes directly to the repo.

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Updated a locale, maybe you can test the Weblate workflow ;)

I haven't been able to figure out, how to configure weblate/github so
that weblate makes pull requests whenever something changes in
translations.

**Comment by juha-h** [comment]
Looks like weblate is now able to push commits to the project.

**Comment by licaon-kter** [comment]
And some leftovers :) https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild_9&oldid=274534

**Comment by juha-h** [comment]
Licaon_Kter writes:

> And some leftovers :) https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild_9&oldid=274534

Thanks for reporting.  I removed the unused strings and recreated tag
v3.0.2.

**Comment by licaon-kter** [comment]
The non plus version has the same issue (as expected :))

**Comment by juha-h** [comment]
Licaon_Kter writes:

> The non plus version has the same issue (as expected :))

OK, but I still don't know what the issue actually is.

**Comment by licaon-kter** [comment]
This is about the "extratranslations"...for the other issue we have another....issue :)

**Comment by licaon-kter** [comment]
And again for build 10? https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild_10&oldid=274871

**Comment by juha-h** [comment]
Licaon_Kter writes:

> And again for build 10?
> https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild_10&oldid=274871

Thanks for reporting.  I deleted the unused strings and recreated tag
v3.1.0.

I haven't yet figured out how to get access to the build info.

**Comment by licaon-kter** [comment]
Access in what way? There's the link above...

Bookmark

https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild and press History if needed

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Access in what way? There's the link above...
> 
> Bookmark
> 
> https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild and press History if needed

OK, I tried

https://f-droid.org/wiki/page/com.tutpro.baresip.plus/

and expected to see build and other app related links, but there was
none.

**Comment by licaon-kter** [comment]
The wiki is obsolete since 2018. Except these section where cycle build info in posted.
