### ISSUE TITLE
About compilation errors

### ISSUE THREAD

**Issue by nojustbb** [juha-h/baresip-studio#285]
Hello, the author, I want to ask why I compiled under Linux and generated the package file here. It was processed according to your readme file. Why does it still not work? I compared it with TIFF /, VO amrwbenc /, zrtpcpp / library. Is that why

![1662716474410](https://user-images.githubusercontent.com/27254745/189321341-87e8d23e-70e7-4972-ba09-48b675794146.jpg)

**Comment by juha-h** [comment]
nojustbb writes:

> Hello, the author, I want to ask why I compiled under Linux and
> generated the package file here. It was processed according to your
> readme file. Why does it still not work? I compared it with TIFF /, VO
> amrwbenc /, zrtpcpp / library. Is that why

Based on the information you gave, I cannot tell what went wrong.

**Comment by nojustbb** [comment]
> nojustbb 写道：
> 楼主你好，想问一下为什么我在Linux下编译，这里生成了包文件。它是根据您的自述文件处理的。为什么它仍然不起作用？我将它与 TIFF /、VO amrwbenc /、zrtpcpp / 库进行了比较。这就是为什么
> 根据您提供的信息，我无法判断出了什么问题。

![1663034861532](https://user-images.githubusercontent.com/27254745/189791540-5b357949-869e-470c-8860-79652ee494fe.jpg)
Hello, can you help me see if there is a problem with the configuration of my file? I followed all your steps, but it still can't run. Is it the wrong configuration or something missing

**Comment by juha-h** [comment]
After you edited your issue, I see error message about missling libilbc.  ILBC codec is not anymore included in libbaresip.a and ilbc module does not exist in baresip.

**Comment by nojustbb** [comment]
> 

Do I need to delete or add the file? I tried to rebuild the code, but I still reported an error like failure

**Comment by juha-h** [comment]
nojustbb writes:

> Do I need to delete or add the file? I tried to rebuild the code, but
> I still reported an error like failure.

There is no ilbc in libbaresip-android or baresip-studio projects.

**Comment by nojustbb** [comment]
> nojustbb writes:
> Do I need to delete or add the file? I tried to rebuild the code, but I still reported an error like failure.
> There is no ilbc in libbaresip-android or baresip-studio projects.

Then I'm going to download the iLBC library outside, right

**Comment by juha-h** [comment]
nojustbb writes:

> > There is no ilbc in libbaresip-android or baresip-studio projects.
> 
> Then I'm going to download the iLBC library outside, right

It is up to you.  This is not an issue that belongs to baresip-studio.

**Comment by nojustbb** [comment]
> 

Thank you. I have solved the problem caused by my wrong version of the master branch. It can be run

**Comment by nojustbb** [comment]
> nojustbb writes:
> > There is no ilbc in libbaresip-android or baresip-studio projects. Then I'm going to download the iLBC library outside, right
> It is up to you. This is not an issue that belongs to baresip-studio.

Thank you. I have solved the problem caused by my wrong version of the master branch. It can be run
