### ISSUE TITLE
(Audio) Problem with the g722 codec - clipping and crackling

### ISSUE THREAD

**Issue by jaimet** [juha-h/baresip-studio#289]
Hi.

I'm testing v48.2.0 and I have a problem when I use the g722 codec.

To reproduce, I set g722 as the only permissible audio module and then I call sip:thetestcall@opensips.org. After the intro message ("This is 722"), I press "#" to get to the main menu, then "4" for "music on hold". The sound is bad quality - I think it is clipping.

The control test is: I set g711 as the only permissible audio module and again I call sip:thetestcall@opensips.org. After the intro message ("This is u-law"), I press "#" to get to the main menu, then "4" for "music on hold". The sound is good quality with no clipping.

(g722 and g711 are the only two codecs accepted by sip:thetestcall@opensips.org but hopefully this is sufficient).

TIA, Jaime

**Comment by juha-h** [comment]
I tested with latest baresip on Debian Linux and noticed the same issue.  So looks like this is issue with baresip project that produces the lib that baresip-studio is using.

Do you have access to baresip on Linux?  If so, could you check and, if necessary, open the issue in baresip project?

**Comment by jaimet** [comment]
> Do you have access to baresip on Linux? If so, could you check and, if necessary, open the issue in baresip project?

Yes, I have several debian bullseye desktops so as long as [1.0.0-4](https://packages.debian.org/bullseye/baresip) is good, then I can install and test this today. :thumbsup:

**Comment by juha-h** [comment]
Jaime writes:

> Yes, I have several debian bullseye desktops so as long as
> [1.0.0-4](https://packages.debian.org/bullseye/baresip) is good, then
> I can install and test this today. :thumbsup:

I have latest bullseye packages available in directory
https://box.tutpro.com/tmp/:

baresip_2.7.0_amd64.deb
librem_2.7.0_amd64.deb
libre_2.7.0_amd64.deb

**Comment by jaimet** [comment]
> I have latest bullseye packages available in directory https://box.tutpro.com/tmp/:
> baresip_2.7.0_amd64.deb
> librem_2.7.0_amd64.deb
> libre_2.7.0_amd64.deb

Brilliant - I'll test them now...

**Comment by jaimet** [comment]
> I have latest bullseye packages available in directory https://box.tutpro.com/tmp/:

That url is just returning an empty page at the moment.

**Comment by juha-h** [comment]
Yes, just add the names of the .deb files after tmp/, e.g.,
```
wget https://box.tutpro.com/tmp/baresip_2.7.0_amd64.deb
```
I did more tests and the cracks exists also between cli baresip and Android baresip.

**Comment by jaimet** [comment]
> `wget https://box.tutpro.com/tmp/baresip_2.7.0_amd64.deb`

Downloaded and installed. :+1: 

> I did more tests and the cracks exists also between cli baresip and Android baresip.

Ok, give me a moment to configure, run and reproduce the issue...

**Comment by juha-h** [comment]
Thanks for noticing and creating the PR.

**Comment by juha-h** [comment]
Should now be fixed in baresip version 49.1.1 and baresip+ version 37.1.1.  Reopen if still an issue.
