### ISSUE TITLE
Voice sounds underwater/robotic with Voip.ms, but only with TLS, not UDP

### ISSUE THREAD

**Issue by xenotropic** [juha-h/baresip-studio#293]
When I connect to VoIP.ms with this app (from the Play store, 49.1.3) via UDP, everything sounds and works fine. The device is a SM-G900V, Android 11. 

When I connect to the same Voip.ms account using this app with TLS, by using the instructions and settings in issue #275 , then incoming audio still sounds fine, but my outgoing audio sounds very poor quality, a sort of robotic, underwater effect, with some cracks and pops. 

Voip.ms allows one to select codecs, so I did test calls with each of G.711U, G.729a, G.722, and gsm as the only allowed codec, and in call cases the effect is the same. 

If I use Zoiper android, with the same device, same voip.ms account, with TLS, it also sounds fine. I'd rather use your app if I can get it working for secure calls, though, since it is more straightforward and lightweight.

Does this sound like any known issue? Any ideas on what to try, or other information I can provide?

**Comment by juha-h** [comment]
Joseph Morris writes:

> When I connect to VoIP.ms with this app (from the Play store, 49.1.3)
> via UDP, everything sounds and works fine. The device is a SM-G900V,
> Android 11.
> 
> When I connect to the same Voip.ms account using this app with TLS, by
> using the instructions and settings in issue #275 , then incoming
> audio still sounds fine, but my outgoing audio sounds very poor
> quality, a sort of robotic, underwater effect, with some cracks and
> pops.

What protocol is used to transfer SIP requests/replies should have
nothing to do with media transfer, which is using its own ports and
protocols.

Can you get debug log of both cases?  Here is some instructions
https://github.com/juha-h/baresip-studio/wiki/Debugging.

**Comment by juha-h** [comment]
I have sip.antisip.com test account and call to thetestcall@sip.antisip.com worked fine using TLS (Outbound Proxies sip:sip.antisip.com:5061;transport=tls).

**Comment by xenotropic** [comment]
Ok, so I did some more testing and it seems like this is occurs over **both** tls and udp, contrary to my earlier report. So it is not a TLS issue. It seems to be because baresip and voip.ms will only negotiate the GSM codec, and, having listened to the GSM sample recording on wikipedia, I realize the issue is a lot of the problem is the GSM codec just sounds that bad (although . . . what I'm experiencing is even worse, the "underwater" quality).

It seems like the question then becomes: why will baresip and voip.ms only use GSM?

In addition to GSM, Voip.ms offers G.711, G.729a, G.722 ("beta"), all three of which appear in baresip's codec listing in settings (and all of which I have enabled). So it seems like they should be able to negotiate one of them . . . right?

But my baresip calls with voip.ms only get GSM. When I use voip.ms's setting to disable GSM as an available codec for my account, so that only G.711, G.729a, and G.722 are available, then when I try to make a call with baresip I get a "488 Not acceptable here", which I am guessing is that no matching codec is found.  

I'm going to email you logs right now for both (1) a call that connects as GSM and sounds robotic/underwater, and (2) one where I get the 488 when I have gsm disabled on the voip.ms side (and G.711, G.729a, G.722 still enabled), and all codecs enabled in baresip, to see if you can see anything that is wrong or that I might try.

**Comment by juha-h** [comment]
I'm on the road today and can't check your logs until
tomorrow.

Regarding codecs, disable gsm from from the active list by swiping it to
left (if is active and has strong color).  Then move G722 to the top of
the active list above PCMU and PCMA.

That should result in INVITE request that has three codecs G722, PCMU,
and PCMA in that order. If the answered obeys SDP standards and supports
G722, G722 should be used in the call.

You can check which codec is in use by touching the Info icon.

**Comment by juha-h** [comment]
Closed (issue had nothing to do with SIP transports).
