### ISSUE TITLE
Notifications in Android 13 not working

### ISSUE THREAD

**Issue by mr-schmolly** [juha-h/baresip-studio#297]
On Androis 13 I can't see any status in the status bar and I don't get notifications for incoming calls. The notification button under Settings -> Apps -> baresip -> Notifications is switched off and cannot be activated.

**Comment by juha-h** [comment]
Looks like Androif 13 requires that the app explicitly asks notification permission from the user.  I'll try to add the new feature, but don't have any Android 13 devices to test it.

**Comment by mr-schmolly** [comment]
If you give me an APK file I can test it for you on an Android 13 device with the latest security updates.

**Comment by juha-h** [comment]
Try with https://box.tutpro.com/tmp/baresip.apk It is good idea to first backup/remove your current baresip app and then install/restore the new one.

**Comment by mr-schmolly** [comment]
Thank you for your help. The new APK file fixed the error.

**Comment by juha-h** [comment]
Thanks for testing.  I'll create a new version.

**Comment by JonnyTech** [comment]
@juha-h your test build also fixed the notification issue on my android 13 / lineageos 20 device too. Can you please tag a new release so that fdroid can build it? Cheers.

**Comment by juha-h** [comment]
JonnyTech writes:

> @juha-h your test build also fixed the notification issue on my
> android 13 / lineageos 20 device too. Can you please tag a new release
> so that fdroid can build it? Cheers.

Jonny, there is still work to do for API 31+ devices.  For example,
isSpeakerphoneOn is now deprecated.  I have made the changes, but need
to properly test them.

I hope to get a new version released tomorrow.
