### ISSUE TITLE
How to turn on echo cancellation?

### ISSUE THREAD

**Issue by goderfly** [juha-h/baresip-studio#3]
I use the biresip on the tablet, the call comes from the dial pad of the intercom, from the side of the tablet I can not hear the echo, but the person who dial from the panel hears himself. How to suppress an echo using opensles or any other module? How to turn on echo cancellation in baresip?

**Comment by juha-h** [comment]
Added reference to https://github.com/juha-h/baresip-studio/issues/26.

**Comment by juha-h** [comment]
Echo cancellation has now been implemented for PCMU, PCMA, and G.722.1 codecs. Opus is not (currently) supported, due to its high frequency and 2 channels.

**Comment by assegaf** [comment]
> 

hi juha, its it automatic enabled or need some config when using that codec,

**Comment by juha-h** [comment]
Currently echo cancellation is enabled for all codecs.  Opus now uses only one channel at sample rate 16000.

**Comment by assegaf** [comment]
I am kinda using the libbaresip to convert whatsapp voice call to sip, kinda point us where to turn that off, we want pure no modification audio to make sure the quality not compromised ..

**Comment by juha-h** [comment]
You  can disable echo cancellation by not loading webrtc_aecm.so module.  Check also other audio related lines in config file.

**Comment by assegaf** [comment]
I thought we talking about spandsp thing, it is pure src/play ? no modification ?

we are not enabling webrtc_aecm  module on compile ...

**Comment by assegaf** [comment]
there module
libbaresip-android/baresip/modules/echo
echo.c  module.mk

is this ?

**Comment by assegaf** [comment]
> You can disable echo cancellation by not loading webrtc_aecm.so module. Check also other audio related lines in config file.

but I will try that module too, maybe quality getting better ...

**Comment by juha-h** [comment]
Din writes:

> there module
> libbaresip-android/baresip/modules/echo
> echo.c  module.mk
> 
> is this ?

No, echo is echo module.  You should ask this kind of questions on
baresip list.

**Comment by assegaf** [comment]
> Echo cancellation has now been implemented for PCMU, PCMA, and G.722.1 codecs. Opus is not (currently) supported, due to its high frequency and 2 channels.

my mistakes, I thought of it enabled by default, it seem its just an echo application (for baresip pc), not pre processing audio.
