### ISSUE TITLE
7.4.0 Failed to allocate new account

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#30]
AOSP 9, F-Droid

Try to add an account for:
`user@sip.mydomain.tld`

It used to work...

Not sure what I should write in that box, if only user, the popup says user@domain.

Logcat: `W Baresip : Failed to allocate UA for user@sip.mydomain.tld`

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Try to add an account for:
> `user@sip.mydomain.tld`
> 
> It used to work...

Indeed.  I'll take a look.

**Comment by juha-h** [comment]
Thanks for reporting. Should be fixed now in tag 8.0.2.
