### ISSUE TITLE
Account Nicknames do Not Stick

### ISSUE THREAD

**Issue by stef204** [juha-h/baresip-studio#300]
baresip+ 38.0.0 F-Droid
Android 12

Once I set nicknames for accounts, they will show up for that session but once I exit the app, they are gone and just do not stick. This is not important -- just wanted to mention it. (Possibly a permission problem?)

PS  This does not seem to occur with baresip 50.1.1 F-Droid

**Comment by juha-h** [comment]
I just tried with 38.1.1 from Play Store as well as 50.1.4 and 38.1.1 from F-Droid (to be published in a few days) and didn't notice this issue.  Re-open if the problem persists with those versions.
