### ISSUE TITLE
Unable to Receive Calls

### ISSUE THREAD

**Issue by stef204** [juha-h/baresip-studio#301]
basresip+ 38 F-Droid
basresip 50.1.1 F-Droid
Android 12

When using the app, I can make outgoing calls but cannot receive ANY calls. I've tried this on 2 numbers.
In Settings, I see:  Listen Address: `0.0.0.0:5060`
Do I need to change this IP address? I am inside a LAN behind a router.

**Comment by juha-h** [comment]
Listen address 0.0.0.0:5060 is fine.  Turn on Debug/SIP Trace and check if baresip gets INVITE request.   If you are behind NAT, your SIP proxy/registrar needs to send the INVITE request over the TCP/TLS connection that baresip opened when it registered.

**Comment by stef204** [comment]
I use UDP as calls with TLS, even though they should work in theory, just have very bad quality in general (not tied to baresip but probably to SIP provider?)
So, noticing that UDP gives better call quality, I use UDP.
Could that be the issue?
(Note: I AM able to receive calls when using another SIP client)

**Comment by juha-h** [comment]
The transport protocol used for sending/receiving SIP requests/responses has nothing to do with call quality.  With ;transport=tcp you may have better chance to get messages through is you are behing NAT.

See https://github.com/juha-h/baresip-studio/wiki/Debugging about debugging.

**Comment by stef204** [comment]
> With ;transport=tcp you may have better chance to get messages through is you are behing NAT.
I've switched to `tcp` to see if it might help.
Let's keep this open for now. Will post debug log if I see anything.

**Comment by stef204** [comment]
When I change protocol to `tcp`, I cannot make outgoing calls, basically, nothing happens.  So my choices are `udp` or `tls`. On `tls` my SIP provider uses port 5061, not 5060. But `tls` creates problem with calls so I have to use `udp` as the "default and only choice." This is likely related to my SIP provider and not baresip.

Here is a [link](https://paste.xinu.at/UJAo/) to the log file (anonymized).

Of interest is calls made from +15555552222@sip.myprovider.com to +15555555555 from account sip:myaccount2@sip.myprovider.com

What I am seeing is:
`Baresip Lib: ua: sip:+15555552222@sip.myprovider.com: UA not found: +155555
Baresip Lib: 55555`

Lines 156-157, etc.

Are you able to take a look at the log file and let me know what I can do to troubleshoot further and identify the problem?

On the positive side, *outgoing* calls are great, very clear and stable connection.  If I could just replicate that on incoming, I could switch to `baresip` as my main SIP  client.

**Comment by juha-h** [comment]
In incoming call Request-URI of INVITE request must match SIP URI of an existing account.  It was not clear to me from your anonymized log file if that was the case. You can turn on trace and see the INVITE request.

For example, I have account sip:bar@test.tutpro.com, which registers like this:
```
02-04 08:37:02.919 19886 19929 D Baresip Lib: ua: ua_register sip:bar@test.tutpro.com
02-04 08:37:02.919 19886 19886 D Baresip Lib: ua event (REGISTERING) 
02-04 08:37:02.919 19886 19886 D Baresip Lib: sending ua/call -5476376650053675056/0 event registering
02-04 08:37:02.920 19886 19886 D Baresip : got uaEvent registering/sip:bar@test.tutpro.com/0
02-04 08:37:03.118 19886 19928 D Baresip Lib: ua event (REGISTER_OK) 200 OK
02-04 08:37:03.118 19886 19929 D Baresip Lib: bar@test.tutpro.com: (prio 0) {1/TCP/v4} 200 OK (OpenSIPg SIP Proxy (5.6.2-3 (x86_64/linux))) [1 binding]
```
Then when I call that account from sip:test@test.tutpro.com and answer, I get to log:
```
02-04 08:37:30.051 19886 19928 D Baresip Lib: sending ua/call -5476376650053675056/-5476376650053884912 event call incoming,sip:test@test.tutpro.com
02-04 08:37:30.052 19886 19928 D Baresip : got uaEvent call incoming,sip:test@test.tutpro.com/sip:bar@test.tutpro.com/-5476376650053884912
02-04 08:37:30.126 19886 19928 D Baresip : Permission android.permission.RECORD_AUDIO is granted
02-04 08:37:30.126 19886 19928 D Baresip : Incoming call -5476376650053675056/-5476376650053884912/sip:test@test.tutpro.com
02-04 08:37:30.129 19886 19928 D Baresip : CurrentInterruptionFilter 1
02-04 08:37:30.161  1473  1933 I MediaFocusControl: requestAudioFocus() from uid/pid 10253/19886 AA=USAGE_VOICE_COMMUNICATION/CONTENT_TYPE_MUSIC clientId=android.media.AudioManager@5dc1ef6com.tutpro.baresip.BaresipService$$ExternalSyntheticLambda3@86c52f7 callingPack=com.tutpro.baresip req=2 flags=0x0 sdk=33
02-04 08:37:30.236 19886 19928 D Baresip : Audio focus granted
02-04 08:37:30.238 19886 19928 D Baresip : Starting Bluetooth SCO
02-04 08:37:30.270 19886 19886 D Baresip : Bluetooth headset SCO is connecting
02-04 08:37:30.786 19886 19928 D Baresip : Posted service event call incoming,sip:test@test.tutpro.com at 178777105484886
02-04 08:37:30.788 19886 19886 D Baresip : Observed event 178777105484886
02-04 08:37:30.793 19886 19886 D Baresip : Handling service event 'call incoming' for -5476376650053675056
02-04 08:37:33.270 19886 19886 D Baresip : Bluetooth headset SCO is disconnected
02-04 08:37:34.323 19886 19886 D Baresip : AoR sip:bar@test.tutpro.com answering call from test
02-04 08:37:34.331 19886 19886 D Baresip : Received onStartCommand action Call Answer
02-04 08:37:34.334  1473  1931 I MediaFocusControl: abandonAudioFocus() from uid/pid 10253/19886 clientId=android.media.AudioManager@5dc1ef6com.tutpro.baresip.BaresipService$$ExternalSyntheticLambda3@86c52f7
02-04 08:37:34.335 19886 19886 D Baresip : Audio focus abandoned
02-04 08:37:34.398  1473  4310 I MediaFocusControl: requestAudioFocus() from uid/pid 10253/19886 AA=USAGE_VOICE_COMMUNICATION/CONTENT_TYPE_SPEECH clientId=android.media.AudioManager@5dc1ef6com.tutpro.baresip.BaresipService$$ExternalSyntheticLambda3@3ea63f5 callingPack=com.tutpro.baresip req=2 flags=0x0 sdk=33
02-04 08:37:34.420 19886 19886 D Baresip : Audio focus granted
02-04 08:37:34.420 19886 19886 D Baresip : Starting Bluetooth SCO
02-04 08:37:34.791 19886 19886 D Baresip : Orig/new 3 volume is 5/11
02-04 08:37:34.794 19886 19886 D Baresip : Orig/new 0 volume is 6/6
02-04 08:37:34.794 19886 19886 D Baresip : Acquiring proximity wake lock
02-04 08:37:34.803 19886 19886 D Baresip Lib: answering ua/call -5476376650053675056/-5476376650053884912 with video mode 0
02-04 08:37:34.803 19886 19886 D Baresip Lib: ua event (CALL_REMOTE_SDP) offer
02-04 08:37:34.803 19886 19886 D Baresip Lib: sending ua/call -5476376650053675056/-5476376650053884912 event call update,3
02-04 08:37:34.803 19886 19886 D Baresip : got uaEvent call update,3/sip:bar@test.tutpro.com/-5476376650053884912
02-04 08:37:34.803 19886 19929 D Baresip Lib: call: answering call on line 1 from sip:test@test.tutpro.com with 200
```
Compare to yours. Most likely I'm offline the next few days and may not be able to respond to any messages.

**Comment by stef204** [comment]
I though I had trace turned on, already but I guess it doesn't survive reboot.
I'll turn it on and get another log,
Will try to do calls toand from some test accounts perhaps so I don't have to anonymize.  If there are any that you know I can use, please let me know.
(I cannot call `thetestcall@opensips.org`, doesn't seem to work.)
Understood you'll be away for the next few days.  Let's keep this open and see if we can isolate the problem.
Will post again once I have the new log.

**Comment by stef204** [comment]
@juha-h 
[This](https://paste.xinu.at/jKEU/) is the new log (an excerpt when call comes in and fails.)
Are you able to see what the issue is?
(It's less anonymized than the previous one.  If you want raw log, let me have you direct email address and I'll send it that way perhaps.)

**Comment by juha-h** [comment]
The log  should shown both register and invite requests.  Request-URI in invite request is the same as  To-URI:
```
t: <sip:+13107700011@10.1x.2xx.8>
```
then your baresip account would need to be sip:+13107700011@10.1x.2xx.8, not sip:+13107700011@sip.myprovider.com.

If still needed, email me the trace that includes register and invite requests to jh@tutpro.com.

**Comment by juha-h** [comment]
juha-h writes:

> The log  should shown both register and invite requests.  Request-URI
> in invite request is the same as  To-URI:

Should read "If Request-URI ..."

**Comment by stef204** [comment]
Thanks for your feedback.  So you are saying that I should stop using the FQDN of the SIP provider in the account configuration but replace with the IP of the SIP provider? I have a primary and secondary IP for the SIP provider.

But the problem is that the `@10.1x.2xx.8` above is an address assigned by IANA and not the primary or secondary IP of the SIP Provider. This is the whois on that address:

```
NetRange:       10.0.0.0 - 10.255.255.255
CIDR:           10.0.0.0/8
NetName:        PRIVATE-ADDRESS-ABLK-RFC1918-IANA-RESERVED
NetHandle:      NET-10-0-0-0-1
Parent:          ()
NetType:        IANA Special Use
OriginAS:       
Organization:   Internet Assigned Numbers Authority (IANA)
RegDate:        
Updated:        2013-08-30
Comment:        These addresses are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
Comment:        
Comment:        These addresses can be used by anyone without any need to coordinate with IANA or an Internet registry.  The traffic from these addresses does not come from ICANN or IANA.  We are not the source of activity you may see on logs or in e-mail records.  Please refer to http://www.iana.org/abuse/answers.
```
So I cannot implement your recommendation, it would not work. 

If I use ` sip:+13107700011@10.1x.2xx.8` it does not work (for obvious reasons--see above.)

I think there is some type of implementation problem perhaps? 

Using another couple of SIP clients, I can receive calls.  (Although they are not as good as `baresip` on outgoing call quality and stability/reliability, which is why I would like to resolve this incoming call issue and switch to `baresip` permanently.

Let me get and email you the trace.

**Comment by juha-h** [comment]
I didn't suggest using ip address as account's domain.  Send me the log that also contains trace of register and invite requests.  I already gave my email.  It is jh@tutpro.com.

**Comment by stef204** [comment]
OK, check your email please.
Ready to do any further troubleshooting steps needed to help debug this.

**Comment by juha-h** [comment]
Turned out that SIP Proxy of the provider does not use Contact URI of REGISTER request as Request-URI in the INVITE request and thus baresip cannot know for which account the request is for.  I'll thus close this issue.

**Comment by stef204** [comment]
Update: This was resolved by changing the DNIS setting in the SIP Provider portal which can change the Inbound connection format.
It was set to "E.164" (which I guess was creating the problems we discussed.)
Changing this to "SIP Username" fixes it and calls now come through.

**Comment by ONiKiDSK** [comment]
> Update: This was resolved by changing the DNIS setting in the SIP Provider portal which can change the Inbound connection format. It was set to "E.164" (which I guess was creating the problems we discussed.) Changing this to "SIP Username" fixes it and calls now come through.

Where exactly is it set? I also encountered a similar situation, thank you.
