### ISSUE TITLE
 Phone only vibrates once when a phone call comes in

### ISSUE THREAD

**Issue by Peter4487** [juha-h/baresip-studio#304]
Hi @juha-h !

This is very similar behavior to a bug I reported to the linphone project: https://github.com/BelledonneCommunications/linphone-android/issues/1794

Perhaps it's the same issue?

    When receiving a phone call, I get a quick "buzz-buzz" and then nothing.
        What I expect is for the phone to continue vibrating until the phone stops ringing or I decline / accept the call.
    The device setting is to vibrate with call ringing, no ascending ringing sound

Pixel 5 running newest Android

Let me know what I can do.

**Comment by juha-h** [comment]
Can you find the patch that was done to Linphone to fix the issue?

**Comment by Peter4487** [comment]
https://gitlab.linphone.org/BC/public/linphone-sdk/-/merge_requests/3236

**Comment by juha-h** [comment]
Perhaps I need to use VIBRATOR_SERVICE and explicitly call vibrate().  I thought that it is done automatically when ringerMode is NORMAL.  I'll take a look when I have time.

**Comment by juha-h** [comment]
Could you try with this https://box.tutpro.com/tmp/baresip.apk?

**Comment by juha-h** [comment]
Should be fixed now in the latest releases 51.0.0 and 39.0.0.  The the single vibrate sound was from the notification. Now  it should vibrate according to Sound and vibration settings, but access to Vibrate while ringing setting is not official and may disappear any time.

Reopen if the issue still persists.
