### ISSUE TITLE
Codec list unreadable with dark theme

### ISSUE THREAD

**Issue by ivorget** [juha-h/baresip-studio#305]
App version: 50.1.5 from Play store

The app automatically adopted my system dark theme OK except that the per-account codec list uses black font against black background (apart from the hold-to-move thingie) so the codecs are unreadable unless you turn brightness way up.
![Screenshot_20230211-203048_baresip](https://user-images.githubusercontent.com/13788702/218277578-0cdffb8f-e1d2-4312-a6c2-cd10e8ce09b6.png)

**Comment by juha-h** [comment]
ivorget writes:

> The app automatically adopted my system dark theme OK except that the per-account codec list uses black font against black background (apart from the hold-to-move thingie) so the codecs are unreadable unless you turn brightness way up.
> ![Screenshot_20230211-203048_baresip](https://user-images.githubusercontent.com/13788702/218277578-0cdffb8f-e1d2-4312-a6c2-cd10e8ce09b6.png)

On my Android 11 and 12 devices (Nokia and Samsung) there is black font
over grey background.  It is baresip app's dark theme.  Use that.

**Comment by ivorget** [comment]
OK the issue seems to be down to the "pure black" I have selected under dark mode setting in Android 11 (lineages 18.1). Using baresip's dark mode setting doesn't help as it still follows the system pure black scheme.

**Comment by juha-h** [comment]
I'll do some tests when I have time.

**Comment by juha-h** [comment]
On my Samsung Android 12 device, I can select in Display settings Dark mode.  Then in Dark mode settings, the only setting is "Turn on as scheduled".  On my Nokia Android 11 device (should be pure Android), I can only turn Dark mode on or off and there is no dark mode settings.   So I have no way to select "pure black" and thus cannot repeat or fix this issue.  

If you are willing to try, I could create a baresip apk that explicitly defines codec list background colors for light and dark modes.

**Comment by ivorget** [comment]
OK I looked a bit and it looks like it's just a LineageOs (Android derivative) specific feature, though there are apparently also other solutions that people use like Repainter.
Yeah I'd be happy to test that apk, probably no sooner than this evening just fyi.

**Comment by juha-h** [comment]
Try with this https://box.tutpro.com/tmp/baresip.apk.  It uses dark green color for codec names when in dark mode.

**Comment by ivorget** [comment]
Thanks for the fix, that looks fine to me.

**Comment by juha-h** [comment]
ivorget writes:

> Thanks for the fix, that looks fine to me.

OK, I'll include the change in the version.

**Comment by juha-h** [comment]
Completed by https://github.com/juha-h/baresip-studio/commit/392d7b725b09c4f872af1ba821f4bc201b67832f.
