### ISSUE TITLE
Remote disconnect of baresip-initiated call rejected

### ISSUE THREAD

**Issue by ivorget** [juha-h/baresip-studio#306]
Version: 50.1.5 from Play store

This may be more a baresip library issue and/or could be specific to this connection.

When I use the # key to end my Localphone voicemail connection the remote end sends BYE but baresip responds '481 Call does not exist'. The app however shows the call continuing.
When I then hangup from the app of course the remote side then responds with '481 Call leg/transaction does not exist' so baresip tries to send one more BYE.

I was able to reproduce the issue so not a one off.

I can add sngrep pcap dump later if needed.

**Comment by juha-h** [comment]
Read section 12 of rfc3261 https://www.rfc-editor.org/rfc/rfc3261.html#page-69, turn on SIP Trace setting and check if the dialog id of incoming BYE request matches that of the dialog.

**Comment by ivorget** [comment]
The Call ID and tags match up OK in the old log. But I can't reproduce it any more so it must have been in a funny state at the time after all. So I guess I'll close it.
