### ISSUE TITLE
Speaker mode automatically activated after a few seconds

### ISSUE THREAD

**Issue by yennor** [juha-h/baresip-studio#307]
When I do an outgoing call (didn't check with incoming) then the speaker is automatically activated after a few seconds. This also happens during ringing, if the other party doesn-t respond for long enough.
Once the speaker mode automatically activated, I need to click twice, on the speaker in the app to deavtivate it.
- After one click, the app shows that speaker mode is activated (which was already before)
-  after the second click the app shows the speaker mode deactivated again, and now it is really deactivated, and stays like that.

baresip version 50.1.5 on android 13.
This behaviour wasn't there before (can't say with which version that started since I've been in holidays and didn't make any calls for a while).

**Comment by juha-h** [comment]
Commit https://github.com/juha-h/baresip-studio/commit/64d82de58bc4a27e38ab0b44eb6dff756eccbe2a changed how speakerphone is turned on/off when API level is >= 31,, because isSpeakerPhoneOn function has been deprecated.  Perhaps that has something to do with this issue.

On the other hand, looks like Android is automatically making the switch from earpiece to speakerphone when it thinks that it is needed.  I see in the log this:
```
02-14 18:05:42.615   900  5701 V APM_AudioPolicyManager: setOutputDevices changing device to {type:0x2,@:}
```
even when that  change was instructed by baresip user.

I don't know yet if reverting the commit would help.

**Comment by yennor** [comment]
> I don't know yet if reverting the commit would help.

neither do I ;-).

The most annoying part is, when you start the phone call over a bluetooth headset. After a few seconds you can-t hear anything anymore. neither on the headset, nor on the phone internal nor external speaker. Then when clicking a few times on the speaker mode icon in the app, you manage to hear it again on the internal or external speaker of the phone. But it doesn't seem to be possible to get it back to the headset.
(Actually this problem already existed before. Once you've changed to external speaker mode (mostly by accident), it wasn't possible to convince the app, to use the bluetooth headset again. Always a reconnection of the call was necessary).

**Comment by yennor** [comment]
I didn't take a look on your code. but maybe that here helps? Checkout the answer:

https://stackoverflow.com/a/71062507

**Comment by juha-h** [comment]
I had read that answer and that prompted me to use setCommunicationDevice instead of setSpeakerPhoneOn:
```
    fun toggleSpeakerPhone(executor: Executor, am: AudioManager) {
        if (Build.VERSION.SDK_INT >= 31)
            setSpeakerPhone(executor, am,
                am.communicationDevice!!.type == AudioDeviceInfo.TYPE_BUILTIN_EARPIECE)
        else
            setSpeakerPhone(executor, am, !am.isSpeakerphoneOn)
    }
```
```
   private fun setSpeakerPhone(executor: Executor, am: AudioManager, enable: Boolean) {
        if (Build.VERSION.SDK_INT >= 31) {
            val current = am.communicationDevice!!.type
            Log.d(TAG, "Current com dev/mode is $current/${am.mode}")
            var speakerDevice: AudioDeviceInfo? = null
            if (enable) {
                for (device in am.availableCommunicationDevices)
                    if (device.type == AudioDeviceInfo.TYPE_BLUETOOTH_SCO) {
                        speakerDevice = device
                        break
                    }
                if (speakerDevice == null)
                    for (device in am.availableCommunicationDevices)
                        if (device.type == AudioDeviceInfo.TYPE_BUILTIN_SPEAKER) {
                            speakerDevice = device
                            break
                        }
            } else {
                for (device in am.availableCommunicationDevices)
                    if (device.type == AudioDeviceInfo.TYPE_BUILTIN_EARPIECE) {
                        speakerDevice = device
                        break
                    }
            }
            if (speakerDevice != null && current != speakerDevice.type) {
                if (speakerDevice.type == AudioDeviceInfo.TYPE_BUILTIN_EARPIECE) {
                    am.clearCommunicationDevice()
                    Log.d(TAG, "Setting com device to TYPE_BUILTIN_EARPIECE")
                    if (!am.setCommunicationDevice(speakerDevice))
                        Log.e(TAG, "Could not set com device")
                    if (BaresipService.isAudioFocused && am.mode == AudioManager.MODE_NORMAL) {
                        Log.d(TAG, "Setting mode to communication")
                        am.mode = AudioManager.MODE_IN_COMMUNICATION
                    }
                } else {
                    // Currently at API levels 31+, speakerphone needs normal mode
                    if (am.mode ==  AudioManager.MODE_NORMAL) {
                        Log.d(TAG, "Setting com device to ${speakerDevice.type} in MODE_NORMAL")
                        if (!am.setCommunicationDevice(speakerDevice))
                            Log.e(TAG, "Could not set com device")
                    } else {
                        val normalListener = object : AudioManager.OnModeChangedListener {
                            override fun onModeChanged(mode: Int) {
                                if (mode == AudioManager.MODE_NORMAL) {
                                    am.removeOnModeChangedListener(this)
                                    Log.d(TAG, "Setting com device to ${speakerDevice.type}" +
                                            " in mode ${am.mode}")
                                    if (!am.setCommunicationDevice(speakerDevice))
                                        Log.e(TAG, "Could not set com device")
                                }
                            }
                        }
                        am.addOnModeChangedListener(executor, normalListener)
                        Log.d(TAG, "Setting mode to NORMAL")
                        am.mode = AudioManager.MODE_NORMAL
                    }
                }
                Log.d(TAG, "New com device/mode is ${am.communicationDevice!!.type}/${am.mode}")
            }
        } else {
            am.isSpeakerphoneOn = enable
            Log.d(TAG, "Speakerphone is ${am.isSpeakerphoneOn}")
        }
    }
```
I could revert to the earlier behavior by changing the API test to
```
(Build.VERSION.SDK_INT >= 100)
```
But looks like Android AudioManager is seriously broken.

The answer tells `There is also a brand new [AudioManager.OnModeChangedListener](https://developer.android.com/reference/android/media/AudioManager.OnModeChangedListener) called when mode is (auto-)changing`.

But that is not happening.  In MainActivity I have
```
 if (Build.VERSION.SDK_INT >= 31) {
            comDevChangedListener = AudioManager.OnCommunicationDeviceChangedListener { device ->
                if (device != null) {
                    Log.d(TAG, "Com device changed to type ${device.type} in mode ${am.mode}")
                    /*if (speakerIcon != null) {
                        if (device.type == AudioDeviceInfo.TYPE_BUILTIN_EARPIECE)
                            speakerIcon!!.setIcon(R.drawable.speaker_off)
                        else
                            speakerIcon!!.setIcon(R.drawable.speaker_on)
                    }*/
                }
            }
            am.addOnCommunicationDeviceChangedListener(mainExecutor, comDevChangedListener)
        }
```
When I touch speaker icon, the log message comes to logcat, but when Android by itself sets speakerphone on, that listener is NOT called and the log message does not appear in logcat. Check your debug log to verify.

**Comment by juha-h** [comment]
See this: https://issuetracker.google.com/issues/204914497.  It is an Android bug that they say is now fixed (Jan 9, 2023).  I have no idea in which Android upgrade the fix will be included.

The solution described in https://stackoverflow.com/a/71062507 does not use MODE_IN_COMMUNICATION at all, which is not a good idea.

**Comment by juha-h** [comment]
@yennor I may have made some progress and cannot anymore notice the issue in my test calls. Since I do not have any Android 13 devices, could you try with this apk: https://box.tutpro.com/tmp/baresip.apk?

**Comment by yennor** [comment]
with that version it doesn't seem to change automatically to the speaker anymore.
But there are two more issues:
- When a bluetooth headset is connected, it seems, forwhatever reason, still to use only the microphone of the mobilephone. Not of the headset. Eventhough the Audio output is over the headset. So when I walk away from the mobile phone, people can't hear me anymore.
- When I connect a bluetooth headset during the call, the voice output does not change to the headset. Only when I click on the speaker Icon, it changes to the bluetooth headset for like 0.5 seconds. This each time I click on the speaker Icon. It doesn-t mater in what mode the speaker icon was before (If red or white).
-

**Comment by yennor** [comment]
ps. and before you ask. "Phone calls" are activated in the bluetooth settings for this headset...

**Comment by juha-h** [comment]
@yennor  I'm on the road, but  made some fixes.  Try with this https://box.tutpro.com/tmp/baresip.apk.

**Comment by juha-h** [comment]
Looks like in Android versions >= 31, bluetooth headset actions are not called anymore and thus baresip does not know when bluetooth is connected/disconnected.  In my tests, bluetooth worked OK, if it was turned on, before call started.

**Comment by juha-h** [comment]
The reason is that at API levels 31+, app must ask for bluetooth connect permission in order to receive bluetooth connection events: https://developer.android.com/reference/kotlin/android/bluetooth/BluetoothHeadset#ACTION_CONNECTION_STATE_CHANGED:kotlin.String.  I'll need to add that.

**Comment by juha-h** [comment]
If I allowed in Settings/Apps/baresip Nearby devices permission, baresip detected when bluetooth was connected/disconnected.

**Comment by juha-h** [comment]
Bluetooth seems to work now when it is connected when call starts.  And since speaker does not turn on automatically anymore after 6 secs, I'll create a new version. It is not perfect yet, but better than the current version on API 31+ devices.

**Comment by yennor** [comment]
> Nearby devices permission, baresip detected when bluetooth was connected/disconnected.

Naming things (and cache invalidation) is difficult. I would have never guessed what that permission does...

>  I'll create a new version.

Cool, thanks a lot for your effort :-).
I'll test it, and open new tickets for new findings.

**Comment by juha-h** [comment]
I'll keep on working on bluetooth improvements.  Need to ask permission from user to allow detection on bluetooth events and replace deprecated bluetooth soc functions with API 31+ equivalents.

**Comment by ONiKiDSK** [comment]
> @yennor I may have made some progress and cannot anymore notice the issue in my test calls. Since I do not have any Android 13 devices, could you try with this apk: https://box.tutpro.com/tmp/baresip.apk?

Regarding the issue of "Speaker mode automatically activated", may I ask how you handled it at that time? I also encountered the same situation, perhaps your thoughts at that time can help me.
