### ISSUE TITLE
Android 13: Bluetooth microphone is not used

### ISSUE THREAD

**Issue by yennor** [juha-h/baresip-studio#312]
When using android 13 and having a bluetooth headset connected, the sound output is correctly routed to the headset, but the microphone of the headset is not used, only the internal microphone of the phone.
When doing a "normal mobile call" using the phone app, the headset microphone is correctly used. So I don't think it's a problem of the headset.

**Comment by juha-h** [comment]
yennor writes:

> When using android 13 and having a bluetooth headset connected, the
> sound output is correctly routed to the headset, but the microphone of
> the headset is not used, only the internal microphone of the phone. 

> When doing a "normal mobile call" using the phone app, the headset
> microphone is correctly used. So I don't think it's a problem of the
> headset.

Latest baresip version 51.0.0 contains lots of bluetooth related fixes
and modifications.  Try with that when it becomes available unless you
already did so.

**Comment by yennor** [comment]
ups sorry. Didn't noticed you just released a new Version. As soon as it hits the fdroid repository I'll try it out and give feedback.

**Comment by juha-h** [comment]
Just tested with JBL bluetooth speaker/microphone and both audio output and input were through that device.  My Android device has Android version 12.

**Comment by yennor** [comment]
I-ve tested the version 51.0.0.
Unfortunately still the same issue. When doing a call with a bluetooth headset, the internal microphone of the phone is beeing used.

**Comment by yennor** [comment]
I've found an echo number, where i can test stuff :-).
I-ve activated debug in baresip. here's the log. Maybe you can see something interesting?
[log.txt](https://github.com/juha-h/baresip-studio/files/10844244/log.txt)

**Comment by yennor** [comment]
Just to be sure, I've tried out linphone (another sip calling app). And linphone is using the bluetooth microphone properly. Please don't ask me what they do differently ;-).

**Comment by juha-h** [comment]
yennor writes:

> Just to be sure, I've tried out linphone (another sip calling
> app). And linphone is using the bluetooth microphone properly. Please
> don't ask me what they do differently ;-).

I'll look at your debug when I have time.  Perhaps your bt device does
not support sco profile, but some other one.

**Comment by juha-h** [comment]
I got Android upgrade to 13 and tried a call using Bluetooth headset.  In the call, both audio source and sink were via the Bluetooth device.

In your log, there are some suspicious lines:
```
02-27 15:57:17.981   797 29444 D audio_hw_primary: adev_open_input_stream: enter: sample_rate(16000) channel_mask(0x10) devices(0x80000008)        stream_handle(0xeaa43490) io_handle(470) source(1) format 1
02-27 15:57:17.982   797 29444 W audio_hw_utils: audio_extn_utils_update_stream_input_app_type_cfg: App type could not be selected. Falling back to default
02-27 15:57:17.982   797 29444 D audio_hw_primary: io_streams_map_insert: Added stream in io_streams_map with handle 470
02-27 15:57:17.982   797 29444 E device_utils: update_device_list: Invalid device: 0
02-27 15:57:17.986   865 20707 I AudioFlinger: AudioFlinger's thread 0xb400007d72977bb0 tid=20707 ready to run
02-27 15:57:17.986   797   797 D audio_hw_primary: in_standby: enter: stream (0xeaa43490) usecase(23: audio-record)
02-27 15:57:17.988   797 29444 D audio_hw_primary: in_standby: enter: stream (0xeaa43490) usecase(23: audio-record)
02-27 15:57:17.991   865  2180 W AudioFlinger: createRecordTrack_l(): mismatch between requested flags (00000005) and input flags (00000001)
02-27 15:57:17.997   797 29444 D audio_hw_primary: adev_close_input_stream: enter:stream_handle(0xeaa43490)
02-27 15:57:17.997   797 29444 D audio_hw_primary: io_streams_map_remove: Removed stream with handle 470
02-27 15:57:17.997   797 29444 E soundtrigger: audio_extn_sound_trigger_check_ec_ref_enable: st_dev NULL
02-27 15:57:17.997   797 29444 E soundtrigger: audio_extn_sound_trigger_update_ec_ref_status: st_dev NULL
02-27 15:57:17.997   797 29444 D audio_hw_primary: in_standby: enter: stream (0xeaa43490) usecase(23: audio-record)
02-27 15:57:18.006   797   797 D audio_hw_primary: adev_open_input_stream: enter: sample_rate(16000) channel_mask(0x10) devices(0x80000008)        stream_handle(0xeaa43490) io_handle(478) source(1) format 1
02-27 15:57:18.006   797   797 D audio_hw_primary: io_streams_map_insert: Added stream in io_streams_map with handle 478
02-27 15:57:18.006   797   797 E device_utils: update_device_list: Invalid device: 0
```
Do you have some other Bluetooth or Android device to try with?

**Comment by juha-h** [comment]
@yennor I added `am.isBluetoothScoOn = true` statement before setting the communication device.  Could you try with this https://box.tutpro.com/tmp/baresip.apk?

**Comment by yennor** [comment]
sorry I didn't reply last week. Was pretty busy.
I've tried with the above version.
Unfortunately there is still the same behaviour.
I've tried with my girlfriend's headset. The same. It is a different model, but the same brand. I don't have access to any other headset :-(
Both work with the normal Calling App and with Linphone.

**Comment by juha-h** [comment]
yennor writes:

> Unfortunately there is still the same behaviour.
> I've tried with my girlfriend's headset. The same. It is a different model, but the same brand. I don't have access to any other headset :-(
> Both work with the normal Calling App and with Linphone.

Do you have some other device to try with?

**Comment by yennor** [comment]
yes, my girlfriend's phone, once she's back.
I guess it's on android 12?

I'll report back

**Comment by juha-h** [comment]
Try with the latest release https://github.com/juha-h/baresip-studio/releases/tag/53.2.2.  It includes also some Bluetooth related fixes, but I don't know if they would have any effect on bt mic use, which works fine with my devices.
