### ISSUE TITLE
peerURI parsing issue -- Calls work, SMS does not

### ISSUE THREAD

**Issue by realPyR3X** [juha-h/baresip-studio#314]
There appears to be an issue with the peerUri being sent for the Chat dialogs. I use voip.ms as a telephony provider and have no issues making/sending calls. I use TLS and SRTP-MAND and therefore have 'mysubaccount@chicago1.voip.ms:5061;transport=tls'. I have also synced my Android contact list. I am able to receive SMS and respond correctly. However, if I select the text icon of a Contact within the Contacts activity something is being lost in translation. Initially this was failing because my contact phone numbers had +1 (444) 444-4444 and the () was failing to parse. I updated all my vcards to have the following format: +14444444444. When sending I get a "failed" toast. I have tried adding the country code and removing it both from within the app and from my contact. However I *am* able to get it to send if I create a new pear myself e.g. '4444444444@chicago1.voip.ms' this will send correctly.

Since this works correctly for dialing it seems the logic is off for the URI parsing for chats. I think it is as simple as the 'sip:' not being brought over. The logic should include sip: and append the telephony provider to create the full uri.

**Comment by juha-h** [comment]
It is not clear me where you are when you send a message.  I created a contact `E.164 Test` with URI `sip:+1234567890@test.tutpro.com`.  Then in the Contacts list, I touch that contact and choose Send Message.  The message is sent out fine.  My SIP Prxy tells:
```
Feb 25 08:30:47 char /usr/bin/sip-proxy[11560]: INFO: MESSAGE <sip:+1234567890@test.tutpro.com> by <bar@test.tutpro.com> as <sip:bar@test.tutpro.com> from <192.168.182.214> is authorized
```
So what does not work?

**Comment by realPyR3X** [comment]
Assume the E.164 only has a "tel:" if it is tel:+1234567890 with a telephony provider 'voip.blah.com' then construct the following: 'sip:+1234567890@voip.blah.com' when making phone calls it is able to take a 'tel:' and change it to 'sip:' the same logic should be applied when sending to chat peers.

**Comment by realPyR3X** [comment]
What is the purpose of the telephony provider and/or sip outgoing proxy if it's not being used in the construction of the outbound MESSAGE as well

**Comment by juha-h** [comment]
Thanks for the clarification.  I'll take a look.

**Comment by juha-h** [comment]
Should be fixed by https://github.com/juha-h/baresip-studio/commit/3eac700fb5d1c3d94dc37df2f0b11541ee16d19d.  The fix will be included in next the version.

**Comment by realPyR3X** [comment]
Looks good. Do you have place to get snapshot APKs so I can test? My machine is too weak to build it

**Comment by arichiardi** [comment]
I am also interested in testing this cause I have noticed the same issue. FWIW like how bare the app is, good job!

**Comment by arichiardi** [comment]
I am also interested in testing this cause I have noticed the same issue. FWIW like how bare the app is, good job!

**Comment by juha-h** [comment]
The fix should be in this apk:  https://box.tutpro.com/tmp/baresip.apk.   There is one thing though.  I noticed that unlike in INVITE, MESSAGE Request-URI is missing ;user=phone parameter.  It needs to get fixed in baresip lib and I created PR about it: https://github.com/baresip/baresip/pull/2469.  Perhaps your provider does not require it.

**Comment by realPyR3X** [comment]
This is still broke. Looking in Wireshark this is what is being sent:

Request-Line: MESSAGE tel:+12345678900 SIP/2.0

Not sure if this needs to be updated as well -- this looks to be just contact matching based on tel:
 https://github.com/juha-h/baresip-studio/blob/3eac700fb5d1c3d94dc37df2f0b11541ee16d19d/app/src/main/kotlin/com/tutpro/baresip/ChatsActivity.kt#L143

Looking at the code I would debug to see what this chatPeer and peerUri is at this point:
https://github.com/juha-h/baresip-studio/blob/3eac700fb5d1c3d94dc37df2f0b11541ee16d19d/app/src/main/kotlin/com/tutpro/baresip/ChatActivity.kt#L78

I'd give you a pull request if I had a machine to build/debug with. Hopefully this helps.

Steps to reproduce:
1.) Create new Android contact with phone number "2345678900" or "+12345678900"
2.) Navigate to Contacts
3.) Select Contact
4.) Select icon for message
5.) Type message
6.) Push send button

Result:
Failed toast with a message "Sending of message failed"
 
Note: Performing the exact same steps but instead selecting the phone icon will correctly dial.

**Comment by arichiardi** [comment]
@realPyR3X 

I am new here and probably you have a better idea on why is this but your original problem is really similar to mine (quoting my ticket to voip.ms):

```
Ok I tested it. Sending works only if I take away the country code (I am in Canada and I guess the system/Linphobe adds it?).  The problem is that all my contacts include the country code.  To summarize, this correctly sends:  sip:5550001111@server  

But this does not:  sip:+15550001111@server
```

The reply there was that Voip.ms currently accepts only the 10 digit format for sms.

Wanted to give this feedback cause it might be relevant here

**Comment by juha-h** [comment]
realPyR3X writes:

> Steps to reproduce:
> 1.) Create new Android contact with phone number "2345678900" or
> "+12345678900"

OK, I think this is the first time you mention "Android contact".  I
have tested it to work with baresip app's tel-contact.  But I'll take a
look if it can be made to work with Android contacts too.

**Comment by juha-h** [comment]
@realPyR3X Adding of tel provider is done in sendButton onclick listener:
```
                var msgUri = ""
                chatMessages.add(msg)
                if (Utils.isTelUri(peerUri))
                    if (ua.account.telProvider == "") {
                        Utils.alertView(this, getString(R.string.notice),
                            String.format(getString(R.string.no_telephony_provider),
                                Utils.plainAor(aor)))
                    } else {
                        msgUri = Utils.telToSip(peerUri, ua.account)
                    }
                else
                    msgUri = peerUri
```

**Comment by juha-h** [comment]
@realPyR3X I did as you instructed:

- Using Google's Contacts app, created contact `E.164 Android Test` with (mobile) phone number `+1234567890`
- In baresip Settings chose Android Contacts
- Using account bar@test.tutpro.com, touched baresip Contacts icon
- Chose `E164 Android Test` contact
- On `E.164 Android Test` page, touched Message icon next to Call icon
- In New message field wrote `New message`
- Touched the send icon (>)

As result, trace showed that message with this kind of request line was sent out:
```
02-27 16:26:35.883  7904  7943 D Baresip Lib: MESSAGE sip:+1234567890@test.tutpro.com SIP/2.0
```
So it seems to work OK.

**Comment by juha-h** [comment]
In order to make sure that Telephone provider domain is used, I changed it from `test.tutpro.com` to `pstn.tutpro.com`.  And indeed this was sent out:
```
02-27 16:39:05.354  7904  7943 D Baresip Lib: MESSAGE sip:+1234567890@pstn.tutpro.com SIP/2.0
```
The only thing that is missing is ;user=phone parameter, which is baresip lib bug.

**Comment by juha-h** [comment]
I think I found the reason.  By accident I had uploaded the apk as:
```
11392 -rw-r--r-- 1 jh       jh        11661557 Feb 27 00:40 app-release.apk
```
not as baresip.apk. Could you please download 
```
https://box.tutpro.com/tmp/baresip.apk
```
again and give it a try.  Sorry about that.

**Comment by realPyR3X** [comment]
@juha-h Yes that was it. Testing against the correct APK worked as expected. Tomorrow I will do more extensive testing. Right now all contacts have the format tel:AAABBBCCCC. I will plan to update to tel:+1AAABBBCCCC and retest. I have two remaining questions:

1.) Did this change fix the parsing issue with parentheses? i.e. tel: +1 (AAA) BBB-CCCC
2.) To save me a few cycles from reading the code -- what does setting the country code do? Is it only for contact matching?

@arichiardi Thanks for the insight it may be relevant as I test tomorrow. This snapshot APK will work with voip.ms now.You'll want to set the interval to 300 to avoid missing any messages.

**Comment by juha-h** [comment]
Regarding  tel: +1 (AAA) BBB-CCCC, the filter currently filters only space and + characters:
```
return "sip:" + telUri.substring(4).filterNot{setOf('-', ' ').contains(it)} +
                "@" + hostPart + ";user=phone"
```
I'll add also ( and ) to the filter.

**Comment by realPyR3X** [comment]
Perhaps just use PhoneNumberUtils and pass the country code? https://developer.android.com/reference/android/telephony/PhoneNumberUtils.html

@arichiardi It appears I am able to send both forms to voip.ms without issue AAABBBCCCC@server and +1AAABBBCCCC@server and it sends

Currently:

1.) +1 (AAA) BBB-CCCC result: failed
2.) +1AAABBBCCCC result: pass
3.) AAABBBCCCC result :pass

How are you using country code? If not using PhoneNumberUtils are you going to apply it somehow in this construction, ignore it, or just use it for contact matching?

**Comment by juha-h** [comment]
I created new https://box.tutpro.com/tmp/baresip.apk.  It now accepts and filters also (and ) characters from telephone number.

**Comment by arichiardi** [comment]
@realPyR3X that makes sense given the filter is trimming pluses. This is great because I don't think voip.ms will fix the issue anytime soon.

@juha-h will also test the apk thank you!

**Comment by arichiardi** [comment]
@realPyR3X that makes sense given the filter is trimming pluses. This is great because I don't think voip.ms will fix the issue anytime soon.

@juha-h will also test the apk thank you!

**Comment by arichiardi** [comment]
> You'll want to set the interval to 300 to avoid missing any messages.

Which interval? App side or within voip.ms settings?

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> > You'll want to set the interval to 300 to avoid missing any messages.
> 
> Which interval? App side or within voip.ms settings?

Actually, if you are using TCP or TLS as SIP transport protocol, tcp
keepalives are sent every minute or so and both the SIP User Agent as
the Proxy should recognize if either is not anymore available. Thus
there should be no need to use a small registration interval.  The
smaller it is, the bigger is battery consumption.

**Comment by realPyR3X** [comment]
> Andrea Richiardi writes:
> > You'll want to set the interval to 300 to avoid missing any messages. Which interval? App side or within voip.ms settings?
> Actually, if you are using TCP or TLS as SIP transport protocol, tcp keepalives are sent every minute or so and both the SIP User Agent as the Proxy should recognize if either is not anymore available. Thus there should be no need to use a small registration interval. The smaller it is, the bigger is battery consumption.

voip.ms has recommended a register interval of 300 on most of the softphones/hardware devices I've used including obi200 and linphone. I have not tested this extensively but without setting it I've missed messages on linphone.

**Comment by realPyR3X** [comment]
@juha-h when messages are received by my telephony provider (voip.ms) as @arichiardi pointed out, the number does not include a country code. This means I will receive a message from AAABBBCCCC which does not match my Android contact which has +1AAABBBCCCC and show two chat dialogs. I can change all my contacts to remove the +1 and have the form tel:AAABBBCCCC which will match, but this seems like using the country code in catch matching is the right approach. Thoughts?

**Comment by arichiardi** [comment]
> This means I will receive a message from AAABBBCCCC which does not match my Android contact which has +1AAABBBCCCC and show two chat dialogs.

I second this, it would be a great quality of life improvement to set the country code and have the contacts group correctly. It is actually quite a miss from voip.ms' side that the SMS format does not include the country code (as probably they only support North America).

**Comment by juha-h** [comment]
realPyR3X writes:

> voip.ms has recommended a register interval of 300 on most of the
> softphones/hardware devices I've used including obi200 and linphone. I
> have not tested this extensively but without setting it I've missed
> messages on linphone.

Did you use TCP or TLS transport.  At least in case of baresip, when it
notices that tcp/tls connection is lost (gets closed or keepalives stop
arriving), it creates new connection to SIP proxy and re-registers.

**Comment by realPyR3X** [comment]
I'm using TLS. This is the guide for linphone where I was mapping similar settings:

https://wiki.voip.ms/article/Linphone_Android

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> > This means I will receive a message from AAABBBCCCC which does not
> > match my Android contact which has +1AAABBBCCCC and show two chat
> > dialogs.
> 
> I second this, it would be a great quality of life improvement to set
> the country code and have the contacts group correctly. It is actually
> quite a miss from voip.ms' side that the SMS format does not include
> the country code (as probably they only support North America).

I think you should try to get it fixed at voip.ms, but have you set
baresip account's Country Code value to +1.  If so, does it add that
to From URI when call comes in but does not add that to From URI of
incoming MESSAGE?  If so, I could try to fix it.

**Comment by arichiardi** [comment]
> Andrea Richiardi writes:
> > This means I will receive a message from AAABBBCCCC which does not > match my Android contact which has +1AAABBBCCCC and show two chat > dialogs. I second this, it would be a great quality of life improvement to set the country code and have the contacts group correctly. It is actually quite a miss from voip.ms' side that the SMS format does not include the country code (as probably they only support North America).
> I think you should try to get it fixed at voip.ms, but have you set baresip account's Country Code value to +1. If so, does it add that to From URI when call comes in but does not add that to From URI of incoming MESSAGE? If so, I could try to fix it.

This seems to be the case, cause the message I receive does not contain the `+1` and therefore contact lookup fails (I do not see any icon)

**Comment by arichiardi** [comment]
When I click on it this is what I see:

![Screenshot_20230227_144356_baresip](https://user-images.githubusercontent.com/1724788/221693160-91fa0cd1-9d89-4b76-a2ba-8c07bdaa26f0.jpg)

**Comment by juha-h** [comment]
Could you try with this https://box.tutpro.com/tmp/baresip.apk.  It
tries to add account's Country code to From URI userpart that is numeric
and does not start with + or 0 or 00.  I haven't had time to test it
myself yet.  Need to create sipp scenario for the test.

**Comment by arichiardi** [comment]
Yep no problem will test it out

**Comment by arichiardi** [comment]
@juha-h I tested it and I indeed see the contact matching now!

**Comment by juha-h** [comment]
Try again with this: https://box.tutpro.com/tmp/baresip.apk.  In my
test I have Android contact 'E.164 Android Test' with number
'+1 (234) 567-8900' and when message comes in with From URI

From: ***@***.***>;tag=147da7666e402259

Chat History pages finds it and shows message coming from 'E.164 Android
Test'.  On the Chat page it still shows the number 2345678900, since I
have not had time to work on it.

I'm offline the next couple of days.  I may need to create a new baresip
version before getting this issue fully solved, since there are more
serious bugs already fixed.

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> @juha-h I tested it and I indeed see the contact matching now!

Good to learn that.  I still need to look what needs to be done to show
the contact on the chat page.

**Comment by arichiardi** [comment]
> Andrea Richiardi writes:
> @juha-h I tested it and I indeed see the contact matching now!
> Good to learn that. I still need to look what needs to be done to show the contact on the chat page.

No worries, just to make sure, the following is not fixed yet right?

> Chat History pages finds it and shows message coming from 'E.164 Android Test'.  On the Chat page it still shows the number 2345678900, since I have not had time to work on it.

Again, not rushing you, just want to make sure I installed the right apk

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> > Chat History pages finds it and shows message coming from 'E.164
> > Android Test'.  On the Chat page it still shows the number
> > 2345678900, since I have not had time to work on it.

It is not yet fixed on the Chat page.

**Comment by juha-h** [comment]
juha-h writes:

> Andrea Richiardi writes:
> 
> > > Chat History pages finds it and shows message coming from 'E.164
> > > Android Test'.  On the Chat page it still shows the number
> > > 2345678900, since I have not had time to work on it.
> 
> It is not yet fixed on the Chat page.

Now it should be fixed,  Try the apk again.  It is getting quite complex
with many different alternatives for contact lookup. Hope this is enough.

**Comment by arichiardi** [comment]
Ok trying

**Comment by arichiardi** [comment]
@juha-h It works! It's minor but the only outstanding thing that probably should be made consistent is when you long press on the contact, you don't see the country code

![Screenshot_20230228_154756_baresip](https://user-images.githubusercontent.com/1724788/221999546-3fe8b36f-ab3a-4155-af05-df827995b44d.jpg)

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> @juha-h It works! It's minor but the only outstanding thing that
> probably should be made consistent is when you long press on the
> contact, you don't see the country code.

Download and try again.  I'm not at present able to test myself.
Running out of power on my laptop and usb stopped working.

**Comment by arichiardi** [comment]
No worries, I can test it ... after a bit...

So I see that the "Confirmation" now correctly shows the name and you Add or Delete. So that is great.
I think I am going to stop asking things here and will open a new feature request cause probably "Add Contact" should not exist if the contact lookup was successful.

No worries though, this apk is already excellent for my current usage pattern :smile: Thank you!

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> I think I am going to stop asking things here and will open a new
> feature request cause probably "Add Contact" should not exist if the
> contact lookup was successful.

I'll fix that after the next release.

**Comment by juha-h** [comment]
juha-h writes:

> I'll fix that after the next release.

Just created new release 51.1.0.

**Comment by arichiardi** [comment]
@juha-h tried it just now

It correctly detects that a contact exists and you do not need to add it now, I will open a new issue for the Add Contact flow

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> It correctly detects that a contact exists and you do not need to add
> it now, I will open a new issue for the Add Contact flow

OK.
