### ISSUE TITLE
Feature request: support call recording

### ISSUE THREAD

**Issue by nicoursi** [juha-h/baresip-studio#315]
Hi, 
It would be really nice if this app could support  automatic call recording,  not as default but available in the settings.

**Comment by juha-h** [comment]
it is in the works.  Needs some new stuff in baresip lib sndfile module.

**Comment by juha-h** [comment]
Added to WiKi https://github.com/juha-h/baresip-studio/wiki/Feature-Requests.

**Comment by juha-h** [comment]
Initial support for call recording is now available in version 52.1.0.
