### ISSUE TITLE
Feature Request: speaker phone

### ISSUE THREAD

**Issue by nicoursi** [juha-h/baresip-studio#316]
What I really miss in this app is the ability to activate the speaker phone.

**Comment by DakarKaret** [comment]
@nicoursi There are mute and speaker toggle buttons in the toolbar

**Comment by nicoursi** [comment]
Oh,  so that strange wireless icon is the speaker phone? I was wondering what that could be 😃

Why not a more self explanatory icon? Or at least explanation of what it is by long pressing?

**Comment by juha-h** [comment]
I didn't invent the icon.  It is official Material Design speaker phone icon:
https://fonts.google.com/icons?icon.set=Material+Icons&icon.query=speaker+phone
