### ISSUE TITLE
Notifications for message received

### ISSUE THREAD

**Issue by realPyR3X** [juha-h/baresip-studio#319]
I am not receiving a notification upon a message being received. Opening the app I can see a changed color on the messages button indicating a new unread message, however, there is no Android notification showing this. I've confirmed notifications are enabled on the app. I'm not sure if this is a feature request or a bug.

**Comment by juha-h** [comment]
Thanks for the report.  Looks like issue with newer Android versions.  Working on a fix.

**Comment by juha-h** [comment]
Could you try with this one: https://box.tutpro.com/tmp/baresip.apk?

**Comment by juha-h** [comment]
Thanks,  the fix is in this commit https://github.com/juha-h/baresip-studio/commit/3e101d22caaa9fc1b5c8ac76c61b1db58b95a3a5 and will be included in the next version.
