### ISSUE TITLE
DNS field - don't ask for port

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#32]
...as by defaut most use 53, so if the user inputs `:port` use it if not...it's probably 53.

**Comment by juha-h** [comment]
Licaon_Kter writes:

> ...as by defaut most use 53, so if the user inputs `:port` use it if
> not...it probably 53.

Will default to 53 in the next version.

**Comment by juha-h** [comment]
This feature was included in commit https://github.com/juha-h/baresip-studio/commit/8c36e7ab3e7d65ea418bf8dfef92f7d41630a0ff.
