### ISSUE TITLE
Baresip doesn't search contacts with more than one phone number

### ISSUE THREAD

**Issue by yennor** [juha-h/baresip-studio#320]
When entering in the "call to" field letters, so it searches through the contacts, that works usually. But it doesn't display any contact which has more than one phone number.
Those I always need to search manually in the contacts screen.
I've told baresip to use the android contacts, not only the baresip ones.

**Comment by juha-h** [comment]
yennor writes:

> When entering in the "call to" field letters, so it searches through
> the contacts, that works usually. But it doesn't display any contact
> which has more than one phone number.

That is how it is.  You need to create two contacts, e.g., Bill Mobile and
Bill Office.  Supporting many numbers under the same contact gets too
complex and I'm not considering to implement that.

**Comment by arichiardi** [comment]
Would it be possible to show, instead of filtering out? I have hundreds of contacts and splitting all of the up would take me some (scripting) time.

**Comment by yennor** [comment]
It would cool if it would be possible to just show all the phone numbers of a contact. The name can just be repeated, like:
Ben 123-456
Ben 234-123

I can recognize 9x% of the phone numbers by their prefix.
I don't know in what kind of datastructur you get the contacts, but maybe just doing some kind of flatmap would be enough?

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> Would it be possible to show, instead of filtering out? I have
> hundreds of contacts and splitting all of the up would take me some
> (scripting) time.

I would need to show a selection dialog where user would select one of
the URIs.  Everything is possible, but right now I don't have time for
it.

**Comment by juha-h** [comment]
Now I remember that the various labels (Home, Mobile, Work, etc) are not standardized and baresip does not get access to them.  So all baresip could do is to list the numbers and I don't know how useful that would be.  For sure users would start to complain about it.

**Comment by gdt** [comment]
It seems surprising to me that the contacts database API doesn't provide labels.   I have lots of contacts with multiple numbers; that's just how people are.   I would far rather see multiple numbers, even if not labeled, and be able to push them, rather than having contacts with multiple numbers just missing.   The idea of changing my contact structure to enforce a one-number-per-contact scheme seems unreasonable.

(I get it that you are doing what you are interested in with limited time; this comment is about what ought to be eventually rather than any request to do it.)

**Comment by juha-h** [comment]
I checked and it provides these https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Phone.  Would the first three suffice?

**Comment by arichiardi** [comment]
In my opinion home, mobile and work suffice, sometimes I have got two mobile ones in a contact, which is covered by the three

**Comment by yennor** [comment]
> So all baresip could do is to list the numbers and I don't know how useful that would be. For sure users would start to complain about it.

I guess users would also complain if numbers don't appear at all. At least I am complaining about it ;-). The first few times it happened I thought that I didn't store the number properly and looked it up on the computer and entered it manually on the phone.

**Comment by juha-h** [comment]
It turned out that Android contact can have  several phone numbers with the same label, e.g. Mobile.  So it would not work if URI completion shows name of the contact and its label.  The only working solution that comes to mind is that only the contact name is shown and when user selects that, another selection appears with the list of numbers and their labels.

It is not trivial code to write.  I'll add it to Feature Requests page.

**Comment by juha-h** [comment]
I added initial support for multiple telephone numbers in Android contacts in apk https://box.tutpro.com/tmp/baresip.apk.  Currently it is only implemented when making a call from Main Activity. Comments?

**Comment by arichiardi** [comment]
I have tried it out and for me it's plenty good!

A couple of observations: 
* probably the same should happen for the sms page, but you are probably already on it 👍 
* this might be a feature request but I think you could [filter by primary contact](https://stackoverflow.com/a/14813907) if set and avoid the popup for those that have it

Thank you!

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> * this might be a feature request but I think you could [filter by
> * primary contact](https://stackoverflow.com/a/14813907) if set and
> * avoid the popup for those that have it

That is very old posting.  I have not found Phone.IS_PRIMARY in the
current phone reference
https://developer.android.com/reference/kotlin/android/provider/ContactsContract.CommonDataKinds.Phone.

I installed Google's Contacts and have not found there a way to tell that
a particular phone number is primary.

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> * probably the same should happen for the sms page, but you are
> * probably already on it.

Andrea,

It should now be done in the apk that I just uploaded.  Give it a try.

-- Juha

**Comment by juha-h** [comment]
Greg Troxel writes:

> It seems surprising to me that the contacts database API doesn't
> provide labels.   I have lots of contacts with multiple numbers;
> that's just how people are.   I would far rather see multiple numbers,
> even if not labeled, and be able to push them, rather than having
> contacts with multiple numbers just missing.   The idea of changing my
> contact structure to enforce a one-number-per-contact scheme seems
> unreasonable.

Try with the apk that I just uploaded: https://box.tutpro.com/tmp/baresip.apk

**Comment by arichiardi** [comment]
> Andrea Richiardi writes:
> * probably the same should happen for the sms page, but you are * probably already on it.
> Andrea, It should now be done in the apk that I just uploaded. Give it a try.
> […](#)
> -- Juha

Works perfectly here!

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> Works perfectly here!

How about the first point in the issue https://github.com/juha-h/baresip-studio/issues/323?

**Comment by arichiardi** [comment]
Still have to try that out with adb, apologies did not have time today.

**Comment by yennor** [comment]
it's working for me. It's minimally confusing that it only asks for the number, when dialing. But I guess it's a question of getting used to it. And like that I've got access to all my numbers :-).
Thanks a lot!

ps. Would it be possible, that when you to a test build, that you give it a different package name? So I don-t have to first uninstall the current installed baresip to install the test build and afterwards uninstall the test build and reinstall the f-droid build?

**Comment by arichiardi** [comment]
> So I don-t have to first uninstall the current installed baresip to install the test build and afterwards uninstall the test build and reinstall the f-droid build

Most package managers for Android would update the app without the need of uninstalling.

I use personally use 

https://github.com/SmartPack/PackageManager

(Go to Installer at the top right)

But there are many many on the play store

**Comment by juha-h** [comment]
yennor writes:
> it's working for me. It's minimally confusing that it only asks for
> the number, when dialing.

It now also asks the number when adding new char peer.

> ps. Would it be possible, that when you to a test build, that you give
> it a different package name? So I don-t have to first uninstall the
> current installed baresip to install the test build and afterwards
> uninstall the test build and reinstall the f-droid build?

It should not be common that people need to install baresip from apk.

**Comment by yennor** [comment]
> It should not be common that people need to install baresip from apk.

I only need to do it when testing one of your test builds. Since they are signed with a different key as the ones in the F-Droid repository but have the same package name, I can't just directly exchange them. But it's a minor issue, as long as I don't do testing regularly.

Personally, I vote for closing the issue since we got a working solution? Unless you want feedback from more people?

**Comment by arichiardi** [comment]
> Personally, I vote for closing the issue since we got a working solution? Unless you want feedback from more people?

Works for me, tested and working here

**Comment by juha-h** [comment]
OK, I'll close this now and create a new version based on the latest master.  The problem with F-Droid is that it can easily take two weeks before a new version is available.
