### ISSUE TITLE
Problem using baresip over mobile network

### ISSUE THREAD

**Issue by bovergaauw** [juha-h/baresip-studio#322]
Using baresip 51.0.0 from F-Droid, I cannot register to my provider when I'm using my mobile connection. Over WiFi everything works as expected.
I probably narrowed the problem down to the use of IPv6 that my mobile provider does not seem to support as I solved the same issue with Linphone when I switched the "Allow IPv6" setting off. Is there a way in baresip to disable the use of IPv6?

**Comment by juha-h** [comment]
bovergaauw writes:

> Using baresip 51.0.0 from F-Droid, I cannot register to my provider
> when I'm using my mobile connection. Over WiFi everything works as
> expected.
> I probably narrowed the problem down to the use of IPv6 that my mobile
> provider does not seem to support as I solved the same issue with
> Linphone when I switched the "Allow IPv6" setting off. Is there a way
> in baresip to disable the use of IPv6?

There is no such option.  Try setting IPv4 address in outbound proxy.
If IPv6 connection fails, baresip should use IPv4, but if your registrat
accepts IPv6 connection and then does not accept registratiopmn over
IPv6, you should open issue with your ptovider, not baresip.  You need
take debug log of the registation attempt.  See Wiki for instructions.

**Comment by juha-h** [comment]
If you want to have support for disabling a particular IP protocol, you would need to add a feature request about it to baresip project.

**Comment by juha-h** [comment]
@bovergaauw Try with the latest baresip.  It has setting to choose IP address family.

**Comment by bovergaauw** [comment]
Hi @juha-h ,
Thanks for your help, I definitely will try as soon as F-Droid updates their repo, but they are awfully slow in doing so lately. If they haven't included your new version in a few days I'll uninstall and reinstall from Github. In any case I'll keep you informed.
Take care
