### ISSUE TITLE
Fix number display when contact is new

### ISSUE THREAD

**Issue by arichiardi** [juha-h/baresip-studio#323]
Hi there, first of all this is from your latest Box sdk.
There are a couple of thing to say on the add contact flow but they are minor, some are questionable and I am not really sure how/if you want to address them. It depends, but I figured I should point your attention to it.

* When you receive an sms the chat history shows the full sip - it should probably show the number (containing your selected area code *if not already present*)

![Screenshot_20230302_221202_baresip](https://user-images.githubusercontent.com/1724788/222638174-1aa099ff-175b-492f-af37-1ff3459b9f7a.jpg)

* When long pressing, the Add contact shows the full sip on the top but the bare number on the bottom - it should probably show the number (containing your selected area code *if not already present*)

![Screenshot_20230302_221150_baresip](https://user-images.githubusercontent.com/1724788/222639133-817db89e-c838-4054-9310-b9cbd68a65e4.jpg)

* Finally, the add contact. This is tricky cause it allows to save the sip. It makes me doubt all of the above tweaks - maybe in the future you can slect if you want to save the full sip or only the number?

Anyways, feel free to discard this if I am misunderstanding something abd thanks for your work! 😊

**Comment by arichiardi** [comment]
@juha-h I should have specified that the sender never has any account on the voip provider (it is a mobile from someone sending me an SMS)

**Comment by juha-h** [comment]
But the screenshot shows that the message is coming from domain vancouver1.voip.ms.  If you have an account with that domain, only the phone number is shown.

**Comment by juha-h** [comment]
For security reason, if domain of incoming message or call does not match domain of any account, then the whole URI is show.  Otherwise only the userpart is shown.  Let me know in which case that is not true.

**Comment by juha-h** [comment]
I made more tests with the latest apk and everything related to to this issue seems to work OK (at least according the current baresip intentions).

**Comment by arichiardi** [comment]
> But the screenshot shows that the message is coming from domain vancouver1.voip.ms. If you have an account with that domain, only the phone number is shown.

Oh ok I misunderstood I think, yes i do have an account with voip.ms.

I will try the latest apk and report back 😊

**Comment by juha-h** [comment]
Domain of your account has to be vancouver1.voip.ms in order to avoid showing the whole URI.

**Comment by arichiardi** [comment]
> Domain of your account has to be vancouver1.voip.ms in order to avoid showing the whole URI.

Yeah ok, I double checked and the domain is correct. Did you upload a newer apk by any chance? I do not see changes from above

**Comment by juha-h** [comment]
Just in case I didn't upload the latest apk, I did it again.  I also tested once more.:
- Message comes in from sip:+35892345671@test.tutpro.com to bar@test.tutpro.com
- On Chat History page and on `Chat with ...` page there is only the number +35892345671 both in the heading and in the message itself
- I then long touch the message on Chat History page and in the Confirmation only the number is shown
- I choose Add Contact, there edit the SIP URI to tel URI tel:+35892345671, give the contact a name, and check Android
- After that I get back to Chat History and the number has changed to name of the contact

So everything works OK in my test.

**Comment by arichiardi** [comment]
Ok tested the apk here:

https://box.tutpro.com/tmp/baresip.apk

It seems to be version 51.2.0.

I still see this:

![Screenshot_20230303_210110_baresip](https://user-images.githubusercontent.com/1724788/222874795-b7de00ac-f0b6-4b5f-be4f-b6f89fe41b7b.jpg)

The only "out of the ordinary thing" I have in my account is the outbound proxy set as:

`sip:vancouver1.voip.ms:5061;transport=tls`

Not sure it matters but thought it might.

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> It seems to be version 51.2.0.

Yes.

> I still see this:
> 
> ![Screenshot_20230303_210110_baresip](https://user-images.githubusercontent.com/1724788/222874795-b7de00ac-f0b6-4b5f-be4f-b6f89fe41b7b.jpg)
> 
> The only "out of the ordinary thing" I have in my account is the outbound proxy set as:
> 
> `sip:vancouver1.voip.ms:5061;transport=tls`
> 
> Not sure it matters but thought it might.

It does not matter.  The only thing that matters here is that your
baresip has to have account with domain vancouver1.voip.ms.

Well, just as I was writing the above, it occurred to me that you seem
to be using Account Nickname "Mine BC", which I have not tested with.

Does it help it you just for the test clear the Account Nickname?

**Comment by juha-h** [comment]
I'll create tomorrow a new apk that includes more debug statements.  You can then check with `adb logcat  | grep Baresip` (or Windows Mac Os equivalent) what they produce to log.  In the meanwhile, could you turn on SIP Trace in Settings and see with adb logcat how exactly the From URI of the incoming MESSAGE looks like.

**Comment by juha-h** [comment]
You can send the From URI to me as email to jh@tutpro.com.

**Comment by arichiardi** [comment]
> Well, just as I was writing the above, it occurred to me that you seem
to be using Account Nickname "Mine BC", which I have not tested with.

Well no that is just a nickname but it is voip.ms under the hood. I will send you the logs as soon as possible, there must be something else there.

Thanks for tour help!

**Comment by juha-h** [comment]
I uploaded again a new baresip.apk.  Try with that.  If it doesn't
help, my public gpg key for the logs is
F304E5A6D6680FDFA055A3F43186DA396929CD3B.

**Comment by juha-h** [comment]
Fixed by https://github.com/juha-h/baresip-studio/commit/02556aa97f76ac3fb4ea684beac1f4fee77d5c4f.
