### ISSUE TITLE
Connection timeout and red dot

### ISSUE THREAD

**Issue by arichiardi** [juha-h/baresip-studio#326]
Dear @juha-h, following up on my comments in #318.

I have got some logs for the red dot issue (send via email). Opening an issue to better track things.

It basically seems that when the `Main` stops, the connections starts timing out and then bringing it forward never really recovers (it cannot reconnect even if internet is available to the phone).

As usual I am open to any debugging you want me to do.

Thank you,
Andrea

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> It basically seems that when the `Main` stops, the connections starts
> timing out and then bringing it forward never really recovers (it
> cannot reconnect even if internet is available to the phone).

Could it be that your device puts baresip into some kind of deep sleep
when the app is not visible?  Try if it helps when you disable Battery
Optimizations in Settings unless you have already done so.  Also, try
with another Android device if you have one.

**Comment by arichiardi** [comment]
I have asked `voip.ms` - the app does seem to fail (red) even on foreground and it does reconnect after a long while - this might be a service problem on the provider side. At this point I am not sure this is app-related so closing - I will reopen in case I have got some news.

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> I have asked `voip.ms` - the app does seem to fail (red) even on
> foreground and it does reconnect after a long while - this might be a
> service problem on the provider side. At this point I am not sure this
> is app-related so closing - I will reopen in case I have got some
> news.

OK, thanks and also, if you have time, try with some other provider,
e.g., sip2sip.info, or I could create you an account on my SIP server.
