### ISSUE TITLE
Creating a new chat from contact results in crash

### ISSUE THREAD

**Issue by arichiardi** [juha-h/baresip-studio#327]
Hey Juha,
I found a problem in the last apk uploaded:

* Go to the chat page
* Select a contact
* Press the plus icon to send a message

The app closes instead of creating a new chat.

FWIW, this happened with a contact with only one number

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> I found a problem in the last apk uploaded:
> 
> * Go to the chat page
> * Select a contact
> * Press the plus icon to send a message
> 
> The app closes instead of creating a new chat.

Thanks for the report.  Too much multitasking.  I just uploaded a new
apk, where the bug should be fixed.

**Comment by arichiardi** [comment]
Yep fixed, big thanks and yeah, multitasking is 👎
