### ISSUE TITLE
Baresip sends account creation URI instead of account settings one

### ISSUE THREAD

**Issue by arichiardi** [juha-h/baresip-studio#328]
Hi @juha-h I think I found the problem that I thought was involving the VPN (surprise surprise, it was not the VPN :smile:)

I'll try to describe to the best of my knowledge of the app. In order to repro:

* Create a new sip2sip account, for instance `foo123@sip2sip.info`
* Add a new account making a mistake in the uri, say `wrong@sip2sip`
* Go into the settings and set your user name to `foo123` and your password
* Tick the "Register" box

At this point I'd expect the account to register correctly, because the user and the password are correct in the account settings.

However, it seems `baresip` is still trying to register with `wrong@sip2sip` and that fails (of course).

Maybe this is expected, please let me know if so.

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> I'll try to describe to the best of my knowledge of the app. In order
> to repro: 
> 
> * Create a new sip2sip account, for instance ***@***.***`
> * Add a new account making a mistake in the uri, say ***@***.***`

So now you have two account where Register box has been checked in each?

> * Go into the settings and set your user name to `foo123` and your password
> * Tick the "Register" box

Settings of which of the two?  It is not possible to change the username
of account's address of record (AoR), only the Authentication username,
which is not always the same as userpart of the AoR.

> At this point I'd expect the account to register correctly, because
> the user and the password are correct in the account settings.

Which account?

> However, it seems `baresip` is still trying to register with
> ***@***.***` and that fails (of course).

If you still have two accounts, it tries to register both (if Register
is checked).

In the above case, you should delete the wrong account.

**Comment by arichiardi** [comment]
@juha-h this happens on a blank app, no prior/existing accounts registered.

>  It is not possible to change the username of account's address of record (AoR), only the Authentication username,
which is not always the same as userpart of the AoR.

This might be my misunderstanding, do I understand right that after clicking on the `+` in the account creation page there is no way to change that address? I'll have to delete the account and recreate?

If so, I'll close this issue cause it seems you expect it (even if I find it a bit confusing).

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> This might be my misunderstanding, do I understand right that after
> clicking on the `+` in the account creation page there is no way to
> change that address? I'll have to delete the account and recreate?

No, there is no way to change the AoR ***@***.***) of the account
after you press the + button.  As I wrote, authentication username can
be changed and does not need to be same as userpart of the AoR. If you
made a mistake in the AoR, you need to delete the account and create a
new one.
 
> If so, I'll close this issue cause it seems you expect it (even if I
> find it ao bit confusing).

SIP is not simple and many times confusing.

**Comment by arichiardi** [comment]
>As I wrote, authentication username can be changed and does not need to be same as userpart of the AoR. If you
made a mistake in the AoR, you need to delete the account and create a
new one.

Ok I will close then, sounds good, sorry for the noise.
