### ISSUE TITLE
Account config reverts on restart when field changes after first setup

### ISSUE THREAD

**Issue by arichiardi** [juha-h/baresip-studio#330]
Hi @juha-h,
I am using your app during my trip and it's greatly liberating to know that you can rely on it and battery usage is minimal.

I found a small quirk I cannot consistently repro

Basically sometimes the account settings are reverted.
Say I change the registration interval to 500. The next time I restart it goes back to what was before.

This happens with the Account nickname and display name as well.

One more thing, if Register is ticked and I restart, the settings stay.

I hope this debugging is useful,
Andrea

**Comment by juha-h** [comment]
I changed Registration Interval and restarted.  The new value prevailed.  Then I did the same experiment with Display Name and again the new value prevailed.  Are you sure that you clicked  the v in the upper right corner and not just pressed the back button?

**Comment by arichiardi** [comment]
Hhm, yep I did that, I will try and send you a video.

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> Hhm, yep I did that, I will try and send you a video.

Video is not needed, just tell the steps you take after starting
baresip.

**Comment by arichiardi** [comment]
Yeah they are not different from what you said, changing a value and restaring does not keep them here. 

One odd thing I noticed is that my interval is always restored to 30, which is invalid but restored. I wonder if that is the problem.

I will try to create a new account with 30 now and see if I can repro

**Comment by arichiardi** [comment]
No, the value does not impact, I have lost the nickname on restart with all default values.

**Comment by juha-h** [comment]
In order to be on the same page, try with this https://box.tutpro.com/tmp/baresip.apk.  It is based on latest master.

**Comment by arichiardi** [comment]
Ok done and it stil happens, here is what I did:

* app uninstalled
* app reinstalled
* config backup restored
* deleted a couple of chars from my account nickname
* unticked "Register"
* restarted

No more nickname was present when it popped back

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> Ok done and it stil happens, here is what I did:
> 
> * app uninstalled
> * app reinstalled
> * config backup restored

And app restarted?

> * deleted a couple of chars from my account nickname
> * unticked "Register"
> * restarted
> 
> No more nickname was present when it popped back

It is really weird.  The above works fine for me and I installed exactly
the same apk.

**Comment by arichiardi** [comment]
> And app restarted?
Yep it did

> It is really weird. The above works fine for me and I installed exactly the same apk.

It is not consistent. For instance I cannot make it happen anymore, no matter what I do now the values save and restore correctly.
Only the speaker icon stays enabled even if I dsabled it.

**Comment by juha-h** [comment]
juha-h writes:

> > * deleted a couple of chars from my account nickname
> > * unticked "Register"

Is Nickname OK after restart if you don't do anything to Register?

When yoy Click v after editing NickName, does the edited nickname show up
in the account spinner on the main page?

**Comment by arichiardi** [comment]
> juha-h writes:
> > * deleted a couple of chars from my account nickname > * unticked "Register"
> Is Nickname OK after restart if you don't do anything to Register? When yoy Click v after editing NickName, does the edited nickname show up in the account spinner on the main page?

Yes it shows up the first time, the lost at restart

**Comment by juha-h** [comment]
So you can't toggle the speaker icon?  Is it always red?  I do not have any issues with it.

**Comment by arichiardi** [comment]
> So you can't toggle the speaker icon? Is it always red? I do not have any issues with it.

Sorry I will open another issue with that cause it seems unrelated.

I might have found, if I add the country code (+1) and restart, the nickname is lost.

**Comment by arichiardi** [comment]
Also, try to add +333 as country code and restart 💥

**Comment by juha-h** [comment]
Changed Country Code to +333, touched V and restarted.  It is still +333. Also Nickname is what it should be.  I have not been able to reproduce this a single time and I don't think it is Android 13 related.

**Comment by arichiardi** [comment]
> Changed Country Code to +333, touched V and restarted. It is still +333. Also Nickname is what it should be. I have not been able to reproduce this a single time and I don't think it is Android 13 related.

Oh wow, that for me results in a crash every time I restart the app. And there is no way to recover, I have to uninstall and reinstall. Very odd stuff.

**Comment by juha-h** [comment]
In order for me to be able to reproduce, install the app.  Don't restore any old config.  Create one new account with values you like to test with and restart.  Did the values stay?  If not, I'll try the same thing tomorrow when you tell what values the account had.

**Comment by arichiardi** [comment]
You might be onto something, I cannot repro which means values are always correct if I start fresh and do not import any config

**Comment by arichiardi** [comment]
I have a theory, my config backup might be from a version prior to "something". I will try to produce it and send it to you.

**Comment by juha-h** [comment]
Please close if you cannot reproduce this and open a new issue later if it still shows up.

**Comment by juha-h** [comment]
Just tried and I cannot reproduce this.  After first restart, everything in the account was preserved. No use to go further, before this one is resolved.

 Are you sure, you touched the save (v) button before Quit?  Also, which fields you filled when you added the account?

**Comment by juha-h** [comment]
Account Nickname and Registration Interval are both included in `;extra` account parameter.  Does your Nickname have some special characters?

**Comment by juha-h** [comment]
I created test apk https://box.tutpro.com/tmp/baresip.apk that produces logcat message showing the saved accounts:
```
Log.e(TAG, "Saved accounts '${accounts}' to '${BaresipService.filesPath}/accounts'")
```
Do you see `nickname` and `reginit` parameters in `extra`?

**Comment by arichiardi** [comment]
Will try it out and report back

**Comment by arichiardi** [comment]
Ok here we go:

```
## First start
#
W Baresip : Main onStart
D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4191)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4233)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4615)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4585)] [com.tutpro.baresip.BaresipService.onCreate(BaresipService.kt:130)] [android.app.ActivityThread.handleCreateService(ActivityThread.java:5073)] [android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)] [android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)]
I Baresip : Asset 'accounts' already copied
I Baresip : Asset 'config' already copied
D Baresip Lib: starting baresip

# And all correct on read  
W Baresip : ********** extra = nickname=Voip.ms;tel_provider=vancouver1.voip.ms;regint=300

##
# Add country code: nickname, regint and tel_provider *all correct* on save
#
W Baresip : Main onStart
W Baresip : Saved accounts '<sip:foo@vancouver1.voip.ms>;auth_user="foo";auth_pass="foo";outbound="sip:vancouver1.voip.ms:5081;transport=tls";sipnat=outbound;audio_codecs=opus/16000/1,AMR-WB/16000/1,G722/16000/1,G7221/16000/1,AMR/8000/1,G726-40/8000/1,G726-32/8000/1,G726-24/8000/1,G726-16/8000/1,G729/8000/1,GSM/8000/1,PCMU/8000/1,PCMA/8000/1;mwi=no;ptime=20;regint=300;regq=0.5;pubint=0;call_transfer=yes;100rel=no;extra="nickname=Voip.ms;tel_provider=vancouver1.voip.ms;country_code=+1;regint=300"
W Baresip : ' to '/data/user/0/com.tutpro.baresip/files/accounts'
W Baresip : Main onStart
W Baresip : uaEvent unregistering did not find ua 536761962720
W Baresip : Main onStart
D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4191)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4233)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4615)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4585)] [com.tutpro.baresip.BaresipService.onCreate(BaresipService.kt:130)] [android.app.ActivityThread.handleCreateService(ActivityThread.java:5073)] [android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)] [android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)]
I Baresip : Asset 'accounts' already copied
I Baresip : Asset 'config' already copied
D Baresip Lib: starting baresip

##
# Add vm_uri: nickname, regint and tel_provider *all correct* on save
#
# And all correct on read
W Baresip : ********** extra = nickname=Voip.ms;tel_provider=vancouver1.voip.ms;country_code=+1;regint=300
W Baresip : Saved accounts '<sip:foo@vancouver1.voip.ms>;auth_user="foo";auth_pass="bar";outbound="sip:vancouver1.voip.ms:5081;transport=tls";sipnat=outbound;audio_codecs=opus/16000/1,AMR-WB/16000/1,G722/16000/1,G7221/16000/1,AMR/8000/1,G726-40/8000/1,G726-32/8000/1,G726-24/8000/1,G726-16/8000/1,G729/8000/1,GSM/8000/1,PCMU/8000/1,PCMA/8000/1;mwi=yes;vm_uri="sip:*97@vancouver1.voip.ms";ptime=20;regint=300;regq=0.5;pubint=0;call_transfer=yes;100rel=no;extra="nickname=Voip.ms;tel_provider=vancouver1.voip.ms;country_code=+1;regint=300"
W Baresip : ' to '/data/user/0/com.tutpro.baresip/files/accounts'
W Baresip : Main onStart
W Baresip : uaEvent unregistering did not find ua 536761964960

##
# Last restart
W Baresip : Main onStart
D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4191)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4233)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4615)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4585)] [com.tutpro.baresip.BaresipService.onCreate(BaresipService.kt:130)] [android.app.ActivityThread.handleCreateService(ActivityThread.java:5073)] [android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)] [android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)]
I Baresip : Asset 'accounts' already copied
I Baresip : Asset 'config' already copied

# Extra seems off
# - all new values are gone
# - the nickname is correct but shows in the app empty
# - tel_provider is missing the final letter "s"
#
D Baresip Lib: starting baresip
W Baresip : ********** extra = "nickname=Voip.ms;tel_provider=vancouver1.voip.m
```

**Comment by juha-h** [comment]
So "First start" is not the very first start, since the account already exists?

**Comment by juha-h** [comment]
I cannot reproduce this issue no matter how many times I do restarts.  I backed up my setup (copied from yours) in this file:  `https://box.tutpro.com/tmp/voip.ms.bs`.  Restore that and try to reproduce the issue.  If you can't then try by changing auth user and password to the real ones if that makes any difference.

**Comment by juha-h** [comment]
Thanks for the account sample.  I found the cause of the issue.  Turned out that your account in accounts file is longer than 512 characters.  I created PR to upstream baresip project to increase the max size of an account to 1024 chars. Once merged, I'll create a new version of the app, where the issue should be fixed.

**Comment by arichiardi** [comment]
Oh wow that is good news, trying out right away, that definitely was a weird one

**Comment by arichiardi** [comment]
Is the limit per account or per "accounts"?

If the latter there might still be a problem in case you have many many accounts

**Comment by arichiardi** [comment]
I tried the original account conf (with three accounts) and it works! 

I am thinking a not should be added to the docs because technically this might still happen. Closing for now.
