### ISSUE TITLE
Speaker icon always on

### ISSUE THREAD

**Issue by arichiardi** [juha-h/baresip-studio#332]
Here is the other issue I noticed.

From clean install, with no accounts, the speaker icon is red.

If I toggle it off and quit/restart, it will go back to red.

**Comment by juha-h** [comment]
It may be a bug that affects Android 13, which I don't have. I uploaded a new apk.  Try with that.  There is also debug messages related to communication device changes in logcat.

**Comment by arichiardi** [comment]
Ok will send you logs, still happening with the new apk here.

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> Ok will send you logs, still happening with the new apk here.

Again new apk.  Try with that.  I reverted back to deprecated
functions.

**Comment by arichiardi** [comment]
I think this last apk, or something, fixed it.

Now any apk works actually, even the ones before the latest. Weird, it seems what you did there reset some internal state here.

Closing cause it is effectively solved.
