### ISSUE TITLE
Cmake error in android studio baresip project

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#333]
I am getting error when i want to run the imported project (baresip studio)

CMake Error at CMakeLists.txt:20 (find_package):
Could not find a package configuration file provided by "re" with any of
the following names:

reConfig.cmake
re-config.cmake
Add the installation prefix of "re" to CMAKE_PREFIX_PATH or set "re_DIR" to
a directory containing one of the above files. If "re" provides a separate
development package or SDK, be sure it has been installed.

If you aware of this error please reply

Thanks in Advance.

**Comment by juha-h** [comment]
You have to first build and install the libraries as README tells.
