### ISSUE TITLE
Adaptive Icon for Themed Icon Support?

### ISSUE THREAD

**Issue by githububub** [juha-h/baresip-studio#336]
Are there plans to provide an [adaptive icon](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) to support Android 13 themed icons? The contrast of the current baresip icon against a dark mode background with a palette of darkened themed icons can be somewhat high.

**Comment by juha-h** [comment]
No plans yet and I don't have Android 13 device to test them.  If you know how to do it, please create a PR.   I'll add adaptive icon support to Feature Requests in the Wiki.

**Comment by juha-h** [comment]
Can you try with this: https://box.tutpro.com/tmp/baresip.apk?  It should have adaptive launcher icon, but I have no Android 13 device to test.

If you try the apk, first backup your baresip.

**Comment by arichiardi** [comment]
I tried it, here is how I see it - seems good!

![Screenshot_20230318_143258_Finder](https://user-images.githubusercontent.com/1724788/226109350-5731905f-810e-4b08-b964-dd24c7774195.jpg)

**Comment by juha-h** [comment]
Andrea Richiardi writes:

> I tried it, here is how I see it - seems good!

Thanks for testing.  I'll merge it to master.

**Comment by juha-h** [comment]
Should be done now by commit https://github.com/juha-h/baresip-studio/commit/95ab3739dbaf86416d55f10f15d12a05139a48ba.

**Comment by juha-h** [comment]
Try when version > 52.2.0 becomes available and open again if monochrome icon does not work.

**Comment by githububub** [comment]
Monochrome icon does not appear to work. Pixel 7. Update from 52.2,0 and new install of 53.0.0...

![baresip-53 0 0-homescreen](https://user-images.githubusercontent.com/20338556/227801875-478da2b2-4a58-459c-8552-6c0a9369c8bc.png)

**Comment by juha-h** [comment]
GitHububub writes:

> Monochrome icon does not appear to work. Pixel 7. Update from 52.2,0
> and new install of 53.0.0...

My device (Galaxy A04) just got Android 13 update.  How can I turn on
monochrome mode for testing?

**Comment by juha-h** [comment]
GitHububub writes:

> Monochrome icon does not appear to work. Pixel 7. Update from 52.2,0
> and new install of 53.0.0...

On my A04 device, I turned on Developer Options -> Simulate color space
-> Monochromacy and baresip launcher icon was gray on white background.

**Comment by githububub** [comment]
On GrapheneOS, the toggle is under: Settings > Wallpaper & style > Themed icons. Also tested on Pixel 6 GrapheneOS in additon to Pixel 7...

**Comment by githububub** [comment]
> I think I got monochrome icon working. Can you try if I create a test apk? It is here: https://box.tutpro.com/tmp/baresip.apk.

I apologize for not revisiting this sooner...53.1.1 monochrome icon works as intended!

![baresip-53 1 1-1](https://user-images.githubusercontent.com/20338556/228403011-dfe16183-d871-4975-9991-8bee93bd87c9.png)

![baresip-53 1 1-2](https://user-images.githubusercontent.com/20338556/228403023-371a8ece-a14a-4a22-8e5e-a80b3020b447.png)

![baresip-53 1 1-3](https://user-images.githubusercontent.com/20338556/228403047-c66b8a29-f7c1-4e23-a332-684021937e88.png)

![baresip-53 1 1-4](https://user-images.githubusercontent.com/20338556/228403068-54cb783c-3d27-417b-90ce-9aa5179efb4c.png)

We also tested this around the office on devices on Android 13...No problems! Thank you much!

**Comment by beaglesnuf** [comment]
Mono icon working here as well. Follows the color theme of my wallpaper now.
