### ISSUE TITLE
8.0 add contact asks for full URI

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#34]
...while it should act like calls/chat and, if only a user is written, try to contact them on the same server.

**Comment by juha-h** [comment]
Licaon_Kter writes:

> ...while it should act like calls and if only a user is written then
> try to contact users on the same server.

Do you mean "New Chat Peer" next to plus icon on Chat History page?
If so, I just tested using Account 'bar@test.tutpro.com', and was able to
write there only 'test'.  On the 'Chat with test' page message was sent
to 'sip:test@test.tutpro.com'.

**Comment by licaon-kter** [comment]
No, contact....Name...URI....

**Comment by juha-h** [comment]
Licaon_Kter writes:

> No, contact....Name...URI....

It because contacts are shared among all accounts.  I just pushed commit
that adds account's domain to contact URI if there is only one account.
