### ISSUE TITLE
Share Contact via QR-Code

### ISSUE THREAD

**Issue by mwarning** [juha-h/baresip-studio#340]
It would be nice to be able to share contacts via QR-Code.

Feel free to take this code for baresip-studio:

* https://github.com/meshenger-app/meshenger-android/blob/master/app/src/main/kotlin/d/d/meshenger/QRScanActivity.kt
* https://github.com/meshenger-app/meshenger-android/blob/master/app/src/main/kotlin/d/d/meshenger/QRShowActivity.kt
build.gradle:
```
  implementation('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
  implementation 'com.google.zxing:core:3.4.1'
```

(feel free to take it as the same license that baresip-studio uses)

**Comment by juha-h** [comment]
Moritz Warning writes:

> It would be nice to be able to share contacts via QR-Code.

Sorry, but I don't want to start using third party code in the app.

**Comment by mwarning** [comment]
Ah, you mean the zxing libs? Well, that is something I cannot help with.

**Comment by juha-h** [comment]
Better to use a contact app that has such a feature.

**Comment by juha-h** [comment]
Moritz Warning writes:

> Ah, you mean the zxing libs? Well, that is something I cannot help
> with.

That it is.  Android is very fast moving target and I don't have
resources to start maintaining third party dependencies.

**Comment by mwarning** [comment]
OK. But for the libs I used there I haven't had API changes in the last four year. I only bumped the version number a few times.
