### ISSUE TITLE
SHA-256 Signing Cert Hash for Authenticity?

### ISSUE THREAD

**Issue by beaglesnuf** [juha-h/baresip-studio#343]
Can you provide/verify the SHA-256 signing cert hash for your GitHub releases? We wish to deploy across a range of devices and want to ensure that the APKs we download from GitHub are indeed signed by you as authentic as part of trust-on-first-use MDM deployments. What we have is currently: 

fecc79c20ab725b9b78bb16a75ba9a04092822cf52ba32e4a437170a68020602

Examples of projects with posted signing cert hashes:

![accresent-auth](https://user-images.githubusercontent.com/86446930/227651816-fc02083a-9926-4982-804a-10616ee82c27.png)

![molly-auth](https://user-images.githubusercontent.com/86446930/227652078-50b6dde0-e533-4b48-9a6e-96fafce9c6ff.png)

**Comment by juha-h** [comment]
I added the fingerprint to README.md:

> Ready to be installed baresip app is available from [F-Droid](https://f-droid.org/app/com.tutpro.baresip) and from [GitHub](https://github.com/juha-h/baresip-studio/releases). Signing certificate SHA-256 fingerprint to verify the GitHub APKs is FECC79C20AB725B9B78BB16A75BA9A04092822CF52BA32E4A437170A68020602.

Hope I got it  right.  Can you verify with it?

**Comment by beaglesnuf** [comment]
That works. Maybe enclose the fingerprint as code for legibility, can then perhaps remove the period. It looks fine as is also :) . With [apksigner](https://developer.android.com/studio/command-line/apksigner):

![baresip_auth](https://user-images.githubusercontent.com/86446930/227700674-bf37ef88-3e09-4770-8487-e8ced92fa6fe.png)

![baresip+_auth](https://user-images.githubusercontent.com/86446930/227700683-e78365cd-7f65-4143-9d93-fbe7fc5bc5be.png)

**Comment by juha-h** [comment]
Good, so this issue can now be closed?

**Comment by beaglesnuf** [comment]
Absolutely. Thank you!
