### ISSUE TITLE
53.0.0: Removed icon and text from status notification when Android version is 13+

### ISSUE THREAD

**Issue by githububub** [juha-h/baresip-studio#345]
Is the following what we are supposed to see when the notification shade is pulled down for 53.0.0 on A13?

![baresip-53 0 0-notification-shade](https://user-images.githubusercontent.com/20338556/227802057-1da7e864-5985-4f28-a626-8440e0fa7beb.png)

**Comment by juha-h** [comment]
On my Android 13 device (A04) and on Pixel 7 (emulated), the notification when I wipe down shows the same b icon as in the above and green registration dot (I have one account that has register checked). There is no `baresip xm` text, which I guess is produced by your version of Android.  It is as intended.

**Comment by juha-h** [comment]
Just  to add, before Android 13, there was no b icon produced automatically by Android.  That is why baresip app produces b image followed by baresip text if Android version is < 13.  I felt that in Android 13, the automaticallt produced b icon is enough and baresip app adds just the registration status dots after it.

**Comment by githububub** [comment]
OK. Let me test this again...One account is indeed checked register, but no green registration dot appears.

**Comment by juha-h** [comment]
Perhaps your `baresip . Xm` overwrites the registration dot.  That text should not be there.  Try with some other device.

**Comment by juha-h** [comment]
I played again with the emulator.  When I started baresip, notification with registration dot was briefly shown and then only the same pull down notification as what you showed in the above.  Perhaps Google does not allow more information in the pull down notification.  On my Galaxy A04, the registration dots are always included in the pull down notification.

**Comment by juha-h** [comment]
In Pixel 7 emulator, full content of the notification is shown only briefly whenever baresip updates the notification.  After that the pull down notification only shows baresip icon followed by time.

As I mentioned earlier, perhaps Google has decided to do it that way and the behavior cannot be changed.  My Galaxxy A04 (Android 13) shows the full notification context also in the pull down notification.

**Comment by githububub** [comment]
> In Pixel 7 emulator, full content of the notification is shown only briefly whenever baresip updates the notification. After that the pull down notification only shows baresip icon followed by time.

The behavior on our A13 devices is exactly as you described: Full notification is shown briefly before the notification shade only shows the baresip icon and time.

**Comment by juha-h** [comment]
In Pixel 4 Android 13 emulator, pull down notification does include the registration dots: [https://box.tutpro.com/tmp/pixel_4_shot.png](url).

I have not found anything in Android developer foreground notification docs that I could do to make the pull down notification show the true content of the notification in Pixel 7 or your A13 like it does with Pixel 4 and my A04.

Ask Google or Samsung why only the icon and app name are shown.

**Comment by juha-h** [comment]
@githububub Could you try with this: https://box.tutpro.com/tmp/baresip.apk. I changed the way content is added to the notification.  In app's notification settings, you can choose at Default level whether to Minimize the notification to one line or not.

**Comment by githububub** [comment]
Works, though we did not notice the option to minimize to one line in the baresip notification settings: Was the same as before: Default/High/Medium/Allow notification dot. That would be fantastic, having the notification default to one line at all times (and with a flat icon vs gradient to match the Material look :smile:)

![baresip-notification-1](https://user-images.githubusercontent.com/20338556/228872888-8720c165-c765-454d-b041-3ece86c47cc7.png)

![baresip-notification-2](https://user-images.githubusercontent.com/20338556/228872927-eaeab2bf-9ed6-4964-8221-80808bb95234.png)

**Comment by juha-h** [comment]
In Pixel 7 emulator, when I touch baresip app's Default notification level, page appears where I can choose to "Minimize notifications".  Don't you have that?

**Comment by githububub** [comment]
Indeed we do; however minimize notifications results in the notification appearing as 'baresip icon + time' vs 'baresip icon + registration status icon'.

**Comment by juha-h** [comment]
In Pixel 7 emulator (Android 13) with minimize on: 'baresip icon + time'.  Reg dots are shown under it after touching v. After touching ^, 'baresip icon + time'.

In Pixel 7 emulator with minimize off: 'baresip icon + time'.  Reg dots are shown under it without touching anything.  After touching ^, 'baresip icon + reg dots'.

In A04 (Android 13) with minimize on: 'baresip icon + time'.  Reg dots are shown under it after touching v. After touching ^, 'baresip icon + time'.

In A04 with minimize off: 'baresip icon + reg dot'.  'baresip icon + time' and reg dots are shown under it after touching v. After touching ^, 'baresip icon + reg dots'.

So "minimize off" behavior is not the same in Pixel 7 and A04.

In Nokia 3.1 (Android 10), 'baresip icon + baresip text + time' and reg dots under it.

Is it OK to close this issue now?

**Comment by githububub** [comment]
Absolutely. Appreciate the work you put into baresip.

**Comment by juha-h** [comment]
> Works, though we did not notice the option to minimize to one line in the baresip notification settings: Was the same as before: Default/High/Medium/Allow notification dot. That would be fantastic, having the notification default to one line at all times (and with a flat icon vs gradient to match the Material look smile)

@githububub Latest release 53.2.0 replaced several icon images with material design vecrot drawables.

**Comment by Rstment25** [comment]
> @githububub Latest release 53.2.0 replaced several icon images with material design vector drawables.

![Screenshot_20230408-125703_Trebuchet](https://user-images.githubusercontent.com/32986283/230717533-30f45a59-3827-4346-88ef-fd3aeebdf568.png)

I've just received the update but it doesn't look like changes have any effect? Android 12 btw
