### ISSUE TITLE
baresip+ app-symbols

### ISSUE THREAD

**Issue by skyballl** [juha-h/baresip-studio#353]
Hello Juha,
first of all: Great Job!
Could you please explane the meaning of the Symbols at the top and bottom?
Thank you!
![1](https://user-images.githubusercontent.com/130644168/231691713-854aac7d-4310-4d04-bcc0-0dbb4d658995.jpeg)
![2](https://user-images.githubusercontent.com/130644168/231691760-81e33b0d-6eca-4e3c-8db6-542a6ba6ea96.jpeg)

**Comment by tomo90** [comment]
Bottom row of symbols starting from left: Contact list (just baresit, Android, both - you can choose the mode in the Settings) - Chat history (messages) - Call history - Switches between numeric / alphanumeric keyboard (writing messages, dialing phone number)

Top row of symbols starting from left: This one I'm actually not sure, what i does. It's some king of recording (recording of what??) - Microphone mute - Switches loudspeaker on your phone on/off - baresip menu (Settings, Accounts, etc.)

**Comment by tomo90** [comment]
Even though the recording feature is not fully completed it still works quite well. :) Maybe I'll explain how it works for others as well, it's not entirely clear at first.

1. Click the call history on the homepage.
2.  When date / time indicator is highlighted in bold, there is some recordings of the call. Tap the date/time to show details (pic. no. 1).
3. Calls that have the duration highlighted in bold are actually recorded and taping the duration plays the recording (pic. no. 2).


![i_view64_W66BiKkyLl](https://user-images.githubusercontent.com/1255345/231759912-04ed7503-e3fb-438d-bb6e-6d5b493e0bd3.png)

![i_view64_jeP0ivsE23](https://user-images.githubusercontent.com/1255345/231760529-3e83f714-02bb-4aea-87c0-6ff3e09848a9.png)

**Comment by juha-h** [comment]
I created Wiki page https://github.com/juha-h/baresip-studio/wiki/Icons that lists baresip apps' icons (not complete yet).

**Comment by skyballl** [comment]
> I created Wiki page https://github.com/juha-h/baresip-studio/wiki/Icons that lists baresip apps' icons (not complete yet).

This is the best solution.
Thx

**Comment by uvok** [comment]
Could you also add a "tooltip" help when the icon is "long tapped"?

**Comment by skyballl** [comment]
Sorry, I can't use baresip+ anymore.

**Comment by juha-h** [comment]
Yes, tooltip on icons would be best solutionl, but that would introduce lots of new string to the app and I would feel pity for the translators.
