### ISSUE TITLE
Get the dialed number in baresip

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#354]
I am using freepbx in that i have 2 extensions one is registered with eyebeam and another one registered with baresip app which the android studio builded successfully and i can make calls between the 2 extensions. Here what i want is whatever the number i typed in eyebeam softphone that should be reflect in baresip app in the textview field where the call is about to place or when receiving the incoming call the number is displayed in the field i want to replace that with the dialed number that should reflect in textview field. 

Is there any method that u wrote to get dialed number in eyebeam that should reflect in baresip not the registered number (account)?

**Comment by juha-h** [comment]
I'm not sure that I understood what you want to do, but when call comes in and From URI is found in contacts, name of contact is shown instead of From URI or userpart of From URI.  So perhaps adding a suitable contact would help.

**Comment by AviWA** [comment]
I am making a call from 999 extension (eyebeam softphone) to 123 (baresip app) extension whatever the number typed in 999 and hit enter it is placing a call to 123 in baresip app when there is an incoming call the textfield is filled with 999 (registered account in eyebeam softphone) but what i want is if i typed 1001 it is placing the call from 999 to 123 i want to reflect 1001 in textfield 

https://user-images.githubusercontent.com/123717548/232184678-5ed4dc42-dd40-47d4-9ab2-063493d22a21.PNG

in this photo the softphone is eyebeam i am making the call with a number which is in the image i want that should reflect in baresip app.

**Comment by juha-h** [comment]
I still don't understand.  Is the call forwarded and you want to see
the call coming from the forwarder instead of the caller?

**Comment by AviWA** [comment]
yes. Did u wrote the code for that in your app?

**Comment by juha-h** [comment]
AviWA writes:

> yes. Did u wrote the code for that in your app?

Call forwarder is not currently show.  Take trace of the INVITE request
and show how it looks like.

**Comment by AviWA** [comment]
Understood. I am trying to develop sip to whatsapp call.

**Comment by AviWA** [comment]
Is it possible display the forwarded number in baresip?

**Comment by juha-h** [comment]
Actually, I just tested and baresip app does show the diverter when INVITE request has Diversion or History-Info header that contains SIP URI of the diverter.

**Comment by AviWA** [comment]
to do this what i have to change in the code

**Comment by juha-h** [comment]
I don't have resources to advice on how to modify my app.  Currently baresip app does display the diverter if INVITE request has Diversion or History-Info header.  You have not shown how the incoming INVITE looks like and thus I have no way tell why you don't see the diverter.

**Comment by AviWA** [comment]
In main activity at the line of 2003 i am setting the diverter uri but i am getting nothing (blank) at autocompletetextview.

I am trying to set diverter at this line 

callUri.setText(Utils.friendlyUri(this, call.peerUri(), ua.account)) changing to 

callUri.setText(Utils.friendlyUri(this, call.diverterUri(), ua.account)) when replacing with this i am getting blank at textview field.

Where can i find History-Info header to get the diverter uri?

**Comment by juha-h** [comment]
As I already wrote, I don't have resources to advice how to modify my baresip app.  You need to study SIP and baresip library to figure things up.
