### ISSUE TITLE
Error while compiling APK

### ISSUE THREAD

**Issue by mwadudjar** [juha-h/baresip-studio#355]
How can i fix this issue?

[CXX1429] error when building with cmake using /Users/admin/Downloads/softphone-bs/app/src/main/cpp/CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/admin/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/admin/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/Users/admin/Downloads/softphone-bs/app/.cxx/Debug/70466c5b/arm64-v8a/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    /Users/admin/Library/Android/sdk/cmake/3.22.1/bin/cmake \
      -H/Users/admin/Downloads/softphone-bs/app/src/main/cpp \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=23 \
      -DANDROID_PLATFORM=android-23 \
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
      -DANDROID_NDK=/Users/admin/Library/Android/sdk/ndk/25.1.8937393 \
      -DCMAKE_ANDROID_NDK=/Users/admin/Library/Android/sdk/ndk/25.1.8937393 \
      -DCMAKE_TOOLCHAIN_FILE=/Users/admin/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/Users/admin/Library/Android/sdk/cmake/3.22.1/bin/ninja \
      "-DCMAKE_C_FLAGS=-DHAVE_INTTYPES_H -lstdc++" \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/admin/Downloads/softphone-bs/app/build/intermediates/cxx/Debug/70466c5b/obj/arm64-v8a \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/admin/Downloads/softphone-bs/app/build/intermediates/cxx/Debug/70466c5b/obj/arm64-v8a \
      -DCMAKE_BUILD_TYPE=Debug \
      -B/Users/admin/Downloads/softphone-bs/app/.cxx/Debug/70466c5b/arm64-v8a \
      -GNinja \
      -DANDROID_STL=c++_shared
  from /Users/admin/Downloads/softphone-bs/app
CMake Error at CMakeLists.txt:20 (find_package):
  Could not find a package configuration file provided by "re" with any of
  the following names:

    reConfig.cmake
    re-config.cmake

  Add the installation prefix of "re" to CMAKE_PREFIX_PATH or set "re_DIR" to
  a directory containing one of the above files.  If "re" provides a separate
  development package or SDK, be sure it has been installed.

**Comment by juha-h** [comment]
Have you built and installed libbarresip-android libraries?  They should be in distribution directory.

**Comment by mwadudjar** [comment]
> Have you built and installed libbarresip-android libraries? They should be in distribution directory.

Thanks for the reply, I had not build and installed the library yet. But when I do so I get a bunch of errors such as npproc command not found.

Is it possible to make this build with android studio and Mac OS m1? Or only with Debian 11?

**Comment by juha-h** [comment]
The libs need to be build separately.  It cannot be done using Android Studio.

I'll close this issue, since I don't have knowledge nor interest with builds in any other environment than Debian 11.

Also F-Droid is able to build the apk as you can see, for example, here: https://monitor.f-droid.org/builds/log/com.tutpro.baresip/277#site-footer.  So there is nothing wrong with the documented build process.
