### ISSUE TITLE
baresip+ -Can't login to my account since 41.3.0

### ISSUE THREAD

**Issue by tomo90** [juha-h/baresip-studio#358]
the non plus baresip version works fine

Invalid argument [22]
![Screenshot_20230419-132301_baresip+_1](https://user-images.githubusercontent.com/1255345/233090928-8be2895d-0bc1-4850-a171-127a1e5d86d4.png)

**Comment by juha-h** [comment]
Thanks for reporting.  Android Studio made wrong simplification and DNS servers were not properly configured.  This is now fixed in version 42.0.2.
