### ISSUE TITLE
Low Contrast in Confirmation

### ISSUE THREAD

**Issue by githububub** [juha-h/baresip-studio#359]
Blue on dark gray. See attached. 55.0.1.
![baresip](https://user-images.githubusercontent.com/20338556/233217038-c8754ac3-51df-4515-b656-f0e8cc6b14e8.png)

**Comment by juha-h** [comment]
Thanks for the suggestion.  Fixed by https://github.com/juha-h/baresip-studio/commit/d605707198800076c6b49e3b26362e92a2a9e07c.

**Comment by githububub** [comment]
The blue remains relatively low contrast, but is an improvement over what was before.

![baresip-contrast](https://user-images.githubusercontent.com/20338556/233713530-92a21989-549c-49c1-b49a-efd53ae68f6a.png)

**Comment by juha-h** [comment]
Commit https://github.com/juha-h/baresip-studio/commits/master made the blue text lighter.  It now is #0ca1fd and if I understand correctly, background is #424242.  Resulting contrast ratio now is 3.60 : 1, which is better than before.  In dark theme, I would not like to make the blue text any more lighter.
