### ISSUE TITLE
Call to trunk in Baresip

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#363]
I am using freepbx server which i can make calls from extension to trunk which is registered with baresip app but the app cant receive calls baresip is rejecting the calls even the trunk is registered. I want to make the app to receive the calls via trunk registered.

**Comment by juha-h** [comment]
AviWA writes:

> I am using freepbx server which i can make calls from extension to
> trunk which is registered with baresip app but the app cant receive
> calls baresip is rejecting the calls even the trunk is registered. I
> want to make the app to receive the calls via trunk registered.

Sorry, but I don't understant what you want to do and what the problem
is.  You need to give your baresip account configuration and sip trace
of the call that fails.

**Comment by AviWA** [comment]
I am using freepbx sip server in that we can create trunks we can register trunks with sip clent apps i also did the trunk registration with baresip app which can sip server can route all calls to trunk but baresip is rejecting not even receiving the calls

**Comment by juha-h** [comment]
AviWA writes:

> I am using freepbx sip server in that we can create trunks we can
> register trunks with sip clent apps i also did the trunk registration
> with baresip app which can sip server can route all calls to trunk but
> baresip is rejecting not even receiving the calls.

See https://github.com/juha-h/baresip-studio/wiki/Reporting-Issues.  I
cannot help without a debug log that includes SIP Trace of the
registration and calls.

**Comment by AviWA** [comment]
I gave the credentials all are correct but no other device registered to the trunk (123) but the app is not able to register here is the log of the app

https://user-images.githubusercontent.com/123717548/235880321-f171db44-1e00-4140-92fd-bd0e62c3bffc.PNG

**Comment by juha-h** [comment]
You need to check from FBPX logs why registering failed.    There can be man reasons, for example, sip uri of the user agent is not correct, authentication username or password is not correct, transport protocol is not correct, etc.  Enable SIP Trace and compare the failing register request to a working one from some other SIP app.

**Comment by AviWA** [comment]
but the trunk can be able to register successfully with eyebeam client app and i can make able to calls to eyebeam with the trunk registration.

**Comment by juha-h** [comment]
AviWA writes:

> but the trunk can be able to register successfully with eyebeam client app and i can make able to calls to eyebeam with the trunk registration.

If eyebeam is able to register, do as I wrote, compare the register
requests.  Also check from your PBX logs, why baresip register fails.
It must tell something.  If not, your PBX is a very bad one.

**Comment by AviWA** [comment]
i dont think how that happens bcoz no other device was registered to the trunk. Do u have any solution for that?

**Comment by juha-h** [comment]
No I don't.  I don't know anything about your PBX.  Ask from the forum of the PBX.  Also, compare the request with a succeeding registration from somewhere else.

**Comment by juha-h** [comment]
I'll close this since it is not an issue with baresip.  When baresip registers, it includes unique instance id of the user agent in Contact header:
```
Contact: <sip:test-0x55ca015c3520@192.168.188.215:5020;transport=tcp>;expires=600;+sip.instance="<urn:uuid:a1f48cf9-ba57-e0f4-b53b-9132ec31214b>";reg-id=1
```
From that the registrar learns if the same user agent has existing active registration can can remove the old one.
