### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Rstment25** [juha-h/baresip-studio#367]
Could you add an option to record calls?

Also if it's not a problem can you explain to me what these buttons do?  Microphone I guess works like a mute button , and the one before mic should be like speakerphone?
![IMG_20230509_211426](https://github.com/juha-h/baresip-studio/assets/32986283/f119f54b-3ebf-45f4-98b6-8ad343273580)

And are they active when they turn red?

Thanks

**Comment by juha-h** [comment]
See Wiki Ions page.  Yes, they are active when red.  There already exists basic support of call recording.
