### ISSUE TITLE
Call log statuses (arrows) fine grained [enhancement]

### ISSUE THREAD

**Issue by osering** [juha-h/baresip-studio#369]
Hi!

There are 6 possible outcomes of voice calls:

Outgoing:
(1) Answered
(2) Missed / Not answered
(3) Rejected/Dropped/Dismissed

Incoming:
(4) Answered (green button pressed)
(5) Missed / Not answered (no button pressed)
(6) Rejected/Dropped/Dismissed (red button pressed)

These are usually shown by small icons (colored arrows, straight or broken) in most dialers' "Call log".

In Baresip so far I noticed just 4 types (not all 6 covered) of icons: 
Green and red arrows up(load) and down(load)

### **Why not to design Baresip's' call log more fine grained and effective?**
Technically it should not be too hard to differentiate these 6 conditions (even closed source Zoiper has it more advanced right now). Could be used 3rd color arrows up and down.

For example, call log in carefully crafted True Dialer (Android, com.hb.dialer.free) looks::
![truephone](https://github.com/juha-h/baresip-studio/assets/62410690/606d7156-13c0-4a18-8951-5ef93fb2686a)

**Comment by juha-h** [comment]
When outgoing call fails, which SIP response codes https://en.wikipedia.org/wiki/List_of_SIP_response_codes would mean (2) Missed / Not answered and which (3) Rejected/Dropped/Dismissed?

**Comment by juha-h** [comment]
Perhaps the only responses to outgoing call that would go to your
(2) Missed / Not answered category are

21.4.18 480 Temporarily Unavailable
21.4.9  408 Request Timeout

Rest non-200 responses would to your (3) Rejected/Dropped/Dismissed
category.

**Comment by juha-h** [comment]
I played with the three way call call history and used yellow straight arrays (up and down) when call failed, but was was not rejected, i.e., when call failed due to no answer.  Straight arrow looked less confusing that the bounce arrow.

I created https://box.tutpro.com/tmp/baresip.apk if you want to give it a try.

**Comment by juha-h** [comment]
Implemented in 56.1.0.
