### ISSUE TITLE
unable to build on AS Flamingo

### ISSUE THREAD

**Issue by tbswork1** [juha-h/baresip-studio#372]
Sync gradle failed in Android Studio Flamingo with the following error:

```
No variants found for ':app'. Check build files to ensure at least one variant exists. at:
com.android.tools.idea.gradle.project.sync.AndroidModule.prepare(GradleModules.kt:266)
  com.android.tools.idea.gradle.project.sync.SyncProjectActionWorker.populateAndroidModels(SyncProjectActionWorker.kt:99)
```

**Comment by juha-h** [comment]
tbswork1 writes:

> Sync gradle failed in Android Studio Flamingo with the following
> error:

Sorry, I'm not Android Studio export and can't help.  Sync and build
work for me.  You need to ask some other forum.

**Comment by juha-h** [comment]
I'm using latest Giraffe.  Try with that.

**Comment by tbswork1** [comment]
I move to Linux (Ubuntu) to build and this problem doesn't show up anymore.
