### ISSUE TITLE
Connect 2 domains in the app

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#373]
I want to connect to sip server to receive the call and place the call with another domain.

Ex: I have registered with 123@192.168.1.10 which can be able to receive and make calls but i need to connect this 123@192.168.1.10 to another sip server address (123@192.168.2.20 ) at the same time.

Do u have any solution for this?

**Comment by juha-h** [comment]
AviWA writes:

> I want to connect to sip server to receive the call and place the call
> with another domain. 
> 
> Ex: I have registered with ***@***.*** which can be able to
> receive and make calls but i need to connect this ***@***.*** to
> another sip server address ***@***.*** ) at the same time.

I don't understand what you mean by "connect".  I you have not specified
an outbound proxy, each request is sent to hostpart of Request-URI.

**Comment by AviWA** [comment]
That means i need merge the 123@192.168.1.10 and 456@192.168.2.20 which these 2 are sip server address that we can able to register and make calls i need to make a call from 123@192.168.1.10 to 456@192.168.2.20. I know how to do this in asterisk and freepbx but i need to make this in an app.

**Comment by juha-h** [comment]
AviWA writes:

> That means i need merge the ***@***.*** and ***@***.***
> which these 2 are sip server address that we can able to register and
> make calls i need to make a call from ***@***.*** to
> ***@***.*** I know how to do this in asterisk and freepbx but i
> need to make this in an app.

In baresip you can make a call from 123 to ***@***.*** by writing
***@***.*** to callee field and touch the call icon.

**Comment by juha-h** [comment]
Show what comes to logcat (see Wiki Debugging).

**Comment by AviWA** [comment]
https://github.com/juha-h/baresip-studio/files/11485459/logcat.txt

logs when dialing

**Comment by AviWA** [comment]
I am trying to make call to 919123456789@s.whatsapp.net from the registered sip server i need to merge the sip call and whatsapp call

**Comment by juha-h** [comment]
Call fails because domain `s.whatsapp.net` does not exist.
```
2023-05-16 03:59:27.608  2241-2368  Baresip Lib             com.tutpro.baresip                   D  sending ua/call -54**************664/-5476376618474960128 event call closed,Destination address required [89],
```

**Comment by AviWA** [comment]
It is used by whatsapp to identify the members i already installed whatsapp does not exist means that we have to provide this inside of the code ?

**Comment by AviWA** [comment]
to merge the call

**Comment by juha-h** [comment]
baresip can only make calls to existing IP addresses or existing domains.  [s.whatsapp.net](mailto:919123456789@s.whatsapp.net) is not either.
