### ISSUE TITLE
Installed on s21ultrs crashes immediately upon opening. 

### ISSUE THREAD

**Issue by Infamous222** [juha-h/baresip-studio#377]

**Comment by juha-h** [comment]
Please read https://github.com/juha-h/baresip-studio/wiki/Reporting-Issues and provide more information.  What is s21ultrs?

**Comment by Infamous222** [comment]
Sorry. Samsung Galaxy S21 Ultra 5G smart phone.

**Comment by juha-h** [comment]
Still no information about Android version.

**Comment by juha-h** [comment]
Could the issue be the same as this https://github.com/juha-h/baresip-studio/issues/385?
