### ISSUE TITLE
Forward sip request call to new event

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#381]
Your app is working excellent first of all thanks for that. 

Will you help me forward the sip request call to a new event new Voip call to a particular destination URI when there is an incoming call.

I want to do when I receive an incoming call the call should be automatically forward to the new event a new Voip to a particular destination URI. I have done some changes to do this in baresip.c file ua_event_call_incoming case but no use.

**Comment by juha-h** [comment]
There is two ways for SIP UA to forward call:

1) UA answers the INVITE and then sends REFER to the caller
2) UA responds to INVITE with 302 Moved Temporarily

Which one do you want to use?

**Comment by AviWA** [comment]
The first one UA answers the INVITE and then sends REFER to the caller.

**Comment by juha-h** [comment]
AviWA writes:

> The first one UA answers the INVITE and then sends REFER to the
> caller.

Currently that requires the callee to manually do blind transfer after
answering the call.

**Comment by juha-h** [comment]
`302 Moved Temporarily` would be easier to implement, but it would require quite a bit of new code.  `Forward URI` and `Forward Mode` items would need to be added to account configuration.  Possible `Forward Mode` choices would be `Inactive`, `Unconditional`, `Unavailable`, `Busy` and  `No Answer`.   There has not been much interest or need for such feature, because the same is usually implemented in SIP Proxy or PBX.

**Comment by AviWA** [comment]
Then what about baresip.c file cant it help to forward the call if we do any changes or addition of code.

ok can u tell me how to do this 302 Moved Temporarily and adding code to account configuration.

**Comment by juha-h** [comment]
You would need to add Contact header to the response and then call ua_hangup. I don't know if baresip lib currently supports adding of headers to response.

**Comment by AviWA** [comment]
if i do any changes at ua_event_call_incoming event it is getting error at baresip service at onStartCommand- baresipStart(filesPath, addresses.removePrefix(";"), logLevel).

This is the code : 
https://github.com/juha-h/baresip-studio/files/11597852/codes.txt


I am unable to find send requests and receiving response code.

**Comment by juha-h** [comment]
Nothing can be done before this PR https://github.com/baresip/baresip/pull/2596 is merged.

**Comment by AviWA** [comment]
There is no call.c or .c files in android studio except baresip.c how can we edit those files

**Comment by juha-h** [comment]
AviWA writes:

> There is no call.c or .c files in android studio except baresip.c how
> can we edit those files

They are in libbaresip.

**Comment by AviWA** [comment]
I have added the suggested lines in libbaresip and baresip filesbut I am getting error of ua_redirect method in baresip.c not with parameters this is the code i have added and error are in the text file 

https://github.com/juha-h/baresip-studio/files/11643379/codes.txt

**Comment by juha-h** [comment]
My new `ua_redirect` API function was not accepted to baresip lib.  So this feature cannot be implemented.  Use some other SIP UA.
