### ISSUE TITLE
Immediately crashing after launching, PixelOS

### ISSUE THREAD

**Issue by officialpiyush** [juha-h/baresip-studio#385]
The application immediately crashes after launching after the necessary permissions are given. 

Device Configuration:
Model: Redmi Note 9 Pro Max
OS: PixelOS
Android Version: 13
App Version: 57.1.0

Debug Log URL: https://bin.kv2.dev/~6489cf8ce599576ea02cac8c

**Comment by officialpiyush** [comment]
#377 might be related to this issue

**Comment by juha-h** [comment]
Piyush Bhangale writes:

> The application immediately crashes after launching after the
> necessary permissions are given.
> 
> Device Configuration:
> Model: Redmi Note 9 Pro Max
> OS: PixelOS
> Android Version: 13

Which version of baresip app?

**Comment by officialpiyush** [comment]
I've mentioned it in the issue description, it's 57.1.0

**Comment by juha-h** [comment]
Your log has:
```
Caused by: java.lang.SecurityException: Settings key: <ringtone2> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
```
That error comes from here:
```
val rtUri = RingtoneManager.getActualDefaultRingtoneUri(applicationContext,
                RingtoneManager.TYPE_RINGTONE)
        rt = RingtoneManager.getRingtone(applicationContext, rtUri)
```
That is the correct way to get default ringtone.  This issue is not related to baresip, but to your platform.  See this:
```
https://forum.xda-developers.com/t/exists-rom-pixel-experience-for-redmi-note-10s.4381201/#post-88184535
```
