### ISSUE TITLE
baresip+ no longer switches seamlessly between WiFi and mobile networks

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#387]
baresip+ 44.1.0 on a 
Pixel 3 running
CalyxOS 4.10.1 (AOSP 13)

When I'm at home, baresip+ registers and communicates via WiFi. It used to be that when I wandered away from my WiFi AP, baresip+ would automatically switch to the mobile network, and back again to WiFi when I returned home. It doesn't any more.

Now, when I leave home, baresip+ loses registration (the idiot light goes yellow) and I have to restart the app to register again. When I return home baresip+ loses registration (the light goes yellow), presumably because things switched over to WiFi. Again, I have to restart baresip+ to register with my provider.

I'm sure I'm waiting long enough, too. I usually forget to restart it until I want to use baresip+ and find I have to restart it because I've changed networks as above.

**Comment by juha-h** [comment]
Thanks for reporting.  I think I found the bug and fixed it by commit https://github.com/juha-h/baresip-studio/commit/f15f881d62bc11112b119e177f455088f2f94877.  Will create a new version soon.

**Comment by juha-h** [comment]
The fix is included in baresip+ 44.1.1.
