### ISSUE TITLE
Audio input from wired headphones

### ISSUE THREAD

**Issue by gibix** [juha-h/baresip-studio#395]
Hello, thank you for your project.

## Device

Android version: 10
Baresip version: 57.1.1

## Step to reproduce

Make a call with wired headphone with microphone plugged in

## Description

The sound output is correctly routed to the headphone, but the mic still comes from the one integrated on the phone. The headphone correctly works on the same device with other apps. I think that there is the same bug on the bluetooth.

**Comment by juha-h** [comment]
I tested with my Sangsung A04 device running Android 12 by calling thetestcall with wired headset and echo test showed that both audio input and output were routed via the headset. Same with bluetooth headset. 

Then I tested with Nokia device running Android 10, and noticed the same as you, i.e., phone mic was used even when wired headset was connected.  But with bluetooth headset both bluetooth mic and speaker were used.

Can you try with a bluetooth mic/speaker device?

**Comment by gibix** [comment]
Yes I confirm that is the same with bluetooth, the speaker works well but the microphone is still the onboard one.

**Comment by juha-h** [comment]
On my Samsung A04 device, when I connect wired headphone, I see this in logcat:
```
7-24 17:58:00.219   956  1081 D AudioALSAHardwareResourceManager: +stopInputDevice(), mInputDevice = 0x80000004, stop_device = 0x80000004, mStartInputDeviceCount = 1, mMicInverse = 0, mNumPhoneMicSupport = 2
07-24 17:58:00.219   956  1081 D AudioALSADeviceConfigManager: ApplyDeviceTurnoffSequenceByName(), DeviceName = builtin_Mic_DualMic descriptor->DeviceStatusCounter = 1
07-24 17:58:00.219   956  1081 D AudioALSACaptureDataClientAurisysNormal: DestroyAurisysLibManager()
07-24 17:58:00.219   956  1081 D aurisys_lib_handler: aurisys_arsi_destroy_handler(), lib_name mtk_speech_enh, 0xeed17a80, arsi_destroy_handler, arsi_handler = 0xe9b65440, retval = 0
07-24 17:58:00.219  2651  2651 V QsExpandAnimator: updateBarAnimator
07-24 17:58:00.219  2651  2651 V QsExpandAnimator: setQsExpansionPosition 0.0
07-24 17:58:00.219  2651  2651 V QsExpandAnimator: onAnimationAtStart
07-24 17:58:00.220   956  1081 D aurisys_lib_manager: delete_aurisys_lib_manager(), manager 0xeea8f540
07-24 17:58:00.221   956  1081 D AudioALSACaptureHandlerNormal: -close()
07-24 17:58:00.221   956  1081 D AudioALSAStreamIn: closeWavDump()
07-24 17:58:00.221   956  1081 D AudioUtility: power_hal_hint - custPowerHint 37, data 0
07-24 17:58:00.221   956  1081 E AudioALSAStreamManager: routingInputDevice(), ptr is NULL!!
07-24 17:58:00.221   956  1081 D AudioALSAStreamIn: routing(), is_lock_in_this_function = true
07-24 17:58:00.221   956  1081 D AudioALSAStreamIn: +routing(), streamin(0x0) is standby, update mStreamAttributeTarget.input_device = 0x80000010
07-24 17:58:00.221   956  1081 D AudioALSAStreamIn: -routing(), this = 0xedf0c100, index = 1438
```
So Android is automatically turning off builtin mic device 0x80000004 and routes audio input through device  0x80000010, whichi is the wired headset mic.

And when I disconnect wired headset, Android automatically changes input device back to builtin mic device 0x8000000:
```
07-24 18:09:32.405   956  1081 D AudioALSAHardwareResourceManager: +stopInputDevice(), mInputDevice = 0x80000010, stop_device = 0x80000010, mStartInputDeviceCount = 1, mMicInverse = 0, mNumPhoneMicSupport = 2
...
07-24 18:09:32.412   956 21162 D AudioALSAStreamManager: +createCaptureHandler(), mAudioMode = 3, input_source = 1, input_device = 0x80000004, mBypassDualMICProcessUL=0, rate=16000, flag=0x0
```
There is no baresip app code involved here.  Perhaps in earlier Android versions of some vendors the switching does not happen automatically.

**Comment by juha-h** [comment]
I re-tested with my Nokia 3.1, which is running pure Android 10 and also with that audio input device was automatically changed from built-in mic to wired headset mic, when the latter was connected:
```
07-25 11:10:21.784  2292 25172 D AudioALSACaptureDataProviderBase: configStreamAttribute(), audio_mode: 3 => 3, input_device: 0x80000004 => 0x80000010, flag: 0x0 => 0x0, input_source: 1->1, output_device: 0x4 => 0x4, DSP out sample_rate: 16000 => 16000
```
So it works on my devices without any baresip related code.  Sorry, but I don't have more time to spend on this.
