### ISSUE TITLE
Unencrypted connection possible?

### ISSUE THREAD

**Issue by toby63** [juha-h/baresip-studio#396]
I have a router which allows an IP telephone connection.

But the domain is a local domain and I guess it is unencrypted. The Wlan is of course encrypted, so the provider seems to think thats enough.

Now I can't seem to be able to connect with baresip+, other SIP clients, such as sipdroid worked.

**Comment by juha-h** [comment]
You can choose in account configuration which protocol is used for SIP
signaling and media.  Choose one that does not use encryption,

**Comment by juha-h** [comment]
I don't think that this is an issue related to baresip.
