### ISSUE TITLE
DTMF not identified by the recipient

### ISSUE THREAD

**Issue by arichiardi** [juha-h/baresip-studio#397]
Hi @juha-h,

I was calling a voicemail and that requires to send my phone number over DTMF. The number(s) though was never identified by the recipient, no matter how hard I tried.

When I switched to Linphone - everything worked. 

My settings are the following:
* In `voip.ms` I have set DTMF to Auto
* In the `Linphone` app, I have `Send in-band DTMFs (RFC 2833)` enabled
* In `Baresip` I have `In-band RTP Events`.

Not sure how to start debugging this so any hint is really appreciated.

Please let me know as always if you want me to try a new apk.

**Comment by juha-h** [comment]
When DTMF digit is touched, `adb logcat | grep Baresip` shows (for example):
```
07-24 21:26:41.699 22317 22317 D Baresip : Got DTMF digit '1'
07-24 21:26:41.699 22317 22317 D Baresip Lib: sending DTMF digit '1' to call -5476376624066310640
07-24 21:26:41.700 22317 22378 D Baresip Lib: audio: send DTMF digit: '1'
07-24 21:26:41.700 22317 22378 D Baresip Lib: audio: send DTMF digit end: '1'
```

**Comment by juha-h** [comment]
Does DTMF work if you change voip.ms DTMF Tx Method to InBand?

**Comment by arichiardi** [comment]
No InBand does not work either, I am now suspecting that noise might be a factor here. Doing a couple of tests with Echo cancellation and Premium/Value routes.

**Comment by arichiardi** [comment]
I tried Premium route and there was no problem whatsoever, apologies. Closing.
