### ISSUE TITLE
SNDFILE_INCLUDE_DIR not found 

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#399]
when building the baresip project i am getting this error 

https://github.com/juha-h/baresip-studio/assets/123717548/c01e4921-aad3-4413-b971-6f20eda6be36

I hope you are aware of this.
Thank you.

**Comment by juha-h** [comment]
Is this issue related to libbaresip-android repository or baresip-studio repository?

**Comment by AviWA** [comment]
libbaresip-android repo

**Comment by juha-h** [comment]
AviWA writes:

> libbaresip-android repo

Then move the issue there.
