### ISSUE TITLE
JNI method with a number

### ISSUE THREAD

**Issue by luansh** [juha-h/baresip-studio#4]
I'm a newer,
JNI method declaration is external fun call_send_digit(callp: String, digit: Char): Int
but in cpp its name is Java_com_tutpro_baresip_MainActivity_call_1send_1digit
why use '1'?
Thanks a lot!

**Comment by luansh** [comment]
I see, because of '_' in C function name will mistake, so '_' is replaced of '_1'
Thanks a lot!

**Comment by juha-h** [comment]
luansh writes:

> JNI method declaration is external fun call_send_digit(callp: String,
> digit: Char): Int but in cpp its name is
> Java_com_tutpro_baresip_MainActivity_call_1send_1digit why use '1'?

I don't know.  You need to ask Google.  Kotlin code looks for a name
with those 1s.  Without them the JNI function is not found.
