### ISSUE TITLE
Use username from input on account creation

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#40]
...so when I write "user@domain" the account should already have the user field be set to "user"

**Comment by juha-h** [comment]
Licaon_Kter writes:

> ...so when I write "user@domain" the account should already have the
> user field be set to "user"

That is authentication username, which may not be the same as userpart
of AoR.

**Comment by licaon-kter** [comment]
Really? That's a thing?

So "username@domain.tld" would auth with "notmyusername" and a password? That's a common thing?

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Really? That's a thing?
> 
> So "username@domain.tld" would auth with "notmyusername" and a
> password? That's a common thing?

For example, some proxies/registrars use username as authentication
username and some use username@domain as authentication username.

It is also common that the same user can have multiple AoRs (SIP URIs),
for example, sip:username@domain and sip:+telephonenumber@domain.

**Comment by licaon-kter** [comment]
I'd vote to autcomplete this with username, users that have it different can just add/change, for the others it's a convenience thing.

**Comment by juha-h** [comment]
Licaon_Kter writes:

> I'd vote to autcomplete this with username, users that have it
> different can just add/change, for the others it's a convenience
> thing.

It is not a big effort for user to write authentication username, since
it needs to be done only once when account is created.

Default value is OK, if it always works, but may not be optimal value
for the user.  In case of authentication username, there is no such
default value.

**Comment by juha-h** [comment]
I'll close this one, since there is no good default value.
