### ISSUE TITLE
error on build : error: cannot combine with previous 'long long' declaration specifier

### ISSUE THREAD

**Issue by moradi-morteza** [juha-h/baresip-studio#400]
i build [libbaresip-android](https://github.com/juha-h/libbaresip-android/tree/45c7d6d4f5605c9e89f57f9880d0a2ab3e44de97) and add fildes to distribution folder, and when i want to build app in android studio i got error : 

`D:\Android\Sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi23 --sysroot=D:/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DARCH=\"armv7-a\" -DHAVE_ACCEPT4 -DHAVE_ARC4RANDOM -DHAVE_ATOMIC -DHAVE_EPOLL -DHAVE_FORK -DHAVE_GETOPT -DHAVE_INET6 -DHAVE_PRCTL -DHAVE_PTHREAD -DHAVE_PWD_H -DHAVE_ROUTE_LIST -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_STRERROR_R -DHAVE_STRINGS_H -DHAVE_SYSLOG -DHAVE_SYS_TIME_H -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_UNIXSOCK=1 -DOS=\"Android\" -DUSE_ZLIB -Dbaresip_EXPORTS -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/openssl/include -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -DHAVE_INTTYPES_H -lstdc++ -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/baresip.dir/baresip.c.o -MF CMakeFiles\baresip.dir\baresip.c.o.d -o CMakeFiles/baresip.dir/baresip.c.o -c C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c

C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:41:9: error: cannot combine with previous 'long long' declaration specifier
    l = re_snprintf(&(debug_buf[0]), 2047, "%H", net_debug, baresip_network());
        ^
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_fmt.h:117:39: note: expanded from macro 're_snprintf'
        _re_snprintf_s((str), (size), (fmt), RE_VA_ARGS(__VA_ARGS__))
                                             ^
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:363:25: note: expanded from macro 'RE_VA_ARGS'
#define RE_VA_ARGS(...) RE_ARG_N2(RE_ARG_VA_NUM(__VA_ARGS__), __VA_ARGS__)
                        ^
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:362:27: note: expanded from macro 'RE_ARG_N2'
#define RE_ARG_N2(N, ...) RE_ARG_N3(N, __VA_ARGS__)
                          ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:338:29: note: expanded from macro 'RE_ARG_2'
#define RE_ARG_2(expr, ...) RE_ARG_SIZE(expr), (expr), RE_ARG_1(__VA_ARGS__)
                            ^
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:325:7: note: expanded from macro 'RE_ARG_SIZE'
        long long:              sizeof(long long),                            \
             ^
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:11:18: note: expanded from macro 'long'
    #define long long long`

`D:\Android\Sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi23 --sysroot=D:/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DARCH=\"armv7-a\" -DHAVE_ACCEPT4 -DHAVE_ARC4RANDOM -DHAVE_ATOMIC -DHAVE_EPOLL -DHAVE_FORK -DHAVE_GETOPT -DHAVE_INET6 -DHAVE_PRCTL -DHAVE_PTHREAD -DHAVE_PWD_H -DHAVE_ROUTE_LIST -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_STRERROR_R -DHAVE_STRINGS_H -DHAVE_SYSLOG -DHAVE_SYS_TIME_H -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_UNIXSOCK=1 -DOS=\"Android\" -DUSE_ZLIB -Dbaresip_EXPORTS -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/openssl/include -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -DHAVE_INTTYPES_H -lstdc++ -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/baresip.dir/baresip.c.o -MF CMakeFiles\baresip.dir\baresip.c.o.d -o CMakeFiles/baresip.dir/baresip.c.o -c C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c

C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:41:9: error: type 'long long' in generic association compatible with previously specified type 'long long'
    l = re_snprintf(&(debug_buf[0]), 2047, "%H", net_debug, baresip_network());
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_fmt.h:117:39: note: expanded from macro 're_snprintf'
        _re_snprintf_s((str), (size), (fmt), RE_VA_ARGS(__VA_ARGS__))
                                             ^~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:363:25: note: expanded from macro 'RE_VA_ARGS'
#define RE_VA_ARGS(...) RE_ARG_N2(RE_ARG_VA_NUM(__VA_ARGS__), __VA_ARGS__)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:362:27: note: expanded from macro 'RE_ARG_N2'
#define RE_ARG_N2(N, ...) RE_ARG_N3(N, __VA_ARGS__)
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:338:29: note: expanded from macro 'RE_ARG_2'
#define RE_ARG_2(expr, ...) RE_ARG_SIZE(expr), (expr), RE_ARG_1(__VA_ARGS__)
                            ^~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:325:2: note: expanded from macro 'RE_ARG_SIZE'
        long long:              sizeof(long long),                            \
        ^~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:11:18: note: expanded from macro 'long'
    #define long long long
                 ^~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:41:9: note: compatible type 'long long' specified here
    l = re_snprintf(&(debug_buf[0]), 2047, "%H", net_debug, baresip_network());
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_fmt.h:117:39: note: expanded from macro 're_snprintf'
        _re_snprintf_s((str), (size), (fmt), RE_VA_ARGS(__VA_ARGS__))
                                             ^~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:363:25: note: expanded from macro 'RE_VA_ARGS'
#define RE_VA_ARGS(...) RE_ARG_N2(RE_ARG_VA_NUM(__VA_ARGS__), __VA_ARGS__)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:362:27: note: expanded from macro 'RE_ARG_N2'
#define RE_ARG_N2(N, ...) RE_ARG_N3(N, __VA_ARGS__)
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:338:29: note: expanded from macro 'RE_ARG_2'
#define RE_ARG_2(expr, ...) RE_ARG_SIZE(expr), (expr), RE_ARG_1(__VA_ARGS__)
                            ^~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:323:2: note: expanded from macro 'RE_ARG_SIZE'
        long:                   sizeof(long),                                 \
        ^~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:11:18: note: expanded from macro 'long'
    #define long long long
                 ^~~~~~~~~`

`D:\Android\Sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi23 --sysroot=D:/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DARCH=\"armv7-a\" -DHAVE_ACCEPT4 -DHAVE_ARC4RANDOM -DHAVE_ATOMIC -DHAVE_EPOLL -DHAVE_FORK -DHAVE_GETOPT -DHAVE_INET6 -DHAVE_PRCTL -DHAVE_PTHREAD -DHAVE_PWD_H -DHAVE_ROUTE_LIST -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_STRERROR_R -DHAVE_STRINGS_H -DHAVE_SYSLOG -DHAVE_SYS_TIME_H -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_UNIXSOCK=1 -DOS=\"Android\" -DUSE_ZLIB -Dbaresip_EXPORTS -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/openssl/include -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include -IC:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -DHAVE_INTTYPES_H -lstdc++ -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/baresip.dir/baresip.c.o -MF CMakeFiles\baresip.dir\baresip.c.o.d -o CMakeFiles/baresip.dir/baresip.c.o -c C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c

C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:41:9: error: type 'unsigned long long' in generic association compatible with previously specified type 'unsigned long long'
    l = re_snprintf(&(debug_buf[0]), 2047, "%H", net_debug, baresip_network());
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_fmt.h:117:39: note: expanded from macro 're_snprintf'
        _re_snprintf_s((str), (size), (fmt), RE_VA_ARGS(__VA_ARGS__))
                                             ^~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:363:25: note: expanded from macro 'RE_VA_ARGS'
#define RE_VA_ARGS(...) RE_ARG_N2(RE_ARG_VA_NUM(__VA_ARGS__), __VA_ARGS__)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:362:27: note: expanded from macro 'RE_ARG_N2'
#define RE_ARG_N2(N, ...) RE_ARG_N3(N, __VA_ARGS__)
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
<scratch space>:19:1: note: expanded from here
RE_ARG_2
^`

'`C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/baresip.c:41:9: error: cannot combine with previous 'long long' declaration specifier
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_fmt.h:117:39: note: expanded from macro 're_snprintf'
        _re_snprintf_s((str), (size), (fmt), RE_VA_ARGS(__VA_ARGS__))
                                             ^
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:363:25: note: expanded from macro 'RE_VA_ARGS'
#define RE_VA_ARGS(...) RE_ARG_N2(RE_ARG_VA_NUM(__VA_ARGS__), __VA_ARGS__)
                        ^
C:/Users/Moradi/Desktop/baresip-studio/app/src/main/cpp/../../../../distribution/re/include/re_types.h:362:27: note: expanded from macro 'RE_ARG_N2'
#define RE_ARG_N2(N, ...) RE_ARG_N3(N, __VA_ARGS__)
                          ^`

**Comment by juha-h** [comment]
Are you sure that you used latest master?

**Comment by moradi-morteza** [comment]
> Are you sure that you used latest master?
yes its master,
but in baresip-studio\app\src\main\cpp\baresip.c

code is like : 
`#if defined(__ARM_ARCH_7A__)
    #define long long long
#endif `

i change it to : 
`#if defined(__ARM_ARCH_7A__)
   
#endif`

and now its build and ok.

**Comment by juha-h** [comment]
Commit https://github.com/juha-h/baresip-studio/commit/74ad71d2ca0a51b74811fe3c6ffbc30451cd4fdf removed that define yesterday.  Your were NOT using latest master at the time when I asked.  Please close this bogus issue.
