### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by ONiKiDSK** [juha-h/baresip-studio#402]
How to get the status of a specified contact?

**Comment by ONiKiDSK** [comment]
enum presence_status contact_presence(const struct contact *c);

JNIEXPORT jint JNICALL
Java_xxx_contactPresence(JNIEnv *env, jclass clazz, jlong contact) {
    return (jint)contact_presence((const struct contact *)contact);
}

The result is 0,why？I need your help.

**Comment by juha-h** [comment]
ONiKiDSK writes:

> How to get the status of a specified contact?

If you mean presence status then presence is not currently supported.
I have not seen much use for it.

**Comment by juha-h** [comment]
`contact_presence` returns 0 if contact is null or its presence is unknown.  Sorry, but I don't have extra resources to comment other than baresip app related issues.
