### ISSUE TITLE
baresip+ hangs up whenever I try to make or answer a call

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#403]
baresip+ 44.2.0
calyxOS 4.12.0 (AOSP 13)

For incoming calls, as soon as I tap the green receiver icon to answer, baresip disappears revealing the home screen and the call gets dumped. 

For outgoing calls, it seems to start dialling, then just stops before ringing starts and returns to the neutral baresip screen (no number showing in the callee field)

**Comment by juha-h** [comment]
See the Wiki Debugging to produce logcat log.  I suspect that this is AOSP, not baresip issue.
