### ISSUE TITLE
Including alsa driver in baresip

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#406]
I wanna include alsa driver into baresip-studio and use alsa instead of opensl es for audio. I have built the alsa in linux but not cant include into the project.

**Comment by juha-h** [comment]
baresip-studio project uses opensles audio module.  If you want to use alsa. please for the repo and do it there.

**Comment by AviWA** [comment]
" please for the repo and do it there" Sorry I can't understand this can u help me?

**Comment by AviWA** [comment]
> please for the repo and do it there.

Sorry I can't understand this can u help me?
