### ISSUE TITLE
baresip-studio project uses opensles audio module.  If you want to use alsa. please for the repo and do it there.

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#407]
baresip-studio project uses opensles audio module.  If you want to use alsa. 
"please for the repo and do it there."

Sorry I can't understand this can u help me?

**Comment by juha-h** [comment]
AviWA writes:

> baresip-studio project uses opensles audio module.  If you want to use alsa. 
> "please for the repo and do it there."

As I wrote, this project is not using alsa module and I don't know if it
would even work at all.  So you are on your own.  I cannot help.
