### ISSUE TITLE
please add support proximity sensor

### ISSUE THREAD

**Issue by wkg** [juha-h/baresip-studio#41]
it need for normal using app..

**Comment by juha-h** [comment]
For what purpose you need proximity sensor?

There exists a call to ignore cheek presses:
```
window.addFlags(WindowManager.LayoutParams.FLAG_IGNORE_CHEEK_PRESSES)
```

**Comment by wkg** [comment]
it doesn't work, I can hang up the cheek.... it would be better to turn off the screen ...

**Comment by juha-h** [comment]
wkg writes:

> it doesn't work, I can hang up the cheek.... it would be better to
> turn off the screen ...

OK, I'll do some testing with proximity sensor in the near future.

**Comment by wkg** [comment]
Thank you!

**Comment by juha-h** [comment]
I just pushed a commit that adds support for proximity sensing during calls.  If you are building your own baresip app, please give it a try.

**Comment by wkg** [comment]
Thank you! I am not building own app, try it in next release

**Comment by juha-h** [comment]
Next release (8.5.0) is now available in Play Store.  It can take many days before it is available in F-Droid.

**Comment by wkg** [comment]
I tested it from Play Store, all good working, thank you again!
