### ISSUE TITLE
Android 14 on Pixel 6a latest release 59.0.0 crashes immediately

### ISSUE THREAD

**Issue by NeroBurner** [juha-h/baresip-studio#412]
Phone: Pixel 6a
OS: Android 14

installing and starting [59.0.0](https://github.com/juha-h/baresip-studio/releases/tag/59.0.0) crashes the app as soon as I've provided all the requested permissions. The moment the third permission is granted the app immediately crashes and it won't stay open until I remove the permissions, it then asks again.

With https://github.com/juha-h/baresip-studio/releases/tag/58.0.0 the app runs

unfortunately I updated to Android 14 yesterday, and today I installed Baresip from FDdroid for the first time. So I can't say if the crash is Android 14 related or not

**Comment by juha-h** [comment]
Looks like one permission was missing.  This one worked for me in Pixel 6 API 34 emulator:
https://box.tutpro.com/tmp/baresip.apk.  Could you give it a try by first uninstalling the crashing baresip and then installing this one.

**Comment by juha-h** [comment]
Created new release 59.0.1.

**Comment by NeroBurner** [comment]
Thanks a lot! That was awesomely fast!

both apks work!

is it expected, that I can't load the backup from the 58.0.0 version?

**Comment by juha-h** [comment]
NeroBurner writes:


> is it expected, that I can't load the backup from the 58.0.0 version?

You should be able to restore from 58.0.0 backup. Did you get some error
message?

**Comment by NeroBurner** [comment]
Yes see screenshot

![Screenshot_20231019-223457](https://github.com/juha-h/baresip-studio/assets/9076163/23ba4b47-6d3b-4dab-b404-e1a6ca14fc90)

**Comment by juha-h** [comment]
I am not able to reproduce this one.  I tried by installing 58.0.0 from GitHub and restored from an old backup file.  Then I made a few calls and created new backup file.  Then I installed 59.0.1 from GutHub and restore from the backup file that I had created using 58.0.0 succeeded.

**Comment by NeroBurner** [comment]
seems my phone is wonky :sweat_smile: Thanks for testing it!

and again thanks for the quick fix!
