### ISSUE TITLE
"start automatically" doesn't really start automatically

### ISSUE THREAD

**Issue by olivluca** [juha-h/baresip-studio#419]
I'm using the baresip+ app from f-droid with lineageos 20 (android 14).
I checked the "start automatically" option in the settings, however what it does it's just to show a notification "tap here to start the application".
I think that the option should really start the application so I can receive calls even if I don't remember to check the notifications and tap the baresip one.
Apologies if android doesn't allow it.

**Comment by juha-h** [comment]
baresip used to start automatically before API level 29 (Android 10).  Android 10 introduced privacy restriction:

`Blocking unwanted interruptions - Android 10 prevents app launches from the background that unexpectedly jump into the foreground and take over focus from another app. Learn more [here](https://developer.android.com/about/versions/10/privacy/changes#background-activity-starts).`

Could you try if it helps if you allow "Appear on top" permission in baresip app's Android settings?

**Comment by olivluca** [comment]
I cannot give it that permission, these are the permissions available (all are granted)

- Camera
- Contacts
- Microphone
- Nearby devices
- Notifications
- Phone

Additionally, if I select "all permissions" I see (but cannot change)

- run foreground service
- route calls through the system
- have full network access
- change your audio settings
- view network connections
- view Wi-Fi connections
- prevent phone from sleeping
- disable your screen lock
- display full notifications as full screen activities on a locked device
- run at startup
- control vibration
- send sticky broadcast

FYI, these are the permissions for, .e.g. FairEmail (which starts checking mail without me tapping any notification)

Normal permissions

- Contacts
- Notifications

Additional permissions:

- have full network access
- view network connections
- run at startup
- run foreground service
- android.permission.SCHEDULE_EXACT_ALARM
- prevent phone from sleeping
- use biometric hardware
- ask to ignore battery optimisations
- google play billing service
- use fingerprint hardware


At first sight it doesn't seem a permission problem (all the seemingly relevant permissions are the same in both apps), but I'm not really into android development so I couldn't say.

**Comment by juha-h** [comment]
My Samsung phone has in Settings/App info a "Appear on top" and when I click it, I get Allow permission.

Anyway, I need to study if it would be possible to start baresip foreground service instead of main activity as boot complete action.  It will take some time since I'm traveling.

**Comment by juha-h** [comment]
Turned out that starting baresip service in the background is not good idea, since there may be accounts where password needs to be asked at start.

I created apk `https://box.tutpro.com/tmp/baresip.apk` that tries to start baresip regardless of which its Android version is.  On my device, autostart worked fine when  "Appear on top"  baresip setting was allowed and didn't work when it was not allowed.

Did you find that setting in your device?  If no, ask your OS people, why it is not there.   Perhaps it is not needed to start apps at start.  Try with the above test apk.

**Comment by juha-h** [comment]
Officially the permission is called `SYSTEM_ALERT_WINDOW`.  Can you allow it?

**Comment by olivluca** [comment]
OK, the permission is **not** among the permissions you can set in each individual app, but it's in Settings-> Apps -> Special App Access -> Display over other Apps.
Once I activate that for the test app it starts automatically, with the one from f-droid I still get the "tap here to start" notification.
I found more details here:
 https://stackoverflow.com/questions/36016369/system-alert-window-how-to-get-this-permission-automatically-on-android-6-0-an (in fact that's where I found that I had to check in Settings -> Apps -> Special App Access).

**Comment by olivluca** [comment]
BTW, from f-droid I installed baresip+, not that I need video, but the "plus" part got me :wink:

**Comment by juha-h** [comment]
Luca Olivetti writes:

> Once I activate that for the test app it starts automatically, with
> the one from f-droid I still get the "tap here to start" notification.

Yes, I have not updated the F-Droid app yet.  What I will try to do is
this:

- if SYSTEM_ALERT_WINDOW setting is allowed, the app starts
  automatically

- if not allowed, the "tap here ..." notification is posted

**Comment by juha-h** [comment]
Luca Olivetti writes:

> BTW, from f-droid I installed baresip+, not that I need video, but the
> "plus" part got me :wink:

I don't use the plus version myself.  I added video support because some
people asked for it.

**Comment by olivluca** [comment]
Will the app ask for the permission if it's not already granted (at least if the "start automatically" option is checked)?
I have other apps with that permission but I don't remember if and how they asked for it

**Comment by olivluca** [comment]
(one of those I wrote myself but I think I targeted an older api version)

**Comment by juha-h** [comment]
Luca Olivetti writes:

> Will the app ask for the permission if it's not already granted (at
> least if the "start automatically" option is checked)?

Might be possible to ask the permission, but I could just add a comment
to the Start Automatically help text and tell that the user needs allow
that permission if user does not like the notify option.

**Comment by olivluca** [comment]
I think you implemented this feature with commit a9ab10682edff932da1dde07a73152152b0031c7
I see that the app uses the  [ACTION_BOOT_COMPLETED](https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED) intent, does it mean one have to manually unlock the device in order for baresip to start?

**Comment by juha-h** [comment]
Luca Olivetti writes:

> I see that the app uses the
> [ACTION_BOOT_COMPLETED](https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED)
> intent, does it mean one have to manually unlock the device in order
> for baresip to start?

Perhaps so.  I haven't tried. I just checked and also Linphone is using
ACTION_BOOT_COMPLETED, not ACTION_LOCKED_BOOT_COMPLETED.

**Comment by juha-h** [comment]
Should be fixed in version 46.3.0.
