### ISSUE TITLE
Mute and speaker buttons at top of app are in "face zone"

### ISSUE THREAD

**Issue by BrunswickBTC** [juha-h/baresip-studio#421]
On Pixel 6pro GrapheneOS.

baresip buttons at top of app are not accessible during a vall. One can see them, but once the finger is within a half inch of them, the screen goes black and the touchscreen is disabled. This is a "face detection" feature to prevent inadvertant screen activation. Some phones use optical IR sensors to detect the face, this one uses capacitive proximity sense through the touchscreen.
Any interfaces during a call should be moved to the bottom or center of the screen.

**Comment by juha-h** [comment]
This does not happen on my Samsung device or my Nokia Android One devices.  In my opinion this is an issue of your device if it confuses finger with face.  I'm not going to move the buttons.

**Comment by BrunswickBTC** [comment]
Thanks for your help
