### ISSUE TITLE
Android: What does the button next to the "more options" do?

### ISSUE THREAD

**Issue by rodrigoaguilera** [juha-h/baresip-studio#43]
This is the only app on f-droid that receives SIP calls correctly, thank you!

There is an icon in the top bar of the app that does not reveal any text when is long pressed and if tapped turns red but I don't know what is the function.

Can you clarify?

**Comment by juha-h** [comment]
That button is speakerphone button (material design speakerphone icon).  Speakerphone is on, when the button is red.

**Comment by rodrigoaguilera** [comment]
Thank you
