### ISSUE TITLE
How can i connect websocket wss://[:host]:[:port] #431

### ISSUE THREAD

**Issue by datpt11** [juha-h/baresip-studio#432]
i try sip:[:host]:[:port];transport=wss not register

**Comment by juha-h** [comment]
See Outbound Proxies comment.  This works for me:
```
sip:<host>:<port>;transport=wss
```

**Comment by datpt11** [comment]
<img width="433" alt="Screenshot 2024-01-15 at 3 36 28 PM" src="https://github.com/juha-h/baresip-studio/assets/48908789/2a0b9840-e7de-4355-a8ea-2b8efd091b3e">
Is this where I enter my server uri?

**Comment by juha-h** [comment]
Yes.  And please see the Wiki about Debugging info.

**Comment by datpt11** [comment]
When I read the code, I don't see any case of wss transport. Can you show me this check? @juha-h

**Comment by juha-h** [comment]
With this kind of Outboun Proxy definition
```
sip:<host>:<port>;transport=wss
```
baresip lib is using wss transport.  Check baresip/re source code.

**Comment by juha-h** [comment]
About wss transport, read the Wiki entry and https://github.com/baresip/baresip/wiki/Roadmap#signaling.

**Comment by datpt11** [comment]
I think it's not a problem with my server because I can still use the jssip library. When I use baresip studio, I don't know if there is any missing configuration, but I get an error message on the client that says Protocol not supported

**Comment by datpt11** [comment]
> With this kind of Outboun Proxy definition
> 
> ```
> sip:<host>:<port>;transport=wss
> ```
> 
> baresip lib is using wss transport. Check baresip/re source code.

yes i tried it

**Comment by juha-h** [comment]
I can connect to my SIP proxy over wss both using baresip and my jssip web client.

**Comment by datpt11** [comment]
I connected successfully, because I wrote the wrong account uri.
