### ISSUE TITLE
Remote Side Can't Hear Me Properly

### ISSUE THREAD

**Issue by muellert** [juha-h/baresip-studio#434]
When I have a phone call with baresip-studio, the other side has massive trouble hearing me. No matter what I tried, my voice seems to be nigh impossible to hear and understand, so much so, that we usually call each other using the normal phone functionality, which works flawlessly. This problem has persisted across a number of versions of baresip now. Currently, I am using baresip 59.3.0 on LineageOS 20-20231103-NIGHTLY-instantnoodlep on a OnePlus 8Pro.

**Comment by juha-h** [comment]
Sorry but this project only tries to implement baresip for Android.  In the past LineageOS users have reported several issues that cannot be reproduced on Android.  There is nothing I can do about those.  You need to either report this issue to some LineageOS forum or use some other SIP application.

**Comment by muellert** [comment]
LineageOS is supposed to be Android, more specifically, AOSP plus the minimal changes to make it run on a given hardware. Therefore, I don't understand what you mean when you are saying "it works on Android".

**Comment by muellert** [comment]
Btw, I've just checked, and Linphone does not have this problem on the same phone. But I generally like baresip much better, so I would like to see this issue fixed.

**Comment by juha-h** [comment]
Make sure your call is using the same audio codec both on baresip and linphone.  Also use logcat as described on Wiki page to check if there exists some media related error messages.

If the issue you reported would be related to baresip and not LineageOS, many users would have reported it during the several years baresip has been available.  I cannot fix anything that I cannot reproduce.

**Comment by muellert** [comment]
Of course you can't fix something you can't reproduce, but the codecs aren't the same in both apps, and I don't know how to figure out which codec is in use at any time. I have noticed that the two applications don't have the same set of codecs, though. Linphone includes a number of "speex" codecs, plus "PCMU", "PCMA", and "G729" of those that I have enabled. In a test call over IPv6, I was also told that the sound was of slightly lower volume than another test call I made over IPv4 (which I find confusing).

**Comment by juha-h** [comment]
Baresip app has info button that tells the codec and other things about the call, like lost packets. Linphone should have something similar, but I don't know.  Turn on SIP Trace and you will see what codec has been negotiated.

Does this issue exists also when both parties of the call are using baresip app?  If so, use a codec such as opus or arm, and check call info at both end points.
