### ISSUE TITLE
Better Handling of IPv6

### ISSUE THREAD

**Issue by muellert** [juha-h/baresip-studio#435]
Where I currently am, my ISP provides me with dual-stack Internet. Using IPv4, baresip registers, so the lamps are green, but when I try to make a call, nothing happens. Using IPv6, baresip registers, the lamps are green, and I can place calls. The problem seems to be that the ISP uses CGN, which is unnecessary for IPv6. Using 'auto' seems to prefer the IPv4 method, and nothing works. However, when I go outside and need to use the cell network, there is frequently only IPv4 available, so if I have baresip configured to use IPv6, nothing happens. I frequently forget to switch the protocol stacks between home and outside, so typically more than half of the time, nobody can call me. It would be nice if baresip had a switch as to which protocol it should prefer.

I am using baresip 59.3.0 on LineageOS 20-20231103-NIGHTLY-instantnoodlep on a OnePlus 8Pro.

**Comment by juha-h** [comment]
baresip library does not support preferring of an address family, but I might be able to do that the Android app.  So you would like to prefer IPv6 if both are available?  If so, I could make a test version of the app that does that.  If it works for you, I could then add the feature to the app.  Would you be willing to try the test apk?

**Comment by muellert** [comment]
Yes, I'm willing to test - can't lose much at this point, anyway.

**Comment by muellert** [comment]
UI-wise, it could just be a change to the protocol switch version, with one new entry: prefer IPv6.

**Comment by juha-h** [comment]
The test version of the app is here:
```
https://box.tutpro.com/tmp/baresip.apk
```
It has ipv6 as the preferred address family hard coded.  I'll add the setting if the test app works for you.

There is logcat message starting with ***s telling which addresses were the preferred ones.

**Comment by juha-h** [comment]
Forgot to mention, save your config before installing the test app and then restore it when the test app is installed.

**Comment by gdt** [comment]
It strikes me that:
   - the basic modern way is to prefer IPv6 if there is both v6 and v4
   - the real modern way is to implement Happy Eyeballs

I suspect HE requires keeping state about "on this network, when I had both, and I tried v4, it worked or didn't, and same for v6.  That requires a programmatic determination of things not working.

Overall, I would say that the default should be to prefer v6 if both, unless a setting says otherwise.   ( It ought to try to register with all the valid addresses until one succeeds, too, independent of this.)

**Comment by juha-h** [comment]
If you want to prefer ipv6, can't you configure domain name of your SIP Proxy so that its IPv6 address has higher priority?

**Comment by muellert** [comment]
I just installed the app, but it doesn't show a different version number, so I'm not 100% sure. Disabling Wifi yielded a registration failure instead of falling back

**Comment by juha-h** [comment]
I did not increase the version. Show logcat debug.

**Comment by gdt** [comment]
> If you want to prefer ipv6, can't you configure domain name of your SIP Proxy so that its IPv6 address has higher priority?

I don't follow this at all.   A domain can have one or more of A and one or more of AAAA records.  I am not aware of any sense of ordering or prioritization.

**Comment by juha-h** [comment]
For example like this:
```
$ host -t NAPTR example.com
example.com NAPTR 10 100 “S” “SIPS+D2T” “” _sips._tcp.example.com.

$ host -t SRV _sips._tcp.example.com
_sips._tcp.example.com SRV 5 100 5060 ipv6.example.com.
_sips._tcp.example.com SRV 10 100 5060 ipv4.example.com.

$ host ipv6.example.com.
ipv6.example.com has IPv6 address 2001:67c:224:666::26 2001:67c:224:666::26

$ host ipv4.example.com.
ipv4.example.com has address 192.26.111.38
```

**Comment by muellert** [comment]
I am sorry to say, but I might have been a bit overoptimistic. In any case, there's also something urgent that prevents me from testing atm. Will come back to you later, probably in 1-2 weeks.

**Comment by juha-h** [comment]
Reopen if you can provide required debug information.

**Comment by gdt** [comment]
> ```
> $ host -t NAPTR example.com
> example.com NAPTR 10 100 “S” “SIPS+D2T” “” _sips._tcp.example.com.
> 
> $ host -t SRV _sips._tcp.example.com
> _sips._tcp.example.com SRV 5 100 5060 ipv6.example.com.
> _sips._tcp.example.com SRV 10 100 5060 ipv4.example.com.
> 
> $ host ipv6.example.com.
> ipv6.example.com has IPv6 address 2001:67c:224:666::26 2001:67c:224:666::26
> 
> $ host ipv4.example.com.
> ipv4.example.com has address 192.26.111.38
> ```

Yes, I suppose you could do that.   But I see that as a kludgy workaround, not something to be recommended.  Specifically, having two domain names for the same host to to force v4/v6 is kludgy.  The intent of multiple SRV is for multiple hosts.

I am certainly not trying to demand that you do anything to fix this.  I am just making the point that the existence of  way to kludge around the problem is not an argument that the basic situation of a domain with multiple A/AAAA records shouldn't be handled better.  (And I have no idea if any other sip program does.)

**Comment by juha-h** [comment]
Greg Troxel writes:

> Yes, I suppose you could do that.   But I see that as a kludgy
> workaround, not something to be recommended.

It is also kludgy to add configuration option to prefer a given address
family.  So I'm not going to do that.

**Comment by gdt** [comment]
Sure, but the modern way, for at least a decade now, is to sort v6 before v4, if not doing happy eyeballs.   I guess you are saying that you just call getaddrinfo and try addresses in the order returned, and I can see the point that this is ok too.
