### ISSUE TITLE
libbaresip .a file not genarate

### ISSUE THREAD

**Issue by tanvirsikdar05** [juha-h/baresip-studio#436]
Thank you for acknowledging the success of the app. However, when attempting to generate the libbaresip.a file from the libbaresip-android folder, it only generates the openssl and opus folders in the distribution folder. I've tried multiple times, but it doesn't generate successfully.

- my uses NDK version (26.1.10909125)
- Api level 23
I use command $make install-all

**Comment by tanvirsikdar05** [comment]
**face this error**
rm: cannot remove 'include_opus/opus/opus_custom.h': Permission denied
rm: cannot remove 'include_opus/opus/opus_defines.h': Permission denied
rm: cannot remove 'include_opus/opus/opus.h': Permission denied
rm: cannot remove 'include_opus/opus/opus_multistream.h': Permission denied
rm: cannot remove 'include_opus/opus/opus_projection.h': Permission denied
rm: cannot remove 'include_opus/opus/opus_types.h': Permission denied
make: *** [Makefile:142: opus] Error 1

**Comment by juha-h** [comment]
Looks to me that this is an issue with libbarasip-android project, not baresip-studio project.   Building and installing the libs should work if you exactly follow the instructions in its README.md.

**Comment by tanvirsikdar05** [comment]
Dear,Teacher I flow same but fail I really need to build ? Can you help me
.I am learner
