### ISSUE TITLE
Missing feature: call recording

### ISSUE THREAD

**Issue by hubbty** [juha-h/baresip-studio#437]
In the screenshots shown on F-droid there is a taperecorder symbol: [https://f-droid.org/en/packages/com.tutpro.baresip/](https://f-droid.org/en/packages/com.tutpro.baresip), 
but on my phone it is missing:
![Screenshot_20240129-155734_Trebuchet](https://github.com/juha-h/baresip-studio/assets/59095639/16539b15-cb2c-4cb0-bc54-ffb472d10c06)

What might be the reason for this deficit?

**Comment by juha-h** [comment]
The icon is "record next call".  You cannot start recording an existing
call.
