### ISSUE TITLE
Missing feature: call recording

### ISSUE THREAD

**Issue by hubbty** [juha-h/baresip-studio#438]
In the screenshots shown on F-droid there is a taperecorder symbol: [https://f-droid.org/en/packages/com.tutpro.baresip/](https://f-droid.org/en/packages/com.tutpro.baresip/),
but on my phone it is missing not only during an ongoing call (which is as intended), but also before starting a call:
![IMG_20240130_134754](https://github.com/juha-h/baresip-studio/assets/59095639/a952160a-bf8c-4ea2-933b-8257258d0eb7)
![300507479-16539b15-cb2c-4cb0-bc54-ffb472d10c06](https://github.com/juha-h/baresip-studio/assets/59095639/f095f821-4751-4963-b117-afd67b4ac772)

What might be the reason for this deficit?

**Comment by juha-h** [comment]
The shots in above do not show the full screen on my browser.

**Comment by hubbty** [comment]
Here ist the full screen: 
![IMG_20240130_Trebuchet](https://github.com/juha-h/baresip-studio/assets/59095639/aa9f051e-c9d0-4ddd-b5e2-d4248e28f30f)

**Comment by juha-h** [comment]
The icon is visible. See the Wiki.

**Comment by hubbty** [comment]
Yes I found the wiki and learned that the missing icon means "Voicemail" and not "Record next call" as I had understood.

I guess this taperecorder icon shown at F-droid is missing because in my account settings the is no voicemail URI configured.

I used that "Record next call" function. But was not able to find the recorded call anywhere on my phone, nor could I find a hint where to find it in the wiki.--
31. Jan. 2024, 01:11 von ***@***.***:

**Comment by juha-h** [comment]
> I used that "Record next call" function. But was not able to find the
> recorded call anywhere on my phone, nor could I find a hint where to
> find it in the wiki.

Look from call details.

**Comment by AndySchroder** [comment]
You are talking about in "Call History"? I cannot find recorded calls in there.

**Comment by juha-h** [comment]
Get to Call Details by touching time of the call(s) in Call History,.

**Comment by juha-h** [comment]
I could and Help item to Call History menu. 
Recording are stored in app's storage.
Recording(s) are delete a row from Call History.  
There is not way to export the recordings files.  In fact, each recording consists of two files: encoding and decoding.  So two files would need to be exported and then the user should somehow merge them to a single file in order to play the recording with some audio app. 
Seek is not in the plans (I don't like recording of calls). 
baresip lib does not support loading/unloading sndfile module during the call.

**Comment by AndySchroder** [comment]
> I could and Help item to Call History menu.

I don't understand this sentence.

**Comment by AndySchroder** [comment]
> Recording(s) are delete a row from Call History.

Okay, looks like you need to long press to get the option to delete the row.

**Comment by AndySchroder** [comment]
> each recording consists of two files: encoding and decoding

I'm not sure why you have both an encoding and decoding. Do you mean encod**ing** and decod**er**?

**Comment by juha-h** [comment]
Yes, I was not careful with the words.

**Comment by juha-h** [comment]
Sorry again, and should be add.
