### ISSUE TITLE
Caller ID Issues with a PBX behind NAT

### ISSUE THREAD

**Issue by dle-baresip** [juha-h/baresip-studio#439]
I've happily run baresip on my phone for a couple of years now.  However, I've always run it in conjunction with a VPN client so that baresip was effectively on the same subnet as my PBX and other non-baresip extensions.  

Recently, I've made some changes that eliminate the VPN requirement and allow direct baresip to make SIP connections directly to my PBX's public IP address when roaming.  This improves my phone's battery life and connection stability.  However, my non-baresip extensions are still behind the original NAT.  I've set up all of the firewall rules and port forwarding so that calls work in both directions, no complaints there.    

The  minor issue I do have is with the "redial" feature.  When one of my internal extensions calls baresip (with baresip registered from the WAN side) the caller ID on baresip shows the extension's private IP address<sup>(1)</sup> from behind the NAT.  And, when I go to redial, baresip attempts to INVITE the private IP address directly, even though private addresses wouldn't be routable in the external WAN context.   However, I can delete the address portion of the SIP contact (i.e. EXT@10.XX.XX.XX becomes just EXT) and the call goes through.

----

My feature request for baresip would be a per-account option to suppress or ignore the domain/address portion of contacts.  When this option is active, the contact would display as the user portion only (i.e. EXT as in the example above).  When interacting with SIP features that need a fully qualified identity, baresip would combine this user portion behind the scenes with the active account's domain.  

At a minimum, this feature would affect the redial function, call history<sup>(2)</sup>, and chat logs<sup>(3)</sup>.  I think it would be generally useful for baresip installations that register as clients of some PBX trunking system and always send/receive calls through that single access point.  The interface would be cleaner without a redundant duplicate address/domain appearing on every contact.  However, this feature should not be the default because it would break standalone baresip installations that might be open to receive direct calls from multiple peers.  

----

(1) I won't deny that it's ultimately my PBX's fault for exposing a private IP address.  I was able to configure the PBX to rewrite the "Contact" header, but I don't seem to have any good options to rewrite the "From" header.  However, I think my proposal has some advantage beyond fixing the redial feature, so I'm submitting it for your consideration while also pursuing a proper PBX fix.  

(2) I know this is terribly North-American of me, but it would be even better if there was a secondary option to display 10- and 11- digit users as "standard" phone numbers: (e.g. 234-456-8901). 

(3) I use SIP messaging as a substitute for SMS, and my chat logs are particularly confusing right now.  All of the incoming messages from an extension are in one conversation "EXT@10.XX.XX.XX", and all of my replies are in another conversation "EXT".

**Comment by juha-h** [comment]
I'm on the road and haven't read your message in detail, but an example on how it is now and how it would be after the new account option would help me to understand what you need.

**Comment by dle-baresip** [comment]
No rush.  This reflects a minor annoyance at worst, not a showstopper.  

If you only want the synopsis, start with the first paragraph of the second section (My feature request...).  Today baresip would treat all of the following as separate contacts based on the "From" header: 
* 123@PRIVATE_IP
* 123@PRIVATE_DOMAIN
* 123@PUBLIC_IP
* 123@PUBLIC_DOMAIN

I think there are configurations where it makes sense to strip the domain/address portion and treat all as a single contact:
* 123

baresip would then connect to this contact as 123@SIP_ACCOUNT_DOMAIN using the baresip account configuration.

**Comment by juha-h** [comment]
How about defining a contact with URI tel:123 and defining Telephony Provider SIP_ACCOUNT_DOMAIN for the account? That is already supported.

**Comment by dle-baresip** [comment]
Hmm...  I don't generally use contacts so I had to do a few experiments.  My conclusion is that defining a contact actually makes baresip more confusing.  

It appears that baresip will _display_ CONTACT_NAME in place of any interface elements that matched the SIP_USER (i.e extension).  So SIP_USER@PRIVATE_IP, SIP_USER@PUBLIC_DOMAIN, etc all get translated on the screen as CONTACT_NAME.  This is visually consistent with my proposal, so I can see why you made the suggestion.  

However, baresip still appears to _use_ the original fully qualified contact string whenever I interact with the interface elements.  To use chat log as an example, I used to be able to distinguish between conversation names.  I could predict that if I sent a message to SIP_USER@PRIVATE_IP the message would fail, but if I sent a message SIP_USER (which I had to type manually) the message would go through (because baresip internally appends @SIP_ACCOUNT_DOMAIN to route the message).

Since contact naming only affects the display, using your suggestion the chat log shows CONTACT_NAME and CONTACT_NAME, but the behavior is still inconsistent.  Sending a message to one CONTACT_NAME will fail (because it still sends to SIP_USER@PRIVATE_IP), and sending a message to the other CONTACT_NAME will succeed.  And of course there are still two separate conversations for sent and received messages when there should be one.  

I've attached a couple of screenshots that show the difference:

<img width=300 src="https://github.com/juha-h/baresip-studio/assets/110635346/c13b045e-1574-4e6a-afd9-d034cea5b0b5">  <img width=300 src="https://github.com/juha-h/baresip-studio/assets/110635346/a6a2b523-5af5-4dd7-9cb6-969e3a414a80">

Per my proposed option, baresip would ignore the domain/address portion of the From header and just extract the SIP_USER field for call display and history.  This is actually consistent with the some feedback from the FreePBX forums when I asked about this issue: "[most SIP clients ignore the From domain](https://community.freepbx.org/t/rewrite-the-from-header-in-calls-to-remote-extensions/94297/2)".

**Comment by juha-h** [comment]
Perhaps allowing to add aliases to contacts would help.  So there could be contact
```
Sombody user@domain
```
with aliases
```
user@ip_addr_1
user@ip_addr_2
user@some_other_domin
```
When call/message comes in and From matches any of the above, Somebody would be shown as originator.  And when there is reply, it would be sent to user@domain.

Would that be OK with you?

**Comment by dle-baresip** [comment]
That wouldn't be ideal.  Because of DHCP, the internal IP addresses can change.  Also, because my FreePBX has a route to the PSTN, I would have to keeping adding contacts for every new inbound phone number.  In practice, it would be simpler for me to just continue to use the workaround (deleting the address/domain portion of any saved "from" information before redialing/replying).

**Comment by juha-h** [comment]
Why don't you configure your PBX to use its domain name in hostpart of From URI?  I don't like the idea of making special user specific changes to baresip app.

**Comment by juha-h** [comment]
Better to fix this in the PBX.
