### ISSUE TITLE
Direct IP call?

### ISSUE THREAD

**Issue by giox069** [juha-h/baresip-studio#447]
I'm trying to do a direct IP call with baresip found on f-droid (what's the difference between baresip and baresip+ on f-droid?).

After installation of baresip, with no SIP accounts defined, I can type the SIP URL of the destination phone `sip:192.168.56.247`, but the dial button cannot be pressed.
After adding a dummy SIP account, I can press the dial button, but I receive a "Call Failed: 484 Address incomplete", and no traffic is generated to the destination phone (tested with tcpdump).
Even if I add and enable a working SIP account, dialing URL `sip:192.168.56.247 ` still show 484 error.

Direct call to `sip:192.168.56.247 ` are working correctly if I use some other clients, like MicroSIP for windows.

Do direct IP calls work on baresip?

Thank you

**Comment by juha-h** [comment]
See Wiki/Debugging and provide the log.

**Comment by giox069** [comment]
This is the log I get when typing sip:192.168.56.247 and pressing the dial button:
```
debian@debian:~$ adb logcat | grep Baresip
02-24 07:31:35.370 15469 15469 W Baresip : Main onStart
02-24 07:31:55.703  1336  4421 I MediaFocusControl: requestAudioFocus() from uid/pid 10417/15469 AA=USAGE_VOICE_COMMUNICATION/CONTENT_TYPE_SPEECH clientId=android.media.AudioManager@f4ea8e1com.tutpro.baresip.BaresipService$Companion$$ExternalSyntheticLambda2@58981cf callingPack=com.tutpro.baresip req=4 flags=0x0 sdk=34
02-24 07:31:56.836  1336  9282 I MediaFocusControl: abandonAudioFocus() from uid/pid 10417/15469 clientId=android.media.AudioManager@f4ea8e1com.tutpro.baresip.BaresipService$Companion$$ExternalSyntheticLambda2@58981cf
02-24 07:31:56.836  1336  9282 D MediaFocusControl: abandonAudioFocus, clientId = android.media.AudioManager@f4ea8e1com.tutpro.baresip.BaresipService$Companion$$ExternalSyntheticLambda2@58981cf
02-24 07:31:56.847 15469 15469 I Toast   : show: caller = com.tutpro.baresip.BaresipService.toast$lambda$4:1218 

```

I also tried case insensitive grep: adb logcat | grep -i Baresip
attached you can find a longer log with case insensitive grep.

[baresip_log_directip.txt](https://github.com/juha-h/baresip-studio/files/14391982/baresip_log_directip.txt)



And this is the screenshot before dialing and after:

Before: 
![t0](https://github.com/juha-h/baresip-studio/assets/5477803/0587f286-e429-45c1-b8fa-bf8c18790ab8)

After pressing the dial (handset) button:
﻿
![t1](https://github.com/juha-h/baresip-studio/assets/5477803/911a6742-77fa-4727-9c52-a3aeba65ffbd)

**Comment by juha-h** [comment]
Giovanni Panozzo writes:

> This is the log I get when typing sip:192.168.56.247 and pressing the
> dial button:

Did you enable Debug and SIP Trace in Settings?

**Comment by giox069** [comment]
no :blush:, I'm sorry. Here is the new log with Debug and SIP Trace enabled.
[log_baresip_3.txt](https://github.com/juha-h/baresip-studio/files/14392116/log_baresip_3.txt)

(or with case insensitive grep:  [log_baresip_2.txt.gz](https://github.com/juha-h/baresip-studio/files/14392118/log_baresip_2.txt.gz) )

**Comment by giox069** [comment]
wait... 2 times same error, now I discovered why debug was not enabled: exiting from settings with the back arrow on the top of the screen does not saves the settings, and does not warn me that I have to save settings... I will recollect logs again in few minutes.

**Comment by giox069** [comment]
Ok, log is attached. As you can see from the log, the 408 answer incomplete comes from the "dummy" asterisk account I had to use  to enable dial button (192.168.56.227 is my asterisk server).
Baresip UDP INVITE packet has my asterisk as destination, instead of the phone at 192.168.56.247

[log_baresip_4.txt](https://github.com/juha-h/baresip-studio/files/14392150/log_baresip_4.txt)

**Comment by juha-h** [comment]
The INVITE that  baresip sends is exactly what you asked for.

**Comment by giox069** [comment]
It's not an invite packet content problem. The problem is on the destination IP address of the UDP packet.
I'm trying to do a DIRECT SIP call to 192.168.56.247 (a gigaset DECT VOIP phone) from baresip, without using an account on a registrar server.
Baresip is composing correctly the INVITE:
`02-24 09:07:27.987 14493 14532 D Baresip Lib: INVITE sip:192.168.56.247 SIP/2.0`
but baresip is sending the INVITE packet to the wrong address:
`02-24 09:07:27.987 14493 14532 D Baresip Lib: UDP 192.168.56.52:60583 -> 192.168.56.227:5060`

192.168.56.277 is WRONG, it should be 192.168.56.247, the IP I typed in the SIP URL to cause a direct call.
192.168.56.52 is obviously my android phone running baresip.

**Comment by juha-h** [comment]
Have you defined your asterisk (at 192.168.56.227) as an Outbound Proxy?

**Comment by giox069** [comment]
> Have you defined your asterisk (at 192.168.56.227) as an Outbound Proxy?

Yes, I was forced to define an Account, because the Dial/Handset button on baresip does not work without an account.

The configured account has 192.168.56.227 as Outbound Proxy.

But I don't want baresip to use that account: direct VOIP call with url like "sip:username@IP:port" should not use an account. It should INVITE IP:port directly, as I understand using other clients.

**Comment by juha-h** [comment]
I tried the same and got:
```
02-25 08:29:50.440 25686 25739 D Baresip Lib: UDP 101.122.79.229:42713 -> 192.168.56.247:5060
02-25 08:29:50.440 25686 25739 D Baresip Lib: INVITE sip:192.168.56.247 SIP/2.0
```

**Comment by giox069** [comment]
> I tried the same and got:
> 
> ```
> 02-25 08:29:50.440 25686 25739 D Baresip Lib: UDP 101.122.79.229:42713 -> 192.168.56.247:5060
> 02-25 08:29:50.440 25686 25739 D Baresip Lib: INVITE sip:192.168.56.247 SIP/2.0
> ```

Maybe you defined an account with Outbound Proxy exactly the same you typed in the sip: URL ? This is not my case, the sip: url I type when calling, is different from the Outbound Proxy defined on the account.

**Comment by juha-h** [comment]
Giovanni Panozzo writes:

> > Have you defined your asterisk (at 192.168.56.227) as an Outbound Proxy?
> 
> Yes, I was forced to define an Account, because the Dial/Handset
> button on baresip does not work without an account.

Account does not need to have an outbound proxy configured.  Only needed
if you want to force requests to there.

> The configured account has 192.168.56.227 as Outbound Proxy.

That is your mistake.

> But I don't want baresip to use that account: direct VOIP call with
> url like ***@***.***:port" should not use an account. It should
> INVITE IP:port directly, as I understand using other clients.

In baresip, an account is needed to create a SIP user agent.  SIP
requests must originate from a user agent (SIP UAC).

**Comment by giox069** [comment]
> In baresip, an account is needed to create a SIP user agent. SIP requests must originate from a user agent (SIP UAC).

So the answer to my question on 1st post is: NO, baresip does not support direct IP calls to other phones.
It only can register to one or more accounts defined by the user.

**Comment by giox069** [comment]
Never mind, removing Outbond Proxy from the account works!

**Comment by giox069** [comment]
Ok! Removing Outbound Proxy from the account configuration works!
So direct IP calls to phones are still routed to an account outbound proxy... this is not clear, but putting a blank outbound proxy worked.
Thank you.

**Comment by giox069** [comment]
Is it possible to make the dial button without any account? I could open an issue with title "When there are no accounts defined, you cannot press the Dial button to call a sip URI" :smile:

**Comment by juha-h** [comment]
I have already tried to explain you that SIP requests need a SIP User Agent and ac account is used to create one.
