### ISSUE TITLE
When I use Api.message_send(...),but no messageEvent(...) is executed.

### ISSUE THREAD

**Issue by ONiKiDSK** [juha-h/baresip-studio#450]
The environment at this time:BARESIP VERSION:3.9.0, build libbaresip-android on Mar 3, 2024（or Mar 2, 2024） 
When I use Api.message_send(...) ,the message was successfully sent, and the server returned the data. But no messageEvent(...) is executed. (ps.The function message_handler(...) in baresip.c did not execute)

But when I use BARESIP VERSION:3.7.0, probably built libbaresip a few months ago,the situation was normal at that time.

**Comment by juha-h** [comment]
Issues published need to be related to baresip app.  See Wiki/Debugging on how to report if you think that baresip app has an issue.
