### ISSUE TITLE
Baresip app eats its configuration after update to 59.6.0

### ISSUE THREAD

**Issue by pelzvieh** [juha-h/baresip-studio#452]
After updating a previously working installation to version 59.6.0 from F-Droid, the app displays an error message, that did not start and suggesting to check settings. Looking into Accounts or Settings reveals that all configuration settings are gone.

Restore prompts to restart the app, after which the same error happens again.

Attempt to restore from the same backup file displays an error that it failed to restore from that file.

**Comment by pelzvieh** [comment]
Apparently, the whole device has been in a weird state, probably not related to baresip.

**Comment by juha-h** [comment]
pelzvieh writes:

> Apparently, the whole device has been in a weird state, probably not
> related to baresip.

Good to hear.  Otherwise would have been a serious issue.
