### ISSUE TITLE
DMTF during calls

### ISSUE THREAD

**Issue by mbush88** [juha-h/baresip-studio#454]
Hi, I tried this Android App but I saw that the third number I insert in DMTF mode during calls is not recognized.

Best regards
Marco

**Comment by juha-h** [comment]
See https://github.com/juha-h/baresip-studio/wiki/Reporting-Issues and provide debug log.

**Comment by juha-h** [comment]
I just called The Test Call and DTMF test worked fine also when there was more than 3 digits.

**Comment by juha-h** [comment]
I'll close this due to lack of debug information.
