### ISSUE TITLE
Unable to open App, crashes straight !

### ISSUE THREAD

**Issue by vincegre** [juha-h/baresip-studio#455]
Hi

Just installed the app through Frdroid on my OnePlus Nord 2 5G running Android 13 and it crashes straight ! Tried even rebooting phone but still the same.
Something I can do to help fix the problem ?

Thanks

Vincèn

**Comment by juha-h** [comment]
Vincèn writes:

> Just installed the app through Frdroid on my OnePlus Nord 2 5G running
> Android 13 and it crashes straight ! Tried even rebooting phone but
> still the same. Something I can do to help fix the problem ?

Which version?

**Comment by vincegre** [comment]
> Which version?

59.7.0

**Comment by juha-h** [comment]
Vincèn writes:

> 59.7.0

I just tried this om my Nokia device (which should be pure Android):

- un-installed baresip
- installed baresip 59.7.0 from F-Droid
- started the app without issues
- restored saved config
- restart worked without issues

If yours crashes, produce logcat (see Wiki) showing baresip and
Baresip lines.

**Comment by vincegre** [comment]
> If yours crashes, produce logcat (see Wiki) showing baresip and Baresip lines.

I'm not able to send logcat right now as I'm on travel but I have already the crash report of Android: https://bin.kv2.dev/~65fc867b5de7ed6bfdc0239f
I'll post you in few days the whole log as requested when I'm back home !

Thanks

**Comment by juha-h** [comment]
There has been no changes to ringtone handling.  This the code:
```
        val ntUri = RingtoneManager.getActualDefaultRingtoneUri(applicationContext,
                RingtoneManager.TYPE_NOTIFICATION)
        nt = RingtoneManager.getRingtone(applicationContext, ntUri)

        val rtUri = RingtoneManager.getActualDefaultRingtoneUri(applicationContext,
                RingtoneManager.TYPE_RINGTONE)
        rt = RingtoneManager.getRingtone(applicationContext, rtUri)
```
It has nothing special and no reference to ringtone2.

I suspect that is issue is related to your device.

**Comment by vincegre** [comment]
> I suspect that is issue is related to your device.

well it's the only app I have that problem :( so I guess no chance you fix the issue ?

**Comment by juha-h** [comment]
Vincèn writes:

> > I suspect that is issue is related to your device.
> 
> well it's the only app I have that problem :( so I guess no chance you
> fix the issue ?

Provide `adb logcat | grep -i baresip` output.  Perhaps it tells
something.

**Comment by juha-h** [comment]
Also, check if there is something strange in your Sounds and Vibration settings.

**Comment by juha-h** [comment]
I started baresip in Android Studio Pixel 7 API 34 emulator and it didn't crash.  So I don't think that this is an issue with baresip app.

**Comment by juha-h** [comment]
Closed due to inactivity from issuer.
