### ISSUE TITLE
DTMF Mode not saved

### ISSUE THREAD

**Issue by dle-baresip** [juha-h/baresip-studio#460]
I have the DTMF set to SIP INFO to match my PBX configuration.  DTMF works as long as baresip is running.  However, when I close and restart baresip, DTMF does not work because the account config reverts back to "in-band RTP".  After I change the account config to SIP INFO, DTMF starts working again.

**Comment by juha-h** [comment]
Thanks for reporting.  Should be now fixed by https://github.com/juha-h/baresip-studio/commit/393a98e8e7c495fa7de706f3f72568bb06731821 that will be included in next baresip version.
