### ISSUE TITLE
Save speaker toggle status and restore on startup

### ISSUE THREAD

**Issue by h3ndrik** [juha-h/baresip-studio#464]
I have a tablet mounted to the wall of my kitchen that is supposed to accept incoming calls and always set up audio in handsfree / speakerphone mode.

Unfortunately the speaker toggle isn't persistent and resets to the default state where I'd need to press my ear against the wall. I'd be fine with any solution to set the audio routing. Either make the icon's state restore to the last state, an option in the audio settings or a SIP header forcing it into either of the modes.

**Comment by juha-h** [comment]
A new audio setting could be introduced to always use speaker phone during calls if audio is not routed via bluetooth. Currently baresip behaves the same way as standard dialers, i.e., speaker phone is turned off when call terminates.

**Comment by juha-h** [comment]
I added Speaker Phone checkbox to Audio Settings.  Could you try this https://box.tutpro.com/tmp/baresip.apk if it works for you?  Backup before install and then restore.

**Comment by juha-h** [comment]
Should now be supported in baresip 60.2.0.

**Comment by h3ndrik** [comment]
I forgot to say thanks: Thank you very much for the quick implementation of the feature. It works great.

**Comment by juha-h** [comment]
h3ndrik writes:

> I forgot to say thanks: Thank you very much for the quick implementation of the feature. It works great.

You are welcome.
