### ISSUE TITLE
Can't get 1&1 SIP account to work

### ISSUE THREAD

**Issue by hubbty** [juha-h/baresip-studio#465]
On my Android phone I tried to confiigure a SIP account in baresip (60.1.0, installed from F-Droid), but I did not succeed. I tried this same account in Sipdroid too and there it worked instanantaneously. The settings are:
![sipdroid](https://github.com/juha-h/baresip-studio/assets/59095639/359c1eef-986b-45ce-9337-e784d96ebd9f)
![baresip](https://github.com/juha-h/baresip-studio/assets/59095639/f141bb61-50c6-4d0e-b550-eb482f3d3bb0)
What is wrong here?

-----

Besides, I could not find an explanation, what the red and yellow dots are trying to tell. Is there a Wiki somewhere, that I just did not find?

**Comment by juha-h** [comment]
Hard to tell what is wrong based on the information you provided.   You didn't show what your 1&1 SIP URI is.   You would need to provide SIP trace of both registrations in order to find out the difference.  See Wiki/Debugging.  I don't know how to do the same with Sipdroid.  You could also ask 1&1 how to ccnfigure baresip for them.

Regarding the dots, read About text.

**Comment by hubbty** [comment]
"SIP trace" and debugging are beyond my reach. Thank you for your answer nevertheless!

What I noticed in the meantime is, that 1&1 are using G.711, but this codec is not available in the list of available codecs. Could this be the cause why it cannot register?

**Comment by juha-h** [comment]
hubbty writes:

> "SIP trace" and debugging are beyond my reach. Thank you for your
> answer nevertheless!

OK, ask 1&1 for help.

> What I noticed in the meantime is, that 1&1 are using G.711, but this
> codec is not available in the list of available codecs. Could this be
> the cause why it cannot register?

baresip does support G.711 codec.  See Settigs/Audio Settings.  But
REGISTER request has nothing to do with codecs.
