### ISSUE TITLE
If you implement a video encoding h264 on android, do you want to register the two strings "codec" and "vidsrc" at the same time, one is the video source and the other is video decoding?

### ISSUE THREAD

**Issue by yuexiajiayan** [juha-h/baresip-studio#47]
Is that so? I think avformat module and avcodec are like this
vidsrc_register and vidcodec_register function

**Comment by yuexiajiayan** [comment]
vidsrc_register and vidcodec_register function

**Comment by juha-h** [comment]
Currently this project does not support video and therefore I cannot comment video related issues.
