### ISSUE TITLE
baresip+ Source Code

### ISSUE THREAD

**Issue by hosseinkaramii** [juha-h/baresip-studio#472]
Hey there. how are you?
thanks for your valuable package you have deployed here. I just searched for baresip+ Source code and I just saw the application itself not the github page. How can I clone that one?

**Comment by juha-h** [comment]
Read the README,  baresip+ is on video branch.

**Comment by vhbcet** [comment]
I set the modules this way, but the video feature does not open in the application. Do I need to do anything differently? I don't know much about these things, I apologize if I sounded cocky.


MODULES := "webrtc_aecm;augain;aaudio;dtls_srtp;opus;g711;g722;g7221;g726;codec2;amr;gzrtp;stun;turn;ice;presence;mwi;account;natpmp;srtp;uuid;sndfile;debug_cmd;avcodec;avformat;v4l2"

**Comment by juha-h** [comment]
Sorry, I don't have resources to help with roll your own baresip.
