### ISSUE TITLE
build fail 

### ISSUE THREAD

**Issue by xiezhouyan1027** [juha-h/baresip-studio#475]
windows   as 2023.3.1 build fail.
![image](https://github.com/juha-h/baresip-studio/assets/57662346/e474c481-2601-486d-9ee5-f5bd74f3cc07)
 
libbaresip-android  build in Debian 11，success。

build fail info:
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app\.cxx\Debug\4m1o661a\arm64-v8a'
  [1/2] Building C object CMakeFiles/baresip.dir/baresip.c.o
  clang: warning: -Z-reserved-lib-stdc++: 'linker' input unused [-Wunused-command-line-argument]
  [2/2] Linking C shared library D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app\build\intermediates\cxx\Debug\4m1o661a\obj\arm64-v8a\libbaresip.so
  FAILED: D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/build/intermediates/cxx/Debug/4m1o661a/obj/arm64-v8a/libbaresip.so 
  cmd.exe /C "cd . && D:\develop\android\ndk\26.2.11394342\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android23 --sysroot=D:/develop/android/ndk/26.2.11394342/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -DHAVE_INTTYPES_H -lstdc++ -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libbaresip.so -o D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app\build\intermediates\cxx\Debug\4m1o661a\obj\arm64-v8a\libbaresip.so CMakeFiles/baresip.dir/baresip.c.o  -landroid  -lOpenSLES  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/baresip/lib/arm64-v8a/libbaresip.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/re/lib/arm64-v8a/libre.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libssl.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libcrypto.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/opus/lib/arm64-v8a/libopus.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/spandsp/lib/arm64-v8a/libspandsp.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/g7221/lib/arm64-v8a/libg722_1.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/g729/lib/arm64-v8a/libbcg729.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/codec2/lib/arm64-v8a/libcodec2.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/amr/lib/arm64-v8a/libamrnb.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/amr/lib/arm64-v8a/libamrwb.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/amr/lib/arm64-v8a/libamrwbenc.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/webrtc/lib/arm64-v8a/libwebrtc.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/gzrtp/lib/arm64-v8a/libzrtpcppcore.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/sndfile/lib/arm64-v8a/libsndfile.a  -lz  -llog  -latomic -lm && cd ."
  ld.lld: error: undefined symbol: __write_chk
  >>> referenced by unistd.h:206 (/opt/Android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/fortify/unistd.h:206)
  >>>               file_io.c.o:(psf_fwrite) in archive D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/sndfile/lib/arm64-v8a/libsndfile.a
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      @echo off
      "D:\\develop\\android\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\project\\tick\\test\\baresip-studio-60.2.0\\baresip-studio-60.2.0\\app\\.cxx\\Debug\\4m1o661a\\arm64-v8a" ^
        baresip
    from D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:buildCMakeDebug[armeabi-v7a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app\.cxx\Debug\4m1o661a\armeabi-v7a'
  [1/2] Building C object CMakeFiles/baresip.dir/baresip.c.o
  clang: warning: -Z-reserved-lib-stdc++: 'linker' input unused [-Wunused-command-line-argument]
  [2/2] Linking C shared library D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app\build\intermediates\cxx\Debug\4m1o661a\obj\armeabi-v7a\libbaresip.so
  FAILED: D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/build/intermediates/cxx/Debug/4m1o661a/obj/armeabi-v7a/libbaresip.so 
  cmd.exe /C "cd . && D:\develop\android\ndk\26.2.11394342\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi23 --sysroot=D:/develop/android/ndk/26.2.11394342/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -DHAVE_INTTYPES_H -lstdc++ -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libbaresip.so -o D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app\build\intermediates\cxx\Debug\4m1o661a\obj\armeabi-v7a\libbaresip.so CMakeFiles/baresip.dir/baresip.c.o  -landroid  -lOpenSLES  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/baresip/lib/armeabi-v7a/libbaresip.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/re/lib/armeabi-v7a/libre.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/openssl/lib/armeabi-v7a/libssl.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/openssl/lib/armeabi-v7a/libcrypto.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/opus/lib/armeabi-v7a/libopus.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/spandsp/lib/armeabi-v7a/libspandsp.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/g7221/lib/armeabi-v7a/libg722_1.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/g729/lib/armeabi-v7a/libbcg729.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/codec2/lib/armeabi-v7a/libcodec2.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/amr/lib/armeabi-v7a/libamrnb.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/amr/lib/armeabi-v7a/libamrwb.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/amr/lib/armeabi-v7a/libamrwbenc.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/webrtc/lib/armeabi-v7a/libwebrtc.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/gzrtp/lib/armeabi-v7a/libzrtpcppcore.a  D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/sndfile/lib/armeabi-v7a/libsndfile.a  -lz  -llog  -latomic -lm && cd ."
  ld.lld: error: undefined symbol: __write_chk
  >>> referenced by unistd.h:206 (/opt/Android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/fortify/unistd.h:206)
  >>>               file_io.c.o:(psf_fwrite) in archive D:/project/tick/test/baresip-studio-60.2.0/baresip-studio-60.2.0/app/src/main/cpp/../../../../distribution/sndfile/lib/armeabi-v7a/libsndfile.a
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      @echo off
      "D:\\develop\\android\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\project\\tick\\test\\baresip-studio-60.2.0\\baresip-studio-60.2.0\\app\\.cxx\\Debug\\4m1o661a\\armeabi-v7a" ^
        baresip
    from D:\project\tick\test\baresip-studio-60.2.0\baresip-studio-60.2.0\app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 1m 31s
74 actionable tasks: 74 executed

help me, thr

**Comment by xiezhouyan1027** [comment]
Ok, I see. I will compile with debian tomorrow. Thank you, my brother,I wish you all the best

**Comment by juha-h** [comment]
xie writes:

> Ok, I see. I will compile with debian tomorrow. Thank you, my
> brother,I wish you all the best

Each published baresip version is also automatically build by F-Droid.
The last version that F-Droid built was 60.3.0.  The build would have
failed, if there would be been some issue.

**Comment by xiezhouyan1027** [comment]
I want to integrate baresip into my existing project and replace the original pjsip. Thank you.

**Comment by xiezhouyan1027** [comment]
I want to integrate baresip into my existing project and replace the original pjsip. Thank you.

**Comment by xiezhouyan1027** [comment]
debian 12 build failed too,
![image](https://github.com/juha-h/baresip-studio/assets/57662346/49569d12-ecd2-4639-82f1-88f4d0db0c1d)

**Comment by juha-h** [comment]
Sorry, but since I cannot reproduce this issue, I cannot do anything to fix it.  Your environment must be somehow different than mine, since the undefined symbol __wrirte_chk does not exist in libbarasip-android libraries nor in my Android Studio app directory.  So you need to find a fix on your own.

**Comment by xiezhouyan1027** [comment]
Yes, I successfully build apk. 
I know what went wrong, and I fixed it.
![image](https://github.com/juha-h/baresip-studio/assets/57662346/24ac40bb-354c-4650-9e99-5ba58e436ba0)

**Comment by juha-h** [comment]
xie writes:

> Yes, I successfully build apk. 
> I know what went wrong, and I fixed it.

What was it?

**Comment by xiezhouyan1027** [comment]
Yes, I learned from the ancient mysterious power of the East that the version of cmake in app/build.gradle should be 3.22.1, not 3.25.1. thank you.
