### ISSUE TITLE
Integration with native dialer

### ISSUE THREAD

**Issue by seppiola** [juha-h/baresip-studio#482]
Would it be possible to implement android native calling account registration to be able to make and receive calls on the native aosp dialer?

**Comment by juha-h** [comment]
What has this to do with baresip app? It used to be possible to make SIP calls using Android dialer and add SIP contacts to native contact app, but I don't know the current status.

**Comment by seppiola** [comment]
I'm not talking about aosp native SIP client which has been removed in android 12.
I don't know the details and from which android version this is available but apparently now it's possible to register an app as a calling account the same way the native SIP client was integrated in the dialer.

I have a matrix client installed that supports this feature:

![e9015c0f-8a88-4ee9-b0a2-2ea5c2a6e1fb](https://github.com/juha-h/baresip-studio/assets/20034870/311c9a06-ab2e-4c90-a43b-7623cf4c426c)
![e2e373f7-b512-4c1a-b74b-4f4d0890713c](https://github.com/juha-h/baresip-studio/assets/20034870/60e6805c-9157-4e4f-99d4-bc7314cdb6d1)
![3ead658a-70cc-4462-8d31-ecfabd85578e](https://github.com/juha-h/baresip-studio/assets/20034870/28649ae8-8ee8-45a5-8026-61db07b4a8dd)
![03cd7273-7df8-49cb-af66-43e6b59fcaab](https://github.com/juha-h/baresip-studio/assets/20034870/848cc154-26fa-47c9-9beb-f0ec4c0dbdb1)
![afde3f46-26e5-4b47-960d-eaa2fe0c612d](https://github.com/juha-h/baresip-studio/assets/20034870/186c2b62-6354-4722-9b63-07b73d8946e7)

This is on LineageOS 21 (Android 14) and aosp dialer but I tried it also on a phone with stock android 13 with google dialer.

**Comment by juha-h** [comment]
There is Default Phone App setting.  Have you tried it?

**Comment by seppiola** [comment]
What for? It seemd to me that's just a quick toggle to set baresip as the default phone app. That would only open baresip when something triggers a phone intent.
What I meant is to use baresip as a SIP client and place/receive calls on aosp dialer the same way it was possible with the integrated aosp SIP client before.
I belive csipsimple did something similar years ago though in an weird way because that wasn't something officially supported by android the same way I could now register an app like fluffychat.
Am I missing something?

**Comment by juha-h** [comment]
> What I meant is to use baresip as a SIP client and place/receive calls
> on aosp dialer the same way it was possible with the integrated aosp
> SIP client before.

Give a concrete example, since I don't understand what you are
after.  Would aosp dialer replace current baresip user interface or
what?

**Comment by seppiola** [comment]
Yes it would. It would appear the same way this fluffychat is listed in the previous screenshots, taken in the default aosp dialer app. The aosp client would ask which account to use when placing a call (either simcard, fluffy, baresip or wathever else you might have) when pressing the call button after dialing the number.
The previous screenshot with blue background is the aosp dialer. When I dialed 123 and pressed call it asked me whether to use my sim card or fluffychat. I choose the latter to show how it worked.

I'm not familiar with the inner workings of android apps and I'm afraid I lack the knowledge to give a more technical explenation of the possible implemention of this feature.

I can only tell you how it handles this [the only app I fount implementing it](https://github.com/krille-chan/fluffychat/blob/cc828411243d9c1293027e008a0f90c68c4c905b/lib/utils/voip/callkeep_manager.dart#L71).

**Comment by seppiola** [comment]
I checked on my semi-broken phone with android 9... apparently this feature was already present there, along with the native SIP client I used that is now gone.
I don't know hot to call it other than using the name it's featured with in the menus, Calling Account.
![1a98e36b-b3c5-488e-98e1-22d80711e142](https://github.com/juha-h/baresip-studio/assets/20034870/a4963839-f673-4387-95f0-84ce88633f29)

**Comment by juha-h** [comment]
baresip is able to receive CALL and DIAL actions from other apps:
```
            <intent-filter>
                <action android:name="android.intent.action.DIAL" />
                <action android:name="android.intent.action.CALL" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```
Intent data contains a tel or sip URI to call. I once tested it using Google dialer to make baresip call.

Is this something you are looking for?

**Comment by seppiola** [comment]
Actually not. Don't get me wrong, call and dial intent are indeed useful and I used them a couple of times but, again that's not what I was talking about.
[This](https://developer.android.com/reference/android/telecom/PhoneAccount) is.

**Comment by juha-h** [comment]
Based on https://developer.android.com/develop/connectivity/telecom/selfManaged, I added skeleton ConnectionService and registered a PhoneAccount. However, on my Samsung device, I have not found anywhere a Calling Accounts setting.  Can you try with this https://box.tutpro.com/tmp/baresip.apk on your device?

**Comment by seppiola** [comment]
> 
> ![1a98e36b-b3c5-488e-98e1-22d80711e142](https://private-user-images.githubusercontent.com/20034870/338320453-a4963839-f673-4387-95f0-84ce88633f29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTAxODgsIm5iZiI6MTcxODIwOTg4OCwicGF0aCI6Ii8yMDAzNDg3MC8zMzgzMjA0NTMtYTQ5NjM4MzktZjY3My00Mzg3LTk1ZjAtODRjZTg4NjMzZjI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MzEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwN2ZjN2M0ZDRmYTU2MzA1OGI1ODkyNmUwODFkNTFjN2U0OGVmYjEzNzQyNjhkMTE0MWU5NDQ2MDk0ZTI3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ivREmwn7huF9HbFQje8NjQQ4V9QAW92lUU4iKUQ706M)

I confirm that it appers now in this settings page with the apk you provided, though no permissions are asked.
If I remember correctly samsung never integrated the native sip client in its dialer when it still existed, maybe that goes for calling accounts too.

**Comment by juha-h** [comment]
Click of the image link you gave in above shows me empty page.  Unfortunately I don't have an other Android device except the cheap Samsung one.  Perhaps I could try with an emulator.

Anyway, completing the skeleton implementation would mean a lot of new code.

**Comment by seppiola** [comment]
I updated the previous comment.

> Unfortunately I don't have an other Android device except the cheap Samsung one. Perhaps I could try with an emulator.

I don't know if this is something only implemented in aosp phone dialer.

> Anyway, completing the skeleton implementation would mean a lot of new code.

I can imagine... I'm sorry but I won't be able to help with the coding, I know too little of that. Maybe we could leave this issue open and someone else who might be interested could eventually give you a hand.

**Comment by juha-h** [comment]
I tried with Android Studio emulator Pixel 7 API 34 device and it didn't find Calling accounts setting.  So it looks to me that it is LineageOS feature.  It is possible to set baresip as Default Phone app or choose baresip as the phone app when making a call from contacts.

**Comment by seppiola** [comment]
That's, weird. I actually tested it on two other phones with stock android 9 and 13 with google dialer and it is indeed present on both, always in the dialer settings after pressing the three dots on the right of the seaech bar on top, then settings and then thers's calling accounts. I even checked on an old android 6 device and it works even there.

Well, thanks anyway, I appreciate it, it was worth trying at least. I probably would have been one of only few people actually using this, so not a great loss.

**Comment by juha-h** [comment]
There is no dialer app in the emulator.  There is Google Phone app.  If I search "dialer" in settings, it shows Default phone app.  And if I choose that, I get to page where I can choose between baresip and Google Phone app (System default).  Where are the three dots?

**Comment by seppiola** [comment]
I gave a spin at the emulator from Android Studio using Pixel 7 API 34, should be the same you tried.

[pixel7api34_callingaccounts.webm](https://github.com/juha-h/baresip-studio/assets/20034870/bde0204a-23cb-46da-8fff-abde9797f1ea)

**Comment by juha-h** [comment]
Thanks for the video.  After I installed Phone by Google app to my Samsung device, I was able to get to Calling accounts setting and active baresip as a calling account.  Weird that it is not possible to access Calling accounts setting directly from the Settings app.

Since it would be big task to fully add calling account feature to baresip, I added a new [feature request](https://github.com/juha-h/baresip-studio/wiki/Feature-Requestsl) about it.

**Comment by juha-h** [comment]
@seppiola baresip 79.1.0 can now manage calls using  Android Telecom framework.  Perhaps it can help you with this issue.

**Comment by seppiola** [comment]
@juha-h thanks I appreciate you remembered that, but unfortunately that does seem to be a different thing.
to be honest I don't really get what this option does. does it uses some android framework to handle audio streaming and compression to avoid doing that in app?

**Comment by juha-h** [comment]
@seppiola OK, I'm now experimenting with making baresip also default calling app so that it would be possible to use baresip to place and receive both SIP and PSTN (mobile network) calls.  Is that what you were after?

**Comment by seppiola** [comment]
@juha-h not really. quite the opposite actually, I would like to place both sip and mobile network calls using the native aosp dialer and contacts. but thanks for the thought and effort anyway.

**Comment by juha-h** [comment]
@seppiola OK, so you need to modify the native aosp dialer to do that.  I'm already able to make both SIP and PSTN (mobile network) calls with baresip app.

**Comment by seppiola** [comment]
@juha-h no, I dont't need to modify anything.
aosp dialer already supports android calling/phone accounts and uses that for mobile calls. in the past I used other sip apps wich supported that android api, across multiple different android versions, and was able to place sip calls from aops dialer.
that dialer, among many others, still supports that feature to this day.

what needs to be done is to implement in baresip that feature, the documentations of which I have linked ane showcased multiple times previously in this thread, in order for it being possible to use a third party dialer via the android phone api. (you even made a test build that created a calling account without it being actually implemented and it indeed showed on aosp dialer)

to be clear I'm not saying you should do it, I would of course really appreciate it as I do really appreciate your thoughtfulness on this old issue and thank you for that, but I'm not impling it should be done, especially if nobody really except from me has ever expressed the need for it.

i just wanted to clarify that this is something that should be implememted BY baresip for it to work with third party dialers which ALSO support that feature. baresip shoud offer a call account via phone account api, and the third party dialer should be able to use android phone accounts to place calls.
aosp native dialer is just a dialer that happens to support it.

**Comment by juha-h** [comment]
@seppiola Baresip (my development version) is registering Android phone account:

private fun registerPhoneAccount() {
        val phoneAccountHandle = getPhoneAccountHandle(this)
        val phoneAccount = android.telecom.PhoneAccount.builder(phoneAccountHandle, getString(R.string.app_name))
            .setCapabilities(android.telecom.PhoneAccount.CAPABILITY_SELF_MANAGED)
            .addSupportedUriScheme(android.telecom.PhoneAccount.SCHEME_SIP)
            .addSupportedUriScheme(android.telecom.PhoneAccount.SCHEME_TEL)
            .build()
        tm.registerPhoneAccount(phoneAccount)
    }

and I can now use baresip both as PSTN (mobile) and SIP calling app.  To me there is no need for any other dialer.  baresip app is all I need.

My development version is here if you want to try:  https://box.tutpro.com/tmp/baresip-calling.apk.  Just turn on Default Phone App in Settings, choose baresip as default calling app, and restart.  Account "Mobile" should show up in the account spinner for mobile PSTN calls and any number of SIP accounts can be added.
