### ISSUE TITLE
Calls fail with "session closed: invalid argument [22]" when SIP server only supports TLS connection

### ISSUE THREAD

**Issue by ndilieto** [juha-h/baresip-studio#483]
I traced this down to a bug in libre. See https://github.com/juha-h/libbaresip-android/issues/43 and https://github.com/juha-h/libbaresip-android/pull/42

**Comment by juha-h** [comment]
@ndilieto Could you check if this PR https://github.com/baresip/re/pull/1141 fixes the issue?

**Comment by juha-h** [comment]
@ndilieto Should now be fixed in baresip version 60.4.0.
