### ISSUE TITLE
Optimization of background noise

### ISSUE THREAD

**Issue by ONiKiDSK** [juha-h/baresip-studio#486]
baresip 60.4.0: During a call (neither party turned on the speaker), background noise can be heard all the time. Although this background noise does not seriously affect the clarity of the call, it is still hoped that this situation can be optimized. After all, when the speaker is turned on, the noise will be more obvious.
ps. This situation will not occur when using linphone.

**Comment by juha-h** [comment]
baresip Android app is based on baresip library and (as far as I know) the lib does not have any background noise reduction capabilities.  Check if your device has a related Sound & vibration setting. Otherwise, keep on using linphone.

**Comment by ONiKiDSK** [comment]
You can also call it static noise.
This situation has been around forever, before someone mentioned and also solved.
[https://github.com/baresip/baresip/issues/2889](url)
Baresip also solved this problem more than a month ago (webrtc_aec_extended_filter yes).
[https://github.com/baresip/baresip/pull/3048/files/a523db103ea4c3edf04cabe7e843236d416d58ed](url)

**Comment by juha-h** [comment]
baresip Android app is using webrtc_aecm module where ExtendedFilter is not supported:
```
enum class ConfigOptionID {
  kMyExperimentForTest,
  kAlgo1CostFunctionForTest,
  kTemporalLayersFactory,  // Deprecated
  kNetEqCapacityConfig,    // Deprecated
  kNetEqFastAccelerate,    // Deprecated
  kVoicePacing,            // Deprecated
  kExtendedFilter,         // Deprecated
  kDelayAgnostic,          // Deprecated
  kExperimentalAgc,
  kExperimentalNs,
  kBeamforming,               // Deprecated
  kIntelligibility,           // Deprecated
  kEchoCanceller3,            // Deprecated
  kAecRefinedAdaptiveFilter,  // Deprecated
  kLevelControl               // Deprecated
};
```
You are welcome to add webrtc_aec module to libbaresip-android and then use it instead of webrtc_aecm module.  Last time when I checked, it will not be an easy task.

**Comment by ONiKiDSK** [comment]
understand
