### ISSUE TITLE
TLS configuration

### ISSUE THREAD

**Issue by mrcasablr** [juha-h/baresip-studio#49]
Hello!

I have a asterisk SIP TLS with self-signed certificates working with baresip linux client with TLS.

I'd like to use baresip android app with TLS. However, to enable the
certificates, I do not see any baresip configuration on a few android 8.x
phones. I'm checking got baresip configuration on android phone at storage/emulated/0

Could anyone help me on how to get baresip TLS config going on android phone?

**Comment by juha-h** [comment]
Configuring of certificate and ca files is not currently supported, but will be when I have extra time.

**Comment by juha-h** [comment]
This has now been implemented in version 9.0.0, which should be available soon in Google Play store and in a few days in F-Droid.  Re-open if problems exist.

**Comment by mrcasablr** [comment]
Brilliant! Thank you will test and report
