### ISSUE TITLE
Calling from Contacts app does not remove '%20'

### ISSUE THREAD

**Issue by futomaki-bit** [juha-h/baresip-studio#490]
I have set baresip as default phone app.
In the Contacts app I press call (718) 111-1111, baresip would see it as tel:718%201111111

I see in [Contact.kt](https://github.com/juha-h/baresip-studio/blob/master/app/src/main/kotlin/com/tutpro/baresip/Contact.kt) it filters some characters:
`filterNot{setOf('-', ' ', '(', ')').contains(it)`

<img src="https://github.com/user-attachments/assets/273094a6-b8f4-42d5-b356-dfb4b1750ed3" width="256">
<img src="https://github.com/user-attachments/assets/37f523b1-c469-4afc-a205-4d8af11c5c34" width="256">

**Comment by juha-h** [comment]
I'm not currently able to reproduce this.  Could you get adb debug log of the call attempt (https://github.com/juha-h/baresip-studio/wiki/Debugging)?

**Comment by futomaki-bit** [comment]
> Edit: Perhaps baresip receives from your contact app %20 instead of space character?
Yes I think that's my issue.
---
with https://github.com/juha-h/baresip-studio/wiki/Debugging
On baresip app, I turned on Debug and SIP Trace [ :heavy_check_mark: ]
`adb logcat | grep Baresip` and `adb shell 'logcat --pid=$(pidof -s com.tutpro.baresip)'` does not show anything when attempting to call from Google Contacts app. `adb logcat` does show some logs of ConnectivityService
---
My device: Samsung Galaxy Z Flip5 on Android 14

**Comment by juha-h** [comment]
I don't currently have a device with me where I could use Default Phone App setting.

**Comment by juha-h** [comment]
I was able to get debug of the call:
```
07-25 21:21:25.952  8567  8567 D Baresip : onNewIntent with action/data 'android.intent.action.CALL/tel:(718)%20111-1111'
07-25 21:21:25.952  8567  8567 D Baresip : Action call to tel:(718)%20111-1111
```
So it was like I suspected.  I'll investigate what is the best way to remove %20.

**Comment by juha-h** [comment]
Can you try with this: https://box.tutpro.com/tmp/baresip.apk ? Backup before installing.

**Comment by futomaki-bit** [comment]
Works for me, but hopefully it did not break anything else.

Thank you

**Comment by juha-h** [comment]
@futomaki-bit Thanks for testing. I committed the fix.  Will be included in next version.
