### ISSUE TITLE
call recording broken

### ISSUE THREAD

**Issue by tomo90** [juha-h/baresip-studio#495]
I turn on the call recording and dial the call. The call is going fine, but once I'd like to end the call, it cannot be ended. The app freezes completely and never recovers. I have to wait for the other party to end the call. But even after the other party ends the call, the app still remains frozen on the call screen. I've tried granting baresip all possible permissions, without any change.

tested with baresip 60.4.1, 60.4.0, 60.3.0

**Comment by juha-h** [comment]
tomo90 writes:

> I turn on the call recording and dial the call. The call is going
> fine, but once I'd like to end the call, it cannot be ended. The app
> freezes completely and never recovers. I have to wait for the other
> party to end the call. But even after the other party ends the call,
> the app still remains frozen on the call screen.

See Wiki about Reporting Issues Debugging.

**Comment by juha-h** [comment]
I was able to reproduce this issue and created baresip issue https://github.com/baresip/baresip/issues/3135 about it.

**Comment by juha-h** [comment]
Thanks for reporting. Should now be fixed in version 60.4.2.
