### ISSUE TITLE
Option to change user agent string

### ISSUE THREAD

**Issue by KillingSpark** [juha-h/baresip-studio#496]
Hi I found this App in my quest for an SIP application that will let me edit the user agent string sent in the sip registration. The reason is simple: my sip provider seems to block encrypted communication based on the user agent string so that third party apps are forced to use unencrypted UDP for registration.

It seems as if baresip allows for a completely custom user agent string mitigating this restriction and this app uses baresip. If I understand correctly to make this happen one would have to pass a customizable string to this function call here:

https://github.com/juha-h/baresip-studio/blob/b148833ef040b1648b5d9b1c1bd0082cdedfff41/app/src/main/kotlin/com/tutpro/baresip/BaresipService.kt#L449

Do you think this is feasible?

**Comment by juha-h** [comment]
So are you suggesting that I add a new Setting "User Agent" that can be used to set custom UA string?

**Comment by KillingSpark** [comment]
That would be nice. I tested it by hardcoding the string I want and that works but having this as a setting would be optimal

**Comment by juha-h** [comment]
OK, I'll work on it.

**Comment by juha-h** [comment]
Completed by PR https://github.com/juha-h/baresip-studio/commit/74fa0c97e6b49c396cdd8ebc8072a06ccbdb5e8d.  Report if you find issues.
