### ISSUE TITLE
libbaresip.a ninja error

### ISSUE THREAD

**Issue by ibrahimsalgin** [juha-h/baresip-studio#50]
I m getting the following error when i try to build the project in Android studio.

ninja: error: 'baresip-studio-master/distribution/baresip/lib/arm64-v8a/libbaresip.a', needed by 'baresip-studio-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so', missing and no known rule to make it

**Comment by juha-h** [comment]
ibrahimsalgin writes:

> I m getting the following error when i try to build the project in
> Android studio. 
> 
> ninja: error: 'baresip-studio-master/distribution/baresip/lib/arm64-v8a/libbaresip.a', needed by 'baresip-studio-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so', missing and no known rule to make it

Have you generated the libs as instructed in README?

  After cloning the project, generate static libraries and include files
  to distribution directory using master branch of
  https://github.com/juha-h/libbaresip-android

**Comment by ibrahimsalgin** [comment]
thank you very much
