### ISSUE TITLE
Logging/ debuging for everyday usage

### ISSUE THREAD

**Issue by xpseudonym** [juha-h/baresip-studio#506]
This is a follow-up to the discussion [Debugging without adb?](https://github.com/juha-h/baresip-studio/discussions/501)

There is no straight forward way to capture sip traffic debug logs etc from everyday usage.

Perhaps something similar to [K9/ Mail](https://gitlab.e.foundation/e/os/mail):
![Screenshot_20241027-074125_Mail](https://github.com/user-attachments/assets/84cda8d4-ad0b-436e-a229-b1d174edd019)

**Comment by xpseudonym** [comment]
You got there before I did - thank you, I d/l a couple of days ago and it seems to be absolutely fab!  Now, I can begin to sort out what's coming and going when my elderly mother on the other side of the earth says I'm always engaged, but I can call myself from this side of the earth...

**Comment by juha-h** [comment]
Good if the new Logcat menu action works for you.
