### ISSUE TITLE
baresip+ as client for video door bell (supporting video in early mode)

### ISSUE THREAD

**Issue by tim-ka** [juha-h/baresip-studio#508]
Hi!
I'm going to use baresip+ as a client for a video door bell (one way video, two way audio). Important feature for such kind of clients is supporing the early media mode and showing a video before answer on the call. For example, linphone android app and linhome have such kind of feature, but have some problems with H.264 video decoding, but it's another story.
So I look the code (i'm totally zero with Kotlin) and baresip library, which already have support for early_media and made a patch for supporting one more answer_mode - early and test it. It's seems working (I can hear sound during income call at least one way). 
[ealy_answer_mode_add.txt](https://github.com/user-attachments/files/17810884/ealy_answer_mode_add.txt)
So, as I understand, next step should be adding video widget on the income calls window before answer and makes the answer button with video works again (it's not working after my patch ;)
Here is the window screenshot in income call state with early media answer mode.  
![early_media_income_call](https://github.com/user-attachments/assets/7a8523de-5433-4fbc-877f-60308b090d26)
I will really appreciate with any help with issue implemenatation.

**Comment by juha-h** [comment]
I don't currently have resources to implement early-video answer mode.  You could try by making video layout visible and then add answer button there.
