### ISSUE TITLE
incoming call ringing never stop

### ISSUE THREAD

**Issue by ibrahimsalgin** [juha-h/baresip-studio#51]
Hello, when an incoming call occurs I press yes button and the caller can hear me but the ringing call of incoming call never stop. I guess call_establish state is never been fired in side of incoming call device.

**Comment by juha-h** [comment]
ibrahimsalgin writes:

> Hello, when an incoming call occurs I press yes button and the caller
> can hear me but the ringing call of incoming call never stop. I guess
> call_establish state is never been fired in side of incoming call.

I have never experienced this and if it would be common, it would have
been reported here before.

When debug is on, take logcat | grep Baresip of the call.

**Comment by ibrahimsalgin** [comment]
this is the logcat file. if you search for "answering call" words you will find the beginning of the call.
[baresip_logcat.txt](https://github.com/juha-h/baresip-studio/files/3620446/baresip_logcat.txt)

**Comment by juha-h** [comment]
ibrahimsalgin writes:

> this is the logcat file. if you search for "answering call" words you will find the beginning of the call.
> [baresip_logcat.txt](https://github.com/juha-h/baresip-studio/files/3620446/baresip_logcat.txt)

Yout logcat output does not show any debug lines from BaresipService or
MainActivity.  It should show how events get propagated from lib to
service and activity (see example below).  Proper events are needed for
ringing to stop and for all other things too.

Something is wrong with your application setup.  I don't what it is and
cannot help more that this.

```
09-17 17:46:50.991 23721 24085 D Baresip Lib: ua event (CALL_INCOMING) sip:test@test.tutpro.com
09-17 17:46:50.992 23721 24085 D Baresip Lib: sending ua/call 543793846416/543795680464 event call incoming
09-17 17:46:50.993 23721 24085 D Baresip Service: uaEvent got event call incoming/543793846416/543795680464
09-17 17:46:50.996 23721 24085 D Baresip Service: Incoming call 543793846416/543795680464/sip:test@test.tutpro.com
09-17 17:46:51.000 23721 24085 D Baresip Service: CurrentInterruptionFilter 1
09-17 17:46:51.071 23721 24085 D Baresip Service: Audio focus granted for stream 2
09-17 17:46:51.076 23721 23721 D Baresip : Handling service event 'call incoming' for 543793846416
09-17 17:46:51.097 23721 23721 D Baresip Service: Received onStartCommand action ProximitySensing
09-17 17:46:51.097 23721 23721 D Baresip Service: Acquiring proximity wake lock
09-17 17:46:53.290 23721 23721 D Baresip : AoR sip:foo@test.tutpro.com answering call 543795680464 from test
09-17 17:46:53.290 23721 23721 D Baresip Lib: answering call 543793846416/543795680464
09-17 17:46:53.291 23721 24086 D Baresip Lib: answering call from sip:test@test.tutpro.com with 200
09-17 17:46:53.291 23721 24086 D Baresip Lib: call: update media
09-17 17:46:53.291 23721 24086 D Baresip Lib: stream: update 'audio'
09-17 17:46:53.291 23721 24086 D Baresip Lib: stream: audio: starting RTCP wi
09-17 17:46:53.291 23721 24086 D Baresip Lib: th remote 192.168.43.99:50481
09-17 17:46:53.291 23721 24086 D Baresip Lib: audio: Set audio decoder: opus 16000Hz 1ch
09-17 17:46:53.291 23721 24086 D Baresip Lib: audio: start
09-17 17:46:53.291 23721 24086 D Baresip Lib: opensles: opening player 16000Hz, 1channe
09-17 17:46:53.291 23721 24086 D Baresip Lib: ls
09-17 17:46:53.344 23721 24086 D Baresip Lib: audio: player started with sample format S16LE
09-17 17:46:53.344 23721 24086 D Baresip Lib: audio: Set audio encoder: opus 16000Hz 1ch
09-17 17:46:53.344 23721 24086 D Baresip Lib: opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandf
09-17 17:46:53.344 23721 24086 D Baresip Lib: ec=1)
09-17 17:46:53.345 23721 24086 D Baresip Lib: audio: start
09-17 17:46:53.345 23721 24086 D Baresip Lib: webrtc_aec: creating shared state: [16000 Hz, 1 channels, subframe 160 samples, num_bands 1]
09-17 17:46:53.345 23721 24086 D Baresip Lib: opensles: opening recorder 16000Hz, 1channels
09-17 17:46:53.377 23721 24086 D Baresip Lib: audio: source started with sample format S16LE
09-17 17:46:53.377 23721 24086 D Baresip Lib: audio tx pipeline:    opensles ---> webrtc_aec ---> opus
09-17 17:46:53.377 23721 24086 D Baresip Lib: audio rx pipeline:    opensles <--- webrtc_aec <--- opus
09-17 17:46:53.384 23721 24085 D Baresip Lib: ua event (CALL_RTCP) audio
09-17 17:46:53.420 23721 24086 D Baresip Lib: call: stream start (active=1)
09-17 17:46:53.420 23721 24086 D Baresip Lib: opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000;cbr=0;useinbandfec=1)
09-17 17:46:53.420 23721 24085 D Baresip Lib: ua event (CALL_ESTABLISHED) sip:test@test.tutpro.com
09-17 17:46:53.420 23721 24085 D Baresip Lib: sending ua/call 543793846416/543795680464 event call established
09-17 17:46:53.421 23721 24085 D Baresip Service: uaEvent got event call established/543793846416/543795680464
09-17 17:46:53.422 23721 24086 D Baresip Lib: audio: start
09-17 17:46:53.422 23721 24086 D Baresip Lib: foo@test.tutpro.com: Call established: sip:test@test.tutpro.com
09-17 17:46:53.423 23721 24085 D Baresip Service: AoR sip:foo@test.tutpro.com call 543795680464 established
09-17 17:46:53.424 23721 24085 D Baresip : Saving history of size 15
09-17 17:46:54.117 23721 24085 D Baresip Service: Audio focus granted for stream 0
09-17 17:46:54.128 23721 24085 D Baresip Service: Original/new call volume of stream 3 is 9/9
09-17 17:46:54.130 23721 24086 D Baresip Lib: stream: incoming rtp for 'audio' established, receiving from 192.168.43.99:50480
09-17 17:46:54.131 23721 23721 D Baresip : Handling service event 'call established' for 543793846416
```

**Comment by ibrahimsalgin** [comment]
this is the new log file. When incoming call occurs although i press yes button, it still remains to ringing. Thank you very much for the help. 
[baresip_logcat.txt](https://github.com/juha-h/baresip-studio/files/3622442/baresip_logcat.txt)

**Comment by juha-h** [comment]
ibrahimsalgin writes:

> this is the new log file. When incoming call occurs although i press
> yes button, it still remains to ringing. Thank you very much for the
> help.

Log shows that the call was never established.  Check that the caller
received 200 OK and that callee (baresip device) received ACK.

-- Juha

**Comment by ibrahimsalgin** [comment]
the caller received 200 OK and it can hear the voice of callee but the callee device still remains ringing. If you have build libraries that included in  distribution folder (arm64-v8a and armeabi-v7a) can you please share with me? The problem may occurs because of wrong builded libraries.

**Comment by juha-h** [comment]
ibrahimsalgin writes:

> the caller received 200 OK and it can hear the voice of callee but the
> callee device still remains ringing.

Call does not get established in baresip before it gets ACK to 200 OK.

> If you have build libraries that
> included in  distribution folder (arm64-v8a and armeabi-v7a) can you
> please share with me? The problem may occurs because of wrong builded
> libraries.

I don't have the libs online.  F-Droid is automatically building baresip
app and the libs each time a new version of baresip in created:

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.tutpro.baresip.yml

If there would be something wrong in Makefile, I would hear about it.

**Comment by ibrahimsalgin** [comment]
problem still remains in all cases. Do you have any apk that work fine?

**Comment by juha-h** [comment]
ibrahimsalgin writes:

> problem still remains in all cases. Do you have any apk that work
> fine?

Try one from F-Droid or Google Play.  They both work fine (tested
today).

**Comment by ibrahimsalgin** [comment]
I tested but still same problem. It seems problem is related to configuration of the app or server. Is there any guide when registering and account or server configuration?

**Comment by juha-h** [comment]
ibrahimsalgin writes:

> I tested but still same problem. It seems problem is related to
> configuration of the app or server. Is there any guide when
> registering and account or server configuration?

baresip is a normal sip client.  there is no specific configuration
guide for it.

as i have mentioned before, i suspect that ACK does not reach your
baresip device or is not correctly formatted.

try with some other sip client, e.g, linphone.
