### ISSUE TITLE
Contact Accrescent Devs

### ISSUE THREAD

**Issue by secretmango** [juha-h/baresip-studio#514]
Hi there! It seems your app is the best FOSS VOIP app out there. It would be great to have it available on the Accrescent store soon.

The Accrescent store is still not completely open to the public, but if you ask the devs you might get an invite. It currently has 22 apps from various open source (and one proprietary) projects.

https://accrescent.app

The Accrescent store will have good privacy for users (no account, unprivileged appstore), control over their apps for devs (no signing keys need to be sent to them, unlike Google Play) and offers better security with minimum version, signed metadata and more.

https://accrescent.app/docs/guide/getting-started/index.html

(I am not part of their team or anything, but heard from a dev that it is pretty easy to get allowlisted and publish apps now)

**Comment by juha-h** [comment]
I don't have resources to publish my app in any new app store.  If Accrescent wants, they are welcome to pull my app from https://github.com/juha-h/baresip-studio/releases or roll it from the sources.
