### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by smith153** [juha-h/baresip-studio#55]
Hi, Thanks for the wonderful app. I've got calls working wonderfully and very easy to setup. However when I connect a bluetooth headset to my phone (Samsung S7), the volume continues to go through the phone ear speaker and not routed to the bluetooth headset. Is this a known limitation?

**Comment by juha-h** [comment]
Never tried myself.  I'll investigate.

**Comment by juha-h** [comment]
Use of bluetooth headset/microphone is not currently supported.  Turned out that it requires quite a lot new code to be written.  I'll give this issue enhancement (new feature) label.

**Comment by smith153** [comment]
Ah I see, that is unfortunate.

**Comment by juha-h** [comment]
@smith153 Version 12.0.0 now has initial support for routing audio through Bluetooth headset.  It has worked in my tests with an Android 9.0 device.  Give it a try when it appears in Google Play or F-Droid or roll your own from GitHub.

**Comment by juha-h** [comment]
I have tested Bluetooth on three different Android versions and it has worked OK.  Re-open if needed.
