### ISSUE TITLE
Custom sip server port 

### ISSUE THREAD

**Issue by oktayaa** [juha-h/baresip-studio#58]
user@domain:port is not accepted. How is this configured?

**Comment by juha-h** [comment]
oktayaa writes:

> user@domain:port is not accepted. How is this configured?

Where is it not accepted?

Account needs to be of form user@domain.  You can include port in
Outbound Proxhy URI.

**Comment by oktayaa** [comment]
But I don't have a proxy. If I did the server would still need a port set
to 9871 in my case.

On Monday, October 28, 2019, juha-h <notifications@github.com> wrote:
> oktayaa writes:
>
>> user@domain:port is not accepted. How is this configured?
>
> Where is it not accepted?
>
> Account needs to be of form user@domain. You can include port in
> Outbound Proxhy URI.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/pd0bVMBLrrQhmjE6K_Rot10ZCEjE6OQYywK7AMggy10aC9DzcMjqf-_x2rL5gxUeh1kM9TvojqkF-WwoU3P8VxhempLM3LnlrGPW4hhZFGnFol-XjBKKKx2zbt0g9_-clfSjAqnAnOmU-FA-Kj_62_iy1Vtz1NymTZ5ZDjjHtzzmBG4GhA4Id8xQiDcGij9nqIv0DhGb9NIcRSi641MMLnHHnuP0FqZbdEGqViT3Cw=s0-d-e1-ft#https://github.com/notifications/beacon/AGDFTCMXJSEGDPJFL4327LTQQ4HVNA5CNFSM4JF4FY6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECNQQVA.gif>

**Comment by juha-h** [comment]
oktayaa writes:

> But I don't have a proxy. If I did the server would still need a port set
> to 9871 in my case.

When you make a call or send a message you can include the port in
Callee or Chat Peer URI, e.g., foo@bar:9871.

**Comment by oktayaa** [comment]
I am not talking about the recipient. This is the account I have to
register with.

**Comment by juha-h** [comment]
oktayaa writes:

> I am not talking about the recipient. This is the account I have to
> register with.

There is no separate URI for Registrar and Outbound Proxy. Create SIP
SRV and A DNS records for your domain so that you when you register as
user@domain, REGISTER request is sent to that port.

**Comment by oktayaa** [comment]
OK I can do this and it would be nice to have a SRV in DNS too but
literally every client I've ever tried allows setting a custom port for the
server. Something to consider.

**Comment by juha-h** [comment]
oktayaa writes:

> OK I can do this and it would be nice to have a SRV in DNS too but
> literally every client I've ever tried allows setting a custom port for the
> server. Something to consider.

I'll consider.

**Comment by juha-h** [comment]
It now possible in version 12.1.0 to add port number to AoR of new accounts. Give it a try.

**Comment by oktayaa** [comment]
Hello thanks for taking the time to implement the feature. I have NOT been
able to register to my server with a custom port but that may be an
unrelated issue. I cannot be sure.

**Comment by juha-h** [comment]
I'll close this now. Reopen if you still think there exists a user@domain:port related account issue and provide `adb logcat | grep Baresip` output showing it.
