### ISSUE TITLE
"You have not granted microphone permission" error when attempting outgoing call 

### ISSUE THREAD

**Issue by afcady** [juha-h/baresip-studio#59]
I am attempting to call from Android `baresip-studio` to a PC on the same LAN running `baresip`.  

I put the SIP url, then press the green "call" icon, which turns to the red "hang up" icon.  After about 1 second, the error messsage pops up at the bottom of the screen.  Then the phone icon then turns back to the green.  The `baresip` on the other end doesn't show any incoming call.

**Comment by afcady** [comment]
I'm using the `com.tutpro.baresip_100.apk` from F-Droid.

**Comment by juha-h** [comment]
As the message tells, you have not granted microphone permission and
thus cannot make a call.  Go to Settings/Apps/baresip/Permissions and
grant it.

**Comment by afcady** [comment]
It should be prompting for this though, like other applications do.

**Comment by afcady** [comment]
I guess I should add that, upon install, the installer says that the application requires no special permissions.  It did not ever ask for microphone permissions or any others.

**Comment by juha-h** [comment]
afcady writes:

> I guess I should add that, upon install, the installer says that the
> application requires no special permissions.  It did not ever ask for
> microphone permissions or any others.

I don't know about F-Droid installer.  Microphone permission is
optional.  It is only needed if you make calls.  You can send/receive
chat messages without it.  So it is not a good idea to force microphone
permission for every user.

**Comment by afcady** [comment]
I didn't use the F-Droid installer, I downloaded the `.apk` from the f-droid.org web site.  But I don't think this matters at all.

Other android applications will pop up a request for permission at the time that the permission is needed.

See https://www.geeksforgeeks.org/android-how-to-request-permissions-in-android-application/

**Comment by juha-h** [comment]
Commit 853c65d45f529168ffcd06d6efc93abe125353c9 improved asking of permissions and acting on the answers.  It was not feasible (== too difficult) to ask microphone permission when needed, since calls can come in when baresip activity is not running.  Instead, now microphone and phone permissions are asked when baresip is started (if not already granted or permanently denied) and explanation is given on what effect it has if user does not grant a permission.  I'll create a new version tomorrow.

**Comment by juha-h** [comment]
@afcady Check version 13.0.1 when it shows up in F-Droid and reopen if the issue still persists.

**Comment by afcady** [comment]
Sounds good.
