### ISSUE TITLE
Avoid crash at quit

### ISSUE THREAD

**Issue by goderfly** [juha-h/baresip-studio#6]
Hello, i faced up with crash at baresip_stop. Can u pls give me changes in native distribution files of this commit https://github.com/juha-h/baresip-studio/commit/a417bf356578fa9632674ad33bfd8348c72ca54d

I have my personal changes and i dont want to cancel them. Just recompile with your changes

**Comment by juha-h** [comment]
goderfly writes:

> Hello, i faced up with crash at baresip_stop. Can u pls give me
> changes in native distribution files of this commit
> https://github.com/juha-h/baresip-studio/commit/a417bf356578fa9632674ad33bfd8348c72ca54d

I used then (13 days ago) latest baresip master to build libbaresip.a.
You need to check from https://github.com/alfredh/baresip, what changes
was made between 29 days (previous libbaresip.a) and 13 days ago.
