### ISSUE TITLE
Display name in contacts has unnecessary restrictions on characters, length

### ISSUE THREAD

**Issue by afcady** [juha-h/baresip-studio#60]
Attempting to add a contact with name `a` causes an `Error` popup saying `Invalid contact name 'a'`.  Other invalid names: `abc@host` and the empty string.

All printable characters should be allowed, there should be no minimum length, and the field itself should be optional (it should display the SIP URI if the string is empty).

**Comment by juha-h** [comment]
I tried to address this in commit https://github.com/juha-h/baresip-studio/commit/03776b99a786ed6bf09461752b850ae32661994e.  There is no check for non-printable chars, since the value comes from EditText field.

**Comment by juha-h** [comment]
@afcady Check version 13.0.1 when it shows up in F-Droid and reopen if the issue still persists.

**Comment by afcady** [comment]
Awesome, thanks.
