### ISSUE TITLE
Build baresip-android libraries for android-x86

### ISSUE THREAD

**Issue by Telefonorosso** [juha-h/baresip-studio#61]
Hello and thank you for this excellent project.
I'm adapting your app to better suit my needs.
The needed [baresip-android](https://github.com/alfredh/baresip-android) libraries builds flawlessly for testing on a real world smartphone.
How about compiling them for the emulated x86 AVD "phone" provided in Studio?
What would be the steps?
Thanks again,
TR

**Comment by juha-h** [comment]
Try to set ANDROID_TARGET_ARCH in https://github.com/juha-h/libbaresip-android Makefile to whatever architecture the emulator uses.

**Comment by Telefonorosso** [comment]
Hello and thank you for your time.
ANDROID_TARGET_ARCH := x86
does build without errors but the x86 folder in target directory is not created.
How should I tweak these others flags in the Makefile?

`ifeq ($(ANDROID_TARGET_ARCH), x86)
        TARGET       := arm-linux-androideabi
        CLANG_TARGET := armv7a-linux-androideabi
        ARCH         := arm
        OPENSSL_ARCH := android-arm
        MARCH        := armv7-a
`

**Comment by juha-h** [comment]
First of all, this issue is does not belong to baresip-studio project. Please move it to https://github.com/juha-h/libbaresip-android project.

I don't know how to deal with x86 architecture and it is not currently supported by libbaresip-android project.  I once tried the emulator and it was far too slow on my laptop.

Perhaps you can find from the net, how the variables need to be set for it.  Once you have done it, there will be a directory for that arch in each of the distribution sub-directories, when you execute
```
make install ANDROID_TARGET_ARCH=x86
```

**Comment by Telefonorosso** [comment]
Thanks again, I'll investigate that.

**Comment by assegaf** [comment]
how the result of running and x86_64 ? at least running well ?

**Comment by juha-h** [comment]
A few weeks ago I tested and was able to run baresip in Android Studio emulator (Pixel 5 API 30) with libbaresip-android `ANDROID_TARGET_ARCH := x86_64` libraries.  It was just a test and I cannot guarantee anything.

**Comment by assegaf** [comment]
are you use latest version of https://github.com/juha-h/libbaresip-android ?,
seem compilation error. I will further try to follow do this, on my debian based pc ... probably my settings/libs etc



but old version I saved months/year ago, success, but when running on X86 i got error in System.loadLibrary("baresip") 
the error is libpthread not found, any suggestion

![image](https://user-images.githubusercontent.com/551532/169979977-14d27489-c60e-4aab-bcce-22a0e838f6d0.png)

**Comment by juha-h** [comment]
I just tried by first installing libs:
```

/usr/src/libbaresip-android$ make install ANDROID_TARGET_ARCH=x86_64
```

Then I added 'x86_64' to app/build.gradle abiFilters line:
```
ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }
```
After that, run of baresip worked fine in Android Studio:

https://tutpro.com/tmp/Screenshot_2022-05-24_12-58-05.png

Try the same.  Sorry, but I don't have more time on  'x86_64'.

**Comment by assegaf** [comment]
great,  there is prove its working, I will try investigate on it,

**Comment by AviWA** [comment]
I am getting error when i want to run the imported project (baresip studio) 

CMake Error at CMakeLists.txt:20 (find_package):
  Could not find a package configuration file provided by "re" with any of
  the following names:

    reConfig.cmake
    re-config.cmake

  Add the installation prefix of "re" to CMAKE_PREFIX_PATH or set "re_DIR" to
  a directory containing one of the above files.  If "re" provides a separate
  development package or SDK, be sure it has been installed.

If you aware of this error please reply 

Thanks in Advance.

**Comment by mwadudjar** [comment]
> I am getting error when i want to run the imported project (baresip studio)
> 
> CMake Error at CMakeLists.txt:20 (find_package): Could not find a package configuration file provided by "re" with any of the following names:
> 
> ```
> reConfig.cmake
> re-config.cmake
> ```
> 
> Add the installation prefix of "re" to CMAKE_PREFIX_PATH or set "re_DIR" to a directory containing one of the above files. If "re" provides a separate development package or SDK, be sure it has been installed.
> 
> If you aware of this error please reply
> 
> Thanks in Advance.

I have the same issue, did you manage to fix it?

**Comment by mtsanket** [comment]
> Reference

Same issue.
