### ISSUE TITLE
Lack of clarity on udp vs tcp vs tls, and port numbers

### ISSUE THREAD

**Issue by gdt** [juha-h/baresip-studio#62]
I am trying to add  an account which is basically user@domain:port.   I can do that, but there is nothing in the UI that says whether baresip will register with UDP, TCP or TLS.  As a lot of the point of TLS is to protect account credentials, I would like there to be a connection type property that I can set to TLS.

**Comment by juha-h** [comment]
If port is specified, but transport is not, transport defaults to udp (RFC 3261).  I'll try add also optional transport to AoR.

**Comment by gdt** [comment]
Thanks.  Mostly I meant that even though I pretty much understand the standards, it was still hard to figure out transport.

**Comment by juha-h** [comment]
Version 15.1.0 now includes possibility to specify also transport protocol for the AoR.  Help text is also available about it in Accounts menu.  Reopen if this is still an issue.

**Comment by gdt** [comment]
I am still finding this confusing.   I put the port and ;transport=tls in the AOR (which feels odd, but maybe that's me), and still couldn't connect.  I then added my asterisk server as an "outbound proxy", and got things to work.

I am wondering if the tls is getting lost.   I deleted and re-added the account, and could see the ";transport=tls".  But then after various going back and forth, now it's gone from the accounts view. 

Not sure if this is related, but I see an outbound proxy setting, but not a regular proxy.  However it seems to be used for registration.

Without a proxy, I can't register, even though the proxy is the same host/port/transport as the aor.   And I see UDP packets arriving to the same number as my TLS port.   So I think transport=tls is getting added but then lost on reading the account back from the DB.

I'm also unclear on yellow for the account; it might mean registration pending and not failed, it might mean registration not asked for, and it might mean something else.

**Comment by gdt** [comment]
Let me know if you want a new bug/bugs that's crisp about the new issues.

**Comment by juha-h** [comment]
I tested with these two accounts:
```
test@test.tutpro.com:5060;transport=tcp
test@test.tutpro.com:5061;transport=tls
```
(without setting Outbound Proxies) and both accounts registered without problems at the registrar pointed to by test.tutpro.com IP address.

If you have problems, check the wireshark or ngrep what happens at your registrar.

Yellow color has multiple meanings: (1) Register is not checked or (2) registration is in progress.
