### ISSUE TITLE
AOR is not editable

### ISSUE THREAD

**Issue by gdt** [juha-h/baresip-studio#63]
After creating an account, I can edit a lot of things.  But the user@domain:port part is not editable.It seems like this should be part of the form with the rest of the parameters.  (I realize there needs to be a check that the new name doesn't collide with another account.)
This is minor, as it's easy to delete and start over.

**Comment by juha-h** [comment]
Editing AoR is not just a simple edit.  The account needs to be deleted and a new one created, account spinner updated, etc.  So, I'm not planing to do it.
