### ISSUE TITLE
Error with inbound calls over IPv6 <incompatible address-family>

### ISSUE THREAD

**Issue by simonsimon006** [juha-h/baresip-studio#64]
I have an asterisk pbx with an ipv6 and ipv4 address which is connected to a SIP Provider. Baresip Android registers with TLS at said pbx. When I call out everything works. But if I am called it rejects the call with:
> incompatible address-family (local=AF_INET6, remote=AF_INET)

which I do not understand, as my LAN and pbx is IPv6 capable.

From reading the logs baresip seems to see the IPv6 address but still fails.

I have attached a logcat dump from the baresip process.
[baresip.log](https://github.com/juha-h/baresip-studio/files/3908684/baresip.log)

**Comment by juha-h** [comment]
My Internet is currently so slow that I can't read the log. Make sure that call the comes in to baresip over IPv6.

**Comment by simonsimon006** [comment]
From what I can see in my asterisk log the call is passed to the correct IPv6 address of my client over the established TLS connection.

**Comment by simonsimon006** [comment]
I checked with an IPv6 only network and the same issue persists.

**Comment by juha-h** [comment]
Try checking Prefer IPv6 in Settings if not already done.

**Comment by simonsimon006** [comment]
The setting is turned on.

**Comment by juha-h** [comment]
In Settings, check Debug, turn on  "adb logcat | grep Baresip" logging, start baresip, and place the incoming call.  Then show the logging.

**Comment by simonsimon006** [comment]
I did. The log is attached.

[baresip.log](https://github.com/juha-h/baresip-studio/files/3939107/baresip.log)

**Comment by juha-h** [comment]
I looked at the log. Perhaps it would help to add interface name to the IPv6 address. I'll check if the API supports it.

**Comment by juha-h** [comment]
There is no way in baresip API to set interface name.  If your device has Android API level 24 or higher, I could create an apk for you to try that should be able to detect the name of the IPv6 interface automatically. Perhaps that would fix the issue.

**Comment by simonsimon006** [comment]
My phone supports it, we can try this.

**Comment by juha-h** [comment]
hytrax writes:

> My phone supports it, we can try this.

OK, try this:
```
https://box.tutpro.com/tmp/baresip.apk
```
Take logcat of starting baresip and placing a call.

**Comment by juha-h** [comment]
Forgot to mention that you need to uninstall existing baresip (if any)
before installing the new apk:
```
$ adb uninstall com.tutpro.baresip
$ adb install baresip.apk
```
Also, take backup before uninstall and restore after install.

**Comment by simonsimon006** [comment]
I did it.

[baresip.log](https://github.com/juha-h/baresip-studio/files/4032814/baresip.log)

**Comment by juha-h** [comment]
I checked the new log and didn't find incompatible address-family messages.  Calls seemed to be working using both IPv4 and IPv6.

Did you still notice some issues?

**Comment by simonsimon006** [comment]
No, I did not. But I currently am in a slightly different environment than when the error occured before thus testing might be less meaningful.

**Comment by juha-h** [comment]
It turned out that error message
```
incompatible address-family (local=AF_INET6, remote=AF_INET)
```
may also come if media IP address in SDP is incompatible.  According to RFC 6157, ICE should be used to find out which IP version works for both caller and callee.

**Comment by juha-h** [comment]
I just created a new baresip version 16.0.0, where global setting "Prefer IPv6" is replaced with an account specific "Prefer IPv6 Media" setting.  Try with that and reopen as a new issue if still problems.
