### ISSUE TITLE
g711 support

### ISSUE THREAD

**Issue by sosaucily** [juha-h/baresip-studio#65]
Hi, 

Seems g711, although not the most efficient codec for voip, is very widespread. I'm trying to use this library to connect to other clients that only support g711. Is it possible to support that codec as well?

**Comment by juha-h** [comment]
G711 is supported (PCMU, PCMA).

**Comment by sosaucily** [comment]
I didn't see it listed in the settings page of the app, and when I called a standard baresip server (without opus), it did not successfully find a matching codec. With opus it works after selecting opus in the settings page.

Is g711 supported under the hood without a setting on that page? If so, any idea why it didn't find a match to my vanilla baresip client? I was using antisip as the server. Thx

**Comment by juha-h** [comment]
There should be g711 listed under Settings/Audio Modules. When you check that, you can choose PCMU and A in Account configuration.
