### ISSUE TITLE
Usage of the unZip function from Utils.kt

### ISSUE THREAD

**Issue by Telefonorosso** [juha-h/baresip-studio#67]
Dear sir,
Thank you for this excellent work.
I I'm trying to unpack a regular zip file created under Linux in order to automate the provisioning of the Baresip Android app.
The directory structure inside my zip file is the one expected by the app:

**/data/user/0/com.tutpro.baresip/files/***

Nonetheless, the unZip function fails with this exception:

`12-11 15:13:22.672 12005-12005/com.tutpro.baresip W/Baresip: Failed to unzip file '/data/user/0/com.tutpro.baresip/files/baresip.zip': java.io.FileNotFoundException: data/user/0/com.tutpro.baresip/files: open failed: EISDIR (Is a directory)`

A leading slash seems to be missing but modifying the unZip routine to prepend it didn't help.
My backend creates the source zip file with this command:

`zip -r baresip.zip /data/user/0/com.tutpro.baresip/files/`

Any help would be greatly appreciated.
Greetings, TR

**Comment by Telefonorosso** [comment]
Solved by modifying backend like this:
`zip -r /var/www/html1/BS/baresip.zip /data/user/0/com.tutpro.baresip/files/*`

**Comment by Telefonorosso** [comment]
Sorry to reopen.
Is there a way to craft encrypted Baresip config files from Bash with standard means like openssl or similar?
I'm able to forge unencrypted .bs files and to modify Baresip Studio to accept them but I'm willing to use "vanilla" Baresip in my project.
Thank you very much.

**Comment by juha-h** [comment]
Telefonorosso writes:

> Is there a way to craft encrypted Baresip config files from Bash with
> standard means like openssl or similar? 
> I'm able to forge unencrypted .bs files and to modify Baresip Studio
> to accept them but I'm willing to use "vanilla" Baresip in my
> project.

Encryption/decryption is done by encrypt[ToFile]/decrypt[FromFile]
functions in Utils.kt.  I don't think there exist equal cli commands,
but you should be able to create them by writing two Java programs that
call those functions.

**Comment by Telefonorosso** [comment]
Thanks a lot, closing again

**Comment by Telefonorosso** [comment]
Hello sir.
Is this example even remotely close?
https://stackoverflow.com/questions/8343894/aes-encrypt-with-openssl-command-line-tool-and-decrypt-in-java
Thank you very much.

**Comment by Telefonorosso** [comment]
Ok, with a lot of manual work I'm now able to DECRYPT only. Note to self:

1) grab the baresip.bs file
2) "deserialize" it with this Java tool:
https://github.com/NickstaDB/SerializationDumper
3) manually extract IV, SALT and DATA
4) calculate the KEY with this other tool:
https://asecuritysite.com/encryption/PBKDF2z
5) use openssl to decrypt:

> openssl enc -d -iter $ITER -S $SALT -iv $IV -pbkdf2 -aes-128-cbc -in rawdata.bin -out baresip.bs -K $KEY

Has been a long night. Cheers, TR

**Comment by juha-h** [comment]
Telefonorosso writes:

> Ok, with a lot of manual work I'm now able to DECRYPT only. Note to self:
> 
> 1) grab the baresip.bs file
> 2) "deserialize" it with this Java tool:
> https://github.com/NickstaDB/SerializationDumper
> 3) manually extract IV, SALT and DATA
> 4) calculate the KEY with this other tool:
> https://asecuritysite.com/encryption/PBKDF2z
> 5) use openssl to decrypt:
> 
> > openssl enc -d -iter $ITER -S $SALT -iv $IV -pbkdf2 -aes-128-cbc -in rawdata.bin -out baresip.bs -K $KEY
> 
> Has been a long night. Cheers, TR

Yes, crypto is not easy.
