### ISSUE TITLE
Opus bitrate / samplerate for best audio quality

### ISSUE THREAD

**Issue by Telefonorosso** [juha-h/baresip-studio#69]
Dear sir,
I'm trying various permutations of config entries:

> opus_bitrate 48000
> opus_samplerate 48000

and account entries:

> audio_codecs=opus/48000/1

to achieve best possible audio quality.
With the ones listed above audio is crippled (cannot decode it with Wireshark and attach it here since Opus codec is not supported by Wireshark itself). Almost similar to static noise.
Also I'm wondering if

> opus_application voip
> ausrc_format s16
> auenc_format s16
> auplay_format s16

> ptime=20 

Come into play.
The call is direct, without any IPPBX in between.
Baresip Studio is version 15.1.1, Android 6 and Android 5 (phones).
Thank you very much.

**Comment by juha-h** [comment]
Only Opus Bitrate and expected packet loss can be changed.  Other opus
settings cannot without loosing AEC.

**Comment by Telefonorosso** [comment]
Hello! Fine but why am I facing this crippled audio? Am I setting up incompatible values? Do I need to "manually" disable AEC? Thank you.

**Comment by juha-h** [comment]
If you don't care about AEC, you can use default audio/opus
configuration:

- remove these:

ausrc_format s16
auenc_format s16
auplay_format s16
audec_format s16
opus_samplerate 16000

- use higher opus bitrate and opus stereo

Your account codec then is OPUS/48000/2.

**Comment by Telefonorosso** [comment]
Thanks a lot, I'll try that and report back. Have a nice day.

**Comment by Telefonorosso** [comment]
That worked flawlessly on 3 different Android releases running Baresip 15.1.1
Wonderful project! Closing.
