### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by Telefonorosso** [juha-h/baresip-studio#71]
Good evening!
Build of APK fails in Win 10, Android Studio 3.5.3.
Error is attached.
"distribution" binaries compiled on Ubuntu 18.04 with "make install-all" reported no errors.
Thank you,
TR
[build-error-message.txt](https://github.com/juha-h/baresip-studio/files/4128626/build-error-message.txt)

**Comment by juha-h** [comment]
You are not using latest version of baresip.c.  Make sure thet your baresip and baresip-studio sources are the current ones.

**Comment by Telefonorosso** [comment]
Ok thank you. I'll report back.

**Comment by juha-h** [comment]
Open if problems with latest sources.
