### ISSUE TITLE
Registration failed in android

### ISSUE THREAD

**Issue by magnatestech** [juha-h/baresip-studio#72]
Registration is working perfectly on below Pie(Android 9), but it fails in android pie and android 10 with authentication issue.

JNIEXPORT jint JNICALL
Java_com_iotran_ioconnect_voipmodels_Api_ua_1register(JNIEnv *env, jobject thiz, jstring javaUA) {
    const char *native_ua = (*env)->GetStringUTFChars(env, javaUA, 0);
    struct ua *ua = (struct ua *) strtoul(native_ua, NULL, 10);
    (*env)->ReleaseStringUTFChars(env, javaUA, native_ua);
    LOGD("registering UA '%s'\n", native_ua);
    return ua_register(ua);
}

above function should return zero but it returns non-zero value '22'

**Comment by juha-h** [comment]
Registrations work fine on my Android 9 device (Android One).  You need to take 'logcat | grep Baresip' of the attempt.

**Comment by magnatestech** [comment]
Thanks for your response sir.

I resolved that issue but for that I have to put IP address instead of domain name in SIP registration link, but I will not get ip address in future I always will get domain name. so now my query is that in android 9 and android 10 how can I register with domain name?

**Comment by juha-h** [comment]
As I said, registration works fine on my Android 9 device using a domain name in an Outbound Proxy or without any Outbound Proxies, in which case baresip makes DNS NAPTR/SRV/A queries to find the registrar.

Baresip gets DNS servers either from Settings or from Android when it starts.  If you have not given any DNS servers in Settings, check with logcat that baresip gets them from the Android when it starts, for example:
```
...
02-12 10:13:47.410 12008 12008 W Baresip : dyn_dns yes
02-12 10:13:47.410 12008 12008 W Baresip : dns_server 203.118.191.1:53
02-12 10:13:47.410 12008 12008 W Baresip : dns_server 203.109.191.1:53
...
02-12 10:13:47.869 12008 12045 D Baresip Lib: --- Network debug ---
...
02-12 10:13:47.869 12008 12045 D Baresip Lib:  DNS Servers from Config: (2)
02-12 10:13:47.869 12008 12045 D Baresip Lib:    0: 203.118.191.1:53
02-12 10:13:47.869 12008 12045 D Baresip Lib:    1: 203.109.191.1:53
```
Also, make sure that you have the latest baresip 16.0.1 installed.

**Comment by magnatestech** [comment]
Thank you sir for your response. I resolved the issue.
