### ISSUE TITLE
Account colors are not documented

### ISSUE THREAD

**Issue by gdt** [juha-h/baresip-studio#73]
I know Android culture is to have apps that do not require documentation, but I'm having a hard time precisely understanding things.  I'm not sure where docs belong; I'd be fine with a USING.md in git linked from README.md, and maybe in the app.    I have provoked failing behavior from another problem, but this bug report is about the UI and documentation.

There is a ball next to the AOR, which I have seen red/yellow/green.   I have come to believe that red means failure, and green means success of some kind.   Yellow seems to be indeterminate, and I'm not sure if it can persist; when intending to register with a setup that fails, I see yellow for a while and then red.  With a setup that works, I see green.

This is complicated by being able to register or not register.  If I configure the account not to register, it stays yellow, which I think now means "not trying to register", whereas before it meant "trying but have not yet succeeeded or failed". 

In this state, I tried a call to hello,world extension, and it showed in process for a long time and then went back to showing me a blank Callee and green phone.   The ball stayed yellow.   I get it that registering and calls are different, but with the same AOR and no proxy, they are related.

I suggest
  - using blue for "not trying to register" (or something)
  - explaining someplace
  - perhaps having something about the recent status of talking to the server for outoing calls, perhaps a second ball to the right of the AOR.

**Comment by juha-h** [comment]
I agree that there is currently no explanation of registration status
colors and that yellow is confusing because of double meaning.

When I'll have time, I'll change non-registering account status color to
white add try to add help text about the colors somewhere.

**Comment by gdt** [comment]
Another thought is to have a circle-slash with an R in it, to be a bigger clue that there is no registration attempt.   I realize the default of not registering a new account is likely intentional, but it seems likely to be unexpected to some.

**Comment by juha-h** [comment]
Account status icon colors are now documented on About page of 17.0.0.  White circle is used if registrations have not been enabled for an account.
