### ISSUE TITLE
AOR with odd port and TLS doesn't work without a proxy

### ISSUE THREAD

**Issue by gdt** [juha-h/baresip-studio#74]
I configured an AOR "user@asterisk.example.com:PORT;transport=tls".
If I configure an "outbound proxy" of "sip:asterisk.example.com:PORT;transport=tls" then registration and outbound calls (to extensions) work, and inbound calls ring, with no observed problems.  If I deconfigure the proxy, then registration fails and outbound calls (to extensions) fail.  If I reconfigure it, I can register and make outbound calls again.   So some part of the PORT and tls AOR config seems not to take effect.  I can see the PORT in the header when I edit the account but the transport=tls appears gone.

(Really, I'd like to see the port and TLS be part of config, not AOR, with a "use this port and this transport instead of what the SRV process returns", but I gather you don't want to do that.  If I'm confused let's open an issue for that.)

**Comment by juha-h** [comment]
Greg Troxel writes:

> I configured an AOR "user@asterisk.example.com:PORT;transport=tls".

> If I configure an "outbound proxy" of
> "sip:asterisk.example.com:PORT;transport=tls" then registration and
> outbound calls (to extensions) work, and inbound calls ring, with no
> observed problems.  If I deconfigure the proxy, then registration
> fails and outbound calls (to extensions) fail.  If I reconfigure it, I
> can register and make outbound calls again.   So some part of the PORT
> and tls AOR config seems not to take effect.  I can see the PORT in
> the header when I edit the account but the transport=tls appears
> gone.

Do you have port and transport in the AoR also when outbound proxy has
been configured?

I don't see why AoR port and transport would be needed when there is an
outbound proxy,

> (Really, I'd like to see the port and TLS be part of config, not AOR,
> with a "use this port and this transport instead of what the SRV
> process returns", but I gather you don't want to do that.  If I'm
> confused let's open an issue for that.)

I myself have never had any use of port and transport included in AoR,
since I use outbound proxy.  I added support for them, when someone
asked.

Also, I don't think it is very common to have a registrar that is not
behind an outbound proxy or that doesn't also act as an outbound proxy.

Which header do you mean that has transport=tls missing?

**Comment by juha-h** [comment]
Greg Troxel writes:
> (Really, I'd like to see the port and TLS be part of config, not AOR,
> with a "use this port and this transport instead of what the SRV
> process returns", but I gather you don't want to do that.  If I'm
> confused let's open an issue for that.)

You can override DNS SRV records by defining outbound proxy URI with
port and transport.

**Comment by juha-h** [comment]
Found reason for missing ;transport param.  libbaresip does not store any parameters of AoR's URI, only the port.  I'll try to find a way to store is somewhere else.

**Comment by gdt** [comment]
Thanks for letting me know you found it.

Makes sense about proxy.  I am finding the terminology confusing, as I thought "outbound proxy" was a proxy to be used when making an outgoing call to a SIP URI that is perhaps not on one's own server.   This seems to be usually different conceptually than a registrar proxy or plain proxy, which is used for registering.

If the proxy field in baresip is used for registration and also for outbound calls, then perhaps it should be labeled "proxy (registrar and outbound)".   I don't currently want them separated, but it seems many clients allow them to be separate.

I also don't understand the behavior with two proxy entries.  I suppose they might be tried sequentially, with the second tried if the first times out, or if it times out or fails.

Finally, it seems proxies often require authentication.   It seems normal to use one's own server (registration point) as an outbound proxy, in which case presumably the same credentials work.

**Comment by gdt** [comment]
I didn't see your earlier comment about "which header is missing", but I meant the detail page for the account, which shows port but not transport at the top.  Given that you've found it, I don't think you need more information from me.

As for what's common, I can't say.   I am trying to use asterisk, with no extra proxy so far, to only make calls that are just numbers with no domain name and hence treated as extensions by asterisk.  I realize I should probably put kamailo in front of it, and that's on the agenda, but it also seems like things should work without that so I'm working through plain asterisk first.

**Comment by juha-h** [comment]
> Makes sense about proxy. I am finding the terminology confusing, as I thought "outbound proxy" was a proxy to be used when making an outgoing call to a SIP URI that is perhaps not on one's own server. This seems to be usually different conceptually than a registrar proxy or plain proxy, which is used for registering.

The tetm "outbound proxy" comes from RFC 5626.  Registrar can be co-located with outbound proxy or be behind it.

> If the proxy field in baresip is used for registration and also for outbound calls, then perhaps it should be labeled "proxy (registrar and outbound)". I don't currently want them separated, but it seems many clients allow them to be separate.

It makes sense to define an outbound proxy, if user does not want to make calls directly.  Many cases outbound proxy can provide all kinds of services for the user (e.g. related to nat traversal, transcoding, etc).

> I also don't understand the behavior with two proxy entries. I suppose they might be tried sequentially, with the second tried if the first times out, or if it times out or fails.

Two is for redundancy as explained in the RFC.
> 
> Finally, it seems proxies often require authentication. It seems normal to use one's own server (registration point) as an outbound proxy, in which case presumably the same credentials work.

Yes, proxies require authentication from users of the domains it is serving.  It is not a good idea to have an open relay for spamming.

**Comment by juha-h** [comment]
Greg Troxel writes:

> As for what's common, I can't say.   I am trying to use asterisk, with
> no extra proxy so far, to only make calls that are just numbers with
> no domain name and hence treated as extensions by asterisk.  I realize
> I should probably put kamailo in front of it, and that's on the
> agenda, but it also seems like things should work without that so I'm
> working through plain asterisk first.

If your Asterisk handles registrations and is able to forward INVITE
requests to called parties, then it also acts as a SIP proxy.

Put a separate SIP proxy in front of it only if Asterisk lacks some
features you need and can find in a SIP proxy such as Kamailio.

**Comment by gdt** [comment]
With asterisk, I'm using it as a PBX, and my sip URI for that is not something I want to deal with other people with.  This is basically making my phone (for that AOR) be an extension on my PBX.
(Agreed on the other comment.)

**Comment by gdt** [comment]
> The tetm "outbound proxy" comes from RFC 5626. Registrar can be co-located with outbound proxy or be behind it.

Yes, but I thought when you configured an "outbound proxy" it was used for outgoing calls, and not necessarily for registration.  Reading the RFC, it seems to exclude registration from the definition ("Authoritative Proxy").

> It makes sense to define an outbound proxy, if user does not want to make calls directly. Many cases outbound proxy can provide all kinds of services for the user (e.g. related to nat traversal, transcoding, etc).

Completely agreed.  I just did not expect registration to use something labeled outbound proxy.

My impressions are partially based from configuring an OBI device.  It has "service provider proxy" and "outbound proxy" separately.   I think baresip uses the given proxy for both registration and outbound calls, and I was only trying to suggest that this be clearer.

> > Finally, it seems proxies often require authentication. It seems normal to use one's own server (registration point) as an outbound proxy, in which case presumably the same credentials work.
> 
> Yes, proxies require authentication from users of the domains it is serving. It is not a good idea to have an open relay for spamming.

Of course.   But I guess the question is what credentials.  Is it a safe assumption that the user's registration credentials are usable with the outbound proxy, and that therefore the outbound proxy must be tightly administratively linked with the registrar?   I guess that is how it basically always is, but it seems like a big assumption.   The OBI config also assumes this.

So I guess all I mean about proxies is:
Please adjust the language so that it's clear that the proxy is used for registration and not just calls.

unless I am confused and this is truly obvious and 100% always true from the RFCs.

**Comment by juha-h** [comment]
AoR with transport param should now be properly saved and used in 17.0.0.  Reopen if the issue persists.
