### ISSUE TITLE
Android unregister

### ISSUE THREAD

**Issue by magnatestech** [juha-h/baresip-studio#75]
Not able to release ( Unregister / Deactivate ) sip number from android app.
I am using below code to deactivate sip account.

String uri = ""; // SIP Account URL
String ua = Api.ua_alloc(uri);
Api.ua_unregister(ua);

**Comment by juha-h** [comment]
magnatestech writes:

> Not able to release ( Unregister / Deactivate ) sip number from android app.
> I am using below code to deactivate sip account.
> 
> String uri = ""; // SIP Account URL
> String ua = Api.ua_alloc(uri);
> Api.ua_unregister(ua);

Sorry, but this (baresip-studio) is not the correct forum for issues
related to development of your own Android app.

**Comment by magnatestech** [comment]
Thanks for your response,
From where can I get answer of my query.

**Comment by juha-h** [comment]
magnatestech writes:

> Thanks for your response,
> >From where can I get answer of my query.

There is baresip project, but you must be much more specific regarding
your issue in order to post there.  Also, most likely you need to make
your source code publicly available.
