### ISSUE TITLE
Android AEC problem

### ISSUE THREAD

**Issue by kar-l** [juha-h/baresip-studio#76]
Hello,
I have downloaded and build latest version of libbaresip-android and latest version of baresip-studio.
All are successfully build.
Application working well but AEC not. I'm running on Android 5.1.1 with tablet without native Android AEC.

In ConfigActivity.kt is one line to load webrtc_aec.so (Api.module_load("webrtc_aec.so")) but:
1. Program go in other way (yes I can make dirty fix for testing...)
2. webrtc_aec.so doesn't exists. So i don't know if I must add this lib from other source or if should be part of buld.

Thank you
Karel

**Comment by juha-h** [comment]
Check that webrtc_aec module gets build without errors when you build libbaresip.  You should see
these lines on your console:
```
  CXX [m] build-arm/modules/webrtc_aec/aec.o
  CXX [m] build-arm/modules/webrtc_aec/encode.o
  CXX [m] build-arm/modules/webrtc_aec/decode.o
```
All modules that get build are then included in libbaresip.a, which gets installed in distribution/baresip.

**Comment by juha-h** [comment]
I cannot reproduce this.  In my app, the module loads fine and webrtc_aec is activated for calls, for example:
```
03-04 11:01:27.758  3939  3998 D Baresip Lib: audio: start
03-04 11:01:27.758  3939  3998 D Baresip Lib: webrtc_aec: creating shared state: [16000 Hz, 1 channels, subframe 160 samples, num_bands 1]
03-04 11:01:27.759  3939  3998 D Baresip Lib: opensles: opening recorder 16000Hz, 1channels
03-04 11:01:27.816  3939  3998 D Baresip Lib: audio: source started with sample format S16LE
03-04 11:01:27.816  3939  3998 D Baresip Lib: audio tx pipeline:    opensles ---> webrtc_aec ---> opus
03-04 11:01:27.816  3939  3998 D Baresip Lib: audio rx pipeline:    opensles <--- webrtc_aec <--- opus
03-04 11:01:27.817  3939  3998 D Baresip Lib: call: stream start (active=1)
```
Therefore (and due to lack of activity) I'm closing this.

**Comment by kar-l** [comment]
Hello,
sorry for my lack, I'm worked on new build and some tests...
1. Yes I see correct building of modules:
 CXX [m] build-arm/modules/webrtc_aec/aec.o
  CXX [m] build-arm/modules/webrtc_aec/encode.o
  CXX [m] build-arm/modules/webrtc_aec/decode.o
In part baresip
And also see compiling AEC in part webrtc:
make[2]: Entering directory '/home/k/Android/libbare/libbaresip-android/webrtc'
[armeabi-v7a] Compile thumb  : webrtc <= aec_core.c
[armeabi-v7a] Compile thumb  : webrtc <= aec_rdft.c
[armeabi-v7a] Compile thumb  : webrtc <= aec_resampler.c
....
[armeabi-v7a] StaticLibrary  : libwebrtc.a

2. Thank you for log stack from your env. But I see some difference in the log:
02-29 18:07:48.627 3551-3600/com.tutpro.baresip D/Baresip Lib: webrtc_aec: creating shared state: [8000 Hz, 1 channels, subframe 80 samples, num_bands 1]
02-29 18:07:48.627 3551-3600/com.tutpro.baresip D/Baresip Lib: opensles: opening recorder 8000Hz, 1channels
02-29 18:07:48.628 3551-3551/com.tutpro.baresip W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
02-29 18:07:48.628 621-621/? E/AudioHardwareTiny: adev_open_input_stream:channel is not support
02-29 18:07:48.628 621-621/? D/AudioHardwareTiny: pcm_config->rate:44100,in->requested_rate:8000,in->channel_mask:2
02-29 18:07:48.636 621-621/? D/AudioHardwareTiny: in->mSpeexFrameSize:96
02-29 18:07:48.636 621-4246/? I/AudioFlinger: AudioFlinger's thread 0xb3c7b008 ready to run
02-29 18:07:48.639 3551-3551/com.tutpro.baresip D/Baresip Lib: ua event (CALL_LOCAL_SDP) answer
02-29 18:07:48.639 3551-3600/com.tutpro.baresip D/Baresip Lib: audio: source started with sample format S16LE
    audio tx pipeline:    opensles ---> webrtc_aec ---> PCMU
    audio rx pipeline:    o
02-29 18:07:48.640 3551-3600/com.tutpro.baresip D/Baresip Lib: pensles <--- webrtc_aec <--- PCMU
02-29 18:07:48.649 621-4246/? D/AudioHardwareTiny: Device     : 0x3d813686
02-29 18:07:48.649 621-4246/? D/AudioHardwareTiny: SampleRate : 0
02-29 18:07:48.649 621-4246/? D/AudioHardwareTiny: Channels   : 0
02-29 18:07:48.649 621-4246/? D/AudioHardwareTiny: Formate    : -1260621508
02-29 18:07:48.649 621-4246/? D/AudioHardwareTiny: PreiodSize : 12
02-29 18:07:48.649 621-4246/? E/AudioHardwareTiny: getInputRouteFromDevice:device:80000004
02-29 18:07:48.649 621-4246/? D/alsa_route: route_info->sound_card 0, route_info->devices 0  
02-29 18:07:48.649 621-4246/? D/alsa_route: route_set_controls() set route 21
02-29 18:07:48.652 3551-3600/com.tutpro.baresip D/Baresip Lib: call: stream start (active=1)

Please have you some idea where should be an problem?

Thank you
K.

**Comment by juha-h** [comment]
What is the problem?  You earlier reported a  issue related to creating/loading of the module.

In the log above I see some errors:
```
02-29 18:07:48.628 3551-3551/com.tutpro.baresip W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
02-29 18:07:48.628 621-621/? E/AudioHardwareTiny: adev_open_input_stream:channel is not support
```
Could they be device specific?  Have you tried with some other device? Have you given record audio permission for the app?  Does everything work OK if you disable AEC in the Settings?

**Comment by kar-l** [comment]
Sorry, maybe confusing information from me.
1. SIP client is working (with or without AEC option) but has very strong echo.
2. The first think was problem with load AEC library (loading webrtc_aec from my first post) But now I'm thinking that this part of code is unused.

About your last think to errors, I see these errors but I don't know if are fatal.
Ok, this problem should be device specific unfortunately I have not other device to test.
So I will to try solve these errors and I see result.

Thank you.

**Comment by juha-h** [comment]
kar-l writes:

> About your last think to errors, I see these errors but I don't know
> if are fatal.

The errors may have something to do with your echo problem.  I'm
experiencing very good audio quality even when delay from the other side
of world is large.
