### ISSUE TITLE
baresip takes over audio routing

### ISSUE THREAD

**Issue by nivex** [juha-h/baresip-studio#77]
Before start, at home screen, volume keys adjust ringer volume. Media (testing with VLC) audio flows to speaker.

After starting baresip, all still OK.

Pause media. Place call. Call audio flows as expected. Hang up.

Unpause media. Media audio flows to handset. Volume keys now adjust call volume, no impact on media volume.

Go back into baresip and tap the speaker icon. Media now flows to wherever this icon is set.

Quit baresip. Media stays flowing where baresip speaker icon last was. Volume keys still adjust call volume.

Only way I've found to get audio flowing and volume adjustment correctly is to reboot the device.

**Comment by nivex** [comment]
Android version 5.1
App version 16.0.1 from F-Droid.

**Comment by juha-h** [comment]
There are several audio related fixes and improvements in versions 17.0.0 and 17.1.0.  When 17.1.0 becomes available on F-Droid, check if this issue still persists. 

Unfortunately F-Droid has some problems with generating apps that include native core.   I don't know when they get fixed.

Google Play Store has 17.1.0.

**Comment by nivex** [comment]
I went ahead and installed 17.1.0 from Play Store. Behaving as expected.

**Comment by juha-h** [comment]
Kevin Otte writes:

> I went ahead and installed 17.1.0 from Play Store. Behaving as
> expected.

Thanks for testing.
