### ISSUE TITLE
not retaining account information

### ISSUE THREAD

**Issue by nivex** [juha-h/baresip-studio#78]
Running Android 5.1

Steps to reproduce:
* Install 17.1.0 from Play Store
* Launch baresip
* Create account at Accounts screen
* Return to main baresip screen
* Verify account is registered
* Restart baresip

Expected result
* Account previously defined should be displayed and register

Actual result
* Main baresip screen appears with no account defined. Tapping on pulldown displays an empty Accounts screen.

**Comment by juha-h** [comment]
Kevin Otte writes:

> Running Android 5.1
> 
> Steps to reproduce:
> * Install 17.1.0 from Play Store
> * Launch baresip
> * Create account at Accounts screen
> * Return to main baresip screen
> * Verify account is registered
> * Restart baresip
> 
> Expected result
> * Account previously defined should be displayed and register
> 
> Actual result
> * Main baresip screen appears with no account defined. Tapping on
> pulldown displays an empty Accounts screen.

I followed your steps, but was not able to reproduce the problem.  Could
you check Debug in Settings before you create the account and show what
logcat | grep Baresip tells when you create the accoun?t

What entries did you fill for that account when you configured it?

I added a debug message when accounts are saved, but that will appear in
the next version of baresip.

While testing this, I did find a bug: status dot for a new account was
initially white even when Register was checked and it should have been
yellow.

**Comment by nivex** [comment]
Steps creating account (showing only values added or changed):
aurora@pbx.home.nivex.net +
Authentication Password: secret
Register: checked
Prefer IPv6 Media: checked
Voicemail URI: 150
Save

Once the account is created I see:
```
D/Baresip Lib(27584): allocating UA '<sip:aurora@pbx.home.nivex.net>;stunserver="stun:stun.l.google.com:19302";regq=0.5;pubint=0;regint=0'
```

Then on restart I see:
```
D/Baresip Lib(28011): account: error p
D/Baresip Lib(28011): arsing SIP address: '<>;auth_pass="secret";stunserver="stun:stun.l.google.com:19302";audio_codecs=opus/16000/1,AMR/8000/1,iL
D/Baresip Lib(28011): BC/8000/1,G722/16000/1,G7221/16000/1,G726-40/8000/1,G726-32/8000/1,G726-24/8000/1,G726-16/8000/1,PCMU/8000/1,PCMA/8000/1;vm_uri
D/Baresip Lib(28011): ="sip:150@pbx.home.nivex.net";ptime=20;regint=3600;regq=0.5;pubint=0;call_transfer=yes;extra="prefer_ipv6_media=yes"'
D/Baresip Lib(28011): dl: mod: ./account.so (dlopen failed: library "./account.so" not found)
D/Baresip Lib(28011): module account.so: No such file or di
D/Baresip Lib(28011): rectory
```

I can send the full log over if that would be useful.

**Comment by juha-h** [comment]
For some reason, account's AoR is missing after restart.  I'll take a look.

**Comment by juha-h** [comment]
Could you try with
```
https://box.tutpro.com/tmp/baresip.apk
```
It worked OK on my 5.1 device.

**Comment by nivex** [comment]
That's got it. Remembered the account across a restart.

**Comment by juha-h** [comment]
Kevin Otte writes:

> That's got it. Remembered the account across a restart.

Thanks for testing.  I just added version 17.2.0 to Play store and it
should also appear on F-Droid.
