### ISSUE TITLE
option to disable mwi subscription

### ISSUE THREAD

**Issue by miconda** [juha-h/baresip-studio#79]
Is there a way to disable sending SUBSCRIBE for MWI? The voicemail uri is not set. Hope I haven't missed anything obvious. Thanks!

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> Is there a way to disable sending SUBSCRIBE for MWI? The voicemail uri
> is not set. Hope I haven't missed anything obvious.

SUBSCRIBE should not be send if VM URI is not given.  I'll check, but
will get delayed until tomorrow.

**Comment by juha-h** [comment]
When account was created, mwi subscription was on even when voicemail uri was not configured.  Should now be fixed by commit https://github.com/juha-h/baresip-studio/commit/29e5e16bafe5d2e422b81f41bb04a19cf25ef91d and in version 17.2.2. Reopen if still an issue.
