### ISSUE TITLE
Receiving Duplicated Text Message

### ISSUE THREAD

**Issue by rdcampos6** [juha-h/baresip-studio#81]
Sending text messages from any app (including baresip) makes receive instantly duplicated on baresip, dont matter the software used to send the message.

Tested sending from baresip to desktop microsip software, everything seems ok, receiving only one message.

Also in Asterisk logs seems not duplicating anything.

Android: 6.0
Kernel: 3.18.19 01003
Baresip: 18.0.1
Asterisk 13.14.1~dfsg-2+deb9u4 built by buildd @ testbuildd on a armv7l running Linux on 2018-10-16 23:52:28 UTC

**Comment by juha-h** [comment]
I tried on my Android 9.0 device and was not able to reproduce the issue.  Check with 'adb logcat | grep Baresip' what happens on your device, when it receives the message.  Settings 'Debug' needs to be checked. My test showed this:
```
05-01 08:43:59.975  8157  8194 D Baresip Lib: got message 'Hello' from peer 'sip:jh@test.tutpro.com'
05-01 08:43:59.976  8157  8194 D Baresip Lib: sending message 491837133904/sip:jh@test.tutpro.com/Hello
05-01 08:43:59.976  8157  8194 D Baresip Service: Message event for 491837133904 from sip:jh@test.tutpro.com at 1588311839976
05-01 08:43:59.982  8157  8194 D Baresip : Saved 6 messages
05-01 08:44:00.050  8157  8157 D Baresip : Handling service event 'message show' for 491837133904
05-01 08:44:00.051  8157  8157 D Baresip : Message for sip:foo@test.tutpro.com from sip:jh@test.tutpro.com
```

**Comment by juha-h** [comment]
I tried also on my Android 5.0 device and was not able to reproduce the
issue.

Are you using UDP transport protocol for SIP?  If yes, messages may get
duplicated by the SIP proxies.

**Comment by rdcampos6** [comment]
Sorry for the delay @juha-h i'm not an Android developer so I have to set the logcat and platform-tools to run adb. Here's my output:

`
05-01 14:19:35.330 D/Baresip Lib(26429): got message 'test' from peer 'sip:x@xxx.xxx.xxx.xxx:port'
05-01 14:19:35.330 D/Baresip Lib(26429): sending message 547456930192/sip:sip:x@xxx.xxx.xxx.xxx:yyyy/test
05-01 14:19:35.330 D/Baresip Service(26429): Message event for 547456930192 from sip:sip:x@xxx.xxx.xxx.xxx:yyyy at 1588353575330
05-01 14:19:35.410 D/Baresip (26429): Saved 100 messages
05-01 14:19:35.478 D/Baresip Lib(26429): got message 'test' from peer 'sip:sip:x@xxx.xxx.xxx.xxx:yyyy'
05-01 14:19:35.478 D/Baresip Lib(26429): sending message 547456930192/sip:sip:x@xxx.xxx.xxx.xxx:yyyy/test
05-01 14:19:35.478 D/Baresip Service(26429): Message event for 547456930192 from sip:sip:x@xxx.xxx.xxx.xxx:yyyy at 1588353575478
05-01 14:19:35.541 D/Baresip (26429): Saved 100 messages
`

**Comment by juha-h** [comment]
Your logcat output shows that baresip library received the message two times, i.e., it was not duplicated by baresip Android app.

Could it be that the message gets duplicated by a SIP Proxy?  It can happen if you are using UDP transport for SIP.

**Comment by rdcampos6** [comment]
Yes, like you said before I post my log. Seems not related with baresip.

The stranger thing its that's not happening before and I dont changed anything, also not receiving duplicarted messages on microsip software.

I'll do a better research about it. Sorry bothering you @juha-h and congrats for your excelent work. I'm the one who translated to Brazilian portuguese on weblate. It's the least I can to thank your effort.

**Comment by juha-h** [comment]
If you have access to the network over which the messages arrive, look with wireshark or ngrep if you see duplicate SIP requests.

Thanks for the your translation contribution.

**Comment by rdcampos6** [comment]
Well, so I know my problem its not related to baresip but I'll update some informations about it:

Not using any proxy, also no change to asterisk protocol, so running throught UDP. (but no problems before like I said).

I remind days before I got an bruteforce attack then I set fail2ban and port fowarding in my router  xxxx to internal 5060.

The android baresip account its running through my fixed external IP, but the microsip its running on internal IP. That's the only difference and maybe related with the problem.

I created an new account to run inside the network on android baresip app and no message duplicated.

I really thanks for your time and patience, I'll analyze with wireshark.
You can close this thread @juha-h

**Comment by juha-h** [comment]
OK, thanks.
