### ISSUE TITLE
Add notes to old app about new app with video

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#82]
* Fastlane (description)
* in-app maybe (if Android 7+)

**Comment by juha-h** [comment]
Licaon_Kter writes:

> * Fastlane (description)
> * in-app maybe (if Android 7+)

Fastlane descriptions exists:

https://github.com/juha-h/baresip-studio/tree/v1.0.0/fastlane/metadata/android/en-US

I don't know what in-app means.

**Comment by licaon-kter** [comment]
Read my post again: "Old app"

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Read my post again: "Old app"

OK, will do after a few hours.

**Comment by juha-h** [comment]
Note added in tag 18.2.0. Reopen if needed.
