### ISSUE TITLE
libbn.a: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by mateuszs7** [juha-h/baresip-studio#88]
I have trouble to build video branch. I make each steps from libbaresip-android@video (there was no problem with master branch). Build Output from Android Studio below. Any tips?

```
Build command failed.
Error while executing process /ZZZ/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /ZZZ/app/.cxx/cmake/debug/arm64-v8a baresip}
ninja: Entering directory `/ZZZ/app/.cxx/cmake/debug/arm64-v8a'
[1/3] Building C object CMakeFiles/baresip.dir/vidisp.c.o
[2/3] Building C object CMakeFiles/baresip.dir/baresip.c.o
[3/3] Linking C shared library /ZZZ/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so
FAILED: /ZZZ/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so ...
/ZZZ/app/src/main/cpp/../../../../distribution/bn/lib/arm64-v8a/libbn.a: error adding symbols: File in wrong format
```

**Comment by juha-h** [comment]
Mateusz Suchowiecki writes:

> I have trouble to build video branch. I make each steps from
> libbaresip-android@video (there was no problem with master
> branch). Build Output from Android Studio below. Any tips?

I don't know what goes wrong, but make sure you rebuild and install
all libs for both architectures using libbaresip video branch before
building baresip-studio video branch.
