### ISSUE TITLE
Cannot use number as Displayname

### ISSUE THREAD

**Issue by spaetz** [juha-h/baresip-studio#9]
Hi there, thanks for quickly fixing my previous issue 😃.
Still having problems with my sip account 1234@sip.1und1.de.
My provider requires the Displayname to be the username (1234 in this case). Otherwise it fails to register with '403 Display user and account user are different' (freely translated from German).

The code checks that the display Name starts with a character. Is that really required? Could we also relax that constraint somewhat?
In the positive side, I was able to make calls with other providers just fine.

**Comment by spaetz** [comment]
Thanks for your quick reply :-). Are you taking donations or anything as a token of gratitude?
I am very happy that you give me the possibility to test baresip on my phone.

**Comment by juha-h** [comment]
Sebastian Spaeth writes:

> Thanks for your quick reply :-). Are you taking donations or anything
> as a token of gratitude?

No, this is a hobby project.

> I am very happy that you give me the possibility to test baresip on my
> phone.

Keep on creating issues if you encounter new problems.
