### ISSUE TITLE
TouchTone dialpad does not appear via icon

### ISSUE THREAD

**Issue by boteman** [juha-h/baresip-studio#90]
During a call, touching the dialpad icon does not bring up the dialpad, but the icon does turn red. Instead, I must touch the "DTMF" text field which brings up the standard Android numeric key pad. I just installed Baresip today.

Baresip library = 20.0.1

Android phone info:
Android 7.1.1
ZTE A2017U
Kernel = 3.18.31
Build = A2017UV1.1.0b35
Build date 2017.12.11 

Thank you.

**Comment by juha-h** [comment]
boteman writes:

> During a call, touching the dialpad icon does not bring up the
> dialpad, but the icon does turn red. Instead, I must touch the "DTMF"
> text field which brings up the standard Android numeric key pad. I
> just installed Baresip today.

Thanks for the report.  I'll investigate.

The idea has been that dialpad icon does not bring up the dialpad, but
just toggles keyboard layout between numeric and alphabetic.

During calls it should automatically become red when DTMF is touched.

**Comment by boteman** [comment]
OK. I suppose that my expectations were different. I guess you can close this ticket then.

Thank you.

**Comment by juha-h** [comment]
boteman writes:

> OK. I suppose that my expectations were different. I guess you can
> close this ticket then.

I'll improve the implementation anyway, for example. during call, always
have dialpad on.  Will close when done.

**Comment by juha-h** [comment]
Latest versions now include some dialpad related improvements.
