### ISSUE TITLE
Why is BaresipService.kt intent on itself?

### ISSUE THREAD

**Issue by maccadoo** [juha-h/baresip-studio#91]
Thanks for the great code.
I'm sorry, but I'm going to ask a question in an issue because I just don't understand something.

Why is BaresipService class intent on itself?
What are the benefits?
Is it going to work as a different instance?
Can you tell me what to do?

https://github.com/juha-h/baresip-studio/blob/master/app/src/main/kotlin/com/tutpro/baresip/BaresipService.kt

class BaresipService: Service() {

......abbreviation......

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {

......abbreviation......

        when (action) {
            "Call Show", "Call Answer" -> {
                val newIntent = Intent(this, MainActivity::class.java)
                newIntent.flags = Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP or
                        Intent.FLAG_ACTIVITY_NEW_TASK
                newIntent.putExtra("action", action.toLowerCase(Locale.ROOT))
                newIntent.putExtra("callp", intent!!.getStringExtra("callp"))
                startActivity(newIntent)
            }

......abbreviation......

    @Keep
    fun uaEvent(event: String, uap: String, callp: String) {

......abbreviation......

        for (account_index in uas.indices) {
            if (uas[account_index].account.aor == aor) {
                when (ev[0]) {
                    "call incoming" -> {

......abbreviation......

                        if (!Utils.isVisible()) {
                            val intent = Intent(this, BaresipService::class.java)
                            intent.action = "Call Show"
                            intent.putExtra("callp", callp)
                            val pi = PendingIntent.getService(this, CALL_REQ_CODE, intent,
                                    PendingIntent.FLAG_UPDATE_CURRENT)
                            val nb = NotificationCompat.Builder(this, HIGH_CHANNEL_ID)
                            val caller = Utils.friendlyUri(ContactsActivity.contactName(peerUri),
                                    Utils.aorDomain(aor))
                            nb.setSmallIcon(R.drawable.ic_stat)
                                    .setColor(ContextCompat.getColor(this,
                                            R.color.colorBaresip))
                                    .setContentIntent(pi)
                                    .setCategory(Notification.CATEGORY_CALL)
                                    .setAutoCancel(true)
                                    .setOngoing(true)
                                    .setContentTitle(getString(R.string.incoming_call_from))
                                    .setContentText(caller)
                            if (Build.VERSION.SDK_INT < 26) {
                                nb.setVibrate(LongArray(0))
                                        .setVisibility(NotificationCompat.VISIBILITY_PRIVATE)
                                        .setPriority(Notification.PRIORITY_HIGH)
                            }
                            val answerIntent = Intent(this, BaresipService::class.java)
                            answerIntent.action = "Call Answer"
                            answerIntent.putExtra("callp", callp)
                            val answerPendingIntent = PendingIntent.getService(this,
                                    ANSWER_REQ_CODE, answerIntent, PendingIntent.FLAG_UPDATE_CURRENT)
                            val rejectIntent = Intent(this, BaresipService::class.java)
                            rejectIntent.action = "Call Reject"
                            rejectIntent.putExtra("callp", callp)
                            val rejectPendingIntent = PendingIntent.getService(this,
                                    REJECT_REQ_CODE, rejectIntent, PendingIntent.FLAG_UPDATE_CURRENT)
                            nb.addAction(R.drawable.ic_stat, getString(R.string.answer), answerPendingIntent)
                            nb.addAction(R.drawable.ic_stat, getString(R.string.reject), rejectPendingIntent)
                            nm.notify(CALL_NOTIFICATION_ID, nb.build())
                            return
                        }
                    }

**Comment by juha-h** [comment]
I don't remember why the implementation is like it is.  My guess is that it allows main activity action to be executed from the notification.

Is there an issue that needs to be fixed?

**Comment by maccadoo** [comment]
As a matter of fact, I'm also making a SIP application.
My app is not stable yet.
The code you wrote was very helpful.
Thanks to you, my code is now much closer to completion.

I compared my code with yours and asked some questions because I couldn't understand some of them.

Thanks for the answers.
Thank you for sharing your code with us.

There are not many people developing SIP apps anymore, but keep up the good work.

I'm going to put it up on github when I finish it too.
