### ISSUE TITLE
F-Droid build error

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#92]
Ref https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild_9&oldid=274657

**Comment by juha-h** [comment]
Licaon_Kter writes:

> Ref https://f-droid.org/wiki/index.php?title=com.tutpro.baresip.plus/lastbuild_9&oldid=274657

I don't know why this error happens:

ninja: Entering directory `/home/vagrant/build/com.tutpro.baresip.plus/app/.cxx/cmake/release/armeabi-v7a'
ninja: error: '/home/vagrant/build/com.tutpro.baresip.plus/distribution/baresip/lib/armeabi-v7a/libbaresip.a', needed by '/home/vagrant/build/com.tutpro.baresip.plus/app/build/intermediates/cmake/release/obj/armeabi-v7a/libbaresip.so', missing and no known rule to make it

baresip.plus libs are installed by libbaresip-android Makefile to
distribution.video dir, not to distribution dir.

And that is the dir from where baresip.plus CMakeLists.txt is looking
them for: 

set(distribution_DIR ${CMAKE_SOURCE_DIR}/../../../../distribution.video)

**Comment by licaon-kter** [comment]
This build fine on my buildserver VM instance....strange...lets see what the next cycle does

**Comment by juha-h** [comment]
Build has now succeeded.

**Comment by licaon-kter** [comment]
https://f-droid.org/wiki/index.php?title=com.tutpro.baresip/lastbuild_135&oldid=275978 ?

**Comment by juha-h** [comment]
Licaon_Kter writes:

> https://f-droid.org/wiki/index.php?title=com.tutpro.baresip/lastbuild_135&oldid=275978 ?

Looks like I had forgotten to create a new tag after re-patch update.
Now the new tag exists and I updated metadata:

> https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7331
