### ISSUE TITLE
Call Transfer

### ISSUE THREAD

**Issue by kairavi-magnates** [juha-h/baresip-studio#93]
How to transfer an ongoing call? I am able to receive call from other device but I don't know how to transfer it.

**Comment by licaon-kter** [comment]
Answer...it?

**Comment by kairavi-magnates** [comment]
Let me explain in detail.
I need some help on call transfer.
I initiated call from device1 > I am able to receive it on device2 > now I want to transfer the same call to device3.
But I don't know how to transfer the call from device2.

**Comment by juha-h** [comment]
Currently only handling of incoming call transfer request (REFER) is supported.

**Comment by kairavi-magnates** [comment]
I can see the implementation of call transfer in `transfer(ua: UserAgent, call: Call, uri: String) ` . So does that mean this method can be used to transfer the call?

**Comment by juha-h** [comment]
kairavi-magnates writes:

> I can see the implementation of call transfer in `transfer(ua:
> UserAgent, call: Call, uri: String) ` . So does that mean this method
> can be used to transfer the call?

Yes, that function can be used.  I haven't added user interface for that
yet.

**Comment by juha-h** [comment]
Latest version of baresip now supports baresip originated call transfer.

**Comment by kairavi-magnates** [comment]
Thank you.
