### ISSUE TITLE
Baresip+ video calling screen issue

### ISSUE THREAD

**Issue by kairavi-magnates** [juha-h/baresip-studio#97]
Below are few problems that I am facing while using video calling in Baresip+

1. Whenever I start the video calling feature, it always starts in landscape mode by default.
2. Video view size is always very small(almoast half of the screen)

Device used : OnePlus 3

Please suggest me the parameters by changing which I can rotate self view and move to full screen/fit to mobile screen size during video call.

**Comment by juha-h** [comment]
Only landscape is currently supported.  From About text:

> In video calls, the device needs to be held in landscape mode rotated 90 degrees left from portrait orientation.

You can configure size of sent video in Settings (Video Frame Size)

**Comment by kairavi-magnates** [comment]
`In video calls, the device needs to be held in landscape mode rotated 90 degrees left from portrait orientation.`

Can we rotate camera instead of screen ?

**Comment by juha-h** [comment]
Yes, it should suffice, if camera is rotated provided that the device supports it.

**Comment by kairavi-magnates** [comment]
To rotate the camera, I need camera instance. But I am not able to find the code/file where I can put my camera rotation related implementations. Can you suggest?

**Comment by juha-h** [comment]
kairavi-magnates writes:

> To rotate the camera, I need camera instance. But I am not able to
> find the code/file where I can put my camera rotation related
> implementations. Can you suggest?

baresip+ app is using baresip avformat module to implement its video
source.  That in turn in based on ffmpeg libavformat/libavdevice
libraries.

I was not able to make camera rotation work.  Here is the related ffmpeg
issue:

https://trac.ffmpeg.org/ticket/8659

Let me know if you get it working.

**Comment by kairavi-magnates** [comment]
Instead of rotating the camera can we rotate display view(self-view & opponent-view) ?

**Comment by juha-h** [comment]
kairavi-magnates writes:

> Instead of rotating the camera can we rotate display view(self-view &
> opponent-view) ?

Perhaps, check cpp/vidisp.c.
