### ISSUE TITLE
Build command failed.

### ISSUE THREAD

**Issue by MS-ELEX** [juha-h/baresip-studio#98]
I've  tried.  but I cannnot build.

```
Build command failed.

Error while executing process [path]\AppData\Local\Android\sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C [path]\AndroidProject\baresip-studio\app\.cxx\cmake\debug\armeabi-v7a baresip}
ninja: Entering directory `[path]\AndroidProject\baresip-studio\app\.cxx\cmake\debug\armeabi-v7a'

ninja: error: '[path]/AndroidProject/baresip-studio/distribution/baresip/lib/armeabi-v7a/libbaresip.a', needed by '[path]/AndroidProject/baresip-studio/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libbaresip.so', missing and no known rule to make it


```

**Comment by licaon-kter** [comment]
Build this first https://github.com/juha-h/libbaresip-android

**Comment by juha-h** [comment]
Yes, after building and installing libbaresip-android, you will have libbaresip.a in baresip-studio/distribution/baresip/lib/armeabi-v7a/ dir.

**Comment by MS-ELEX** [comment]
Thanks!!

But I cannot make 
It's too difficult.
I've change two paths. and make 

`PS D:\Users\karikomi\Documents\AndroidProject\libbaresip-android> make
make libbaresip ANDROID_TARGET_ARCH=arm64-v8a
'uname' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
process_begin: CreateProcess(NULL, pwd, ...) failed.
make[1]: ディレクトリ `D:/Users/karikomi/Documents/AndroidProject/libbaresip-android' に入ります
make distclean -C openssl
make: Entering an unknown directory
make: *** openssl: No such file or directory.  中止.
make: Leaving an unknown directory
make[1]: [openssl] エラー 2 (無視されました)
cd openssl && \
        CC=clang ANDROID_NDK=D:/Users/karikomi/AppData/Local/Android/sdk/ndk-bundle PATH=D:/Users/karikomi/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/bin:/bin ./Configure android-arm64 no-shared -D__ANDROID_API__=21 && \
        CC=clang ANDROID_NDK=D:/Users/karikomi/AppData/Local/Android/sdk/ndk-bundle PATH=D:/Users/karikomi/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/bin:/bin make build_libs
指定されたパスが見つかりません。
make[1]: *** [openssl] エラー 1
make[1]: ディレクトリ `D:/Users/karikomi/Documents/AndroidProject/libbaresip-android' から出ます
make: *** [default] エラー 2`

**Comment by licaon-kter** [comment]
Get openssl...

**Comment by juha-h** [comment]
Closed as explained in https://github.com/juha-h/libbaresip-android/issues/14#issuecomment-683390621.
